### ISSUE TITLE
Lighthouse - rimraf - directory not empty exception

### ISSUE THREAD

**Issue by ramlmn** [GoogleChrome/lighthouse#1001]
Lighthouse exits due to an exception during removing the temp folder on Windows.
This happens after finishing the audit and closing chrome.
It exits with:
```
...
  ChromeLauncher Killing all Chrome Instances +487ms
C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\node_modules\rimraf\rimraf.js:312
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\ramlmn\AppData\Local\Temp\lighthouse.35898675'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:886:18)
    at rmkidsSync (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\node_modules\rimraf\rimraf.js:342:11)
    at rmdirSync (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\node_modules\rimraf\rimraf.js:332:7)
    at Function.rimrafSync [as sync] (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\node_modules\rimraf\rimraf.js:303:9)
    at ChromeLauncher.destroyTmp (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\chrome-launcher.js:182:20)
    at ChildProcess.chrome.on (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\chrome-launcher.js:164:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
```

This error occurs to me since the I started using lighthouse on my Windows machine, didn't try on others but it still gives me the same error after the total audit (At Least it saves the audit file).

It happens even though when I run console as Administrator. Please have a look into it (My `%temp%` directory is full of empty lighthouse directories).

**Comment by wardpeet** [comment]
You just run  lighthouse? Or is there a specific path to follow?

**Comment by ramlmn** [comment]
@wardpeet I just run it.

**Comment by dnutels** [comment]
Reproduced on Windows 10 Proffessional. Node 7.2.0.

**Comment by ramlmn** [comment]
@wardpeet Sometimes it spits the same error and sometimes it doesn't (even in 1.2.2)

**Comment by ramlmn** [comment]
@wardpeet Still gives the a similar error (verbose):
```
  ChromeLauncher Killing all Chrome Instances +363ms
  Printer html output written to ./pwa.rocks_2016-11-30_22-07-30.report.html +370ms
  ChromeLauncher:verbose Removing C:\Users\ramlmn\AppData\Local\Temp\lighthouse.51295464 +91ms
C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\node_modules\rimraf\rimraf.js:312
        throw er
        ^

Error: EBUSY: resource busy or locked, unlink 'C:\Users\ramlmn\AppData\Local\Temp\lighthouse.51295464\CrashpadMetrics-active.pma'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1089:18)
    at rimrafSync (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\node_modules\rimraf\rimraf.js:305:17)
    at C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\node_modules\rimraf\rimraf.js:340:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\node_modules\rimraf\rimraf.js:339:26)
    at rmdirSync (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\node_modules\rimraf\rimraf.js:332:7)
    at Function.rimrafSync [as sync] (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\node_modules\rimraf\rimraf.js:303:9)
    at ChromeLauncher.destroyTmp (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\chrome-launcher.js:188:20)
    at ChildProcess.chrome.on (C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\chrome-launcher.js:164:26)
```

I think this issue needs to be reopened.

**Comment by wardpeet** [comment]
Pretty weird, will look at it again but tested it on my windows 10 on node v6

@ramlmn what node are you on?

**Comment by ramlmn** [comment]
@wardpeet node v6.9.1 (npm 3.10.8)

**Comment by ramlmn** [comment]
@wardpeet Something like
``` js
rimraf(this.TMP_PROFILE_DIR, fs, _ => {});
```
instead of
``` js
rimraf.sync(this.TMP_PROFILE_DIR);
```
works totally fine for me ([https://github.com/isaacs/rimraf#rimrafsync](https://github.com/isaacs/rimraf#rimrafsync)).

**Comment by wardpeet** [comment]
well rimraf is async, I could do some promise magic. i'll try that :)

**Comment by brendankenny** [comment]
@ramlmn if you get a chance, try out master and see if #1127 helped

**Comment by ramlmn** [comment]
@wardpeet @brendankenny That works but I was having issues with making an install from repo so I've copied the TS installed lighthouse from npm changed the TS and made a build. That works right now.

I always get this when installing lighthouse from repo. Should I make an issue for it:
``` bash
ramlmn@Dell-PC: "~/Desktop/lighthouse" (master)
$ npm install -g
C:\Users\ramlmn\AppData\Roaming\npm\lighthouse -> C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\index.js
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\manual-chrome-launcher.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\manual-chrome-launcher.js'
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\ramlmn\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-cli\manual-chrome-launcher.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ramlmn\Desktop\lighthouse\npm-debug.log
```
![capture](https://cloud.githubusercontent.com/assets/12368291/21036360/48953786-bdeb-11e6-8096-af88a1a86f7e.PNG)

**Comment by paulirish** [comment]
for the new issue ... rather than `npm install -g` i would typically recommend `npm link` from the same directory. that'll link the globals to your local install rather than putting copies of this checking into your /npm/node_modules/ directory.

**Comment by ramlmn** [comment]
@paulirish I actually do that without having a lighthouse installation prior to it.
Ahhhh... this is happening to me right now (lighthouse is actually uninstalled and iam trying to install it):

![capture2](https://cloud.githubusercontent.com/assets/12368291/21037305/cf7bdd70-bdf2-11e6-84c6-884051d313c4.PNG)

**Comment by ramlmn** [comment]
Did `npm link` made the build and the temp looks clean that fixed the issue finely.

**Comment by paulirish** [comment]
super :)
