### ISSUE TITLE
LH fails to create tmp directory on WSL

### ISSUE THREAD

**Issue by villasv** [GoogleChrome/lighthouse#10288]
#### Provide the steps to reproduce
1. Run LH inside WSL2
  
#### What is the current behavior?
```
Runtime error encountered: EACCES: permission denied, mkdir '/mnt/undefined'
Error: EACCES: permission denied, mkdir '/mnt/undefined'
    at Object.mkdirSync (fs.js:750:3)
    at sync (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/mkdirp/index.js:71:13)
    at sync (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/mkdirp/index.js:77:24)
    at sync (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/mkdirp/index.js:77:24)
    at sync (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/mkdirp/index.js:77:24)
    at sync (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/mkdirp/index.js:77:24)
    at Function.sync (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/mkdirp/index.js:77:24)       at makeWin32TmpDir (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/utils.js:115:12)
    at Object.makeTmpDir (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/utils.js:85:20)
    at Launcher.makeTmpDir (/home/villasv/.nvm/versions/node/v10.14.1/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:115:24)
```

#### What is the expected behavior?
No error.

#### Environment Information
* Affected Channels: CLI
* Lighthouse version: 5.6.0
* Chrome version:
* Node.js version: 10.14.1
* Operating System: Ubuntu on Windows 10 WSL2

**Comment by paulirish** [comment]
ah wsl2.

this was fixed in is-wsl: https://github.com/sindresorhus/is-wsl/pull/3

but we have to pull it into chrome-launcher and then roll deps.

thanks for the heads up!

**Comment by paulirish** [comment]
Ah @patrickhulce pointed out we already have that fix in chrome-launcher/LH that you're using..

the relevant lines are https://github.com/GoogleChrome/chrome-launcher/blob/d39af59b722f5670f4ae29291837fb9b58e99327/src/utils.ts#L57-L70

so this isn't as straightforward as I was hoping..

---

it appears it's falling through to the win32 case which means `is-wsl` module is returning false on your system. 

so.. reading the is-wsl source, I'm wondering what `require('os').release` in node and `/proc/version` are on your machine, @villasv 

cc @KyivJunta since you solved this last time.

**Comment by villasv** [comment]
```
$ nvm --version
0.35.1
$ node --version
v10.14.1
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
$ node
> require('os').release()
'4.19.84-microsoft-standard'
```

**Comment by villasv** [comment]
I had a problem once with some Python packages failing to identify the system as Linux (even though the OS said so) because they tried to guess from the file system, which is NTFS. Maybe this is a similar situation.

**Comment by villasv** [comment]
I had a problem once with some Python packages failing to identify the system as Linux (even though the OS said so) because they tried to guess from the file system, which is NTFS. Maybe this is a similar situation.

**Comment by villasv** [comment]
Looking at the code you highlighted, I think it's something else. I don't have my Windows PATH appended, so very likely `process.env.TEMP = getLocalAppDataPath(`${process.env.PATH}`);` is yielding `TEMP = undefined`.

It's pretty common nowadays to configure WSL not to append the Windows PATH to the Linux PATH because it slows everything down SO MUCH. My suggestion is to rely on the usual linux tooling for tmp directories.

Should I close this and copy the bug report on chrome-launcher?

**Comment by villasv** [comment]
Looking at the code you highlighted, I think it's something else. I don't have my Windows PATH appended, so very likely `process.env.TEMP = getLocalAppDataPath(`${process.env.PATH}`);` is yielding `TEMP = undefined`.

It's pretty common nowadays to configure WSL not to append the Windows PATH to the Linux PATH because it slows everything down SO MUCH. My suggestion is to rely on the usual linux tooling for tmp directories.

Should I close this and copy the bug report on chrome-launcher?

**Comment by patrickhulce** [comment]
Ah great find @villasv! No need to copy we can transfer the issue over :)
