### ISSUE TITLE
SyntaxError: Unexpected number in JSON

### ISSUE THREAD

**Issue by itwars** [GoogleChrome/lighthouse#1028]
Hi,

I got a strange error using : 

- Chrome 54
- lighthouse 1.2.1 (but got the same error with previous version)
- node 7.1.0

```
lighthouse http://www.it-wars.com
```
```
  Lighthouse:warn The URL provided should be on HTTPS +0ms
  Lighthouse:warn Performance stats will be skewed redirecting from HTTP to HTTPS. +2ms
undefined:1
{"method":"Page.loadEventFired","params":{"timestamp":29541,686521}}
                                                            ^
SyntaxError: Unexpected number in JSON at position 60
    at JSON.parse (<anonymous>)
    at CriConnection.handleRawMessage (/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:91:25)
    at WebSocket.ws.on.data (/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:53:39)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/usr/local/lib/node_modules/lighthouse/node_modules/ws/lib/WebSocket.js:841:10)
    at /usr/local/lib/node_modules/lighthouse/node_modules/ws/lib/Receiver.js:536:18
    at /usr/local/lib/node_modules/lighthouse/node_modules/ws/lib/Receiver.js:368:7
    at /usr/local/lib/node_modules/lighthouse/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:388:3)
```

**Comment by paulirish** [comment]
Wow thanks for reporting! This is a fun one.

It's upstream and fixed here: https://bugs.chromium.org/p/v8/issues/detail?id=5551. It had to do with localization of numbers and commas in the json. naturally. :)

You're fine if you use Chrome 55 or later. And stable will be updated in one week.

In the meantime if you use Canary (or beta) you should be fine and not see this problem.

Thanks again!

**Comment by paulirish** [comment]
btw- This was a little tricky to repro, but this should do it:

```sh
export LANG=fr_FR.UTF-8
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 --user-data-dir=blahblah
lighthouse http://foo.com
```

It requires LANG being set in the terminal, and Chrome launched from the terminal. If lang is set to  `LANG=en_US.UTF-8` or chrome is launched outside the terminal this problem wasn't visible.

**Comment by itwars** [comment]
Works fine with Chrome 55.

Thx
