### ISSUE TITLE
Tracing failed at Function.fromProtocolMessage 

### ISSUE THREAD

**Issue by lovasoa** [GoogleChrome/lighthouse#10298]
#### Provide the steps to reproduce
1. Run LH on https://reg-game.netlify.com/

#### What is the current behavior?

The following message appears

> Ah, sorry, we ran into an error.

```
Protocol error (Tracing.end): Tracing failed

Channel: DevTools
Initial URL: https://reg-game.netlify.com/
Chrome Version: 78.0.3882.0
Stack Trace: Error: Protocol error (Tracing.end): Tracing failed
    at Function.fromProtocolMessage (devtools://devtools/remote/serve_file/@19d4547535ab5aba70b4730443f84e8153052174/audits_worker/audits_worker_module.js:1603:121)
    at eval (devtools://devtools/remote/serve_file/@19d4547535ab5aba70b4730443f84e8153052174/audits_worker/audits_worker_module.js:1209:253)
```

<img width="1674" alt="image" src="https://user-images.githubusercontent.com/552629/73830209-8fed8b00-4804-11ea-891b-ed0652e53362.png">

#### What is the expected behavior?
No error appears

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version:
* Chrome version: Chromium Version 78.0.3882.0 (Developer Build) (64-bit)
* Operating System: MacOS 10.15.2 (19C57)

**Comment by patrickhulce** [comment]
Thanks very much for filing @lovasoa!

I'm not able to reproduce this error though from CLI, DevTools Canary, or DevTools stable :/ Any additional information for us that could help reproduce? Does it happen even after updating to latest stable?

![image](https://user-images.githubusercontent.com/2301202/73857917-3897ec80-47fd-11ea-9de3-1cfcb4b60b3b.png)

Congrats on your 100 performance score btw! :)

**Comment by lovasoa** [comment]
I tried again with a few more sites, and I get the error everytime, so it does not seem to be related to the website itself. I tried in Chrome and it works.
So the issue seems to be tied to Chromium 78 on MacOS.

**Comment by patrickhulce** [comment]
Can I ask how you happened to install that particular Chromium build? There have been cases in the past (#7246) where a distributor of Chromium messes with the `Tracing` category of the DevTools protocol in a way that breaks it for Lighthouse.

**Comment by lovasoa** [comment]
I do not remember how I installed it. I think it was though npm.

**Comment by patrickhulce** [comment]
You installed Chromium Version 78.0.3882.0 (Developer Build) through npm? I wasn't aware one could even do that. It's an odd version to be using, would you be able to try with Chrome stable or Chrome canary to see if the problem is reproducible and legitimate? I'm not able to reproduce this issue.

**Comment by paulirish** [comment]
Can you try again with an official up to date build of Chrome?

**Comment by lovasoa** [comment]
This does not reproduce with an official up to date build on chrome. Only with chromium installed though npm.

**Comment by patrickhulce** [comment]
Thanks for the extra info @lovasoa, glad to hear it's working in latest Chrome! We can only support stable Chromium and later over official channels as some Chromium builds from other sources are intentionally modified in ways that break Lighthouse (see #7246 for an example), so we'll have to close this one. If there are other issues preventing you from using the latest versions, we'd love to hear about those separately.

**Comment by lovasoa** [comment]
If it is a known issue and that builds that break lighthouse are common, maybe lighthouse could at least explain the situation in the error message it gives. Error messages like [this](https://user-images.githubusercontent.com/552629/73830209-8fed8b00-4804-11ea-891b-ed0652e53362.png) are not really helpful. If the error message had given an actionable advice such as 
> LightHouse does not support modified Chromium builds, try with [an official build](https://www.chromium.org/getting-involved/download-chromium)

both lighthouse developers and me could have saved time.

**Comment by patrickhulce** [comment]
Fair! We should probably add this new message to [knownBugPatterns](https://cs.chromium.org/chromium/src/third_party/devtools-frontend/src/front_end/lighthouse/LighthouseStatusView.js?type=cs&q=f:lighthouse+-f:out+%22github%22&sq=package:chromium&g=0&l=303)
