### ISSUE TITLE
PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by imnikhilsharma** [GoogleChrome/lighthouse#10346]
Hi Team,

I m facing an issue in the lighthouse while auditing the website.  The error shows that 
![Screenshot_3](https://user-images.githubusercontent.com/50795450/74608873-caabc900-510a-11ea-8164-f01f3cb5db3a.png)
 

Channel: DevTools
Initial URL: https://vcetrainer.com/
Chrome Version: 77.0.3865.120
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@416d6d8013e9adb6dd33b0c12e7614ff403d1a94/audits_worker/audits_worker_module.js:1250:210)
```
why this issue occur in the desktop version of the website auditing

**Comment by imnikhilsharma** [comment]
Hi Team,

I m facing an issue in the lighthouse while auditing the website.  The error shows that 
![Screenshot_3](https://user-images.githubusercontent.com/50795450/74608873-caabc900-510a-11ea-8164-f01f3cb5db3a.png)
 

Channel: DevTools
Initial URL: https://vcetrainer.com/
Chrome Version: 77.0.3865.120
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@416d6d8013e9adb6dd33b0c12e7614ff403d1a94/audits_worker/audits_worker_module.js:1250:210)
```
why this issue occurs in the desktop version of the website auditing
