### ISSUE TITLE
report crash - 

### ISSUE THREAD

**Issue by rafaqat** [GoogleChrome/lighthouse#10367]
annot read property 'frame' of undefined
```
Channel: DevTools
Initial URL: https://smartprivacyngadminstaging.herokuapp.com/msolidair
Chrome Version: 80.0.3987.106
Stack Trace: TypeError: Cannot read property 'frame' of undefined
    at Driver._getOrCreateIsolatedContextId (devtools://devtools/remote/serve_file/@f68069574609230cf9b635cd784cfb1bf81bb53a/audits_worker/audits_worker_module.js:1314:124)
    at async Driver.evaluateAsync (devtools://devtools/remote/serve_file/@f68069574609230cf9b635cd784cfb1bf81bb53a/audits_worker/audits_worker_module.js:1274:81)
    at async Function.afterPass (devtools://devtools/remote/serve_file/@f68069574609230cf9b635cd784cfb1bf81bb53a/audits_worker/audits_worker_module.js:1383:812)
    at async Function.runPass (devtools://devtools/remote/serve_file/@f68069574609230cf9b635cd784cfb1bf81bb53a/audits_worker/audits_worker_module.js:1398:84)
    at async Function.run (devtools://devtools/remote/serve_file/@f68069574609230cf9b635cd784cfb1bf81bb53a/audits_worker/audits_worker_module.js:1392:576)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/remote/serve_file/@f68069574609230cf9b635cd784cfb1bf81bb53a/audits_worker/audits_worker_module.js:1982:151)
    at async Function.run (devtools://devtools/remote/serve_file/@f68069574609230cf9b635cd784cfb1bf81bb53a/audits_worker/audits_worker_module.js:1974:11)
```

**Comment by patrickhulce** [comment]
p3 because this feels like one of those Chromium-side bugs that is impossible to reproduce. Unable to repro locally.

**Comment by janwittkamp** [comment]
Same error today
```
Channel: DevTools
Initial URL: https://interweber.de/
Chrome Version: 83.0.4103.116
Stack Trace: TypeError: Cannot read property 'frame' of undefined
    at Driver._getOrCreateIsolatedContextId (devtools://devtools/remote/serve_file/@8f0c18b4dca9b6699eb629be0f51810c24fb6428/lighthouse_worker/lighthouse_worker_module.js:1314:124)
    at async Driver.evaluateAsync (devtools://devtools/remote/serve_file/@8f0c18b4dca9b6699eb629be0f51810c24fb6428/lighthouse_worker/lighthouse_worker_module.js:1274:81)
    at async Function.afterPass (devtools://devtools/remote/serve_file/@8f0c18b4dca9b6699eb629be0f51810c24fb6428/lighthouse_worker/lighthouse_worker_module.js:1383:812)
    at async Function.runPass (devtools://devtools/remote/serve_file/@8f0c18b4dca9b6699eb629be0f51810c24fb6428/lighthouse_worker/lighthouse_worker_module.js:1398:84)
    at async Function.run (devtools://devtools/remote/serve_file/@8f0c18b4dca9b6699eb629be0f51810c24fb6428/lighthouse_worker/lighthouse_worker_module.js:1392:576)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/remote/serve_file/@8f0c18b4dca9b6699eb629be0f51810c24fb6428/lighthouse_worker/lighthouse_worker_module.js:1982:151)
    at async Function.run (devtools://devtools/remote/serve_file/@8f0c18b4dca9b6699eb629be0f51810c24fb6428/lighthouse_worker/lighthouse_worker_module.js:1974:11)
````

**Comment by oekraiens** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/73040546/97338398-0a29d800-188a-11eb-9669-8f2abfd3d86f.png)

The index.html was opened with Live Server.

**Comment by oekraiens** [comment]
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: http://127.0.0.1:5500/index.html
Chrome Version: 86.0.4240.111
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@b8c36128a06ebad76af51591bfec980224db5522/lighthouse_worker/lighthouse_worker_module.js:1589:229)
```

**Comment by ndugger** [comment]
Just hit this error today

```
Channel: DevTools
Initial URL: http://localhost:1150/news/ckkkv36rs3pal0a85rrh4k5vx/worlds-largest-drone-set-to-deliver-satellites-to-orbit
Chrome Version: 88.0.4324.104
Stack Trace: TypeError: Cannot read property 'frame' of undefined
    at Driver._endNetworkStatusMonitoring (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:462:533)
    at async Driver.gotoURL (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:464:563)
    at async Function.loadPage (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:474:299)
    at async Function.runPass (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:482:879)
    at async Function.run (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:481:730)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:607:184)
    at async Function.run (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:605:118)
```

It worked when I retried, so I was only able to produce this just the one time so far

**Comment by trevor-ofarrell** [comment]
I also hit this error, but when running lighthouse again right after it ran properly. 
`Cannot read property 'frame' of undefined
```
Channel: DevTools
Initial URL: http://localhost:3000/dashboard
Chrome Version: 88.0.4324.150
Stack Trace: TypeError: Cannot read property 'frame' of undefined
    at Driver._getOrCreateIsolatedContextId (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:463:69)
    at async Driver.evaluateAsync (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:455:430)
    at async Function.afterPass (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:479:1)
    at async Function.runPass (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:483:430)
    at async Function.run (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:481:730)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:607:184)
    at async Function.run (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:605:118)
````

**Comment by connorjclark** [comment]
not reproducing today
