### ISSUE TITLE
PROTOCOL_TIMEOUT ``` Channel: DevTools Initial URL: http://localhost:3000/#/ Chrome Version: 80.0.3987.149 Stack Trace: LHError: PROTOCOL_TIMEOUT     at eval (devtools://devtools/remote/serve_file/@5f4eb224680e5d7dca88504586e9fd951840cac6/audits_worker/audits_worker_module.js:1268:229) ```

### ISSUE THREAD

**Issue by krystianwojtowicz** [GoogleChrome/lighthouse#10500]
**Summary**

**Comment by mamtach** [comment]
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://www.ecmsdjango.com/
Chrome Version: 80.0.3987.149
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@5f4eb224680e5d7dca88504586e9fd951840cac6/audits_worker/audits_worker_module.js:1268:229)
```
