### ISSUE TITLE
Extension Error: artifacts.ConsoleTimeUsage.usage.filter is not a function

### ISSUE THREAD

**Issue by cnbn96** [GoogleChrome/lighthouse#1055]
**Lighthouse Version**: 1.2.1
**Chrome Version**: 52.3.2743.138
**Error Message**: artifacts.ConsoleTimeUsage.usage.filter is not a function
**Stack Trace**:
 ```TypeError: artifacts.ConsoleTimeUsage.usage.filter is not a function
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:807:54)
    at chain.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11082:24)```

**Comment by wardpeet** [comment]
Dupe of #1031
