### ISSUE TITLE
Unsupported time zone specified undefined

### ISSUE THREAD

**Issue by quynh2150** [GoogleChrome/lighthouse#1056]
Lighthouse Version: 1.2.1
Chrome Version: 54.0.2840.99 
Error Message: Unexpected token , in JSON at position 45
Stack Trace:

> RangeError: Unsupported time zone specified undefined
    at new DateTimeFormat (native)
    at ReportGenerator._formatTime (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10838:23)
    at ReportGenerator.generateHTML (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10970:27)
    at window.createReportPageAsBlob (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:38312:28)
    at connection.getCurrentTabURL.then.then.results (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:38282:30)

**Comment by ebidel** [comment]
Would you be able to share the URL tested?

**Comment by quynh2150** [comment]
https://tiki.vn/

**Comment by ebidel** [comment]
Interesting. Can you do me a favor and run this in the console:

`new Intl.DateTimeFormat('en-US', { timeZoneName: 'long'}).resolvedOptions()`

and post a screenshot of the results. This looks like a bug in Chrome.

**Comment by quynh2150** [comment]
I ran lighthouse for this site in 1 of my lap and i got this bug. However, when i test in another computers, it worked fine just like you did
bte, I'll run your command and post it later
thanks

**Comment by quynh2150** [comment]
![2016-11-30](https://cloud.githubusercontent.com/assets/20279257/20757724/0bedb256-b74a-11e6-9863-8ab4f0205cec.png)
This is the result after i ran your commands
Hope it'll help
