### ISSUE TITLE
Lighthouse ran into an error

### ISSUE THREAD

**Issue by ROCHatty** [GoogleChrome/lighthouse#10649]
Protocol error (Target.setAutoAttach): Could not obtain database names.
```
Channel: DevTools
Initial URL: http://localhost/admin/dashboard.php
Chrome Version: 81.0.4044.122
Stack Trace: Error: Protocol error (Target.setAutoAttach): Could not obtain database names.
    at Function.fromProtocolMessage (devtools://devtools/remote/serve_file/@44f4233f08910d83b146130c1938256a2e05b136/audits_worker/audits_worker_module.js:1634:121)
    at eval (devtools://devtools/remote/serve_file/@44f4233f08910d83b146130c1938256a2e05b136/audits_worker/audits_worker_module.js:1232:246)

**Comment by patrickhulce** [comment]
Well this a new one 🤔 

This only seems to happen in Chromium when it can't fetch indexeddb databases list, but not sure why it would throw on `setAutoAttach`...

https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/indexeddb/inspector_indexed_db_agent.cc?q=%22Could%20not%20obtain%20database%20names%22&ss=chromium

**Comment by paulirish** [comment]
@ROCHatty did you disable your indexeddb or local storage somehow?  

> This only seems to happen in Chromium when it can't fetch indexeddb databases list, but not sure why it would throw on `setAutoAttach`...

yeah this is very odd..

**Comment by ROCHatty** [comment]
> @ROCHatty did you disable your indexeddb or local storage somehow?
> 
> > This only seems to happen in Chromium when it can't fetch indexeddb databases list, but not sure why it would throw on `setAutoAttach`...
> 
> yeah this is very odd..

Well, I just tried running it again, and it worked. But at first it gave me that error, and it told me to report it, so I did that :)

**Comment by Koalaknightmi** [comment]
also having it 
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://phaser-planes.glitch.me/
Chrome Version: 81.0.4044.129
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@3d71af9f5704a40b85806f4d08925db24605ba25/audits_worker/audits_worker_module.js:1268:229)
```

**Comment by ashishdommety** [comment]
Faced the same issue 🤔 
```
PROTOCOL_TIMEOUT
Channel: DevTools
Initial URL: https://www.ashcodes.com/
Chrome Version: 81.0.4044.129
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@3d71af9f5704a40b85806f4d08925db24605ba25/audits_worker/audits_worker_module.js:1268:229)
```

It seems like it's only happening the first time I run "generate report" - I had the same experience trying it on two different websites.

**Comment by samos123** [comment]
I'm getting this error occasionally  for the same URL with lighthouse 7.2.0. I am running lighthouse in a docker container like this: https://github.com/websu-io/websu/blob/master/build/Dockerfile_lighthouse
So it seems to be something that can't be reliably reproduced however in previous versions of lighthouse I never saw this error.

Note that the method isn't always setAutoattach ocassionally it's another one but didn't capture it.

**Comment by connorjclark** [comment]
many years later: I haven't seen "setAutoattach" in recent years myself so I'll go ahead and close this.
