### ISSUE TITLE
Add LH error code to DevTools error dialog

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#10659]
useful to see `TRACING_ALREADY_` `STARTED` in here
![image](https://user-images.githubusercontent.com/39191/80537523-11167300-8959-11ea-8420-9d62f44fd78d.png)

**Comment by Daudxu** [comment]
Mi.connect is not a function
```
Channel: DevTools
Initial URL: http://127.0.0.1:5173/login
Chrome Version: 116.0.0.0
Stack Trace: TypeError: Mi.connect is not a function
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:624:662
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:527:132)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:624:548)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:626:696)
    at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%401a391816688002153ef791ffe60d9e899a71a037%2F:1:2668)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%401a391816688002153ef791ffe60d9e899a71a037%2F:1:3056)
```

**Comment by adamraine** [comment]
@Daudxu see #15300
