### ISSUE TITLE
Faced a PROTOCOL_TIMEOUT (again and again)

### ISSUE THREAD

**Issue by Vallenain** [GoogleChrome/lighthouse#10738]
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://undercovid.web.app/welcome
Chrome Version: 81.0.4044.138
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@8c6c7ba89cc9453625af54f11fd83179e23450fa/audits_worker/audits_worker_module.js:1268:229)
```

I check all "categories" and same result whether I select "mobile" or "desktop".

**Comment by LonelyCpp** [comment]
same error- 
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://lonelycpp.github.io/
Chrome Version: 81.0.4044.138
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@8c6c7ba89cc9453625af54f11fd83179e23450fa/audits_worker/audits_worker_module.js:1268:229)
```

**Comment by patrickhulce** [comment]
Please see #6512
