### ISSUE TITLE
Unhandled promise rejection (lighthouse-core/gather/fetcher.js)

### ISSUE THREAD

**Issue by mikedijkstra** [GoogleChrome/lighthouse#11033]
We're seeing a number of errors being thrown from `lighthouse-core/gather/fetcher.js` as unhandled promise rejections. 

Examples of errors:

- Protocol error (Fetch.failRequest): Fetch domain is not enabled
- Protocol error (Fetch.continueRequest): Invalid InterceptionId.
- Error: Invalid response status code: 404
- Invalid response status code: 403
- Invalid response status code: 301

<details><summary>Error output</summary>

```bash
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Invalid response status code: 404
      at ./node_modules/lighthouse/lighthouse-core/gather/fetcher.js:119:18
      at Fetcher._onRequestPaused (./node_modules/lighthouse/lighthouse-core/gather/fetcher.js:75:13)
      at EventEmitter.emit (events.js:315:20)
      at EventEmitter.emit (domain.js:482:12)
      at Driver._handleProtocolEvent (./node_modules/lighthouse/lighthouse-core/gather/driver.js:299:24)
      at EventEmitter.emit (events.js:315:20)
      at EventEmitter.emit (domain.js:482:12)
      at CalibreProtocol.emitProtocolEvent (./node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:148:24)
      at CalibreProtocol.handleRawMessage (./node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:113:12)
      at WebSocket.<anonymous> (./node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:72:37)
} reason: Error: Invalid response status code: 404
    at ./node_modules/lighthouse/lighthouse-core/gather/fetcher.js:119:18
    at Fetcher._onRequestPaused (./node_modules/lighthouse/lighthouse-core/gather/fetcher.js:75:13)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:482:12)
    at Driver._handleProtocolEvent (./node_modules/lighthouse/lighthouse-core/gather/driver.js:299:24)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:482:12)
    at CalibreProtocol.emitProtocolEvent (./node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:148:24)
    at CalibreProtocol.handleRawMessage (./node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:113:12)
    at WebSocket.<anonymous> (./node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:72:37)
(node:25717) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 10)
Error: Invalid response status code: 404
    at ./node_modules/lighthouse/lighthouse-core/gather/fetcher.js:119:18
    at Fetcher._onRequestPaused (./node_modules/lighthouse/lighthouse-core/gather/fetcher.js:75:13)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:482:12)
    at Driver._handleProtocolEvent (./node_modules/lighthouse/lighthouse-core/gather/driver.js:299:24)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:482:12)
    at CalibreProtocol.emitProtocolEvent (./node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:148:24)
    at CalibreProtocol.handleRawMessage (./node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:113:12)
    at WebSocket.<anonymous> (./node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:72:37)
```

</details>

I'm seeing the error in Node and when using the Lighthouse CLI.

#### Provide the steps to reproduce

 Run:
```bash
lighthouse https://www.clarin.com/deportes/basquet/ginobili-volvio-hacer-magia-definicion-exquisita_0_H16J9aAaZ.html --view
```

#### What is the current behavior?

Lighthouse returns `Unhandled Rejection. Reason: Error: Invalid response status code: 404`. See [full output](https://gist.github.com/mikedijkstra/cff70091adaac0e01583357860b9655f).

#### What is the expected behavior?

Lighthouse report is generated and opened in the browser

#### Environment Information
* Affected Channels: CLI, Node
* Lighthouse version: 6.1
* Chrome version: 83.0.4103.116
* Node.js version: 12.18.0
* Operating System: Mac, Linux

**Comment by patrickhulce** [comment]
Thanks for filing @mikedijkstra! The sendCommand ones are an easy fix but I'm not immediately seeing how the invalid status code ones are unhandled 🤔 we'll have to investigate.

**Comment by connorjclark** [comment]
![image](https://user-images.githubusercontent.com/4071474/86048126-d38ba000-ba04-11ea-9012-2d1405ca9183.png)
![image (1)](https://user-images.githubusercontent.com/4071474/86048130-d4bccd00-ba04-11ea-9ac8-d5bbbc4d21e9.png)

It's being rejected before the evaluation ends.
