### ISSUE TITLE
Auditing localhost... error

### ISSUE THREAD

**Issue by mlucanu** [GoogleChrome/lighthouse#11066]
**Summary**
Runtime.evaluate response did not contain a "result" object
```
Channel: DevTools
Initial URL: http://localhost/testsamm/
Chrome Version: 83.0.4103.116
Stack Trace: Error: Runtime.evaluate response did not contain a "result" object
    at Driver._evaluateInContext (devtools://devtools/remote/serve_file/@8f0c18b4dca9b6699eb629be0f51810c24fb6428/lighthouse_worker/lighthouse_worker_module.js:1286:55)
    at async Driver.evaluateAsync (devtools://devtools/remote/serve_file/@8f0c18b4dca9b6699eb629be0f51810c24fb6428/lighthouse_worker/lighthouse_worker_module.js:1274:145)
    at async Function.afterPass (devtools://devtools/remote/serve_file/@8f0c18b4dca9b6699eb629be0f51810c24fb6428/lighthouse_worker/lighthouse_worker_module.js:1383:812)
    at async Function.runPass (devtools://devtools/remote/serve_file/@8f0c18b4dca9b6699eb629be0f51810c24fb6428/lighthouse_worker/lighthouse_worker_module.js:1398:84)
    at async Function.run (devtools://devtools/remote/serve_file/@8f0c18b4dca9b6699eb629be0f51810c24fb6428/lighthouse_worker/lighthouse_worker_module.js:1392:576)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/remote/serve_file/@8f0c18b4dca9b6699eb629be0f51810c24fb6428/lighthouse_worker/lighthouse_worker_module.js:1982:151)
    at async Function.run (devtools://devtools/remote/serve_file/@8f0c18b4dca9b6699eb629be0f51810c24fb6428/lighthouse_worker/lighthouse_worker_module.js:1974:11)
```

**Comment by brendankenny** [comment]
This should be resolved by now. Please comment and we can reopen if not!
