### ISSUE TITLE
error running release/test.sh–Cannot find module 'lodash.clonedeep' 

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#11231]
```
+ npm install /Users/cjamcl/src/lighthouse/lighthouse-core/scripts/release/../../../../lighthouse-pristine/lighthouse-6.1.0.tgz
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN lighthouse-local-test@1.0.0 No description
npm WARN lighthouse-local-test@1.0.0 No repository field.

+ lighthouse@6.1.0
added 266 packages from 207 contributors in 8.562s
found 0 vulnerabilities

+ npm explore lighthouse -- npm run smoke -- --retries=3

> lighthouse@6.1.0 smoke /private/tmp/lighthouse-local-test/node_modules/lighthouse
> node lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js "--retries=3"

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'lodash.clonedeep'
Require stack:
- /private/tmp/lighthouse-local-test/node_modules/lighthouse/lighthouse-cli/test/smokehouse/report-assert.js
- /private/tmp/lighthouse-local-test/node_modules/lighthouse/lighthouse-cli/test/smokehouse/smokehouse.js
- /private/tmp/lighthouse-local-test/node_modules/lighthouse/lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/private/tmp/lighthouse-local-test/node_modules/lighthouse/lighthouse-cli/test/smokehouse/report-assert.js:13:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/tmp/lighthouse-local-test/node_modules/lighthouse/lighthouse-cli/test/smokehouse/report-assert.js',
    '/private/tmp/lighthouse-local-test/node_modules/lighthouse/lighthouse-cli/test/smokehouse/smokehouse.js',
    '/private/tmp/lighthouse-local-test/node_modules/lighthouse/lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lighthouse@6.1.0 smoke: `node lighthouse-cli/test/smokehouse/frontends/smokehouse-bin.js "--retries=3"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lighthouse@6.1.0 smoke script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cjamcl/.npm/_logs/2020-08-06T19_53_07_244Z-debug.log
npm ERR! weird error 1
```

lol `weird error`

**Comment by connorjclark** [comment]
`lodash.clonedeep` is a dev dep used in smoke tests, but we are trying to run smoke tests from within the packed npm package, which won't included dev deps.
