### ISSUE TITLE
PWA not implemented in Opera

### ISSUE THREAD

**Issue by Arnoost** [GoogleChrome/lighthouse#11293]
Protocol error (Page.getInstallabilityErrors): PWA not implemented in Opera
```
Channel: DevTools
Initial URL: https://webdilna.com/cz/jednoduchy-e-shop
Chrome Version: 84.0.4147.105
Stack Trace: Error: Protocol error (Page.getInstallabilityErrors): PWA not implemented in Opera
    at Function.fromProtocolMessage (devtools://devtools/remote/serve_file/@a6b12dfad6663f13a7e16e9a42a6a4975374096b/lighthouse_worker/lighthouse_worker_module.js:1898:121)
    at eval (devtools://devtools/remote/serve_file/@a6b12dfad6663f13a7e16e9a42a6a4975374096b/lighthouse_worker/lighthouse_worker_module.js:1417:246)
```

#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @Arnoost! This sounds like an Opera problem, have you already filed with them? 

Lighthouse can't officially support running against browsers that remove important parts of Chromium necessary to run the audits.
