### ISSUE TITLE
Audit Error: Runtime.evaluate response did not contain a "result" object

### ISSUE THREAD

**Issue by tannerdolby** [GoogleChrome/lighthouse#11387]
#### Provide the steps to reproduce
1. Run LH on https://www.rothecoder.com/
2. Let audit run as I usually would, to notice it throw a stack trace error before completing.

#### What is the current behavior?
Runtime.evaluate response did not contain a "result" object
```
Channel: DevTools
Initial URL: https://www.rothecoder.com/
Chrome Version: 84.0.4147.135
Stack Trace: Error: Runtime.evaluate response did not contain a "result" object
    at Driver._evaluateInContext (devtools://devtools/remote/serve_file/@c42bd09b3f24da1698d71d3b4f57402137163566/lighthouse_worker/lighthouse_worker_module.js:1471:55)
    at async Driver.evaluateAsync (devtools://devtools/remote/serve_file/@c42bd09b3f24da1698d71d3b4f57402137163566/lighthouse_worker/lighthouse_worker_module.js:1459:145)
    at async Function.afterPass (devtools://devtools/remote/serve_file/@c42bd09b3f24da1698d71d3b4f57402137163566/lighthouse_worker/lighthouse_worker_module.js:1571:287)
    at async Function.runPass (devtools://devtools/remote/serve_file/@c42bd09b3f24da1698d71d3b4f57402137163566/lighthouse_worker/lighthouse_worker_module.js:1593:84)
    at async Function.run (devtools://devtools/remote/serve_file/@c42bd09b3f24da1698d71d3b4f57402137163566/lighthouse_worker/lighthouse_worker_module.js:1585:576)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/remote/serve_file/@c42bd09b3f24da1698d71d3b4f57402137163566/lighthouse_worker/lighthouse_worker_module.js:2257:151)
    at async Function.run (devtools://devtools/remote/serve_file/@c42bd09b3f24da1698d71d3b4f57402137163566/lighthouse_worker/lighthouse_worker_module.js:2249:11)
```
#### What is the expected behavior?
LH to run until completion and show a dashboard with the audit results. 

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: Lighthouse 6.0.0
* Chrome version: Version 84.0.4147.135 (Official Build) (64-bit)
* Node.js version: v11.0.0
* Operating System: macOS High Sierra

#### Notes
The page I'm trying to run the audit on currently has many errors logged to the console for a number of reasons. After clearing the cache and refreshing the page, running a LH audit worked as expected. I was only able to reproduce this error two times out of five LH audits.

**Related issues**
Potential duplicate #6869

**Comment by patrickhulce** [comment]
Thanks for filing @tannerdolby with a URL and explanation! You're right though we'll dedupe this into #6869 :)
