### ISSUE TITLE
error while auditing - Cannot read property 'frame' of undefined

### ISSUE THREAD

**Issue by kavishsoam** [GoogleChrome/lighthouse#11392]
#### Provide the steps to reproduce
1. Run LH on <affected url>
  

#### Environment Information
* Affected Channels: 
* Lighthouse version:
* Chrome version: 
* Node.js version:
* Operating System:

**Related issues**

Cannot read property 'frame' of undefined
```
Channel: DevTools
Initial URL: https://app.massagenow321.com:4433/auth/login
Chrome Version: 81.0.4044.122
Stack Trace: TypeError: Cannot read property 'frame' of undefined
    at Driver._getOrCreateIsolatedContextId (devtools://devtools/remote/serve_file/@44f4233f08910d83b146130c1938256a2e05b136/audits_worker/audits_worker_module.js:1314:124)
    at async Driver.evaluateAsync (devtools://devtools/remote/serve_file/@44f4233f08910d83b146130c1938256a2e05b136/audits_worker/audits_worker_module.js:1274:81)
    at async Function.afterPass (devtools://devtools/remote/serve_file/@44f4233f08910d83b146130c1938256a2e05b136/audits_worker/audits_worker_module.js:1383:287)
    at async Function.runPass (devtools://devtools/remote/serve_file/@44f4233f08910d83b146130c1938256a2e05b136/audits_worker/audits_worker_module.js:1398:84)
    at async Function.run (devtools://devtools/remote/serve_file/@44f4233f08910d83b146130c1938256a2e05b136/audits_worker/audits_worker_module.js:1392:576)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/remote/serve_file/@44f4233f08910d83b146130c1938256a2e05b136/audits_worker/audits_worker_module.js:1982:151)
    at async Function.run (devtools://devtools/remote/serve_file/@44f4233f08910d83b146130c1938256a2e05b136/audits_worker/audits_worker_module.js:1974:11)

**Comment by patrickhulce** [comment]
Thanks for filing @kavishsoam! I'm not able to reproduce this unfortunately :/ Any extra steps or settings that might be relevant?

**Comment by connorjclark** [comment]
dupe https://github.com/GoogleChrome/lighthouse/issues/10367
