### ISSUE TITLE
Getting Error: Expected expectedValue of type boolean, got number

### ISSUE THREAD

**Issue by Hosar** [GoogleChrome/lighthouse#1148]
```Runtime error encountered: Error: Expected expectedValue of type boolean, got number: Unable to get document body innerText: result was not a string```

Linux 16
node v7.0.0

**Comment by ebidel** [comment]
Can you post the page you were testing against and steps to repro?

**Comment by WeiweiAtGit** [comment]
I got the same error.

command:
```
node lighthouse-cli http://localhost:8887/ --output json --output-path report.json --quiet
```

Error:
```
Runtime error encountered: Error: Expected expectedValue of type boolean, got number: Error in determining viewport
    at Function._convertToWeight (/usr/local/google/home/weiweilin/WebstormProjects/lighthouse/lighthouse-core/aggregator/aggregate.js:97:13)
    at expectedNames.forEach.e (/usr/local/google/home/weiweilin/WebstormProjects/lighthouse/lighthouse-core/aggregator/aggregate.js:191:35)
    at Array.forEach (native)
    at items.map.item (/usr/local/google/home/weiweilin/WebstormProjects/lighthouse/lighthouse-core/aggregator/aggregate.js:164:21)
    at Array.map (native)
    at Function.compare (/usr/local/google/home/weiweilin/WebstormProjects/lighthouse/lighthouse-core/aggregator/aggregate.js:148:18)
    at Function.aggregate (/usr/local/google/home/weiweilin/WebstormProjects/lighthouse/lighthouse-core/aggregator/aggregate.js:226:29)
    at config.aggregations.map.a (/usr/local/google/home/weiweilin/WebstormProjects/lighthouse/lighthouse-core/runner.js:133:28)
    at Array.map (native)
    at run.then.runResults (/usr/local/google/home/weiweilin/WebstormProjects/lighthouse/lighthouse-core/runner.js:132:46)
Error: Expected expectedValue of type boolean, got number: Error in determining viewport
    at Function._convertToWeight (/usr/local/google/home/weiweilin/WebstormProjects/lighthouse/lighthouse-core/aggregator/aggregate.js:97:13)
    at expectedNames.forEach.e (/usr/local/google/home/weiweilin/WebstormProjects/lighthouse/lighthouse-core/aggregator/aggregate.js:191:35)
    at Array.forEach (native)
    at items.map.item (/usr/local/google/home/weiweilin/WebstormProjects/lighthouse/lighthouse-core/aggregator/aggregate.js:164:21)
    at Array.map (native)
    at Function.compare (/usr/local/google/home/weiweilin/WebstormProjects/lighthouse/lighthouse-core/aggregator/aggregate.js:148:18)
    at Function.aggregate (/usr/local/google/home/weiweilin/WebstormProjects/lighthouse/lighthouse-core/aggregator/aggregate.js:226:29)
    at config.aggregations.map.a (/usr/local/google/home/weiweilin/WebstormProjects/lighthouse/lighthouse-core/runner.js:133:28)
    at Array.map (native)
    at run.then.runResults (/usr/local/google/home/weiweilin/WebstormProjects/lighthouse/lighthouse-core/runner.js:132:46)
```

localhost HTML
```
<html>
<body>
	<p>Hello World!</p>
</body>
</html>
```
