### ISSUE TITLE
Lighthouse throwing error: Error: Protocol error (Fetch.disable): 'Fetch.disable' wasn't found

### ISSUE THREAD

**Issue by JamieREvans** [GoogleChrome/lighthouse#11596]
#### Provide the steps to reproduce
1. Copy programmatic use script from the docs and run against any URL
2. Run script

Here's the code that I have (slightly changed to accommodate for catching the error.

``` javascript
const fs = require('fs');
const lighthouse = require('lighthouse');
const chromeLauncher = require('chrome-launcher');

(async () => {
  const chrome = await chromeLauncher.launch({chromeFlags: ['--headless']});
  const options = {logLevel: 'info', output: 'html', onlyCategories: ['performance'], port: chrome.port};
  try {
    const runnerResult = await lighthouse('https://www.google.com', options);

    // `.report` is the HTML report as a string
    const reportHtml = runnerResult.report;
    fs.writeFileSync('lhreport.html', reportHtml);

    // `.lhr` is the Lighthouse Result as a JS object
    console.log('Report is done for', runnerResult.lhr.finalUrl);
    console.log('Performance score was', runnerResult.lhr.categories.performance.score * 100);
  } catch(error) {
    console.error(error);
  }

  await chrome.kill();
})();
```

#### What is the current behavior?
It's failing before performing any tests.

Console error:
```
  status Connecting to browser +0ms
  status Resetting state with about:blank +17ms
  status Benchmarking machine +136ms
  status Initializing… +1s
  status Running defaultPass pass CSSUsage, JsUsage, ViewportDimensions, ConsoleMessages, ImageElements, LinkElements, ScriptElements, DOMStats, OptimizedImages, ResponseCompression, TagsBlockingFirstPaint, TraceElements, SourceMaps +202ms
  status Resetting state with about:blank +0ms
  status Setting up network for the pass trace +8ms
  status Cleaning browser cache +1ms
  status Beginning devtoolsLog and trace +7ms
  status Loading page & waiting for onload +3ms
  status Gathering in-page: CSSUsage +3s
  status Gathering in-page: JsUsage +1ms
  status Gathering in-page: ViewportDimensions +0ms
  status Gathering in-page: ConsoleMessages +0ms
  status Gathering in-page: ImageElements +0ms
  status Gathering in-page: LinkElements +0ms
  status Gathering in-page: ScriptElements +0ms
  status Gathering in-page: DOMStats +0ms
  status Gathering in-page: OptimizedImages +0ms
  status Gathering in-page: ResponseCompression +0ms
  status Gathering in-page: TagsBlockingFirstPaint +0ms
  status Gathering in-page: TraceElements +0ms
  status Gathering in-page: SourceMaps +0ms
  status Gathering trace +0ms
  status Gathering devtoolsLog & network records +108ms
  status Gathering: CSSUsage +10ms
  status Gathering: JsUsage +36ms
  status Gathering: ViewportDimensions +106ms
  status Gathering: ConsoleMessages +2ms
  status Gathering: ImageElements +3ms
  status Gathering: LinkElements +94ms
  status Gathering: ScriptElements +7ms
  status Gathering: DOMStats +30ms
  status Gathering: OptimizedImages +6ms
  status Gathering: ResponseCompression +13ms
  status Gathering: TagsBlockingFirstPaint +47ms
  status Gathering: TraceElements +5ms
  status Gathering: SourceMaps +16ms
  method <= browser ERR:error Fetch.enable  +1ms
  method <= browser ERR:error Fetch.disable  +122ms
  status Disconnecting from browser... +0ms
Error: Protocol error (Fetch.disable): 'Fetch.disable' wasn't found
    at Function.fromProtocolMessage (/Users/jamie.evans/Development/performance_tests/node_modules/lighthouse/lighthouse-core/lib/lh-error.js:140:19)
    at /Users/jamie.evans/Development/performance_tests/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:124:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  protocolMethod: 'Fetch.disable',
  protocolError: "'Fetch.disable' wasn't found"
}
```

#### Environment Information
* Affected Channels: Node
* Lighthouse version: 6.4.1
* Chrome version: 86.0.4240.111
* Node.js version: v14.13.0
* Operating System: macOS 10.15.6 (19G2021)

**Comment by patrickhulce** [comment]
Thanks for filing @JamieREvans!

What does 
```bash
"$(node -e "console.log(require('chrome-launcher/dist/chrome-finder').darwinFast())")" --version
```

output for you?

> Protocol error (Fetch.disable): 'Fetch.disable' wasn't found

This error only happens when the Chrome version is very old. I'm assuming that whatever Chrome is being used is not actually `86.0.4240.111`

**Comment by JamieREvans** [comment]
@patrickhulce I have no idea what has changed other than entering the above command, but the code is working now and I'm getting results. The only "new" thing I've done is globally installed chrome launcher (`npm install -g chrome-launcher`) in another shell, but npm has already included `chrome-launcher` in its dependencies (AND I had already globally installed `lighthouse`).

My console window shows the error I posted above, immediately followed by `node index.js` to re-run the same script and it worked on the re-run (after many, MANY failures). Either time was the solution or that global install.

I won't try to waste both of our time debug why it's working, so we can mark this as resolved, I guess?
