### ISSUE TITLE
Ran into error 

### ISSUE THREAD

**Issue by oekraiens** [GoogleChrome/lighthouse#11600]
Cannot read property 'frame' of undefined
```
Channel: DevTools
Initial URL: http://127.0.0.1:5500/index.html
Chrome Version: 86.0.4240.111
Stack Trace: TypeError: Cannot read property 'frame' of undefined
    at Driver._endNetworkStatusMonitoring (devtools://devtools/remote/serve_file/@b8c36128a06ebad76af51591bfec980224db5522/lighthouse_worker/lighthouse_worker_module.js:1632:250)
    at async Driver.gotoURL (devtools://devtools/remote/serve_file/@b8c36128a06ebad76af51591bfec980224db5522/lighthouse_worker/lighthouse_worker_module.js:1638:46)
    at async Function.loadBlank (devtools://devtools/remote/serve_file/@b8c36128a06ebad76af51591bfec980224db5522/lighthouse_worker/lighthouse_worker_module.js:1689:1198)
    at async Function.runPass (devtools://devtools/remote/serve_file/@b8c36128a06ebad76af51591bfec980224db5522/lighthouse_worker/lighthouse_worker_module.js:1733:316)
    at async Function.run (devtools://devtools/remote/serve_file/@b8c36128a06ebad76af51591bfec980224db5522/lighthouse_worker/lighthouse_worker_module.js:1727:576)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/remote/serve_file/@b8c36128a06ebad76af51591bfec980224db5522/lighthouse_worker/lighthouse_worker_module.js:2410:151)
    at async Function.run (devtools://devtools/remote/serve_file/@b8c36128a06ebad76af51591bfec980224db5522/lighthouse_worker/lighthouse_worker_module.js:2402:11)
```

**Comment by patrickhulce** [comment]
Thanks for filing @oekraiens! We'll de-dupe this into #10367 so we can track in one place :)
