### ISSUE TITLE
Extension Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by LaurentPerche** [GoogleChrome/lighthouse#1183]
**Lighthouse Version**: 1.2.2
**Chrome Version**: 55.0.2883.95
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
 ```Error: Protocol error (Tracing.start): Tracing is already started
    at ExtensionConnection.handleRawError (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:7377:11)
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:7526:33)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by brendankenny** [comment]
This is the same as #1091, so closing in favor of that issue.

If you have details of how you reached this error they would be very appreciated there!
