### ISSUE TITLE
Runtime.evaluate response did not contain a "result" object

### ISSUE THREAD

**Issue by laravelman** [GoogleChrome/lighthouse#11939]
Runtime.evaluate response did not contain a "result" object
```
Channel: DevTools
Initial URL: https://quotesdonut.com/
Chrome Version: 87.0.4280.141
Stack Trace: Error: Runtime.evaluate response did not contain a "result" object
    at Driver._evaluateInContext (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:456:814)
    at async Driver.evaluateAsync (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:455:491)
    at async Function.afterPass (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:479:1)
    at async Function.runPass (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:483:430)
    at async Function.run (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:481:730)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:607:184)
    at async Function.run (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:605:118)
```

**Comment by patrickhulce** [comment]
Thanks for filing @laravelman! This is tracked by #6869 so we'll close this as a duplicate.
