### ISSUE TITLE
After running Cmd "lighthouse yourURL" its showing me this issue

### ISSUE THREAD

**Issue by Shabbir124** [GoogleChrome/lighthouse#11953]
/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:68
  _traceCategories = Driver.traceCategories;
                   ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/lighthouse/lighthouse-core/runner.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by patrickhulce** [comment]
Thanks for filing @Shabbir124!

The minimum node version that Lighthouse supports is Node 12, upgrade the node version to run Lighthouse.
