### ISSUE TITLE
SyntaxError: Invalid or unexpected token (node_modules/lighthouse/lighthouse-core/computed/layout-shift-variants.js:37)

### ISSUE THREAD

**Issue by electrachong** [GoogleChrome/lighthouse#12105]
#### Provide the steps to reproduce
1. Run LH programatically with node using the example README.md script on https://example.com
 

#### What is the current behavior?

Get this error:

```
➜  grove git:(master) ✗ node assets/js/tests/lighthouse.js
(node:21355) UnhandledPromiseRejectionWarning: <redacted>/grove/node_modules/lighthouse/lighthouse-core/computed/layout-shift-variants.js:37
      if (event.ts - prevTs > 5_000_000) clusterCount++;
                              ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/electrachong/grove-repos/deus-ex-machina/grove/node_modules/lighthouse/lighthouse-core/computed/metrics/cumulative-layout-shift.js:10:29)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
(node:21355) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21355) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C%
➜  grove git:(master) ✗ npm list lighthouse
grove@0.3.0 /Users/electrachong/grove-repos/deus-ex-machina/grove
└── lighthouse@7.1.0
```

#### What is the expected behavior?

Works as expected for previous tagged version:
```
➜  grove git:(master) ✗ npm list lighthouse
grove@0.3.0 /Users/electrachong/grove-repos/deus-ex-machina/grove
└── lighthouse@7.0.1

➜  grove git:(master) ✗ node assets/js/tests/lighthouse.js
  status Connecting to browser +0ms
  status Resetting state with about:blank +22ms
  status Benchmarking machine +85ms
  status Initializing… +1s
  status Running defaultPass pass CSSUsage, JsUsage, ViewportDimensions, ConsoleMessages, ImageElements, LinkElements, ScriptElements, DOMStats, OptimizedImages, ResponseCompression, TagsBlockingFirstPaint, TraceElements, SourceMaps, FullPageScreenshot +73ms
  status Resetting state with about:blank +0ms
  status Setting up network for the pass trace +13ms
  status Cleaning browser cache +2ms
  status Beginning devtoolsLog and trace +25ms
  status Loading page & waiting for onload +62ms
  status Gathering in-page: CSSUsage +2s
  status Gathering in-page: JsUsage +0ms
  status Gathering in-page: ViewportDimensions +0ms
  status Gathering in-page: ConsoleMessages +1ms
  status Gathering in-page: ImageElements +0ms
  status Gathering in-page: LinkElements +0ms
  status Gathering in-page: ScriptElements +0ms
  status Gathering in-page: DOMStats +0ms
  status Gathering in-page: OptimizedImages +0ms
  status Gathering in-page: ResponseCompression +0ms
  status Gathering in-page: TagsBlockingFirstPaint +0ms
  status Gathering in-page: TraceElements +0ms
  status Gathering in-page: SourceMaps +0ms
  status Gathering in-page: FullPageScreenshot +0ms
  status Gathering trace +0ms
  status Gathering devtoolsLog & network records +45ms
  status Gathering: CSSUsage +7ms
  status Gathering: JsUsage +28ms
  status Gathering: ViewportDimensions +3ms
  status Gathering: ConsoleMessages +2ms
  status Gathering: ImageElements +2ms
  status Gathering: LinkElements +13ms
  status Gathering: ScriptElements +6ms
  status Gathering: DOMStats +4ms
  status Gathering: OptimizedImages +12ms
  status Gathering: ResponseCompression +2ms
  status Gathering: TagsBlockingFirstPaint +1ms
  status Gathering: TraceElements +4ms
  status Gathering: SourceMaps +9ms
  status Gathering: FullPageScreenshot +3ms
  status Populate base artifacts +257ms
  status Get webapp manifest +1ms
  status Collect stacks +2ms
  status Disconnecting from browser... +19ms
  status Analyzing and running audits... +9ms
  status Auditing: First Contentful Paint +3ms
  status Auditing: Largest Contentful Paint +36ms
  status Auditing: First Meaningful Paint +5ms
  status Auditing: Speed Index +4ms
  status Auditing: Screenshot Thumbnails +158ms
  status Auditing: Final Screenshot +67ms
  status Auditing: Estimated Input Latency +2ms
  status Auditing: Total Blocking Time +3ms
  status Auditing: Max Potential First Input Delay +4ms
  status Auditing: Cumulative Layout Shift +5ms
  status Auditing: Initial server response time was short +4ms
  status Auditing: First CPU Idle +3ms
  status Auditing: Time to Interactive +3ms
  status Auditing: User Timing marks and measures +2ms
  status Auditing: Avoid chaining critical requests +3ms
  status Auditing: Avoid multiple page redirects +2ms
  status Auditing: Minimizes main-thread work +5ms
  status Auditing: JavaScript execution time +4ms
  status Auditing: Preload key requests +3ms
  status Auditing: Preconnect to required origins +3ms
  status Auditing: All text remains visible during webfont loads +2ms
  status Auditing: Diagnostics +2ms
  status Auditing: Network Requests +0ms
  status Auditing: Network Round Trip Times +1ms
  status Auditing: Server Backend Latencies +3ms
  status Auditing: Tasks +2ms
  status Auditing: Metrics +0ms
  status Auditing: Performance budget +3ms
  status Auditing: Timing budget +2ms
  status Auditing: Keep request counts low and transfer sizes small +2ms
  status Auditing: Minimize third-party usage +5ms
  status Auditing: Lazy load third-party resources with facades +3ms
  status Auditing: Largest Contentful Paint element +3ms
  status Auditing: Avoid large layout shifts +2ms
  status Auditing: Avoid long main-thread tasks +1ms
  status Auditing: Avoid non-composited animations +2ms
  status Auditing: Image elements have explicit `width` and `height` +2ms
  status Auditing: Preload Largest Contentful Paint image +2ms
  status Auditing: Full-page screenshot +3ms
  status Auditing: Uses efficient cache policy on static assets +0ms
  status Auditing: Avoids enormous network payloads +9ms
  status Auditing: Defer offscreen images +2ms
  status Auditing: Eliminate render-blocking resources +3ms
  status Auditing: Minify CSS +3ms
  status Auditing: Minify JavaScript +3ms
  status Auditing: Remove unused CSS +2ms
  status Auditing: Remove unused JavaScript +2ms
  status Auditing: Serve images in next-gen formats +2ms
  status Auditing: Efficiently encode images +2ms
  status Auditing: Enable text compression +1ms
  status Auditing: Properly size images +2ms
  status Auditing: Use video formats for animated content +2ms
  status Auditing: Remove duplicate modules in JavaScript bundles +2ms
  status Auditing: Avoid serving legacy JavaScript to modern browsers +2ms
  status Auditing: Avoids an excessive DOM size +5ms
  status Auditing: Avoids `document.write()` +2ms
  status Auditing: Use HTTP/2 +2ms
  status Auditing: Uses passive listeners to improve scrolling performance +2ms
  status Generating results... +1ms
Report is done for https://example.com/
Performance score was 100
```

#### Environment Information
* Affected Channels: Node
* Lighthouse version: 7.1.0
* Chrome version: Version 88.0.4324.150 (Official Build) (x86_64)
* Node.js version: v12.4.0
* Operating System: Mac OS X 10.14.5 (18F132)

**Related issues**

**Comment by connorjclark** [comment]
Our minimum required Node for 7.1.0 is `12.13.0` ... but numeric separators was added in Node 12.5 so I'd expect this to work... https://v8.dev/features/numeric-separators

**Comment by electrachong** [comment]
Node version is 12.4 so maybe that makes sense @connorjclark ? Thanks for looking into. Is the minimum required Node version for the latest version documented somewhere?

**Comment by connorjclark** [comment]
> Node version is 12.4

Ah, yup, that's it then.

> Is the minimum required Node version for the latest version documented somewhere?

We announce it w/ every major release changelog, you can also check package.json engine entry.

**Comment by electrachong** [comment]
Thanks!
