### ISSUE TITLE
PROTOCOL_TIMEOUT running lighthouse

### ISSUE THREAD

**Issue by gillesosx** [GoogleChrome/lighthouse#12156]
#### Provide the steps to reproduce
I am developing a PWA app. I first loaded the URL in Chrome and then added the app to my Desktop (Windows 10).

1- I Open the PWA App using the added icon.
2- I Click on F12 to open the DevTools.
3- I select Lighthouse from the top bar.
4 - I click Generate report, with either Mobile or Desktop selected
5- I get an error message:

I tried again by opening the site directly in Chrome and got the same error.

  

#### What is the current behavior?
I get an error.

PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://wfuneradoc-1.web.app/index.html
Chrome Version: 88.0.4324.190
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:454:772
```

#### What is the expected behavior?
I should get the report.

#### Environment Information
* Affected Channels:  DevTools
* Lighthouse version: ?
* Chrome version:  88.0.4324.190
* Node.js version: v12.18.4
* Operating System: Windows 10 20H2

**Related issues**

**Comment by connorjclark** [comment]
Thanks for filing!

```
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Page.getInstallabilityErrors)
LHError: PROTOCOL_TIMEOUT
    at Timeout.<anonymous> (/Users/cjamcl/src/lighthouse/lighthouse-core/gather/driver.js:376:21)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
error Command failed with exit code 1.
```

**Comment by mattzeunert** [comment]
Seems like a Chrome regression, I'm getting the error in 87 but not 84.

**Comment by gillesosx** [comment]
@mattzeunert 

I tired on a different computer, same Windows 10 version, Chrome 88.0.4234.190 and I get no error, the report is generated fine.

Back on my development computer, I tried again, Chrome 89.0.4389.72, Generate Report still fails.

I wonder if the dev computer fails generating the report for reasons outside of Chrome:

- Workbox is installed but I can't see how that would prevent reporting to complete
- I get on Lighthouse this message in orange: "There may be stored data affecting loading performance in this location IndexedDB. Audit this page in an incognito window to prevent those resources from affecting your score". I don't know what to do with this.
- I have an error in the console when getting to the site I run Lighthouse for: "Uncaught (in promise) DOMException: Entry was not found. sw.js:1

Regarding the error, it's not there after loading the page, but happens after trying to generate the report: I click on 0 error once, there are still none, I click on (debug icon) 79 verbose, and during the time messages from Workbox are loading the the error appears.

**Comment by connorjclark** [comment]
> I have an error in the console when getting to the site I run Lighthouse for: "Uncaught (in promise) DOMException: Entry was not found. sw.js:1

This is a potential clue. @mattzeunert do you also see uncaught promise errors when this happens?

**Comment by mattzeunert** [comment]
There's a service worker on the page, and an uncaught rejection, but the rejection isn't from the service worker. Installing the service worker works fine.

**Comment by DotIN13** [comment]
Having the same orange error message, and the timeout audit error on my website.

PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://www.wannaexpresso.com/2021/02/20/m1-macbook-minecraft/
Chrome Version: 89.0.4389.82
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:469:563
```

**Comment by DotIN13** [comment]
For unknown reasons, the inablity to perform audition was gone for me as of today. Running Chrome Version 89.0.4389.82 (Official Build) (arm64).
