### ISSUE TITLE
Unexpected token = fatal exception on v 7.2.0 linux installed via npm just now... in lighthouse-core/gather/driver.js

### ISSUE THREAD

**Issue by tomachinz** [GoogleChrome/lighthouse#12212]
I had just installed it, but did a re-install just in case. Type `lighthouse` at the CLI gives the error. From the looks of the error, the issue seems to be that `_eventEmitter` is not being set correctly.

It looks like the author is trying to set it to` (new EventEmitter())` but there is a comment jam in the middle of the line:

```
tom@putin:~$ sudo npm install  -g lighthouse 
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/lighthouse -> /usr/local/lib/node_modules/lighthouse/lighthouse-cli/index.js
/usr/local/bin/chrome-debug -> /usr/local/lib/node_modules/lighthouse/lighthouse-core/scripts/manual-chrome-launcher.js
npm WARN notsup Unsupported engine for lighthouse@7.2.0: wanted: {"node":">=12.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: lighthouse@7.2.0

+ lighthouse@7.2.0
added 239 packages from 212 contributors in 13.295s
tom@putin:~$ lighthouse
/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:72
  **_eventEmitter = /** @type {CrdpEventEmitter} */ (new EventEmitter());**
                ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/lighthouse/lighthouse-core/runner.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
tom@putin:~$ which lighthouse
/usr/local/bin/lighthouse
tom@putin:~$ uname -a
Linux putin 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
tom@putin:~$ node -v
v10.19.0
tom@putin:~$ npm -v
6.14.4
tom@putin:~$ ls -la /usr/local/bin/lighthouse
lrwxrwxrwx 1 root root 54 Mar  7 06:20 /usr/local/bin/lighthouse -> ../lib/node_modules/lighthouse/lighthouse-cli/index.js

```
Normally it would not crash out like that.

* Affected Channels: CLI
* Lighthouse version: 7.2.0
* Node.js version: 10.19.0
* Operating System: Linux Kubuntu 20

PS I just realised that neither chrome nor chromium are installed (it's a new machine).

**Comment by connorjclark** [comment]
Minimum node version is 12.13.0. Upgrade and it should work!
