### ISSUE TITLE
INVALID_URL in DevTools from Performance Report

### ISSUE THREAD

**Issue by tekstrand** [GoogleChrome/lighthouse#12229]
#### Provide the steps to reproduce
1. Run LH on https://www.bigcommerce.com

#### What is the current behavior?
Fails to complete performance test suite

```
INVALID_URL
Channel: DevTools
Initial URL: 
Chrome Version: 89.0.4389.82
Stack Trace: LHError: INVALID_URL
    at Function.run (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:630:255)
    at lighthouse (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:502:68)
    at devtools://devtools/bundled/lighthouse_worker/LighthouseService.js:69:23
```

#### What is the expected behavior?
Should complete test suite

#### Environment Information
* Affected Channels: DevTools
* Lighthouse version: N/A
* Chrome version: 89.0.4389.82
* Node.js version: N/A
* Operating System: OSX 10.15.7

**Comment by tekstrand** [comment]
#6421 isn't open anymore 😬
