### ISSUE TITLE
Runtime.evaluate response did not contain a "result" object

### ISSUE THREAD

**Issue by rockybear67** [GoogleChrome/lighthouse#12321]
suddenly getting an error while measuring the site through LightHouse. I can't find a cause for that symptom.

------------------------------------------------------------------------------------------------------------
Runtime.evaluate response did not contain a "result" object
```
Channel: DevTools
Initial URL: https://lunacellstone.tistory.com/118
Chrome Version: 89.0.4389.90
Stack Trace: Error: Runtime.evaluate response did not contain a "result" object
    at ExecutionContext._evaluateInContext (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:481:901)
    at async ExecutionContext.evaluateAsync (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:482:189)
    at async Function.afterPass (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:496:437)
    at async Function.runPass (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:501:102)
    at async Function.run (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:499:427)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:632:439)
    at async Function.run (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:630:308)
```

**Comment by adamraine** [comment]
Are you still getting this, I can't reproduce?
