### ISSUE TITLE
Extension Error: You must provide a url to the driver

### ISSUE THREAD

**Issue by nagarajuepuri** [GoogleChrome/lighthouse#1241]
**Lighthouse Version**: 1.3.0
**Chrome Version**: 55.0.2883.95
**Error Message**: You must provide a url to the driver
**Stack Trace**:
 ```Error: You must provide a url to the driver
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11221:29)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:12188:17)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:12201:25)```

sky.com is one url that triggers this.

**Comment by wardpeet** [comment]
@nagarajuepuri  would it be possible to share the url with us that you are trying it on.

**Comment by ebidel** [comment]
Dupelicate of https://github.com/GoogleChrome/lighthouse/issues/1214.
