### ISSUE TITLE
Cannot find module 'debug/browser' when running 'npm run watch' for lighthouse-extension

### ISSUE THREAD

**Issue by yajiex** [GoogleChrome/lighthouse#1261]
I just sync the latest code, navigate to `lighthouse-extension` folder and run `npm install` (both under the root path and lighthouse-extensions path) and `npm run watch`, the following errors come, maybe a global environment issue or what else do I need to do?

```
E:\Personal\lighthouse\lighthouse-extension>npm run watch

> lighthouse@ watch E:\Personal\lighthouse\lighthouse-extension
> gulp watch

[14:51:31] Using gulpfile E:\Personal\lighthouse\lighthouse-extension\gulpfile.js
[14:51:31] Starting 'lint'...
[14:51:31] Starting 'browserify'...
[14:51:31] Starting 'browserify-lighthouse'...
[14:51:31] Starting 'html'...
[14:51:31] Finished 'html' after 764 ms
[14:51:32] Finished 'lint' after 1 s
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: Cannot find module 'debug/browser' from 'E:\Personal\lighthouse\lighthouse-core\lib'
    at E:\Personal\lighthouse\lighthouse-extension\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (E:\Personal\lighthouse\lighthouse-extension\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (E:\Personal\lighthouse\lighthouse-extension\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (E:\Personal\lighthouse\lighthouse-extension\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (E:\Personal\lighthouse\lighthouse-extension\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at E:\Personal\lighthouse\lighthouse-extension\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by Janpot** [comment]
you need to `npm install` in the main folder, not the `lighthouse-extension` folder

**Comment by yajiex** [comment]
@Janpot, Hi Janpot, in fact I ever tried `npm install` both the root path and `lighthouse-extension`, the error still shows.

**Comment by Janpot** [comment]
I see, `debug` package was updated. It looks like lighthouse has a bad way of importing it. Will look a bit further into this.

**Comment by wardpeet** [comment]
@yajiex try to do a `npm install debug@2.2.0`or a `yarn` in lighthouse-core and lighthouse-extension. Or wait for @janpot PR #1272
