### ISSUE TITLE
PROTOCOL_TIMEOUT from `redirects-http`

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#12636]
consistent repro for me locally with CLI.
Doesn't happen in CDT.
Error in LR (when PWA checked): `Rendering canceled - timeout during idle.`

ref #6512

```
yarn start https://www.delicious.com.au/ --only-audits=redirects-http

...

waitFor:warn Timed out waiting for page load. Checking if page is hung... +54s
  waitFor:warn Page appears to be hung, killing JavaScript... +11s
  status Disconnecting from browser... +42s
  ChromeLauncher Killing Chrome instance 41162 +1ms
  Driver:warn clearDataForOrigin timed out +11s
  GatherRunner disconnect:error connect ECONNREFUSED 127.0.0.1:50656 +22ms
  CLI:warn Warning: Chrome process could not be killed because it already exited. +171ms
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Emulation.setScriptExecutionDisabled)
LHError: PROTOCOL_TIMEOUT
    at Timeout.<anonymous> (/Users/cjamcl/src/lighthouse/lighthouse-core/gather/driver.js:322:21)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
error Command failed with exit code 1.
```

**Comment by connorjclark** [comment]
Another:

```
yarn start https://los40.com/pruebas/mj/carga/1571272256_339300_sinpubli.html --only-audits=redirects-http
```

**Comment by patrickhulce** [comment]
AFAICT these are all caused by us blocking their resources on redirect pass (to speed up page load) causes the page to go into an infinite loop which we can never recover from. 


Perhaps something to keep in mind for future multi-pass setups.

**Comment by connorjclark** [comment]
Perhaps empty 200 responses would have been more appropriate.

**Comment by patrickhulce** [comment]
> Perhaps empty 200 responses would have been more appropriate.

I'm have to think that would probably send some pages (possibly different ones) into other loops. Like the `<img onerror="this.src = '/404'>` bug, these are page bugs, but we should find a way to gracefully handle them which apparently halting script execution does not do :/

**Comment by patrickhulce** [comment]
ref https://github.com/GoogleChrome/lighthouse/issues/12382#issuecomment-826869326
