### ISSUE TITLE
`yarn build:all` throws exception upon building from source

### ISSUE THREAD

**Issue by svkrclg** [GoogleChrome/lighthouse#12800]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

N/A

### What happened?

(Proposing a patch ) I was trying to build it from source code according to the documentation [here](https://github.com/GoogleChrome/lighthouse/#setup). But on running the fourth step (`yarn build:all`) it threw an exception since Lighthouse was trying to build the `/dist` and hence deleting the existing ones first.

### What did you expect?

I expect a successful execution of the above step which will build all the necessary pages and viewers.

### What have you tried?

I tried commenting few lines of code that were executing `fs.rmdirsync()` during this step of `yarn build` and it worked.
My question is, should I open a PR for this issue since it is problematic for everyone on their first build?

### How were you running Lighthouse?

CLI

### Lighthouse Version

8.1.0

### Chrome Version

90.0.4430.212

### Node Version

v16.5.0

### Relevant log output

```shell
node:internal/fs/utils:343
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/home/azureuser/lighthouse/dist/dt-report-resources'
    at Object.statSync (node:fs:1526:3)
    at __node_internal_ (node:internal/fs/utils:767:8)
    at Object.rmdirSync (node:fs:1146:15)
    at Object.<anonymous> (/home/azureuser/lighthouse/build/build-dt-report-resources.js:29:4)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/home/azureuser/lighthouse/dist/dt-report-resources'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: npm run build-all:task
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.<anonymous> (/home/azureuser/lighthouse/node_modules/npm-run-posix-or-windows/bin/cli.js:18:19)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 21051,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
```

**Comment by hktime** [comment]
Encountered the same problem, any solution yet?

**Comment by svkrclg** [comment]
@hktime yes ofcourse. You can comment out those error producing lines.

**Comment by connorjclark** [comment]
> at Object.<anonymous> (/home/azureuser/lighthouse/build/build-dt-report-resources.js:29:4)

https://github.com/GoogleChrome/lighthouse/blob/43b11e0/build/build-dt-report-resources.js#L29

Note the `recursive` flag. This line should never fail. Are you using at least Node `12.13.0`, as described in our package.json ?

**Comment by connorjclark** [comment]
minor thing I just noticed: that very next line should also use `recursive`.

**Comment by svkrclg** [comment]
>  Are you using at least Node 12.13.0

yes, I mentioned by node version as `v16.5.0`.

> Note the recursive flag. This line should never fail.

Not sure, since the documentation of `fs` mentioned something else `rmdirSync() `.  [here](https://nodejs.org/api/fs.html#fs_fs_rmdirsync_path_options)

> recursive <boolean> If true, perform a recursive directory removal. In recursive mode, operations are retried on failure. Default: false. Deprecated.

**Comment by hktime** [comment]
node version `v16.5.0`
**Relevant log output**
```
(node:71720) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/admin/code/lighthouse/node_modules/mold-source-map/package.json' of 'mold-source-map.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/fs/utils:343
    throw err;
    ^

Error: ENOENT: no such file or directory, stat '/Users/admin/code/lighthouse/dist/dt-report-resources'
    at Object.statSync (node:fs:1526:3)
    at __node_internal_ (node:internal/fs/utils:767:8)
    at Object.rmdirSync (node:fs:1146:15)
    at Object.<anonymous> (/Users/admin/code/lighthouse/build/build-dt-report-resources.js:28:4)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/Users/admin/code/lighthouse/dist/dt-report-resources'
}
error Command failed with exit code 1.
```

**Comment by svkrclg** [comment]
Well, I was following the documentation [here](https://github.com/GoogleChrome/lighthouse/blob/master/CONTRIBUTING.md#contributing-a-patch) to get started with my first PR but this was not expected 😕

**Comment by connorjclark** [comment]
Sorry for the trouble all, should all be good now!
