### ISSUE TITLE
flaky test `safelySetBlobHref`

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#12934]
```
FAIL report/test/renderer/dom-test.js
  ● DOM › safelySetBlobHref › sets href for safe blob types

    TypeError: The "obj" argument must be an instance of Blob. Received an instance of Blob

      178 |       throw new Error('Unsupported blob type');
      179 |     }
    > 180 |     const href = URL.createObjectURL(blob);
          |                      ^
      181 |     elem.href = href;
      182 |   }
      183 |

      at DOM.safelySetBlobHref (report/renderer/dom.js:180:22)
      at report/test/renderer/dom-test.js:213:13
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (report/test/renderer/dom-test.js:211:9)
```

https://github.com/GoogleChrome/lighthouse/pull/12930/checks?check_run_id=3364452167#step:12:338

Saw this in two different PRs, both for node 16

**Comment by connorjclark** [comment]
lol just read  the error message

> argument must be an instance of Blob. Received an instance of Blob

what more do you want!

**Comment by connorjclark** [comment]
node 16 implemented `URL.createObjectURL`. we mock that function but only if it does not exist https://github.com/GoogleChrome/lighthouse/blob/1d4092f/report/test/renderer/dom-test.js#L30

however, the native function expects something of type `require('node:buffer').Blob`, now jsdom's `Blob`.

a fix is to just always mock `URL.createObjectURL`.
