### ISSUE TITLE
Hangs on walmart.com

### ISSUE THREAD

**Issue by HenrikJoreteg** [GoogleChrome/lighthouse#13428]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.walmart.com

### What happened?

It hangs and never completes.

This happens both when I run it from the CLI and when I run it in devtools. But not for other sites.

### What did you expect?

Lighthouse to give me a perf score.

### What have you tried?

Tried it on multiple different laptops, via devtools and via lighthouse CLI directly.

I've also tried blocking the bot-detection script to avoid any potential redirects.

### How were you running Lighthouse?

CLI, Chrome DevTools

### Lighthouse Version

9.0.0 (cli)

### Chrome Version

96.0.4664.55 (Official Build) (x86_64)

### Node Version

NA

### OS

Mac

### Relevant log output

```shell
$ lighthouse --version
9.0.0
$ lighthouse https://www.walmart.com                                                                       
  LH:ChromeLauncher Waiting for browser. +0ms
  LH:ChromeLauncher Waiting for browser... +0ms
  LH:ChromeLauncher Waiting for browser..... +511ms
  LH:ChromeLauncher Waiting for browser....... +502ms
  LH:ChromeLauncher Waiting for browser......... +504ms
  LH:ChromeLauncher Waiting for browser........... +503ms
  LH:ChromeLauncher Waiting for browser...........✓ +2ms
  LH:config:warn IFrameElements gatherer requested, however no audit requires it. +616ms
  LH:config:warn FormElements gatherer requested, however no audit requires it. +0ms
  LH:status Connecting to browser +105ms
  LH:status Resetting state with about:blank +141ms
  LH:status Navigating to about:blank +0ms
  LH:status Benchmarking machine +42ms
  LH:status Initializing… +1s
  LH:status Preparing target for navigation mode +3ms
  LH:status Running defaultPass pass CSSUsage, JsUsage, ViewportDimensions, ConsoleMessages, AnchorElements, ImageElements, LinkElements, MetaElements, ScriptElements, IFrameElements, FormElements, MainDocumentContent, GlobalListeners, Doctype, DOMStats, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, FontSize, EmbeddedContent, RobotsTxt, TapTargets, Accessibility, TraceElements, InspectorIssues, SourceMaps, FullPageScreenshot +11ms
  LH:status Resetting state with about:blank +0ms
  LH:status Navigating to about:blank +0ms
  LH:status Preparing target for navigation +12ms
  LH:status Cleaning origin data +7ms
  LH:status Cleaning browser cache +7ms
  LH:status Preparing network conditions +46ms
  LH:status Beginning devtoolsLog and trace +12ms
  LH:status Loading page & waiting for onload +89ms
  LH:status Navigating to https://www.walmart.com/ +0ms
  LH:waitFor:warn Timed out waiting for page load. Checking if page is hung... +45s
  LH:waitFor:warn Page appears to be hung, killing JavaScript... +1s
  LH:status Disconnecting from browser... +30s
  LH:status Cleaning origin data +0ms
  LH:ChromeLauncher Killing Chrome instance 83431 +2ms
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Emulation.setScriptExecutionDisabled)
LHError: PROTOCOL_TIMEOUT
    at /Users/vn0uatr/.nvm/versions/node/v16.6.2/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:341:50
    at new Promise (<anonymous>)
    at Driver.sendCommandToSession (/Users/vn0uatr/.nvm/versions/node/v16.6.2/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:339:28)
    at Driver.sendCommand (/Users/vn0uatr/.nvm/versions/node/v16.6.2/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:362:17)
    at /Users/vn0uatr/.nvm/versions/node/v16.6.2/lib/node_modules/lighthouse/lighthouse-core/gather/driver/wait-for-condition.js:469:23
    at async Promise.all (index 0)
    at async Object.gotoURL (/Users/vn0uatr/.nvm/versions/node/v16.6.2/lib/node_modules/lighthouse/lighthouse-core/gather/driver/navigation.js:120:26)
    at async Function.loadPage (/Users/vn0uatr/.nvm/versions/node/v16.6.2/lib/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:74:36)
    at async Function.runPass (/Users/vn0uatr/.nvm/versions/node/v16.6.2/lib/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:586:49)
    at async Function.run (/Users/vn0uatr/.nvm/versions/node/v16.6.2/lib/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:509:29)
```

**Comment by HenrikJoreteg** [comment]
Hey @paulirish 👋 . It's been a long time, hope you're doing well. I know @devtools-bot lumped this into the `PROTOCOL_TIMEOUT` issue and closed it, but I'm not convinced it's the same.

It all seems to first go wrong in this step:

```
LH:status Navigating to https://www.walmart.com/ +0ms
LH:waitFor:warn Timed out waiting for page load. Checking if page is hung... +45s
LH:waitFor:warn Page appears to be hung, killing JavaScript... +1s
```

It happens on every run I do against walmart.com, this feels like a bigger thing than what is described in that protocol issue. But I could certainly be wrong.

**Comment by paulirish** [comment]
@HenrikJoreteg sorry i'm late getting back to you on this. can you still reproduce this?

while trying i had to deal with a "are you a bot?" prompt, but did and now my subsequent runs load the mobile homepage successfully. but nothing gets hung. i'll try a few more ways tho.

**Comment by HenrikJoreteg** [comment]
Sorry for the false alarm. It hangs and fails both on an off the VPN on the walmart issued laptop (both LH version 9.0.0 and 9.1.0), but... I just tried it and works fine on my personal machine.  Although, the site thinks LH is a bot.  But it still hangs either way on the walmart machine.

Not sure what is going on w/ the walmart laptop, but this appears to not be directly related to LH. I'll close it.
