### ISSUE TITLE
Extension Error: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by lanes** [GoogleChrome/lighthouse#1345]
**Lighthouse Version**: 1.3.2
**Chrome Version**: 55.0.2883.95
**Error Message**: Failed to construct 'URL': Invalid URL
**Stack Trace**:
 ```TypeError: Failed to construct 'URL': Invalid URL
    at artifacts.AnchorsWithNoRelNoopener.usages.filter.anchor (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:691:47)
    at Array.filter (native)
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:691:8)
    at Promise.resolve.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11395:20)```

**Comment by patrickhulce** [comment]
@lanes would you be willing to provide the url you were testing with?

Looks like another edge case of `href` but not sure if it should be surfaced in the report or not without knowing where it sends you.

**Comment by lanes** [comment]
For sure, thanks @patrickhulce !

Here's the URL -- http://www.margaretelizabeth.com/

**Comment by patrickhulce** [comment]
Looks like it's failing on anchors with `href="http://"`. PR pending to provide better debug info and not crash in these cases.

**Comment by lanes** [comment]
Cool, thanks @patrickhulce!
