### ISSUE TITLE
Extension Error: Protocol error (Storage.clearDataForOrigin): Internal error

### ISSUE THREAD

**Issue by adben** [GoogleChrome/lighthouse#1353]
**Lighthouse Version**: 1.3.2
**Chrome Version**: 57.0.2966.0
**Error Message**: Protocol error (Storage.clearDataForOrigin): Internal error
**Stack Trace**:
 ```Error: Protocol error (Storage.clearDataForOrigin): Internal error
    at ExtensionConnection.handleRawError (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:7382:11)
    at Object.chrome.debugger.sendCommand.result [as callback] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:7532:33)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)```

**Comment by ebidel** [comment]
Can you let us know how to reproduce and the URL you were testing against?

**Comment by ebidel** [comment]
I'm getting this reliably on the latest Canary 57.0.2966.0.

**Comment by patrickhulce** [comment]
I just started getting this as well

**Comment by patrickhulce** [comment]
Investigating a potential culprit CL in the devtools backend.

**Comment by patrickhulce** [comment]
Seems like it was introduced by this [CL](https://codereview.chromium.org/2590293003) working on a patch now

**Comment by AdrianoCahete** [comment]
Same here

```
C:\> lighthouse https://www.google.com.br/
  Lighthouse CLI Launching Chrome... +0ms
  ChromeLauncher Waiting for browser. +13ms
  ChromeLauncher Waiting for browser... +2ms
  ChromeLauncher Waiting for browser...√ +1s
  status Initializing… +1s
  method <= browser ERR:error Storage.clearDataForOrigin  +36ms
  status Disconnecting from browser... +2ms
  ChromeLauncher Killing all Chrome Instances +2ms
Runtime error encountered: Error: Protocol error (Storage.clearDataForOrigin): Internal error
    at CriConnection.handleRawError (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-core\gather\connections\connection.js:132:11)
    at callback.resolve.Promise.resolve.then._ (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-core\gather\connections\connection.js:101:23)
Error: Protocol error (Storage.clearDataForOrigin): Internal error
    at CriConnection.handleRawError (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-core\gather\connections\connection.js:132:11)
    at callback.resolve.Promise.resolve.then._ (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-core\gather\connections\connection.js:101:23)
```

**Comment by patrickhulce** [comment]
Fix has [landed](https://codereview.chromium.org/2608793002/), should be fixed on next Canary build

**Comment by ebidel** [comment]
Not seeing this on the latest Canary. If you all update and still see it, let us know.
