### ISSUE TITLE
Lighthouse Not Working for certain URLs

### ISSUE THREAD

**Issue by prateek552** [GoogleChrome/lighthouse#13645]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.vaseline.com/in/en, https://www.vaseline.com/in/en/products.html

### What happened?

I run lighthouse on multiple urls on multiple occasions but it always fails for these two specific urls. I am running the lighthouse on ec2. I have tried multiple configuration and multiple versions of lighthouse but it fails for all of them.

We are using these configurations - 

```
{
      args: [...chromeLauncher.args, '--disable-dev-shm-usage'],
      defaultViewport: chromeLauncher.defaultViewport,
      executablePath: await chromeLauncher.executablePath,
      headless: chromeLauncher.headless,
  }
```

The options are 

```
{
      output: "json",
      onlyCategories: ["performance", "accessibility", "seo", "best-practices"],
      port: new URL(chrome.wsEndpoint()).port,
   }
```

### What did you expect?

We are getting this error

2022-02-08T12:50:25.344Z 9cacff7b-5fdf-5fc8-93c5-a50736c2826a INFO Error: not opened
at WebSocket.send (/var/task/node_modules/lighthouse/node_modules/ws/lib/WebSocket.js:344:18)
at CriConnection.sendRawMessage (/var/task/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:167:14)
at CriConnection.sendCommand (/var/task/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:66:10)
at Driver._innerSendCommand (/var/task/node_modules/lighthouse/lighthouse-core/gather/driver.js:421:29)
at /var/task/node_modules/lighthouse/lighthouse-core/gather/driver.js:383:35
at new Promise (<anonymous>)
at Driver.sendCommandToSession (/var/task/node_modules/lighthouse/lighthouse-core/gather/driver.js:374:12)
at Driver.sendCommand (/var/task/node_modules/lighthouse/lighthouse-core/gather/driver.js:401:17)
at ExecutionContext._evaluateInContext (/var/task/node_modules/lighthouse/lighthouse-core/gather/driver/execution-context.js:104:42)

### How were you running Lighthouse?

node

### Lighthouse Version

7.2 / 8 / 9.2

**Comment by connorjclark** [comment]
Were there logs?

**Comment by alexnj** [comment]
Closing this old issue out; please feel free to reopen if the issue still persists.
