### ISSUE TITLE
Extension Error: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by thangchung** [GoogleChrome/lighthouse#1375]
I could not run lighthouse in my browser. Don't know about the reason, just after run it always threw this exception:

**Lighthouse Version**: 1.3.2
**Chrome Version**: 55.0.2883.87
**Error Message**: Failed to construct 'URL': Invalid URL
**Stack Trace**:
 ```TypeError: Failed to construct 'URL': Invalid URL
    at artifacts.DateNowUse.usage.filter.err (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:1054:24)
    at Array.filter (native)
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:1050:48)
    at Promise.resolve.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:11395:20)```

Could anyone help me to explain this? I will be very appreciated that. Thanks.

**Comment by cpheimbach** [comment]
check this one. I deactivated my redux dev tool extension and it worked. Solution discussed here: https://github.com/GoogleChrome/lighthouse/issues/1282

Please let the community know in case you find another extension that makes trouble. Cheers!

**Comment by thangchung** [comment]
@cpheimbach It works. Thanks for your help 👍
