### ISSUE TITLE
Lighthouse may end with an unhandled rejection due to an invalid URL

### ISSUE THREAD

**Issue by panthony** [GoogleChrome/lighthouse#13956]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.salesforce.com/au/editions-pricing/quip/%00

### What happened?

Using the following pattern:

```js
try {
  await lighthouse(url, {});
} catch (lhError) {
  //
}
```

An unhandled rejection is thrown (eventually caught by a listener on `unhandledRejection` in `process`):

```
 Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at Function.fromProtocolMessage (/.../node_modules/lighthouse/lighthouse-core/lib/lh-error.js:148:19)
    at /.../node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:141:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  protocolMethod: 'Page.navigate',
  protocolError: 'Cannot navigate to invalid URL'
}
```

Then, once timeout is reached (I believe), I receive this same error as `lhError`.

### What did you expect?

No unhandled promise or run stuck until the timeout.

Whether it should return an `LHError` error instead with an `INVALID_URL` code I can't really tell.

### What have you tried?

Ran lighthouse CLI using the latest version:

> lighthouse --version
> 9.5.0

> lighthouse "https://www.salesforce.com/au/editions-pricing/quip/%00" --skip-audits --disable-storage-reset

And got:

```
  LH:status Preparing network conditions +1ms
  LH:status Beginning devtoolsLog and trace +14ms
  LH:status Loading page & waiting for onload +83ms
  LH:status Navigating to https://www.salesforce.com/au/editions-pricing/quip/%00 +0ms
  LH:method <= browser ERR:error Page.navigate  +5ms
Unhandled Rejection. Reason: Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
  LH:ChromeLauncher Killing Chrome instance 67680 +1ms
```

Whereas an invalid URL (ex: starting with 'htp://') would end with:

```
  LH:ChromeLauncher Waiting for browser... +0ms
  LH:ChromeLauncher Waiting for browser..... +510ms
  LH:ChromeLauncher Waiting for browser.....✓ +1ms
  LH:ChromeLauncher Killing Chrome instance 67742 +942ms
Runtime error encountered: The URL you have provided appears to be invalid.
LHError: INVALID_URL
    at Function.normalizeUrl (/Users/anthony/.nvm/versions/node/v14.17.3/lib/node_modules/lighthouse/lighthouse-core/lib/url-shim.js:263:13)
    at /Users/anthony/.nvm/versions/node/v14.17.3/lib/node_modules/lighthouse/lighthouse-core/index.js:51:30
    at Function.gather (/Users/anthony/.nvm/versions/node/v14.17.3/lib/node_modules/lighthouse/lighthouse-core/runner.js:170:27)
    at lighthouse (/Users/anthony/.nvm/versions/node/v14.17.3/lib/node_modules/lighthouse/lighthouse-core/index.js:50:34)
    at runLighthouse (file:///Users/anthony/.nvm/versions/node/v14.17.3/lib/node_modules/lighthouse/lighthouse-cli/run.js:252:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### How were you running Lighthouse?

node

### Lighthouse Version

9.5.0

### Node Version

14.17.3

### OS

Mac

**Comment by panthony** [comment]
Just in case a human somehow stumble upon this, doing this in chrome:

``` 
window.location = 'https://www.salesforce.com/au/editions-pricing/quip/%00'
```

Raise the following error:

```
VM402:1 Uncaught DOMException: Failed to set the 'href' property on 'Location': 'https://www.salesforce.com/au/editions-pricing/quip/%00' is not a valid URL.
    at <anonymous>:1:17
```

Whereas CURL does respond:

```
curl -I 'https://www.salesforce.com/au/editions-pricing/quip/%00'
HTTP/2 404
server: Apache
x-frame-options: SAMEORIGIN
last-modified: Wed, 04 May 2022 00:08:04 GMT
x-content-type-options: nosniff
referrer-policy: no-referrer-when-downgrade
x-ua-compatible: IE=9; IE=8; IE=7; IE=EDGE
content-type: text/html
cache-control: max-age=297
expires: Wed, 04 May 2022 06:56:54 GMT
date: Wed, 04 May 2022 06:51:57 GMT
strict-transport-security: max-age=86400
```

**Comment by connorjclark** [comment]
shutup bot

sorry, this is a real bug

**Comment by panthony** [comment]
I created an issue in Chromium since it does not seems valid that the parse fails to begin with:

https://bugs.chromium.org/p/chromium/issues/detail?id=1322359#c1
