### ISSUE TITLE
Missing flow-report/assets folder causes breaking error

### ISSUE THREAD

**Issue by Kosai106** [GoogleChrome/lighthouse#14066]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

*

### What happened?

Attempting to run Lighthouse from within a Cypress test using `@cypress-audit/lighthouse` triggers an error due to the `flow-report/assets` folder no longer being exported to NPM. (I'm guessing this PR is the culprit: https://github.com/GoogleChrome/lighthouse/pull/12855)

Linked issue: https://github.com/mfrachet/cypress-audit/issues/157

### What did you expect?

I expect this not to be an issue and that Lighthouse will work as intended by not ignoring folders it needs to work.

### How were you running Lighthouse?

Other

### Lighthouse Version

9.6.1

### Chrome Version

102.0.5005.61

### Node Version

16.13.0

### OS

MacOS Monterey 12.3.1

### Relevant log output

![Screenshot 2022-05-30 at 15 16 20](https://user-images.githubusercontent.com/6379824/171014035-f709f203-da37-4736-af36-4e13372b2d46.png)

```shell
**Message:** Your `pluginsFile` is invalid: `/Users/**/**/end_to_end/cypress/plugins/index.js`

It threw an error when required, check the stack trace below:

**Details:** Error: ENOENT: no such file or directory, open '/Users/**/**/end_to_end/node_modules/lighthouse/report/generator/../../flow-report/assets/standalone-flow-template.html'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (/Users/**/**/end_to_end/node_modules/lighthouse/report/generator/flow-report-assets.js:11:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/**/**/end_to_end/node_modules/lighthouse/report/generator/report-assets.js:10:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by adamraine** [comment]
`flow-report/assets/standalone-flow-template.html` should be included in the NPM package. I saw it after inspecting the contents of the 9.6.1 package from `npm pack lighthouse`. Same for Lighthouse 9.5.0 which appears to be the version shipped with `@cypress-audit/lighthouse`.

**Comment by Kosai106** [comment]
@adamraine I'll try to set something up tomorrow.

**Comment by Kosai106** [comment]
@adamraine Okay upon further inspection it turns out we had a `.yarnclean` file which removed the assets folder 🤦‍♂️
I had not noticed this at all, many apologies!
