### ISSUE TITLE
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Page.enable)

### ISSUE THREAD

**Issue by boitcex** [GoogleChrome/lighthouse#14154]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.google.com/

### What happened?

I have installed the latest version of the lighthouse: npm install -g lighthouse
Then try to use it: lighthouse https://www.google.com/
Chrome is opening, but the needed page isn't being opened.
Finally, everything is crashed and we have an error in the console: 
Reason: The operation attempted is not supported.
 +168ms
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Page.enable)
LHError: PROTOCOL_TIMEOUT
   

### What did you expect?

The web page is opened

### What have you tried?

tried to re-install everything from scratch, played with different versions, googling a lot

### How were you running Lighthouse?

CLI

### Lighthouse Version

9.6.2

### Chrome Version

Version 103.0.5060.53 (Official Build) (64-bit)

### Node Version

16.15.1

### OS

Windows

### Relevant log output

```shell
C:\WINDOWS\system32>lighthouse https://www.google.com/
  LH:ChromeLauncher Waiting for browser. +0ms
  LH:ChromeLauncher Waiting for browser... +1ms
  LH:ChromeLauncher Waiting for browser..... +507ms
  LH:ChromeLauncher Waiting for browser.....√ +2ms
  LH:config:warn IFrameElements gatherer requested, however no audit requires it. +514ms
  LH:config:warn Inputs gatherer requested, however no audit requires it. +0ms
  LH:status Connecting to browser +86ms
  LH:status Resetting state with about:blank +32ms
  LH:status Navigating to about:blank +1ms
  LH:status Disconnecting from browser... +30s
  LH:status Cleaning origin data +1ms
  LH:ChromeLauncher Killing Chrome instance 10360 +4ms
  LH:ChromeLauncher:error taskkill stderr ERROR: The process with PID 16744 (child process of PID 10360) could not be terminated.
Reason: The operation attempted is not supported.
 +194ms
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Page.enable)
LHError: PROTOCOL_TIMEOUT
    at C:\Users\Roman_Voitseshevskyi\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-core\gather\driver.js:348:50
    at new Promise (<anonymous>)
    at Driver.sendCommandToSession (C:\Users\Roman_Voitseshevskyi\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-core\gather\driver.js:346:28)
    at Driver.sendCommand (C:\Users\Roman_Voitseshevskyi\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-core\gather\driver.js:369:17)
    at NetworkMonitor.enable (C:\Users\Roman_Voitseshevskyi\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-core\gather\driver\network-monitor.js:111:25)
    at Object.gotoURL (C:\Users\Roman_Voitseshevskyi\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-core\gather\driver\navigation.js:95:24)
    at Function.loadBlank (C:\Users\Roman_Voitseshevskyi\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-core\gather\gather-runner.js:52:22)
    at Function.run (C:\Users\Roman_Voitseshevskyi\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-core\gather\gather-runner.js:487:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function._gatherArtifactsFromBrowser (C:\Users\Roman_Voitseshevskyi\AppData\Roaming\npm\node_modules\lighthouse\lighthouse-core\runner.js:264:23)
```

**Comment by boitcex** [comment]
![2022-06-24_16h14_41](https://user-images.githubusercontent.com/2488949/175543526-a77c0811-8f93-41a1-a199-2fe447867d42.png)

**Comment by connorjclark** [comment]
This happens every time for you?

**Comment by connorjclark** [comment]
can you share the domains
