### ISSUE TITLE
Extension Error: Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by saulogm** [GoogleChrome/lighthouse#1427]
**Lighthouse Version**: 1.4.1
**Chrome Version**: 55.0.2883.87
**URL**: http://10.1.10.7:8011/h_home.apw
**Error Message**: Cannot read property 'children' of undefined
**Stack Trace**:
 ```TypeError: Cannot read property 'children' of undefined
    at artifacts.requestCriticalRequestChains.then.chains (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:560:62)```

**Comment by ebidel** [comment]
repros: https://www.chiarezza.it/preventivo-assicurazione/rc-auto-1

**Comment by alvaropinot** [comment]
+1 trying to use lighthouse cli


**Lighthouse Version:** 1.4.1

```
ChromeLauncher Killing all Chrome Instances +2ms
Runtime error encountered: TypeError: Cannot read property 'children' of undefined
    at artifacts.requestCriticalRequestChains.then.chains (/node_modules/lighthouse/lighthouse-core/audits/critical-request-chains.js:68:62)
TypeError: Cannot read property 'children' of undefined
    at artifacts.requestCriticalRequestChains.then.chains (/node_modules/lighthouse/lighthouse-core/audits/critical-request-chains.js:68:62)
```

at 

```
npm ERR! Darwin 16.3.0
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
```
