### ISSUE TITLE
Lighthouse not running and giving error on a website in Chrome canary: PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by jitendravyas** [GoogleChrome/lighthouse#14318]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://vwo.com

### What happened?

I am getting an error every time I try to run lighthouse

<img width="972" alt="image" src="https://user-images.githubusercontent.com/77309/186721335-bc23703b-495f-465c-91e6-71871eaf2cab.png">

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/77309/186721216-0743f66f-aed9-4958-b98e-6da74ceb8fd1.png">

### What did you expect?

Lighthouse should run as usual

### What have you tried?

I tried to run the lighthouse multiple times

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

I can't see the version of lighthouse because It not running for me

### Chrome Version

Chrome Canary Version 107.0.5260.0 (Official Build) canary (x86_64

### OS

Mac 12.5.1

### Relevant log output

```shell
PROTOCOL_TIMEOUT

Channel: DevTools
Initial URL: https://vwo.com/
Chrome Version: 107.0.0.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:842
    at new Promise (<anonymous>)
    at Driver$5.sendCommandToSession (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:794)
    at Driver$5.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:168:33)
    at Object.getImportantStorageWarning (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:185:430)
    at resetStorageForUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:436)
    at Object.prepareTargetForIndividualNavigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:565)
    at GatherRunner$1.runPass (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:232:633)
    at async GatherRunner$1.run (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:231:810)
    at async Runner$9._gatherArtifactsFromBrowser (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:353:872)
```

**Comment by connorjclark** [comment]
Tried it once in 107 and it worked for me.

Try unchecking "clear storage"
