### ISSUE TITLE
Lighthouse Stack Trace: LHError: PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by imbharat420** [GoogleChrome/lighthouse#14380]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/master/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://web.dev/codelab-use-lazysizes-to-lazyload-images/

### What happened?

Not working properly

### What did you expect?

Not working properly

### What have you tried?

Having error while Auditing a website

![image](https://user-images.githubusercontent.com/51924618/189470677-3baeeeb3-3f80-4911-a910-64ba008adf3e.png)

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

9.6.1

### Chrome Version

104.0.5112.81

### Node Version

v18.8.0

### OS

Arch Linux

### Relevant log output

```shell
PROTOCOL_TIMEOUT

Channel: DevTools
Initial URL: https://web.dev/codelab-use-lazysizes-to-lazyload-images/
Chrome Version: 104.0.5112.81
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:167:841
    at new Promise (<anonymous>)
    at Driver$5.sendCommandToSession (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:167:793)
    at Driver$5.sendCommand (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:168:33)
    at Object.clearBrowserCaches (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:185:150)
    at resetStorageForUrl (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:188:530)
    at async Object.prepareTargetForIndividualNavigation (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:188:369)
    at async GatherRunner$1.runPass (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:232:624)
    at async GatherRunner$1.run (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:231:810)
    at async Runner$9._gatherArtifactsFromBrowser (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:353:872)
```

**Comment by Kingmax1981** [comment]
****

**Comment by Kingmax1981** [comment]
😫
