### ISSUE TITLE
Lighthouse Report Error

### ISSUE THREAD

**Issue by VRAshwa** [GoogleChrome/lighthouse#14475]
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://www.vrashwa.com/
Chrome Version: 103.0.0.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:841
    at new Promise (<anonymous>)
    at Driver$5.sendCommandToSession (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:793)
    at Driver$5.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:168:33)
    at Object.clearBrowserCaches (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:185:150)
    at resetStorageForUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:530)
    at async Object.prepareTargetForIndividualNavigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:369)
    at async GatherRunner$1.runPass (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:232:624)
    at async GatherRunner$1.run (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:231:810)
    at async Runner$9._gatherArtifactsFromBrowser (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:353:872)
```

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/issues/6512
