### ISSUE TITLE
Evaluation exception: TypeError: Promise is not a constructor

### ISSUE THREAD

**Issue by mahmoodhormati** [GoogleChrome/lighthouse#14639]
Evaluation exception: TypeError: Promise is not a constructor
    at wrapInNativePromise (<anonymous>:7:16)
    at <anonymous>:17:8
```
Channel: DevTools
Initial URL: http://localhost:3000/dashboard
Chrome Version: 108.0.0.0
Stack Trace: Error: Evaluation exception: TypeError: Promise is not a constructor
    at wrapInNativePromise (<anonymous>:7:16)
    at <anonymous>:17:8
    at ExecutionContext$3._evaluateInContext (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:120:922)
    at async ExecutionContext$3.evaluateAsync (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:121:326)
```

**Comment by adamraine** [comment]
Can you provide a page that reproduces this error?
