### ISSUE TITLE
TypeError on www.visa.com.hk

### ISSUE THREAD

**Issue by adamraine** [GoogleChrome/lighthouse#14643]
Moving https://github.com/GoogleChrome/lighthouse/issues/14631#issuecomment-1365982938 to a separate issue. Content copied below:

-----

Got similar issues on some URLs of `www.visa.com.hk`:

Ex: https://www.visa.com.kh/en_KH/travel-with-visa/destinations/paris.html

Running it on PageSpeed insights too.

**edit**

Digging the error locally this is due to a JS error on the page:

```
bundle.js?as:1 Unhandled promise rejection Error: TypeError: null is not a function
    at navigation.js:1:89935
    at navigation.js:1:89168
    at Object.throw (navigation.js:1:89273)
    at a (navigation.js:1:88062)
```

It somehow "leaks" in lighthouse:

```
Error: Evaluation exception: TypeError: null is not a function
    at t.exports (https://cdn.visa.com/cdn/scripts/cms-ui/bundle.js?as:1:84499)
    at new W (https://cdn.visa.com/cdn/scripts/cms-ui/bundle.js?as:1:146671)
    at t.then (https://cdn.visa.com/cdn/scripts/offers/elements.js:1:17224)
    at https://cdn.visa.com/cdn/scripts/cms-ui/bundle.js?as:1:147410
    at new W (https://cdn.visa.com/cdn/scripts/cms-ui/bundle.js?as:1:146707)
    at t.p.unsafe [as then] (https://cdn.visa.com/cdn/scripts/cms-ui/bundle.js?as:1:147388)
    at Promise.R.t.then (https://cdn.visa.com/cdn/scripts/offers/elements.js:1:18142)
    at ExecutionContext._evaluateInContext (/path/to/lighthouse/lighthouse-core/gather/driver/execution-context.js:116:29)
```

The exception is raised by:

```js
    const response = await this._session.sendCommand('Runtime.evaluate', evaluationParams);
    if (response.exceptionDetails) {
      // An error occurred before we could even create a Promise, should be *very* rare.
      // Also occurs when the expression is not valid JavaScript.
      const errorMessage = response.exceptionDetails.exception ?
        response.exceptionDetails.exception.description :
        response.exceptionDetails.text;
      return Promise.reject(new Error(`Evaluation exception: ${errorMessage}`));
    }
```

Not sure how I could recover from this to simply "ignore" the issue like the browser does.

**edit 2**

In practice, every call to `.evaluate()` fails with this exception.

**edit 3**

![Capture d’écran 2022-12-28 à 07 48 02](https://user-images.githubusercontent.com/230462/209770489-947265a1-b99e-44db-9b6c-82b2e77d22ad.png)

**Comment by connorjclark** [comment]
no longer errors
