### ISSUE TITLE
Error: Protocol error (CSS.startRuleUsageTracking): 'CSS.startRuleUsageTracking' wasn't found

### ISSUE THREAD

**Issue by wardpeet** [GoogleChrome/lighthouse#1473]
When doing a lighthouse run (latest master) on current stable chrome I get the error that startRuleUsageTracking is not found. (luckily it's not an issue in latest npm version)

Command rule `lighthouse --disable-device-emulation --disable-cpu-throttling https://airhorner.com --output=json --select-chrome`

```
status Retrieving: HTMLWithoutJavaScript +2ms
  method <= browser ERR:error CSS.startRuleUsageTracking +345ms
  status Disconnecting from browser... +1ms
  ChromeLauncher Killing all Chrome Instances +1ms
Runtime error encountered: Error: Protocol error (CSS.startRuleUsageTracking): 'CSS.startRuleUsageTracking' wasn't found
    at CriConnection.handleRawError (/Volumes/MAC_EXTRA/Projects/tmp/lighthouse/lighthouse-core/gather/connections/connection.js:134:11)
    at callback.resolve.Promise.resolve.then._ (/Volumes/MAC_EXTRA/Projects/tmp/lighthouse/lighthouse-core/gather/connections/connection.js:103:23)
Error: Protocol error (CSS.startRuleUsageTracking): 'CSS.startRuleUsageTracking' wasn't found
    at CriConnection.handleRawError (/Volumes/MAC_EXTRA/Projects/tmp/lighthouse/lighthouse-core/gather/connections/connection.js:134:11)
    at callback.resolve.Promise.resolve.then._ (/Volumes/MAC_EXTRA/Projects/tmp/lighthouse/lighthouse-core/gather/connections/connection.js:103:23)
```

@patrickhulce can you look at this? It's probably not supported in chrome 55 yet

**Comment by patrickhulce** [comment]
Ah yes, it hits stable in 56.

**Comment by nathanjd** [comment]
Thanks for the quick fix!
