### ISSUE TITLE
Protocol_Timeout

### ISSUE THREAD

**Issue by theexcitedquestion** [GoogleChrome/lighthouse#14929]
Every report I am trying to run on several different websites is having the same issue. Lighthouse says if it is reproducible to report it here. Below is all the messages I get when trying to run a report. I did this on several sites and got a similar response every time so then I moved to bigger better managed sites and got the same response. I tried the mobile and desktop reports.  

PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://flintavenue.com/
Chrome Version: 110.0.0.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:842
    at new Promise (<anonymous>)
    at Driver$5.sendCommandToSession (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:794)
    at Driver$5.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:168:33)
    at Object.clearBrowserCaches (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:185:150)
    at resetStorageForUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:530)
    at async Object.prepareTargetForIndividualNavigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:369)
    at async GatherRunner$1.runPass (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:232:624)
    at async GatherRunner$1.run (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:231:810)
    at async Runner$9._gatherArtifactsFromBrowser (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:353:872)
```

PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://drill2frac.com/
Chrome Version: 110.0.0.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:842
    at new Promise (<anonymous>)
    at Driver$5.sendCommandToSession (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:794)
    at Driver$5.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:168:33)
    at Object.clearBrowserCaches (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:185:150)
    at resetStorageForUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:530)
    at async Object.prepareTargetForIndividualNavigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:369)
    at async GatherRunner$1.runPass (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:232:624)
    at async GatherRunner$1.run (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:231:810)
    at async Runner$9._gatherArtifactsFromBrowser (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:353:872)
```

PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://drill2frac.com/
Chrome Version: 110.0.0.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:842
    at new Promise (<anonymous>)
    at Driver$5.sendCommandToSession (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:794)
    at Driver$5.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:168:33)
    at Object.clearBrowserCaches (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:185:150)
    at resetStorageForUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:530)
    at async Object.prepareTargetForIndividualNavigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:369)
    at async GatherRunner$1.runPass (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:232:624)
    at async GatherRunner$1.run (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:231:810)
    at async Runner$9._gatherArtifactsFromBrowser (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:353:872)
```

PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://www.dropbox.com/official-teams-page?_tk=paid_sem_goog_biz_b&_camp=18696674559&_kw=dropbox%20com|e&_ad=649958538864||c&gclid=Cj0KCQjwlPWgBhDHARIsAH2xdNdN99tMm2xkPX5ATYayaPCIHQfmZzDWLeMStD4NYu3MTXii84x6E1AaAjHGEALw_wcB
Chrome Version: 110.0.0.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:842
    at new Promise (<anonymous>)
    at Driver$5.sendCommandToSession (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:794)
    at Driver$5.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:168:33)
    at Object.clearBrowserCaches (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:185:150)
    at resetStorageForUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:530)
    at async Object.prepareTargetForIndividualNavigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:369)
    at async GatherRunner$1.runPass (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:232:624)
    at async GatherRunner$1.run (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:231:810)
    at async Runner$9._gatherArtifactsFromBrowser (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:353:872)
```

PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://www.walmart.com/
Chrome Version: 110.0.0.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:842
    at new Promise (<anonymous>)
    at Driver$5.sendCommandToSession (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:167:794)
    at Driver$5.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:168:33)
    at Object.clearBrowserCaches (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:185:150)
    at resetStorageForUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:530)
    at async Object.prepareTargetForIndividualNavigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:188:369)
    at async GatherRunner$1.runPass (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:232:624)
    at async GatherRunner$1.run (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:231:810)
    at async Runner$9._gatherArtifactsFromBrowser (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:353:872)
```

**Comment by adamraine** [comment]
I can't reproduce any of these unfortunately, so going to have to merge into #6512
