### ISSUE TITLE
Unable to build with webpack: Path is undefined.

### ISSUE THREAD

**Issue by shadryck** [GoogleChrome/lighthouse#15007]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://stackblitz.com/edit/node-fnsjsq

### What happened?

Attempting to build typescript webpack project with lighthouse fails with path undefined in esm-utils. I'm unsure whether it is issue in dependency. I'm confused because I'm not seeing other similar issues so surely I must be doing something wrong, but I'm just not seeing it?

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at Object.fileURLToPath (node:internal/url:1485:11)
    at getModulePath (webpack://lighthouse-test/./node_modules/lighthouse/esm-utils.js?:33:43)
    at getModuleDirectory (webpack://lighthouse-test/./node_modules/lighthouse/esm-utils.js?:40:52)
    at eval (webpack://lighthouse-test/./node_modules/lighthouse/shared/localization/locales.js?:37:84)
    at ./node_modules/lighthouse/shared/localization/locales.js (D:\Projects\Nodejs\lighthouse\dist\index.js:4111:1)
    at __webpack_require__ (D:\Projects\Nodejs\lighthouse\dist\index.js:5290:42)
    at eval (webpack://lighthouse-test/./node_modules/lighthouse/shared/localization/format.js?:21:69)
    at ./node_modules/lighthouse/shared/localization/format.js (D:\Projects\Nodejs\lighthouse\dist\index.js:4100:1)
    at __webpack_require__ (D:\Projects\Nodejs\lighthouse\dist\index.js:5290:42) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### What did you expect?

Tried with node versions 18.12.1 and 16.14.2.

### What have you tried?

Build fails all versions forward from 10.0.0, unable to debug further if unable to build bare webpack project.

### How were you running Lighthouse?

node

### Lighthouse Version

10.1.1

### Node Version

18.12.1

### OS

Windows / Linux

### Relevant log output

```shell
❯ npm run start
$ webpack && node ./dist/index.js
asset index.js 3.3 MiB [emitted] (name: main)
asset vendors-node_modules_sentry_node_esm_index_js.index.js 437 KiB [compared for emit] (id hint: vendors)
asset vendors-node_modules_cross-fetch_dist_node-ponyfill_js.index.js 383 KiB [compared for emit] (id hint: vendors)
runtime modules 3.89 KiB 10 modules
orphan modules 28.6 KiB [orphan] 7 modules
cacheable modules 3.35 MiB
  javascript modules 2.91 MiB 529 modules
  json modules 451 KiB
    ./node_modules/third-party-web/dist/entities-nostats.json 197 KiB [built] [code generated]
    ./node_modules/tr46/lib/mappingTable.json 254 KiB [built] [code generated]
+ 28 modules

WARNING in ./node_modules/yargs-parser/build/index.cjs 1029:19-32
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/yargs/build/index.cjs 1:60574-60597 1:61846-61869
 @ ./node_modules/yargs/yargs.mjs 3:0-36 4:68-71
 @ ./node_modules/@puppeteer/browsers/lib/esm/CLI.js 32:0-32 50:30-35
 @ ./node_modules/@puppeteer/browsers/lib/esm/main.js 20:0-53 20:0-53 20:0-53
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js 18:0-151 151:19-46 152:25-49 164:19-54 166:19-51 168:19-52 170:19-54
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/node/node.js 17:0-36 17:0-36
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js 18:0-31 18:0-31
 @ ./node_modules/lighthouse/core/gather/navigation-runner.js 7:0-39 356:26-43
 @ ./node_modules/lighthouse/core/index.js 18:0-63 95:29-45
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/yargs/build/index.cjs 1:437-463
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/yargs/yargs.mjs 3:0-36 4:68-71
 @ ./node_modules/@puppeteer/browsers/lib/esm/CLI.js 32:0-32 50:30-35
 @ ./node_modules/@puppeteer/browsers/lib/esm/main.js 20:0-53 20:0-53 20:0-53
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js 18:0-151 151:19-46 152:25-49 164:19-54 166:19-51 168:19-52 170:19-54
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/node/node.js 17:0-36 17:0-36
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js 18:0-31 18:0-31
 @ ./node_modules/lighthouse/core/gather/navigation-runner.js 7:0-39 356:26-43
 @ ./node_modules/lighthouse/core/index.js 18:0-63 95:29-45
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/yargs/build/index.cjs 1:626-644
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/yargs/yargs.mjs 3:0-36 4:68-71
 @ ./node_modules/@puppeteer/browsers/lib/esm/CLI.js 32:0-32 50:30-35
 @ ./node_modules/@puppeteer/browsers/lib/esm/main.js 20:0-53 20:0-53 20:0-53
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js 18:0-151 151:19-46 152:25-49 164:19-54 166:19-51 168:19-52 170:19-54
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/node/node.js 17:0-36 17:0-36
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js 18:0-31 18:0-31
 @ ./node_modules/lighthouse/core/gather/navigation-runner.js 7:0-39 356:26-43
 @ ./node_modules/lighthouse/core/index.js 18:0-63 95:29-45
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/yargs/build/index.cjs 1:60888-60895
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/yargs/yargs.mjs 3:0-36 4:68-71
 @ ./node_modules/@puppeteer/browsers/lib/esm/CLI.js 32:0-32 50:30-35
 @ ./node_modules/@puppeteer/browsers/lib/esm/main.js 20:0-53 20:0-53 20:0-53
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js 18:0-151 151:19-46 152:25-49 164:19-54 166:19-51 168:19-52 170:19-54
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/node/node.js 17:0-36 17:0-36
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js 18:0-31 18:0-31
 @ ./node_modules/lighthouse/core/gather/navigation-runner.js 7:0-39 356:26-43
 @ ./node_modules/lighthouse/core/index.js 18:0-63 95:29-45
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/yargs/build/index.cjs 1:61280-61287
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/yargs/yargs.mjs 3:0-36 4:68-71
 @ ./node_modules/@puppeteer/browsers/lib/esm/CLI.js 32:0-32 50:30-35
 @ ./node_modules/@puppeteer/browsers/lib/esm/main.js 20:0-53 20:0-53 20:0-53
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js 18:0-151 151:19-46 152:25-49 164:19-54 166:19-51 168:19-52 170:19-54
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/node/node.js 17:0-36 17:0-36
 @ ./node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js 18:0-31 18:0-31
 @ ./node_modules/lighthouse/core/gather/navigation-runner.js 7:0-39 356:26-43
 @ ./node_modules/lighthouse/core/index.js 18:0-63 95:29-45
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/lighthouse/core/config/config-helpers.js 231:19-38
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/lighthouse/core/user-flow.js 14:0-74 76:52-61 77:24-43
 @ ./node_modules/lighthouse/core/index.js 14:0-58 85:13-21 146:15-31
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/lighthouse/core/config/config-helpers.js 234:19-38
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/lighthouse/core/user-flow.js 14:0-74 76:52-61 77:24-43
 @ ./node_modules/lighthouse/core/index.js 14:0-58 85:13-21 146:15-31
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/lighthouse/core/config/config-helpers.js 297:55-66
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)
 @ ./node_modules/lighthouse/core/user-flow.js 14:0-74 76:52-61 77:24-43
 @ ./node_modules/lighthouse/core/index.js 14:0-58 85:13-21 146:15-31
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/lighthouse/core/config/config-helpers.js 520:28-39
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)
 @ ./node_modules/lighthouse/core/user-flow.js 14:0-74 76:52-61 77:24-43
 @ ./node_modules/lighthouse/core/index.js 14:0-58 85:13-21 146:15-31
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/lighthouse/core/config/config.js 36:21-32
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)
 @ ./node_modules/lighthouse/core/user-flow.js 12:0-52 332:37-53
 @ ./node_modules/lighthouse/core/index.js 14:0-58 85:13-21 146:15-31
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/lighthouse/core/legacy/config/config.js 168:51-62
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)
 @ ./node_modules/lighthouse/core/index.js 11:0-63 67:31-60
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/lighthouse/core/lib/i18n/i18n.js 201:43-54
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)
 @ ./node_modules/lighthouse/core/user-flow.js 15:0-43 43:13-36
 @ ./node_modules/lighthouse/core/index.js 14:0-58 85:13-21 146:15-31
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/lighthouse/core/runner.js 29:37-48
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)
 @ ./node_modules/lighthouse/core/index.js 9:0-35 73:26-39 75:11-45 77:9-21 96:9-21 106:9-21 118:11-23 150:9-28
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/lighthouse/report/generator/flow-report-assets.js 12:37-48
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)
 @ ./node_modules/lighthouse/report/generator/report-assets.js 10:0-57 25:5-21
 @ ./node_modules/lighthouse/report/generator/report-generator.js 8:0-48 53:32-70 55:42-70 70:32-75 71:42-75 75:59-87
 @ ./node_modules/lighthouse/core/index.js 15:0-72 130:23-53
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/lighthouse/report/generator/report-assets.js 13:37-48
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)
 @ ./node_modules/lighthouse/report/generator/report-generator.js 8:0-48 53:32-70 55:42-70 70:32-75 71:42-75 75:59-87
 @ ./node_modules/lighthouse/core/index.js 15:0-72 130:23-53
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/lighthouse/root.js 11:35-46
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)
 @ ./node_modules/lighthouse/core/runner.js 24:0-45 93:8-25
 @ ./node_modules/lighthouse/core/index.js 9:0-35 73:26-39 75:11-45 77:9-21 96:9-21 106:9-21 118:11-23 150:9-28
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/lighthouse/shared/localization/format.js 15:37-48
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)
 @ ./node_modules/lighthouse/core/runner.js 18:0-59 120:36-70 126:37-62 244:28-47 386:24-43
 @ ./node_modules/lighthouse/core/index.js 9:0-35 73:26-39 75:11-45 77:9-21 96:9-21 106:9-21 118:11-23 150:9-28
 @ ./src/index.ts 1:0-36 2:0-10

WARNING in ./node_modules/lighthouse/shared/localization/locales.js 31:37-48
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)
 @ ./node_modules/lighthouse/shared/localization/format.js 13:0-37 18:24-31
 @ ./node_modules/lighthouse/core/runner.js 18:0-59 120:36-70 126:37-62 244:28-47 386:24-43
 @ ./node_modules/lighthouse/core/index.js 9:0-35 73:26-39 75:11-45 77:9-21 96:9-21 106:9-21 118:11-23 150:9-28
 @ ./src/index.ts 1:0-36 2:0-10

18 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.80.0 compiled with 18 warnings in 2536 ms
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined
    at TypeError.get (https://nodefnsjsq-fwi0.w-credentialless.staticblitz.com/blitz.95b70c8d.js:35:344852)
    at getStackString (https://nodefnsjsq-fwi0.w-credentialless.staticblitz.com/blitz.95b70c8d.js:35:104948)
    at https://nodefnsjsq-fwi0.w-credentialless.staticblitz.com/blitz.95b70c8d.js:35:100602
    at https://nodefnsjsq-fwi0.w-credentialless.staticblitz.com/blitz.95b70c8d.js:35:102399
    at formatValue (https://nodefnsjsq-fwi0.w-credentialless.staticblitz.com/blitz.95b70c8d.js:35:104785)
    at inspect (https://nodefnsjsq-fwi0.w-credentialless.staticblitz.com/blitz.95b70c8d.js:35:93476)
    at _0x19a412 (https://nodefnsjsq-fwi0.w-credentialless.staticblitz.com/blitz.95b70c8d.js:44:157266)
    at _0x4acf0a (https://nodefnsjsq-fwi0.w-credentialless.staticblitz.com/blitz.95b70c8d.js:37:131929)
    at https://nodefnsjsq-fwi0.w-credentialless.staticblitz.com/blitz.95b70c8d.js:44:108763
    at process._0x2a0003 [as reallyExit] (https://nodefnsjsq-fwi0.w-credentialless.staticblitz.com/blitz.95b70c8d.js:44:108787)
    at _0x7285fd (https://nodefnsjsq-fwi0.w-credentialless.staticblitz.com/blitz.95b70c8d.js:37:260781)
    at _0x139319 (https://nodefnsjsq-fwi0.w-credentialless.staticblitz.com/blitz.95b70c8d.js:63:2344)
    at _0x2f5661.run (https://nodefnsjsq-fwi0.w-credentialless.staticblitz.com/blitz.95b70c8d.js:63:848) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by shadryck** [comment]
There is little that has caused me as much pain and agony as attempting to use webpack 5 with nodejs ESM/CJS node modules.

After further investigation the issue appears to stem from webpack 5 no longer automatically polyfilling native node modules. However neither polyfilling them with 'node-polyfill-webpack-plugin' or excluding node modules with 'webpack-node-externals' will solve this, so I have come to the sane conclusion that the best solution is to purge webpack altogether and touch grass outside.

After doing so, everything is working fine again. I don't imagine any further consideration for adjustment is necessary from lighthouse's side.
