### ISSUE TITLE
CommonJS await import fails with `Error [ERR_REQUIRE_ESM]`

### ISSUE THREAD

**Issue by tkmcmaster** [GoogleChrome/lighthouse#15044]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://github.com/tkmcmaster/lighthouse-commonjs

### What happened?

I was trying to upgrade from lighthouse 9.6.8 to 10.1.1 and adding the updated types. (Thank you for adding typings). We're stuck using CommonJS due to other dependencies that we can't upgrade. I read the changelog saying:

From the [changelog](https://github.com/GoogleChrome/lighthouse/blob/main/changelog.md#for-node-users)
```
...
Converted from CommonJS to ES modules. 
You can still use lighthouse in CommonJS by using an dynamic import: await import('lighthouse'). 
For access to just the lighthouse function in CommonJS, you can also use require('lighthouse/core/index.cjs')
```

When attempting to import `startFlow()` I tried the following and all fail with `Error [ERR_REQUIRE_ESM]: require() of ES Module ...`:
```
const { startFlow } = await import("lighthouse");
const startFlow = await import("lighthouse").startFlow;
const { startFlow } = await import("lighthouse/core");
const startFlow = await import("lighthouse/core").startFlow;
```

Only the pure CJS import works (which doesn't give access to startFlow). See the linked github repo. I am doing a dynamic import but still getting the error that I need to change to a dynamic import.

### What did you expect?

`const { startFlow } = await import("lighthouse");` should work in CommonJS modules.

### What have you tried?

I've tried multiple ways of doing a dynamic import below. Only the pure CJS import works but it doesn't provide access to startFlow.

```
const { startFlow } = await import("lighthouse");
const startFlow = await import("lighthouse").startFlow;
const { startFlow } = await import("lighthouse/core");
const lh = await import("lighthouse/core");
const lighthouse = await import("lighthouse/core/index.cjs");
```

### How were you running Lighthouse?

node

### Lighthouse Version

10.1.1

### Chrome Version

113

### Node Version

16.19.0

### OS

Ubuntu 20.04

### Relevant log output

```shell
[0-0] RUNNING in chrome - file:///build/test/ligthousewdio.spec.js
2023-05-04T17:36:36.024Z WARN chromedriver: [1683221796.024][WARNING]: This version of ChromeDriver has not been tested with Chrome version 113.
[0-0] runLighthouse import
[0-0] single page error Error [ERR_REQUIRE_ESM]: require() of ES Module /home/mcmaster/lighthouse-commonjs/node_modules/lighthouse/core/index.js from /home/mcmaster/lighthouse-commonjs/build/test/ligthousewdio.spec.js not supported.
[0-0] Instead change the require of index.js in /home/mcmaster/lighthouse-commonjs/build/test/ligthousewdio.spec.js to a dynamic import() which is available in all CommonJS modules.
[0-0]     at Object.require.extensions.<computed> [as .js] (/home/mcmaster/lighthouse-commonjs/node_modules/ts-node/dist/index.js:851:20)
[0-0]     at /home/mcmaster/lighthouse-commonjs/build/test/ligthousewdio.spec.js:58:83
[0-0]     at async Context.<anonymous> (/home/mcmaster/lighthouse-commonjs/build/test/ligthousewdio.spec.js:58:35) {
[0-0]   code: 'ERR_REQUIRE_ESM'
[0-0] }
[0-0] Error in "LightHouseWDIO.Should log single page"
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/mcmaster/lighthouse-commonjs/node_modules/lighthouse/core/index.js from /home/mcmaster/lighthouse-commonjs/build/test/ligthousewdio.spec.js not supported.
Instead change the require of index.js in /home/mcmaster/lighthouse-commonjs/build/test/ligthousewdio.spec.js to a dynamic import() which is available in all CommonJS modules.
    at Object.require.extensions.<computed> [as .js] (/home/mcmaster/lighthouse-commonjs/node_modules/ts-node/dist/index.js:851:20)
    at /home/mcmaster/lighthouse-commonjs/build/test/ligthousewdio.spec.js:58:83
    at async Context.<anonymous> (/home/mcmaster/lighthouse-commonjs/build/test/ligthousewdio.spec.js:58:35)
[0-0] FAILED in chrome - file:///build/test/ligthousewdio.spec.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome 113.0.5672.63 linux #0-0] Running: chrome (v113.0.5672.63) on linux
[chrome 113.0.5672.63 linux #0-0] Session ID: 4922a8bf2b7c9e101257b340c5def12e
[chrome 113.0.5672.63 linux #0-0]
[chrome 113.0.5672.63 linux #0-0] » /build/test/ligthousewdio.spec.js
[chrome 113.0.5672.63 linux #0-0] LightHouseWDIO
[chrome 113.0.5672.63 linux #0-0]    ✖ Should log single page
[chrome 113.0.5672.63 linux #0-0]
[chrome 113.0.5672.63 linux #0-0] 1 failing (146ms)
[chrome 113.0.5672.63 linux #0-0]
[chrome 113.0.5672.63 linux #0-0] 1) LightHouseWDIO Should log single page
[chrome 113.0.5672.63 linux #0-0] require() of ES Module /home/mcmaster/lighthouse-commonjs/node_modules/lighthouse/core/index.js from /home/mcmaster/lighthouse-commonjs/build/test/ligthousewdio.spec.js not supported.
Instead change the require of index.js in /home/mcmaster/lighthouse-commonjs/build/test/ligthousewdio.spec.js to a dynamic import() which is available in all CommonJS modules.
[chrome 113.0.5672.63 linux #0-0] Error [ERR_REQUIRE_ESM]: require() of ES Module /home/mcmaster/lighthouse-commonjs/node_modules/lighthouse/core/index.js from /home/mcmaster/lighthouse-commonjs/build/test/ligthousewdio.spec.js not supported.
[chrome 113.0.5672.63 linux #0-0] Instead change the require of index.js in /home/mcmaster/lighthouse-commonjs/build/test/ligthousewdio.spec.js to a dynamic import() which is available in all CommonJS modules.
[chrome 113.0.5672.63 linux #0-0]     at Object.require.extensions.<computed> [as .js] (/home/mcmaster/lighthouse-commonjs/node_modules/ts-node/dist/index.js:851:20)
[chrome 113.0.5672.63 linux #0-0]     at /home/mcmaster/lighthouse-commonjs/build/test/ligthousewdio.spec.js:58:83
[chrome 113.0.5672.63 linux #0-0]     at async Context.<anonymous> (/home/mcmaster/lighthouse-commonjs/build/test/ligthousewdio.spec.js:58:35)
```

**Comment by adamraine** [comment]
The `import('lighthouse')` works when running a raw CJS script, however your build pipeline converts this to `require('lighthouse')`.

That being said, it should be pretty easy for us to add `startFlow` to the CJS entry point.

**Comment by tkmcmaster** [comment]
That's probably the typescript converting it. But yes, exporting `startFLow` from the cjs script should solve it as well. Thanks.
