### ISSUE TITLE
Inconsistent ESM and CJS index

### ISSUE THREAD

**Issue by mrceperka** [GoogleChrome/lighthouse#15130]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://google.com/url-does-not-matter-in-this-case

### What happened?

I want to generate a html report or import default config.
But I can't use ESM.
So I have to import lighthouse like this `import * as lighthouse from 'lighthouse/core/index.cjs'`
But there is no `generateReport` method (in ESM index, there is)

```text
// console.log(lighthouse) CJS
{
  legacyNavigation: [Getter],
  startFlow: [Getter],
  navigation: [Getter],
  startTimespan: [Getter],
  snapshot: [Getter],
  default: [AsyncFunction: lighthouse] {
    legacyNavigation: [AsyncFunction: legacyNavigation],
    startFlow: [AsyncFunction: startFlow],
    navigation: [AsyncFunction: navigation],
    startTimespan: [AsyncFunction: startTimespan],
    snapshot: [AsyncFunction: snapshot]
  }
}
```

### What did you expect?

I expect them to be the same

### What have you tried?

Patch `index.cjs` by myself, which works, but I would like it to go upstream.
```js
/** @type {import('./index.js')['generateReport']} */
const generateReport = async function generateReport(...args) {
  const {generateReport} = await import('./index.js');
  return generateReport(...args);
};

// also something similar for defaultConfig, etc.
```

### How were you running Lighthouse?

node

### Lighthouse Version

10.2.0

### Chrome Version

does not matter

### Node Version

v18.14.2

### OS

Linux

### Relevant log output

```shell
/var/docker/dist/website-info/lighthouse.js:31
const lighthouse_1 = __importDefault(require("lighthouse"));
                                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /var/docker/node_modules/lighthouse/core/index.js from /var/docker/dist/website-info/lighthouse.js not supported.
Instead change the require of index.js in /var/docker/dist/website-info/lighthouse.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/var/docker/dist/website-info/lighthouse.js:31:38)
    at Object.<anonymous> (/var/docker/dist/website-info/index.js:36:22)
    at Object.<anonymous> (/var/docker/dist/cli/website-info.js:32:17) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.14.2
```

**Comment by adamraine** [comment]
Dynamic imports of ESM should work in CJS files, that's how the `index.cjs` entry point works. Is it possible for you to define your helper function outside the Lighthouse module?

Example:

```js
async function generateReport(...args) {
  const {generateReport} = await import('lighthouse');
  return generateReport(...args);
}
```

**Comment by mrceperka** [comment]
I will try, maybe my TS config is messed up. But I am afraid that I will still hit that same error. 

Thanks for the idea

**Comment by mrceperka** [comment]
```ts
// utils/lighthouse.ts
// @ts-ignore
export async function generateReport(...args) {
  const { generateReport } = await import('lighthouse')
  // @ts-ignore
  return generateReport(...args)
}
```

```js
// dist/utils/lighthouse.js

"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateReport = void 0;
// @ts-ignore
async function generateReport(...args) {
    const { generateReport } = await Promise.resolve().then(() => __importStar(require('lighthouse')));
    // @ts-ignore
    return generateReport(...args);
}
exports.generateReport = generateReport;
//# sourceMappingURL=lighthouse.js.map
```

```ts
// main.ts
import { generateReport } from '@utils/lighthouse'
await generateReport()
```

Error:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /var/docker/node_modules/lighthouse/core/index.js from /var/docker/dist/utils/lighthouse.js not supported.
Instead change the require of index.js in /var/docker/dist/utils/lighthouse.js to a dynamic import() which is available in all CommonJS modules.
    at /var/docker/dist/utils/lighthouse.js:28:80
    at async generateReport (/var/docker/dist/utils/lighthouse.js:28:32)
    at async main (/var/docker/dist/cli/website-info.js:191:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by mrceperka** [comment]
I have changed `tsconfig.json` and now imports seem to work.

```diff
-"moduleResolution": "node",
+"moduleResolution": "node16"
```

**Comment by alphonse92** [comment]
Sorry for raising it, but it is still happening. Actually, I tried the same workaround  @mrceperka before I found this. Is there a solution for this? I tried even including it in my typescript dist folder

**Comment by yoniaiz** [comment]
I encountered the same issue. We need to run our code in CJS, so I tried using dynamic import, and i received the following error:
```typescript
   /.../node_modules/lighthouse/core/index.js:7
    import Trace from './gather/gatherers/trace.js';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

     export const lighthousePatch = async () => {
     const { startFlow } = await import('lighthouse');
```

any ideas how to solve this?

**Comment by adamraine** [comment]
Since this issue was closed a while ago could you please fill out a full bug report with steps to reproduce your specific issues.
