### ISSUE TITLE
Running multiple urls in for loop is causing issues

### ISSUE THREAD

**Issue by ashwinrajanta** [GoogleChrome/lighthouse#15308]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.linkedin.com

### What happened?

```
LH:status Navigating to https://www.linkedin.com/ +60ms
  LH:waitFor:warn Timed out waiting for page load. Checking if page is hung... +45s
  LH:waitFor:warn Page appears to be hung, killing JavaScript... +4ms
  LH:ChromeLauncher Killing Chrome instance 116 +2ms
  LH:ChromeLauncher:warn Chrome could not be killed kill ESRCH +1ms
Runtime error encountered: Protocol error (Emulation.setScriptExecutionDisabled): Session closed. Most likely the page has been closed.
TargetCloseError: Protocol error (Emulation.setScriptExecutionDisabled): Session closed. Most likely the page has been closed.
    at CDPSessionImpl.send (file:///usr/lib/node_modules/lighthouse/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:405:35)
    at ProtocolSession.sendCommand (file:///usr/lib/node_modules/lighthouse/core/gather/session.js:96:44)
    at file:///usr/lib/node_modules/lighthouse/core/gather/driver/wait-for-condition.js:485:23
    at async Promise.all (index 0)
    at async gotoURL (file:///usr/lib/node_modules/lighthouse/core/gather/driver/navigation.js:127:26)
    at async _navigate (file:///usr/lib/node_modules/lighthouse/core/gather/navigation-runner.js:100:55)
    at async _navigation (file:///usr/lib/node_modules/lighthouse/core/gather/navigation-runner.js:236:26)
    at async _navigations (file:///usr/lib/node_modules/lighthouse/core/gather/navigation-runner.js:297:30)
    at async file:///usr/lib/node_modules/lighthouse/core/gather/navigation-runner.js:370:27
    at async Runner.gather (file:///usr/lib/node_modules/lighthouse/core/runner.js:218:21)
root@aa44f9178693:/#
```

### What did you expect?

Navigating to the page and getting the metrics successfully 

### What have you tried?

https://github.com/GoogleChrome/lighthouse/discussions/15305#discussion-5439984

### How were you running Lighthouse?

node

### Lighthouse Version

10.4.0

### OS

debian. bullseye

### Relevant log output

```shell
LH:status Navigating to https://www.linkedin.com/ +60ms
  LH:waitFor:warn Timed out waiting for page load. Checking if page is hung... +45s
  LH:waitFor:warn Page appears to be hung, killing JavaScript... +4ms
  LH:ChromeLauncher Killing Chrome instance 116 +2ms
  LH:ChromeLauncher:warn Chrome could not be killed kill ESRCH +1ms
Runtime error encountered: Protocol error (Emulation.setScriptExecutionDisabled): Session closed. Most likely the page has been closed.
TargetCloseError: Protocol error (Emulation.setScriptExecutionDisabled): Session closed. Most likely the page has been closed.
    at CDPSessionImpl.send (file:///usr/lib/node_modules/lighthouse/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:405:35)
    at ProtocolSession.sendCommand (file:///usr/lib/node_modules/lighthouse/core/gather/session.js:96:44)
    at file:///usr/lib/node_modules/lighthouse/core/gather/driver/wait-for-condition.js:485:23
    at async Promise.all (index 0)
    at async gotoURL (file:///usr/lib/node_modules/lighthouse/core/gather/driver/navigation.js:127:26)
    at async _navigate (file:///usr/lib/node_modules/lighthouse/core/gather/navigation-runner.js:100:55)
    at async _navigation (file:///usr/lib/node_modules/lighthouse/core/gather/navigation-runner.js:236:26)
    at async _navigations (file:///usr/lib/node_modules/lighthouse/core/gather/navigation-runner.js:297:30)
    at async file:///usr/lib/node_modules/lighthouse/core/gather/navigation-runner.js:370:27
    at async Runner.gather (file:///usr/lib/node_modules/lighthouse/core/runner.js:218:21)
root@aa44f9178693:/#
```

**Comment by ashwinrajanta** [comment]
```
 LH:NavigationRunner:error Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. (Status code: 429) https://www.linkedin.com/ +5ms
  LH:status Analyzing and running audits... +20ms

```

**Comment by adamraine** [comment]
I can't reproduce this but the messages seem to indicate that the page is hung. Maybe the Chrome on your machine is having trouble rendering the page.

**Comment by ashwinrajanta** [comment]
FROM debian:bullseye-slim


# Install deps + add Chrome Stable + purge all the things
RUN apt-get update && apt-get install -y \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg \
  --no-install-recommends \
  #&& curl -sSL https://deb.nodesource.com/setup_20.x | bash - \
  && curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
  && apt-get update && apt-get install -y \
  google-chrome-stable \
  fontconfig \
  fonts-ipafont-gothic \
  fonts-wqy-zenhei \
  fonts-thai-tlwg \
  fonts-kacst \
  fonts-symbola \
  fonts-noto \
  fonts-freefont-ttf \
  nodejs \
  npm \
  --no-install-recommends \
  && apt-get purge --auto-remove -y curl gnupg \
  && rm -rf /var/lib/apt/lists/*

ARG CACHEBUST=1
RUN apt-get install -y chromium
RUN npm install -g lighthouse

RUN apt-get update

RUN apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash -
RUN apt-get update
RUN apt-get install -y nodejs


RUN apt-get -y  update
RUN apt-get -y  install dpkg-dev



RUN chmod 777 entrypoint.sh
#COPY ./chrome.json /home/
RUN groupadd -r chrome && useradd -r -g chrome -G audio,video chrome \
  && mkdir -p /home/chrome/reports && chown -R chrome:chrome /home/chrome

#USER chrome
ENTRYPOINT ["entryoint.sh"]

**Comment by ashwinrajanta** [comment]
```
FROM debian:bullseye-slim


# Install deps + add Chrome Stable + purge all the things
RUN apt-get update && apt-get install -y \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg \
  --no-install-recommends \
  #&& curl -sSL https://deb.nodesource.com/setup_20.x | bash - \
  && curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
  && apt-get update && apt-get install -y \
  google-chrome-stable \
  fontconfig \
  fonts-ipafont-gothic \
  fonts-wqy-zenhei \
  fonts-thai-tlwg \
  fonts-kacst \
  fonts-symbola \
  fonts-noto \
  fonts-freefont-ttf \
  nodejs \
  npm \
  --no-install-recommends \
  && apt-get purge --auto-remove -y curl gnupg \
  && rm -rf /var/lib/apt/lists/*

ARG CACHEBUST=1
RUN apt-get install -y chromium
RUN npm install -g lighthouse

RUN apt-get update

RUN apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_current.x | bash -
RUN apt-get update
RUN apt-get install -y nodejs


RUN apt-get -y  update
RUN apt-get -y  install dpkg-dev



RUN chmod 777 /etc/oxeud/entrypoint.sh
#COPY ./chrome.json /home/
RUN groupadd -r chrome && useradd -r -g chrome -G audio,video chrome \
  && mkdir -p /home/chrome/reports && chown -R chrome:chrome /home/chrome

#USER chrome
ENTRYPOINT ["/etc/oxeud/entryoint.sh"]

```

**Comment by ashwinrajanta** [comment]
@adamraine  We have created a container using the above dockerfile. Please let us know using the dockerfile if you are able to reproduce or suggest a fix please.. appreciate your help.. Thanks in advance

**Comment by adamraine** [comment]
Have you tried adding `--disable-dev-shm-usage` to your Chrome launch options? Also I don't know what's in `entrypoint.sh`.

**Comment by paulirish** [comment]
Can you show us the for loop?  You must be awaiting the lighthouse invocation, right???

Does your setup work without a for loop?

**Comment by ashwinrajanta** [comment]
@paulirish @adamraine 

My Docker file is what i have shared above. The entry point script is just a stub to keep the docker up and running.

my python code is below

`#! /usr/bin/python3
import subprocess
import time

urllist = ["https://www.facebook.com","https://www.yahoo.com","https://www.wikipedia.org","https://www.twitter.com","https://www.ebay.com","https://www.linkedin.com","https://www.instagram.com","https://www.netflix.com","https://www.bing.com"]

for url in urllist:
    #command1 = 'su -c "lighthouse --chrome-flags="--headless" --chrome-flags="--disable-gpu" --chrome-flags="--ignore-certificate-errors"  {0}" chrome'.format(url)
    reportFileName = url[12:url.find('.com')]
    #command1 = 'lighthouse {0} -A --output json --output-path="./lighthouseReport_{1}.json"'.format(url,reportFileName)
    command1 = 'su -c "lighthouse {0} -GA --chrome-flags="--headless" --chrome-flags="--ignore-certificate-errors" --only-categories=performance " chrome'.format(url)
    subprocess.check_output(command1,shell=True)
    time.sleep(10)
`

Adding --disable-dev-shm-usage chrome flag to the lighthouse commands helps a bit, But not too much.

**Comment by ashwinrajanta** [comment]
@paulirish @adamraine 
And also if you could see the Dockerfile only if i add the following code, the lighthouse command works.

```
# Add chrome user
RUN groupadd -r chrome && useradd -r -g chrome -G audio,video chrome \
    && mkdir -p /home/chrome/Downloads && chown -R chrome:chrome /home/chrome
```

if i dont start the docker with the above code , lighthouse commands stops in the `waiting for browser` steps..

**Comment by ashwinrajanta** [comment]
@paulirish @adamraine can you please help me with this ???  https://github.com/GoogleChrome/lighthouse/issues/15371
