### ISSUE TITLE
While running Lighthouse it showing error Ni.connect is not a function  and asked to report. so i am here to do same

### ISSUE THREAD

**Issue by d4dsoni** [GoogleChrome/lighthouse#15332]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://safepills4ed.com/

### What happened?

Ni.connect is not a function
```
Channel: DevTools
Initial URL: https://safepills4ed.com/product/silagra-100-mg/
Chrome Version: 115.0.0.0
Stack Trace: TypeError: Ni.connect is not a function
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:972
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:524:349)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:858)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:620:940)
    at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%405e87dfef0c85687ea835e444d33466745cc0725f%2F:1:2668)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%405e87dfef0c85687ea835e444d33466745cc0725f%2F:1:3056)
```

### What did you expect?

Light house test should run properly 

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

v10.2.0

### Chrome Version

115.0.0.0

### OS

Windows

**Comment by mikejamesthompson** [comment]
I've also just seen this bug attempting to run Lighthouse in Chrome developer tools.

- Lighthouse: 10.2.0
- Chrome: Version 115.0.5790.170 (Official Build) (arm64)
- OS: macOS 13.3

Stack trace:
```
Ni.connect is not a function

Channel: DevTools
Initial URL: https://build.nisra.gov.uk/en/
Chrome Version: 115.0.0.0
Stack Trace: TypeError: Ni.connect is not a function
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:972
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:524:349)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:858)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:620:940)
    at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40cc0d30c2ca5577520c8646671513241faa0bc105%2F:1:2668)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40cc0d30c2ca5577520c8646671513241faa0bc105%2F:1:3056)
```

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/issues/15300
