### ISSUE TITLE
Ni.connect is not a function

### ISSUE THREAD

**Issue by adam1215** [GoogleChrome/lighthouse#15346]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://saplaw.com

### What happened?

Error occurs on "Page Analyze Load" in incognito

Ni.connect is not a function
```
Channel: DevTools
Initial URL: https://saplaw.com/index.html
Chrome Version: 115.0.0.0
Stack Trace: TypeError: Ni.connect is not a function
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:972
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:524:349)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:858)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:620:940)
    at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%4067277e15806bf7f0307b37cd6f8f29e71b615796%2F:1:2668)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%4067277e15806bf7f0307b37cd6f8f29e71b615796%2F:1:3056)

### What did you expect?

Successful execution

### What have you tried?

Other sites scans are successful

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

11.0.0

### Chrome Version

Version 115.0.5790.114 (Official Build) (x86_64)

### Node Version

na

### OS

11.7.8

### Relevant log output

```shell
Above
```

**Comment by adamraine** [comment]
#15300
