### ISSUE TITLE
Generate a Lighthouse report fails - Ni.connect is not a function

### ISSUE THREAD

**Issue by BruceRoyce** [GoogleChrome/lighthouse#15373]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.ft.com/

### What happened?

# Generate a Lighthouse report fails
On the DevTools, as soon as I click on the Analyse page load the error message pops up
The same process seemingly works fine in Incognito

### What did you expect?

It is expected to see functions to run error free and to end up with a generated report

### What have you tried?

Running the same in incognito works

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

10.2.0

### Chrome Version

115.0.0.0

### OS

Windows 10

### Relevant log output

```shell
Ni.connect is not a function

Channel: DevTools
Initial URL: https://www.ft.com/
Chrome Version: 115.0.0.0
Stack Trace: TypeError: Ni.connect is not a function
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:972
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:524:349)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:618:858)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:620:940)
    at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40cc0d30c2ca5577520c8646671513241faa0bc105%2F:1:2668)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40cc0d30c2ca5577520c8646671513241faa0bc105%2F:1:3056)
```
```

**Comment by adamraine** [comment]
#15300
