### ISSUE TITLE
CLI Error: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#1537]
I've already fixed this in #1536 but I'll split out a fix since that review will likely take some time.

**Comment by patrickhulce** [comment]
Full stack trace:
```
Runtime error encountered: TypeError: Cannot read property 'startsWith' of undefined
    at row.cols.forEach.col (/Users/phulce/Code/Chrome/lighthouse/lighthouse-core/formatters/table.js:42:22)
    at Array.forEach (native)
    at table.rows.forEach.row (/Users/phulce/Code/Chrome/lighthouse/lighthouse-core/formatters/table.js:40:22)
    at Array.forEach (native)
    at result (/Users/phulce/Code/Chrome/lighthouse/lighthouse-core/formatters/table.js:38:22)
    at item.subItems.forEach.subitem (/Users/phulce/Code/Chrome/lighthouse/lighthouse-cli/printer.js:109:34)
    at Array.forEach (native)
    at aggregation.score.forEach.item (/Users/phulce/Code/Chrome/lighthouse/lighthouse-cli/printer.js:89:27)
    at Array.forEach (native)
    at results.aggregations.forEach.aggregation (/Users/phulce/Code/Chrome/lighthouse/lighthouse-cli/printer.js:84:27)
```
