### ISSUE TITLE
Unable to use lighthouse, Tip Mi.connect is not a function

### ISSUE THREAD

**Issue by Passing-of-A-Dream** [GoogleChrome/lighthouse#15398]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

private project

### What happened?

Mi.connect is not a function
```
Channel: DevTools
Initial URL: http://192.168.0.13/flowable/task/todo/detail/index?procInsId=650071&executionId=650115&deployId=650067&taskId=650127&taskName=%E5%AE%A1%E6%89%B9%E4%BA%BA1&procDefName=%E5%BA%94%E6%94%B6%E6%AC%BE%E7%99%BB%E8%AE%B0%E5%AE%A1%E6%89%B9&startUser=%E5%90%AB%E7%84%B6-%E5%AE%A2%E6%88%B7
Chrome Version: 116.0.0.0
Stack Trace: TypeError: Mi.connect is not a function
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:624:662
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:527:132)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:624:548)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:626:696)
    at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%405128dafac6222fd3ac218660ab6dbf7ff260d768%2F:1:2668)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%405128dafac6222fd3ac218660ab6dbf7ff260d768%2F:1:3056)
```

### What did you expect?

Tell me why it happened

### What have you tried?

Refresh, clear cache, restart local service

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

116.0.0.0

### Chrome Version

116.0.0.0

### OS

Windows

**Comment by adamraine** [comment]
#15300
