### ISSUE TITLE
this is a bug

### ISSUE THREAD

**Issue by lxl521999** [GoogleChrome/lighthouse#15408]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://proc-bidding.jd.com/center/projects

### What happened?

Mi.connect is not a function
```
Channel: DevTools
Initial URL: https://proc-bidding.jd.com/center/projects
Chrome Version: 116.0.0.0
Stack Trace: TypeError: Mi.connect is not a function
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:624:662
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:527:132)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:624:548)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:626:696)
    at async i (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%401a391816688002153ef791ffe60d9e899a71a037%2F:1:2668)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%401a391816688002153ef791ffe60d9e899a71a037%2F:1:3056)
```

### What did you expect?

generate the report correctly

### What have you tried?

i don't know

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

v10

### Chrome Version

116.0.5845.96

**Comment by adamraine** [comment]
#15300
