### ISSUE TITLE
Lighthouse crashed while running "Analyze Page Load" (same error for Desktop + Mobile)

### ISSUE THREAD

**Issue by GwenDragon** [GoogleChrome/lighthouse#15429]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://vivaldi.com/de/

### What happened?

Lighthouse started "Analyze Page Load" and the gave a error in a popup

### What did you expect?

Lightouse runs all tests

### What have you tried?

Checked Developer Tools → Lighthouse in Vivaldi 6.2 Stable and 6.3 Snapshot, that shows the error. 

Checked Developer Tools → Lighthouse in Chromium 116.0.5845.141 that works. 

Checked Developer Tools → Lighthouse in Edge 116.0.1938.62 , that failed and freezed. 

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

i can not get such report

### Chrome Version

116.0.5845.168 

### OS

Windows 11 22H2

### Relevant log output

```shell
Mi.connect is not a function

Channel: DevTools
Initial URL: https://vivaldi.com/de/
Chrome Version: 116.0.0.0
Stack Trace: TypeError: Mi.connect is not a function
    at devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:624:662
    at Runner.gather (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:527:132)
    at navigationGather (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:624:548)
    at async navigation (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:626:696)
    at async invokeLH (devtools://devtools/bundled/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40fe31e9b0b97a3adadcb087415c8c3635145ba2a2%2F:115:12)
    at async onFrontendMessage (devtools://devtools/bundled/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40fe31e9b0b97a3adadcb087415c8c3635145ba2a2%2F:160:22)
```
```

**Comment by adamraine** [comment]
#15300

We don't officially support Edge or Vivaldi, I would suggest filing a bug with those browsers if you don't see an issue in Chromium.
