### ISSUE TITLE
Upgrading from Lighthouse 9.1.0 to 9.6.8 is causing an error.

### ISSUE THREAD

**Issue by Forsh75** [GoogleChrome/lighthouse#15495]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.aesop.com/uk/ 

### What happened?

I'm running some lighthouse reports using version 9.1.0 and Specrun via VS and everything works fine. If I upgraded lighthouse to 9.6.8 I get the error below:

`[ERROR] C:\Users\MichaelForshaw\AppData\Local\Temp\lighthouse-net-48c99957be13472183a78c8c2333ff38.js:15            return chrome.kill().then(() => results.lhr);                                ^TypeError: Cannot read properties of undefined (reading 'then')    at C:\Users\JoeBloggs\AppData\Local\Temp\lighthouse-net-48c99957be13472183a78c8c2333ff38.js:15:33    at runMicrotasks (<anonymous>)    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

If I then downgrade back to 9.1.0 I still get the error above. The only way I can resolve is to copy the original npm folder, from the initial working tests back into the Appdata/Roaming folder. 

Any ideas greatly appreciated.

Thanks.

### What did you expect?

I expected the tests to continue to run after upgrading Lighthouse

### How were you running Lighthouse?

Other

### Lighthouse Version

9.1.0 & 9.6.8

### OS

Windows

### Relevant log output

```shell
2023-09-27T12:37:48.5311701+01:00;VSTestExecutionThread;Info;SpecFlow+Runner execution started
2023-09-27T12:37:48.5313359+01:00;VSTestExecutionThread;Info;SpecFlow+Runner 3.9.7 in Framework netcore31 in x64 mode execution started
2023-09-27T12:37:48.5313410+01:00;VSTestExecutionThread;Info;TestAdapter Location: C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\TechTalk.SpecRun.VisualStudio.TestAdapter.dll
2023-09-27T12:37:48.5324978+01:00;VSTestExecutionThread;Info;Current UserName: 'MichaelForshaw', MachineName: 'SPIKE-YOGA-MF'
2023-09-27T12:37:48.5926139+01:00;VSTestExecutionThread;Info;SpecRun: running tests in C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\GoogleLighthouse.dll
2023-09-27T12:37:48.5927644+01:00;VSTestExecutionThread;Info;Output folder configured to "C:\Repos\GoogleLighthouse\GoogleLighthouse\TestResults" (default)
2023-09-27T12:37:48.5928011+01:00;VSTestExecutionThread;Info;Profile: GoogleLighthouse
2023-09-27T12:37:48.6090322+01:00;VSTestExecutionThread;Info;Log file path: C:\Repos\GoogleLighthouse\GoogleLighthouse\TestResults\GoogleLighthouse_GoogleLighthouse_2023-09-27T123748.log
2023-09-27T12:37:48.6117192+01:00;Thread#12;Info;Checking activation
2023-09-27T12:37:48.6554606+01:00;Thread#12;Info;Activated.
2023-09-27T12:37:48.6556349+01:00;Thread#12;Info;Activation check completed
2023-09-27T12:37:48.6556762+01:00;Thread#12;Info;Starting test run
2023-09-27T12:37:48.6969643+01:00;Thread#12;Info;Discovering target: Default
2023-09-27T12:37:48.6970957+01:00;Thread#12;Info;Discovering tests from assembly: C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\GoogleLighthouse.dll
2023-09-27T12:37:48.7458220+01:00;Thread#12;Info;Discovered tests from assembly: C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\GoogleLighthouse.dll
2023-09-27T12:37:48.7464862+01:00:Test Suite Dump
2023-09-27T12:37:48.7473863+01:00:#0: GoogleLighthouse/GoogleLighthouse - 
2023-09-27T12:37:48.7474024+01:00:#1: Default - 
2023-09-27T12:37:48.7474040+01:00:#2: GoogleLighthouse - 
2023-09-27T12:37:48.7474059+01:00:#3: Major Retailer League Table for Desktop - 
2023-09-27T12:37:48.7480903+01:00:#4: League table for Desktop, Aesop - TestAssembly:GoogleLighthouse/Feature:Major+Retailer+League+Table+for+Desktop/Scenario:League+table+for+Desktop%2c+Aesop
2023-09-27T12:37:48.7481330+01:00:End: Test Suite Dump
2023-09-27T12:37:48.7567410+01:00:Thread#0:Scheduler: get next test for thread 0
2023-09-27T12:37:48.7576019+01:00:Thread#:Scheduler: testitem #4 from normal test queue 
2023-09-27T12:37:48.7576277+01:00:Thread#0:Scheduler: considering testitem #4 for thread 0
2023-09-27T12:37:48.7591373+01:00:Thread#0:TestItem#4:testItemMatchesCurrentTestThread:UnSpecific
2023-09-27T12:37:48.7591482+01:00:Thread#0:TestItem#4:runsOnOneOtherThreadSpecific:False
2023-09-27T12:37:48.7591497+01:00:Thread#0:TestItem#4:runsOnOneOtherThreadUnspecific:False
2023-09-27T12:37:48.7591514+01:00:Thread#0:Scheduler: using testitem #4 for thread 0
2023-09-27T12:37:48.7594795+01:00:Thread#0:Scheduler: Test #4 is scheduled for thread
2023-09-27T12:37:48.7599309+01:00:Thread#0:Scheduler: with testItemExecutionIndex 0
2023-09-27T12:37:48.7609696+01:00:Thread #0: creating new test thread executor for GoogleLighthouse, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (target: Default)
2023-09-27T12:37:48.7622284+01:00:Thread #0: Creating test assembly executor for execution model OutProc
2023-09-27T12:37:48.7623321+01:00:Thread #0: Creating test assembly executor for execution model OutProc
2023-09-27T12:37:48.7901561+01:00:Thread #0: using TechTalk.SpecRun.Framework.Execution.OutOfProc.StreamJsonRPC.OutOfProcessTestAssemblyExecutorHost to execute tests
2023-09-27T12:37:48.7909104+01:00:starting Out Of Process Executor
2023-09-27T12:37:48.9042304+01:00:Assembly resolving Microsoft.VisualStudio.Validation, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2023-09-27T12:37:48.9060184+01:00:[AssemblyCache] Trying to resolve 'Microsoft.VisualStudio.Validation' from .deps.json file
2023-09-27T12:37:48.9060331+01:00:[AssemblyCache] Could not resolve 'Microsoft.VisualStudio.Validation' from .deps.json
2023-09-27T12:37:48.9069305+01:00:[AssemblyCache] Trying to resolve 'Microsoft.VisualStudio.Validation' in folder 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1'
2023-09-27T12:37:48.9071405+01:00:[AssemblyCache] Trying to resolve 'Microsoft.VisualStudio.Validation' to 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\Microsoft.VisualStudio.Validation.dll'
2023-09-27T12:37:48.9071928+01:00:[AssemblyCache] Trying to resolve 'Microsoft.VisualStudio.Validation' to 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\Microsoft.VisualStudio.Validation.exe'
2023-09-27T12:37:48.9072074+01:00:[AssemblyCache] Could not resolve 'Microsoft.VisualStudio.Validation' in folder 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1'
2023-09-27T12:37:48.9073150+01:00:TargetFramework: .NETCoreApp,Version=v3.1
2023-09-27T12:37:48.9074429+01:00:Tfm: netcoreapp3.1
2023-09-27T12:37:48.9074511+01:00:[AssemblyCache] Trying to resolve 'Microsoft.VisualStudio.Validation' in folder 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\SpecFlowPlusRunner\netcoreapp3.1'
2023-09-27T12:37:48.9074523+01:00:[AssemblyCache] Trying to resolve 'Microsoft.VisualStudio.Validation' to 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\SpecFlowPlusRunner\netcoreapp3.1\Microsoft.VisualStudio.Validation.dll'
2023-09-27T12:37:48.9074878+01:00:[AssemblyCache] Found file 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\SpecFlowPlusRunner\netcoreapp3.1\Microsoft.VisualStudio.Validation.dll' for assembly 'Microsoft.VisualStudio.Validation'
2023-09-27T12:37:48.9077532+01:00:[AssemblyCache] Resolved 'Microsoft.VisualStudio.Validation' to C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\SpecFlowPlusRunner\netcoreapp3.1\Microsoft.VisualStudio.Validation.dll
2023-09-27T12:37:48.9081534+01:00:Starting callback TCP Rpc server
2023-09-27T12:37:48.9181384+01:00:Asynchronously starting background TCP Rpc Server on port 32768
2023-09-27T12:37:48.9182001+01:00:Started callback TCP Rpc server on port 32768
2023-09-27T12:37:48.9182031+01:00:Starting logger TCP Rpc server
2023-09-27T12:37:48.9191578+01:00:Asynchronously starting background TCP Rpc Server on port 32769
2023-09-27T12:37:48.9191795+01:00:Started logger TCP Rpc server on port 32769
2023-09-27T12:37:49.1179399+01:00:Executing test executor at 'dotnet' 'exec "C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\SpecFlowPlusRunner\netcoreapp3.1\TechTalk.SpecRun.Framework.Executor.anycpu.netcoreapp3_1.dll" --remoteRunnerPid 5648 --uniqueId "2023-09-27T123748" --outputFolder "C:\Repos\GoogleLighthouse\GoogleLighthouse\TestResults" --callbackPort 32768 --loggerPort 32769' in 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1'
2023-09-27T12:37:49.1245528+01:00:Executor with PID 18508 has been started successfully.
2023-09-27T12:37:49.1263588+01:00:Out of Process Executor 18508 started
2023-09-27T12:37:49.1263736+01:00:Waiting for endpoint
2023-09-27T12:37:49.6555105+01:00:Assembly resolving Microsoft.VisualStudio.Threading, Version=15.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2023-09-27T12:37:49.6555712+01:00:[AssemblyCache] Trying to resolve 'Microsoft.VisualStudio.Threading' from .deps.json file
2023-09-27T12:37:49.6555744+01:00:[AssemblyCache] Could not resolve 'Microsoft.VisualStudio.Threading' from .deps.json
2023-09-27T12:37:49.6555930+01:00:[AssemblyCache] Trying to resolve 'Microsoft.VisualStudio.Threading' in folder 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1'
2023-09-27T12:37:49.6555943+01:00:[AssemblyCache] Trying to resolve 'Microsoft.VisualStudio.Threading' to 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\Microsoft.VisualStudio.Threading.dll'
2023-09-27T12:37:49.6556085+01:00:[AssemblyCache] Trying to resolve 'Microsoft.VisualStudio.Threading' to 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\Microsoft.VisualStudio.Threading.exe'
2023-09-27T12:37:49.6556353+01:00:[AssemblyCache] Could not resolve 'Microsoft.VisualStudio.Threading' in folder 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1'
2023-09-27T12:37:49.6556395+01:00:TargetFramework: .NETCoreApp,Version=v3.1
2023-09-27T12:37:49.6556850+01:00:Tfm: netcoreapp3.1
2023-09-27T12:37:49.6556939+01:00:[AssemblyCache] Trying to resolve 'Microsoft.VisualStudio.Threading' in folder 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\SpecFlowPlusRunner\netcoreapp3.1'
2023-09-27T12:37:49.6556977+01:00:[AssemblyCache] Trying to resolve 'Microsoft.VisualStudio.Threading' to 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\SpecFlowPlusRunner\netcoreapp3.1\Microsoft.VisualStudio.Threading.dll'
2023-09-27T12:37:49.6557254+01:00:[AssemblyCache] Found file 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\SpecFlowPlusRunner\netcoreapp3.1\Microsoft.VisualStudio.Threading.dll' for assembly 'Microsoft.VisualStudio.Threading'
2023-09-27T12:37:49.6560169+01:00:[AssemblyCache] Resolved 'Microsoft.VisualStudio.Threading' to C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\SpecFlowPlusRunner\netcoreapp3.1\Microsoft.VisualStudio.Threading.dll
2023-09-27T12:37:49.7622915+01:00:Remote executor port received: 32770
2023-09-27T12:37:49.7624626+01:00:Creating executor TCP client on port 32770
2023-09-27T12:37:49.7626547+01:00:Created executor TCP client on port 32770
2023-09-27T12:37:49.7626626+01:00:Connecting to remote executor TCP server
2023-09-27T12:37:49.7631491+01:00:Connected remote executor TCP server
2023-09-27T12:37:49.7632437+01:00:trying to connect to Out of Process Executor the 1 attempt
2023-09-27T12:37:49.7632511+01:00:Connection to Out of Process Executor established in the 1 attempt
2023-09-27T12:37:49.8850997+01:00:2023-09-27T12:37:49.8837181+01:00:OutOfProcessTestAssemblyExecutor: initialized for C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\GoogleLighthouse.dll on test thread #0
2023-09-27T12:37:49.8879269+01:00:Endpoint 18508 started
2023-09-27T12:37:49.8982079+01:00:2023-09-27T12:37:49.8978636+01:00:OutOfProcessTestAssemblyExecutor: running tests...
2023-09-27T12:37:49.9516047+01:00:2023-09-27T12:37:49.9511679+01:00:Assembly resolving TechTalk.SpecFlow, Version=3.9.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41
2023-09-27T12:37:49.9537057+01:00:2023-09-27T12:37:49.9532995+01:00:[AssemblyCache] Trying to resolve 'TechTalk.SpecFlow' from .deps.json file
2023-09-27T12:37:49.9554803+01:00:2023-09-27T12:37:49.9551865+01:00:[AssemblyCache] Resolved 'TechTalk.SpecFlow' to 'C:\Users\MichaelForshaw\.nuget\packages\specflow\3.9.22\lib\netstandard2.0\TechTalk.SpecFlow.dll'
2023-09-27T12:37:50.0104275+01:00:2023-09-27T12:37:50.0099333+01:00:Thread#0:T:-> Loading plugin C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\GoogleLighthouse.dll
2023-09-27T12:37:50.0115731+01:00:2023-09-27T12:37:50.0110998+01:00:Assembly resolving Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
2023-09-27T12:37:50.0121950+01:00:2023-09-27T12:37:50.0119133+01:00:[AssemblyCache] Trying to resolve 'Microsoft.Extensions.DependencyModel' from .deps.json file
2023-09-27T12:37:50.0134297+01:00:2023-09-27T12:37:50.0129690+01:00:[AssemblyCache] Resolved 'Microsoft.Extensions.DependencyModel' to 'C:\Users\MichaelForshaw\.nuget\packages\microsoft.extensions.dependencymodel\1.0.3\lib\netstandard1.6\Microsoft.Extensions.DependencyModel.dll'
2023-09-27T12:37:50.0340957+01:00:2023-09-27T12:37:50.0336224+01:00:Assembly resolving Microsoft.DotNet.PlatformAbstractions, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
2023-09-27T12:37:50.0346101+01:00:2023-09-27T12:37:50.0343574+01:00:[AssemblyCache] Trying to resolve 'Microsoft.DotNet.PlatformAbstractions' from .deps.json file
2023-09-27T12:37:50.0352379+01:00:2023-09-27T12:37:50.0349775+01:00:[AssemblyCache] Resolved 'Microsoft.DotNet.PlatformAbstractions' to 'C:\Users\MichaelForshaw\.nuget\packages\microsoft.dotnet.platformabstractions\1.0.3\lib\netstandard1.3\Microsoft.DotNet.PlatformAbstractions.dll'
2023-09-27T12:37:50.0396496+01:00:2023-09-27T12:37:50.0391898+01:00:Thread#0:T:-> Loading plugin C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\SpecRun.Runtime.SpecFlowPlugin.dll
2023-09-27T12:37:50.0643581+01:00:2023-09-27T12:37:50.0637439+01:00:Thread#0:T:-> Using default config
2023-09-27T12:37:50.0694193+01:00:2023-09-27T12:37:50.0689584+01:00:Assembly resolving Cucumber.Messages, Version=6.0.1.0, Culture=neutral, PublicKeyToken=b10c5988214f940c
2023-09-27T12:37:50.0702336+01:00:2023-09-27T12:37:50.0697822+01:00:[AssemblyCache] Trying to resolve 'Cucumber.Messages' from .deps.json file
2023-09-27T12:37:50.0709147+01:00:2023-09-27T12:37:50.0706374+01:00:[AssemblyCache] Resolved 'Cucumber.Messages' to 'C:\Users\MichaelForshaw\.nuget\packages\cucumber.messages\6.0.1\lib\netstandard2.0\Cucumber.Messages.dll'
2023-09-27T12:37:50.0723886+01:00:2023-09-27T12:37:50.0720617+01:00:Assembly resolving Google.Protobuf, Version=3.7.0.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604
2023-09-27T12:37:50.0728906+01:00:2023-09-27T12:37:50.0726396+01:00:[AssemblyCache] Trying to resolve 'Google.Protobuf' from .deps.json file
2023-09-27T12:37:50.0734273+01:00:2023-09-27T12:37:50.0731838+01:00:[AssemblyCache] Resolved 'Google.Protobuf' to 'C:\Users\MichaelForshaw\.nuget\packages\google.protobuf\3.7.0\lib\netstandard1.0\Google.Protobuf.dll'
2023-09-27T12:37:50.0761209+01:00:2023-09-27T12:37:50.0757436+01:00:Assembly resolving lighthouse.net, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null
2023-09-27T12:37:50.0766263+01:00:2023-09-27T12:37:50.0763695+01:00:[AssemblyCache] Trying to resolve 'lighthouse.net' from .deps.json file
2023-09-27T12:37:50.0772364+01:00:2023-09-27T12:37:50.0769719+01:00:[AssemblyCache] Resolved 'lighthouse.net' to 'C:\Users\MichaelForshaw\.nuget\packages\lighthouse.net\1.0.5\lib\netstandard2.0\lighthouse.net.dll'
2023-09-27T12:37:50.0787738+01:00:2023-09-27T12:37:50.0786082+01:00:Assembly resolving Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2023-09-27T12:37:50.0789816+01:00:2023-09-27T12:37:50.0788870+01:00:[AssemblyCache] Trying to resolve 'Microsoft.VisualStudio.TestPlatform.ObjectModel' from .deps.json file
2023-09-27T12:37:50.0792967+01:00:2023-09-27T12:37:50.0791958+01:00:[AssemblyCache] Resolved 'Microsoft.VisualStudio.TestPlatform.ObjectModel' to 'C:\Users\MichaelForshaw\.nuget\packages\microsoft.testplatform.objectmodel\16.5.0\lib\netstandard2.0\Microsoft.VisualStudio.TestPlatform.ObjectModel.dll'
2023-09-27T12:37:50.0937279+01:00:2023-09-27T12:37:50.0932722+01:00:Assembly resolving SpecFlow.Internal.Json, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41
2023-09-27T12:37:50.0946047+01:00:2023-09-27T12:37:50.0942122+01:00:[AssemblyCache] Trying to resolve 'SpecFlow.Internal.Json' from .deps.json file
2023-09-27T12:37:50.0953331+01:00:2023-09-27T12:37:50.0949888+01:00:[AssemblyCache] Resolved 'SpecFlow.Internal.Json' to 'C:\Users\MichaelForshaw\.nuget\packages\specflow.internal.json\1.0.8\lib\netstandard2.0\SpecFlow.Internal.Json.dll'
2023-09-27T12:37:50.1327889+01:00:Thread#0: Test #4/0 is started on thread #0
2023-09-27T12:37:50.1410815+01:00:2023-09-27T12:37:50.1405720+01:00:Thread#0:B:Given We audit the https://www.aesop.com/uk/ for a major retail Aesop using the Desktop strategy
2023-09-27T12:38:16.0203105+01:00:2023-09-27T12:38:16.0185079+01:00:Thread#0:T:error: C:\Users\MichaelForshaw\AppData\Local\Temp\lighthouse-net-48c99957be13472183a78c8c2333ff38.js:15            return chrome.kill().then(() => results.lhr);                                ^TypeError: Cannot read properties of undefined (reading 'then')    at C:\Users\MichaelForshaw\AppData\Local\Temp\lighthouse-net-48c99957be13472183a78c8c2333ff38.js:15:33    at runMicrotasks (<anonymous>)    at processTicksAndRejections (node:internal/process/task_queues:96:5) (25.9s)
2023-09-27T12:38:16.0231089+01:00:2023-09-27T12:38:16.0222301+01:00:Thread#0:B:When the results are returned successfully
2023-09-27T12:38:16.0250439+01:00:2023-09-27T12:38:16.0243799+01:00:Thread#0:T:skipped because of previous errors
2023-09-27T12:38:16.0287173+01:00:2023-09-27T12:38:16.0277891+01:00:Thread#0:B:Then the LeagueTable is updated
2023-09-27T12:38:16.0303032+01:00:2023-09-27T12:38:16.0294647+01:00:Thread#0:T:skipped because of previous errors
2023-09-27T12:38:16.0640293+01:00:Thread#0:TestItem#4:Scheduler: reschedule tests for testitem #4
2023-09-27T12:38:16.0661182+01:00:Thread#0:Scheduler: get next test for thread 0
2023-09-27T12:38:16.0661578+01:00:Thread#:Scheduler: at the end of normal test queue
2023-09-27T12:38:16.0661603+01:00:Thread#0:Scheduler: enumerator for thread is at end
2023-09-27T12:38:16.0661634+01:00:Thread#0:Scheduler: No more tests for thread
2023-09-27T12:38:16.0980188+01:00:Thread#0: Test #4/0 is finished on thread #0 as Failed within 25.9647178 seconds
2023-09-27T12:38:16.1114139+01:00:2023-09-27T12:38:16.1110329+01:00:Got Deinitialize Signal
2023-09-27T12:38:16.1140352+01:00:RPC Client disconnected, because 'Disposed'. 
LastMessage: 
Description:Stream has been disposed
Exception:<none>
2023-09-27T12:38:16.1150312+01:00:RPC Server disconnected, because 'Disposed'. 
LastMessage: 
Description:Reached end of stream.
Exception:<none>
2023-09-27T12:38:16.1159343+01:00:RPC Server disconnected, because 'Disposed'. 
LastMessage: 
Description:Stream has been disposed
Exception:<none>
2023-09-27T12:38:16.1168553+01:00:Assembly resolving System.Diagnostics.Process.resources, Version=4.2.2.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a
2023-09-27T12:38:16.1168741+01:00:[AssemblyCache] Trying to resolve 'System.Diagnostics.Process.resources' from .deps.json file
2023-09-27T12:38:16.1168781+01:00:[AssemblyCache] Could not resolve 'System.Diagnostics.Process.resources' from .deps.json
2023-09-27T12:38:16.1168828+01:00:[AssemblyCache] Trying to resolve 'System.Diagnostics.Process.resources' in folder 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1'
2023-09-27T12:38:16.1168847+01:00:[AssemblyCache] Trying to resolve 'System.Diagnostics.Process.resources' to 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\System.Diagnostics.Process.resources.dll'
2023-09-27T12:38:16.1169020+01:00:[AssemblyCache] Trying to resolve 'System.Diagnostics.Process.resources' to 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\System.Diagnostics.Process.resources.exe'
2023-09-27T12:38:16.1169134+01:00:[AssemblyCache] Could not resolve 'System.Diagnostics.Process.resources' in folder 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1'
2023-09-27T12:38:16.1169191+01:00:TargetFramework: .NETCoreApp,Version=v3.1
2023-09-27T12:38:16.1169582+01:00:Tfm: netcoreapp3.1
2023-09-27T12:38:16.1169605+01:00:[AssemblyCache] Trying to resolve 'System.Diagnostics.Process.resources' in folder 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\SpecFlowPlusRunner\netcoreapp3.1'
2023-09-27T12:38:16.1169619+01:00:[AssemblyCache] Trying to resolve 'System.Diagnostics.Process.resources' to 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\SpecFlowPlusRunner\netcoreapp3.1\System.Diagnostics.Process.resources.dll'
2023-09-27T12:38:16.1169841+01:00:[AssemblyCache] Trying to resolve 'System.Diagnostics.Process.resources' to 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\SpecFlowPlusRunner\netcoreapp3.1\System.Diagnostics.Process.resources.exe'
2023-09-27T12:38:16.1170052+01:00:[AssemblyCache] Could not resolve 'System.Diagnostics.Process.resources' in folder 'C:\Repos\GoogleLighthouse\GoogleLighthouse\bin\Debug\netcoreapp3.1\SpecFlowPlusRunner\netcoreapp3.1'
2023-09-27T12:38:16.1216107+01:00:[AssemblyCache] Trying to resolve 'System.Diagnostics.Process.resources' in folder 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.32'
2023-09-27T12:38:16.1216261+01:00:[AssemblyCache] Trying to resolve 'System.Diagnostics.Process.resources' to 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.32\System.Diagnostics.Process.resources.dll'
2023-09-27T12:38:16.1216545+01:00:[AssemblyCache] Trying to resolve 'System.Diagnostics.Process.resources' to 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.32\System.Diagnostics.Process.resources.exe'
2023-09-27T12:38:16.1216686+01:00:[AssemblyCache] Could not resolve 'System.Diagnostics.Process.resources' in folder 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.32'
2023-09-27T12:38:16.1223624+01:00:Assembly resolving System.Diagnostics.Process.resources, Version=4.2.2.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
2023-09-27T12:38:16.1290464+01:00:Thread#-1:Scheduler: get next test for thread -1
2023-09-27T12:38:16.1290891+01:00:Thread#:Scheduler: at the end of normal test queue
2023-09-27T12:38:16.1290928+01:00:Thread#-1:Scheduler: enumerator for thread is at end
2023-09-27T12:38:16.1304632+01:00;Thread#12;Info;test run finished
2023-09-27T12:38:16.1306347+01:00;Thread#12;Info;publishing test results
2023-09-27T12:38:16.1307237+01:00;Thread#12;Info;Not publishing results.
2023-09-27T12:38:16.1307658+01:00;Thread#12;Info;test results published
2023-09-27T12:38:16.1307922+01:00;Thread#12;Info;generating reports
2023-09-27T12:38:16.1750100+01:00;Thread#12;Info;Starting external report generation process
2023-09-27T12:38:19.0828307+01:00;Thread#12;Info;Successfully generated reports.
2023-09-27T12:38:19.0842977+01:00;Thread#12;Info;Successfully generated reports
2023-09-27T12:38:19.0887391+01:00:Total: 1
2023-09-27T12:38:19.0895892+01:00:Succeeded: 0
2023-09-27T12:38:19.0897253+01:00:Ignored: 0
2023-09-27T12:38:19.0898181+01:00:Pending: 0
2023-09-27T12:38:19.0898243+01:00:Skipped: 0
2023-09-27T12:38:19.0899111+01:00:Failed: 1
2023-09-27T12:38:19.0928459+01:00;VSTestExecutionThread;Info;Adding attachments to VSTest
2023-09-27T12:38:19.0928798+01:00;VSTestExecutionThread;Info;adding Test Execution Report 'C:\Repos\GoogleLighthouse\GoogleLighthouse\TestResults\GoogleLighthouse_GoogleLighthouse_2023-09-27T123748.html'
========== End of log file ==========
```

**Comment by adamraine** [comment]
Lighthouse v9.x is long out of date at this point, and there are no repro steps here. Please try with the latest version of Lighthouse and provide reproduction steps.
