### ISSUE TITLE
ProtocolError: Protocol error (Debugger.enable): Script execution is prohibited

### ISSUE THREAD

**Issue by sandeepchan** [GoogleChrome/lighthouse#15525]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

http://13.48.26.180/

### What happened?

I'm running lighthouse flow  and following this URL 
https://github.com/GoogleChrome/lighthouse/blob/main/docs/user-flows.md
But I'm getting error in some of the flow below is the error 

```
****ProtocolError: Protocol error (Debugger.enable): Script execution is prohibited**
    at <instance_members_initializer> (C:\Users\chand\Downloads\lg\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:42:14)
    at new Callback (C:\Users\chand\Downloads\lg\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:46:16)
    at CallbackRegistry.create (C:\Users\chand\Downloads\lg\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:86:26)
    at Connection._rawSend (C:\Users\chand\Downloads\lg\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:208:26)
    at CdpCDPSession.send (C:\Users\chand\Downloads\lg\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\CDPSession.js:61:33)
    at ProtocolSession.sendCommand (file:///C:/Users/chand/Downloads/lg/node_modules/lighthouse/core/gather/session.js:96:44)
    at enable (file:///C:/Users/chand/Downloads/lg/node_modules/lighthouse/core/gather/driver/prepare.js:20:19)
    at Module.enableAsyncStacks (file:///C:/Users/chand/Downloads/lg/node_modules/lighthouse/core/gather/driver/prepare.js:45:9)
    at _navigation (file:///C:/Users/chand/Downloads/lg/node_modules/lighthouse/core/gather/navigation-runner.js:238:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)**

```

### What did you expect?

I want to execute this flow. 

### What have you tried?

![image](https://github.com/GoogleChrome/lighthouse/assets/25325312/7c3cd1a3-ab41-4cf8-8a8a-2dab755fcf14)

### How were you running Lighthouse?

node

### Lighthouse Version

21.3.8

### Relevant log output

```shell
ProtocolError: Protocol error (Debugger.enable): Script execution is prohibited
    at <instance_members_initializer> (C:\Users\chand\Downloads\lg\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:42:14)
    at new Callback (C:\Users\chand\Downloads\lg\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:46:16)
    at CallbackRegistry.create (C:\Users\chand\Downloads\lg\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:86:26) 
    at Connection._rawSend (C:\Users\chand\Downloads\lg\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Connection.js:208:26)
    at CdpCDPSession.send (C:\Users\chand\Downloads\lg\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\CDPSession.js:61:33)
    at ProtocolSession.sendCommand (file:///C:/Users/chand/Downloads/lg/node_modules/lighthouse/core/gather/session.js:96:44)
    at enable (file:///C:/Users/chand/Downloads/lg/node_modules/lighthouse/core/gather/driver/prepare.js:20:19)
    at Module.enableAsyncStacks (file:///C:/Users/chand/Downloads/lg/node_modules/lighthouse/core/gather/driver/prepare.js:45:9)
    at _navigation (file:///C:/Users/chand/Downloads/lg/node_modules/lighthouse/core/gather/navigation-runner.js:238:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by adamraine** [comment]
> 21.3.8

This is not a valid Lighthouse version, perhaps you are referring to your Puppeteer version?

Can you also provide the entire script you are using?

**Comment by sandeepchan** [comment]
Lighthouse version is 11.1.0
Puppeteer version is 21.3

**Comment by sandeepchan** [comment]
Here is the script
```
const fs = require("fs");
const puppeteer = require("puppeteer"); // v20.7.4 or later

(async () => {
  const args = [];
  const browser = await puppeteer.launch({
    headless: false,
    args: [
      "--disable-gpu",
      "--disable-dev-shm-usage",
      "--disable-setuid-sandbox",
      "--no-first-run",
      "--no-sandbox",
      "--no-zygote",
      "--deterministic-fetch",
      "--disable-features=IsolateOrigins",
      "--disable-site-isolation-trials",
      // '--single-process',
    ],
  });
  const page = await browser.newPage();
  const session = await page.target().createCDPSession();

  const timeout = 30000;
  page.setDefaultTimeout(timeout);

  const lhApi = await import("lighthouse"); // v10.0.0 or later
  const flags = {
    screenEmulation: {
      disabled: true,
    },
  };
  const config = lhApi.desktopConfig;
  const lhFlow = await lhApi.startFlow(page, {
    name: "Recording 10/10/2023 at 10:05:09 PM",
    config,
    flags,
  });
  {
    const targetPage = page;
    await targetPage.setViewport({
      width: 1903,
      height: 963,
    });
  }
  await lhFlow.startNavigation();
  {
    const targetPage = page;
    const promises = [];
    const startWaitingForEvents = () => {
      promises.push(targetPage.waitForNavigation());
    };
    startWaitingForEvents();
    await targetPage.goto("http://13.48.26.180/");
    await Promise.all(promises);
  }
  await lhFlow.endNavigation();
  await lhFlow.startNavigation();
  {
    const targetPage = page;
    const promises = [];
    const startWaitingForEvents = () => {
      promises.push(targetPage.waitForNavigation());
    };
    await puppeteer.Locator.race([
      targetPage.locator("::-p-aria(ABOUT)"),
      targetPage.locator("li:nth-of-type(2) > a"),
      targetPage.locator(
        '::-p-xpath(//*[@id=\\"navbarSupportedContent\\"]/ul/li[2]/a)'
      ),
      targetPage.locator(":scope >>> li:nth-of-type(2) > a"),
    ])
      .setTimeout(timeout)
      .on("action", () => startWaitingForEvents())
      .click({
        offset: {
          x: 46.546875,
          y: 21.5,
        },
      });
    await Promise.all(promises);
  }
  await lhFlow.endNavigation();
  await lhFlow.startNavigation();
  {
    const targetPage = page;
    const promises = [];
    const startWaitingForEvents = () => {
      promises.push(targetPage.waitForNavigation());
    };
    await puppeteer.Locator.race([
      targetPage.locator("::-p-aria(SERVICES)"),
      targetPage.locator("li:nth-of-type(3) > a"),
      targetPage.locator(
        '::-p-xpath(//*[@id=\\"navbarSupportedContent\\"]/ul/li[3]/a)'
      ),
      targetPage.locator(":scope >>> li:nth-of-type(3) > a"),
    ])
      .setTimeout(timeout)
      .on("action", () => startWaitingForEvents())
      .click({
        offset: {
          x: 36.171875,
          y: 20.5,
        },
      });
    await Promise.all(promises);
  }
  await lhFlow.endNavigation();
  await lhFlow.startNavigation();
  {
    const targetPage = page;
    const promises = [];
    const startWaitingForEvents = () => {
      promises.push(targetPage.waitForNavigation());
    };
    await puppeteer.Locator.race([
      targetPage.locator("::-p-aria(WHY US)"),
      targetPage.locator("li:nth-of-type(4) > a"),
      targetPage.locator(
        '::-p-xpath(//*[@id=\\"navbarSupportedContent\\"]/ul/li[4]/a)'
      ),
      targetPage.locator(":scope >>> li:nth-of-type(4) > a"),
    ])
      .setTimeout(timeout)
      .on("action", () => startWaitingForEvents())
      .click({
        offset: {
          x: 62.875,
          y: 8.5,
        },
      });
    await Promise.all(promises);
  }
  await lhFlow.endNavigation();
  await lhFlow.startTimespan();
  {
    const targetPage = page;
    await puppeteer.Locator.race([
      targetPage.locator("::-p-aria( LOGIN)"),
      targetPage.locator("li:nth-of-type(6) > a"),
      targetPage.locator(
        '::-p-xpath(//*[@id=\\"navbarSupportedContent\\"]/ul/li[6]/a)'
      ),
      targetPage.locator(":scope >>> li:nth-of-type(6) > a"),
      targetPage.locator("::-p-text(Login)"),
    ])
      .setTimeout(timeout)
      .click({
        offset: {
          x: 47.546875,
          y: 22.5,
        },
      });
  }
  {
    const targetPage = page;
    await puppeteer.Locator.race([
      targetPage.locator("::-p-aria( LOGIN)"),
      targetPage.locator("li:nth-of-type(6) > a"),
      targetPage.locator(
        '::-p-xpath(//*[@id=\\"navbarSupportedContent\\"]/ul/li[6]/a)'
      ),
      targetPage.locator(":scope >>> li:nth-of-type(6) > a"),
      targetPage.locator("::-p-text(Login)"),
    ])
      .setTimeout(timeout)
      .click({
        offset: {
          x: 45.546875,
          y: 23.5,
        },
      });
  }
  {
    const targetPage = page;
    await puppeteer.Locator.race([
      targetPage.locator("::-p-aria( LOGIN)"),
      targetPage.locator("li:nth-of-type(6) > a"),
      targetPage.locator(
        '::-p-xpath(//*[@id=\\"navbarSupportedContent\\"]/ul/li[6]/a)'
      ),
      targetPage.locator(":scope >>> li:nth-of-type(6) > a"),
      targetPage.locator("::-p-text(Login)"),
    ])
      .setTimeout(timeout)
      .click({
        offset: {
          x: 42.546875,
          y: 11.5,
        },
      });
  }
  await lhFlow.endTimespan();
  await lhFlow.startNavigation();
  {
    const targetPage = page;
    const promises = [];
    const startWaitingForEvents = () => {
      promises.push(targetPage.waitForNavigation());
    };
    await puppeteer.Locator.race([
      targetPage.locator("::-p-aria(TEAM)"),
      targetPage.locator("li:nth-of-type(5) > a"),
      targetPage.locator(
        '::-p-xpath(//*[@id=\\"navbarSupportedContent\\"]/ul/li[5]/a)'
      ),
      targetPage.locator(":scope >>> li:nth-of-type(5) > a"),
    ])
      .setTimeout(timeout)
      .on("action", () => startWaitingForEvents())
      .click({
        offset: {
          x: 34.765625,
          y: 21.5,
        },
      });
    await Promise.all(promises);
  }
  await lhFlow.endNavigation();
  await lhFlow.startTimespan();
  {
    const targetPage = page;
    await puppeteer.Locator.race([
      targetPage.locator("::-p-aria( LOGIN)"),
      targetPage.locator("li:nth-of-type(6) > a"),
      targetPage.locator(
        '::-p-xpath(//*[@id=\\"navbarSupportedContent\\"]/ul/li[6]/a)'
      ),
      targetPage.locator(":scope >>> li:nth-of-type(6) > a"),
      targetPage.locator("::-p-text(Login)"),
    ])
      .setTimeout(timeout)
      .click({
        offset: {
          x: 45.546875,
          y: 14.5,
        },
      });
  }
  await lhFlow.endTimespan();
  const lhFlowReport = await lhFlow.generateReport();
  await session.send("Input.synthesizeScrollGesture", {
    x: 100,
    y: 0,
    yDistance: -2500,
    speed: 1000,
    repeatCount: 2,
    repeatDelayMs: 250,
  });
  fs.writeFileSync(__dirname + "/flow.report.html", lhFlowReport);

  await browser.close();
})().catch((err) => {
  console.error(err);
  process.exit(1);
});

```

**Comment by adamraine** [comment]
I was able to reproduce this without Lighthouse and filed a bug with puppeteer: https://github.com/puppeteer/puppeteer/issues/11138

**Comment by adamraine** [comment]
The site is no longer available, so we can't reproduce this anymore. @sandeepchan we can consider reopening if you provide another site where this happens.
