### ISSUE TITLE
SyntaxError: The "start lh:runner:gather" performance mark has not been set

### ISSUE THREAD

**Issue by brdaugherty** [GoogleChrome/lighthouse#15529]
I am able to reliably reproduce [15379](https://github.com/GoogleChrome/lighthouse/issues/15379), or something very close to this when `preset` is unset and `plugins` is defined in the options passed to lighthouse. See lines 40,43 of Gist.  The origin being audited matters, not all URIs result in an exception being thrown, see line 36 of Gist.

https://gist.github.com/brdaugherty/3a2b19a46fd94649430800ce0623e3d8

Exception 
```0|gis-lh-plugin-runner  | SyntaxError: The "start lh:runner:gather" performance mark has not been set
0|gis-lh-plugin-runner  |     at new DOMException (node:internal/per_context/domexception:53:5)
0|gis-lh-plugin-runner  |     at __node_internal_ (node:internal/util:664:10)
0|gis-lh-plugin-runner  |     at getMark (node:internal/perf/usertiming:68:11)
0|gis-lh-plugin-runner  |     at calculateStartDuration (node:internal/perf/usertiming:193:13)
0|gis-lh-plugin-runner  |     at measure (node:internal/perf/usertiming:211:7)
0|gis-lh-plugin-runner  |     at Performance.measure (node:internal/perf/performance:135:12)
0|gis-lh-plugin-runner  |     at exports.stop (/var/www/html/gis-lighthouse/node_modules/marky/lib/marky.cjs.js:77:24)
0|gis-lh-plugin-runner  |     at Log.timeEnd (file:///var/www/html/gis-lighthouse/node_modules/lighthouse-logger/index.js:144:11)
0|gis-lh-plugin-runner  |     at Runner.gather (file:///var/www/html/gis-lighthouse/node_modules/lighthouse/core/runner.js:216:13)
0|gis-lh-plugin-runner  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

_Originally posted by @brdaugherty in https://github.com/GoogleChrome/lighthouse/issues/15379#issuecomment-1756347314_

**Comment by adamraine** [comment]
If you have more information, please add it to #15379
