### ISSUE TITLE
Could not create page handle for the target page

### ISSUE THREAD

**Issue by henning-kln** [GoogleChrome/lighthouse#15530]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://app.baeckerei-welsch.de/auth

### What happened?

The report crashed and showed a error window, with the message to report it to github.

### What did you expect?

I expected to run the test

### What have you tried?

Other pages without connecting to a phone. Then it works, with the debugging the phone, it doesn't work.

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

The newest Version with Chrome

### Chrome Version

117.0.0.0

### OS

Windows, Manjaro Linux

### Relevant log output

```shell
Channel: DevTools
Initial URL: https://app.baeckerei-welsch.de/auth
Chrome Version: 117.0.0.0
Stack Trace: Error: Could not create page handle for the target page
    at i (devtools://devtools/remote/serve_internal_file/@588c66dfb93af8aa3bb790479b69bb79e1bf194a/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js:1:2404)
    at async self.onmessage (devtools://devtools/remote/serve_internal_file/@588c66dfb93af8aa3bb790479b69bb79e1bf194a/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js:1:3002)
```
```

**Comment by adamraine** [comment]
I haven't reproduced this yet, and there could be a lot of different reasons for this error.

> Other pages without connecting to a phone. Then it works, with the debugging the phone, it doesn't work.

Are you connection to a remote device? Can you provide more details about this setup?

**Comment by henning-kln** [comment]
Yes only on remote devices, on chrome itself it works fine on every page.

**Comment by adamraine** [comment]
Gotcha, I can reproduce this.

**Comment by adamraine** [comment]
So I can repro on Chrome Stable (M117), but Lighthouse works on Chrome Canary (M120). @henning-kln can you confirm if using a newer version of Chrome fixes the issue for you?

**Comment by henning-kln** [comment]
Where can i select Chrome Canary

**Comment by adamraine** [comment]
https://www.google.com/chrome/canary/

**Comment by henning-kln** [comment]
thx, but Linux is not supported

**Comment by henning-kln** [comment]
On Windows with Chrome Canary:
Could not create page handle for the target page
```
Channel: DevTools
Initial URL: https://app.baeckerei-welsch.de/auth
Chrome Version: 120.0.0.0
Stack Trace: Error: Could not create page handle for the target page
    at i (devtools://devtools/remote/serve_internal_file/@588c66dfb93af8aa3bb790479b69bb79e1bf194a/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js:1:2404)
    at async self.onmessage (devtools://devtools/remote/serve_internal_file/@588c66dfb93af8aa3bb790479b69bb79e1bf194a/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js:1:3002)
```

**Comment by adamraine** [comment]
@henning-kln can you provide the full version from your canary if you go to chrome://version/

**Comment by DmitryEfimenko** [comment]
The error occurs for me when trying to inspect a tab open with Samsung browser. For example, https://www.x.com

Could not create page handle for the target page
```
Channel: DevTools
Initial URL: https://twitter.com/
Chrome Version: 123.0.0.0
Stack Trace: Error: Could not create page handle for the target page
    at i (devtools://devtools/remote/serve_rev/@1404acff38afe99f1585ba7d820005d6ca209351/entrypoints/lighthouse_worker/lighthouse_worker.js:1:2404)
    at async self.onmessage (devtools://devtools/remote/serve_rev/@1404acff38afe99f1585ba7d820005d6ca209351/entrypoints/lighthouse_worker/lighthouse_worker.js:1:3002)
```

Chrome version on PC:
Version 123.0.6312.106 (Official Build) (64-bit)

Samsung Internet Browser version on Phone:
Version 24.0.7.1 (latest)

Phone:
Pixel 6a
Andrpoid 14

**Comment by adamraine** [comment]
> The error occurs for me when trying to inspect a tab open with Samsung browser

Sorry, we don't support Samsung browser
