### ISSUE TITLE
Protocol error (Target.attachToTarget): No target with given id found

### ISSUE THREAD

**Issue by yumengChenVerticalScope** [GoogleChrome/lighthouse#15634]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://www.ratemds.com/best-doctors/on/toronto/urologist/

### What happened?

Protocol error (Target.attachToTarget): No target with given id found
The error message asks me to report this issue

### What did you expect?

That it provides a report

### What have you tried?

The error message asks me to report this issue

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

11.1.0

### Relevant log output

```shell
Channel: DevTools
Initial URL: https://www.ratemds.com/best-doctors/on/toronto/urologist/
Chrome Version: 119.0.0.0
Stack Trace: Xe: Protocol error (Target.attachToTarget): No target with given id found
    at <instance_members_initializer> (devtools://devtools/bundled/devtools-frontend/front_end/third_party/puppeteer/puppeteer.js:1:35288)
    at new At (devtools://devtools/bundled/devtools-frontend/front_end/third_party/puppeteer/puppeteer.js:1:35327)
    at Ot.create (devtools://devtools/bundled/devtools-frontend/front_end/third_party/puppeteer/puppeteer.js:1:35822)
    at t._rawSend (devtools://devtools/bundled/devtools-frontend/front_end/third_party/puppeteer/puppeteer.js:1:36921)
    at t.send (devtools://devtools/bundled/devtools-frontend/front_end/third_party/puppeteer/puppeteer.js:1:36872)
    at t._createSession (devtools://devtools/bundled/devtools-frontend/front_end/third_party/puppeteer/puppeteer.js:1:38203)
    at devtools://devtools/bundled/devtools-frontend/front_end/services/puppeteer/puppeteer.js:1:993
    at Array.map (<anonymous>)
    at PuppeteerConnectionHelper.connectPuppeteerToConnection (devtools://devtools/bundled/devtools-frontend/front_end/services/puppeteer/puppeteer.js:1:983)
    at o (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40eaa767197fa7dd412133d1b84f7eb60da43409c9%2F:1:1816)
```
```

**Comment by adamraine** [comment]
For reference #15161 

I can't reproduce this. What OS and Chrome version are you using?

**Comment by yumengChenVerticalScope** [comment]
macOS 12.2.1 Chrome Version 119.0.6045.159 (Official Build) (arm64)
