### ISSUE TITLE
i run light house and got INVALID_URL error it says to report it in github repo

### ISSUE THREAD

**Issue by bilalbutt044** [GoogleChrome/lighthouse#15657]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

www.sparkon.org

### What happened?

i ran light house and got this error 

INVALID_URL
```
Channel: DevTools
Initial URL: 
Chrome Version: 119.0.0.0
Stack Trace: LighthouseError: INVALID_URL
    at UrlUtils.normalizeUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:250:39543)
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:447:13093
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:260:197012)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:447:13063)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:447:14473)
    at async o (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40f6fcaed63cb61e2eeff44a3268ac6fbaaa2a8f88%2F:1:2362)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40f6fcaed63cb61e2eeff44a3268ac6fbaaa2a8f88%2F:1:2716)
```

### What did you expect?

it should run well and return matrix of my website

### What have you tried?

nothing special, simply click `Analyze page load` button  and get above error

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

dont know as it is not generating any report

### Chrome Version

Version 119.0.6045.200 (Official Build) (64-bit)

### OS

window 11

### Relevant log output

```shell
INVALID_URL

Channel: DevTools
Initial URL: 
Chrome Version: 119.0.0.0
Stack Trace: LighthouseError: INVALID_URL
    at UrlUtils.normalizeUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:250:39543)
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:447:13093
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:260:197012)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:447:13063)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:447:14473)
    at async o (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40f6fcaed63cb61e2eeff44a3268ac6fbaaa2a8f88%2F:1:2362)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40f6fcaed63cb61e2eeff44a3268ac6fbaaa2a8f88%2F:1:2716)
```
```

**Comment by adamraine** [comment]
I can't reproduce this. @bilalbutt044 can you try auditing from an incognito window?

**Comment by bilalbutt044** [comment]
I did try that time in incognito mode but it was showing error. But it is
working now.

Not sure why it was throwing error that time
