### ISSUE TITLE
Ran into error running in incog

### ISSUE THREAD

**Issue by justingolden21** [GoogleChrome/lighthouse#15719]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://desktopclock.app/

### What happened?

```
Channel: DevTools
Initial URL: 
Chrome Version: 120.0.0.0
Stack Trace: LighthouseError: INVALID_URL
    at UrlUtils.normalizeUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:252:39542)
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:449:13090
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:446:3581)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:449:13061)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:449:14470)
    at async a (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40204016af461e03117aa3858b51ba4534c7cfda81%2F:1:2166)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%40204016af461e03117aa3858b51ba4534c7cfda81%2F:1:2520)
```

### What did you expect?

Successful run

### What have you tried?

Ran in incog on website

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

latest as of 12-28-2023 chrome dev tools

### Chrome Version

Version 120.0.6099.130 (Official Build) (64-bit)

### Node Version

n/a

### OS

windows 10

### Relevant log output

```shell
Ah, sorry! We ran into an error.
```

**Comment by justingolden21** [comment]
Didn't work after multiple refreshes, hard refreshes, and new tabs. Opened a new tab and ran on youtube as an example site and it worked. Then in that tab, navigated to the original url and it worked.

**Comment by adamraine** [comment]
I can't repro this. We have seen this error pop up a few times in the past (e.g. https://github.com/GoogleChrome/lighthouse/issues/13956) but without a repro it's hard to know what's going on in this case. Does restarting Chrome fix this issue at all?
