### ISSUE TITLE
Improve `runtimeError`

### ISSUE THREAD

**Issue by connorjclark** [GoogleChrome/lighthouse#15825]
#15824 produces these errors in the LHR:

```json
"runtimeError": {
  "code": "PROTOCOL_TIMEOUT",
  "message": "Waiting for DevTools protocol response has exceeded the allotted time. (Method: Runtime.evaluate)"
},
...
"accesskeys": {
  "id": "accesskeys",
  "title": "`[accesskey]` values are unique",
  "description": "Access keys let users quickly focus a part of the page. For proper navigation, each access key must be unique. [Learn more about access keys](https://dequeuniversity.com/rules/axe/4.8/accesskeys).",
  "score": null,
  "scoreDisplayMode": "error",
  "errorMessage": "Required Accessibility gatherer encountered an error: PROTOCOL_TIMEOUT",
  "errorStack": "LighthouseError: PROTOCOL_TIMEOUT\n    at file:///usr/local/google/home/cjamcl/code/lighthouse/core/gather/session.js:102:47\n    at new Promise (<anonymous>)\n    at ProtocolSession.sendCommand (file:///usr/local/google/home/cjamcl/code/lighthouse/core/gather/session.js:100:28)\n    at ExecutionContext._evaluateInContext (file:///usr/local/google/home/cjamcl/code/lighthouse/core/gather/driver/execution-context.js:128:42)\n    at ExecutionContext.evaluateAsync (file:///usr/local/google/home/cjamcl/code/lighthouse/core/gather/driver/execution-context.js:173:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///usr/local/google/home/cjamcl/code/lighthouse/core/gather/runner-helpers.js:106:24\n    at async collectPhaseArtifacts (file:///usr/local/google/home/cjamcl/code/lighthouse/core/gather/runner-helpers.js:123:5)\n    at async _computeNavigationResult (file:///usr/local/google/home/cjamcl/code/lighthouse/core/gather/navigation-runner.js:186:5)\n    at async file:///usr/local/google/home/cjamcl/code/lighthouse/core/gather/navigation-runner.js:310:25"
},
```

1. runtimeError should have a stack trace
2. I want to know which gatherer or whatever failed from runtimeError
3.  Can we possibly get async stack traces? the stack in the audit error is missing the line that actually issued the Runtime.evaluate

**Comment by connorjclark** [comment]
seems #16524 added this, closing.
