### ISSUE TITLE
Runtime error encountered: Error: Expected expectedValue of type boolean, got number: Error in determining viewport

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1582]
Using Chrome 56.0.2924.76 (64-bit) and current master (4350e67a9bf53a34dbf489859e0c783df82f5064) on Windows 7 64-bit with node.js 6.9.4.

```
C:\Users\xmr\Desktop\lighthouse>node lighthouse-cli\index.js --output=pretty https://kangax.github.io/html-minifier/

  Lighthouse CLI Launching Chrome... +0ms
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +0ms
  ChromeLauncher Waiting for browser...√ +536ms
  status Initializing… +990ms
  status Loading page & waiting for onload +365ms URL, HTTPS, Viewport, ThemeColor, Manifest, Accessibility, ImageUsage, ContentWidth
  statusEnd Loading page & waiting for onload +4s
  status Retrieving trace +0ms
  status Retrieving network records +240ms
  status Retrieving: URL +0ms
  status Retrieving: HTTPS +0ms
  status Retrieving: Viewport +16ms
  status Retrieving: ThemeColor +0ms
  status Retrieving: Manifest +0ms
  status Retrieving: Accessibility +0ms
  status Retrieving: ImageUsage +594ms
  status Retrieving: ContentWidth +0ms
  status Loading page & waiting for onload +352ms ServiceWorker, Offline
  statusEnd Loading page & waiting for onload +551ms
  status Retrieving network records +2ms
  status Retrieving: ServiceWorker +2ms
  status Retrieving: Offline +1ms
  status Loading page & waiting for onload +322ms HTTPRedirect, HTMLWithoutJavaScript
  statusEnd Loading page & waiting for onload +1s
  status Retrieving network records +2ms
  status Retrieving: HTTPRedirect +2ms
  status Retrieving: HTMLWithoutJavaScript +3ms
  status Loading page & waiting for onload +360ms ChromeConsoleMessages, Styles, CSSUsage, EventListeners, AnchorsWithNoRelNoopener, AppCacheManifest, ConsoleTimeUsage, DateNowUse, DocWriteUse, GeolocationOnStart, NotificationOnStart, OptimizedImages, TagsBlockingFirstPaint, WebSQL
  statusEnd Loading page & waiting for onload +3s
  status Retrieving network records +0ms
  status Retrieving: ChromeConsoleMessages +0ms
  status Retrieving: Styles +0ms
  status Retrieving: CSSUsage +125ms
  status Retrieving: EventListeners +15ms
  status Retrieving: AnchorsWithNoRelNoopener +393ms
  status Retrieving: AppCacheManifest +0ms
  status Retrieving: ConsoleTimeUsage +16ms
  status Retrieving: DateNowUse +0ms
  status Retrieving: DocWriteUse +0ms
  status Retrieving: GeolocationOnStart +0ms
  status Retrieving: NotificationOnStart +15ms
  status Retrieving: OptimizedImages +0ms
  status Retrieving: TagsBlockingFirstPaint +16ms
  status Retrieving: WebSQL +0ms
  status Disconnecting from browser... +522ms
  status Evaluating: Site is on HTTPS +16ms
  status Evaluating: Site redirects HTTP traffic to HTTPS +0ms
  status Evaluating: Has a registered Service Worker +0ms
  status Evaluating: URL responds with a 200 when offline +0ms
  status Evaluating: HTML has a `<meta name="viewport">` tag containing `width` or `initial-scale` +0ms
  status Evaluating: Manifest's `display` property is set +0ms
  status Evaluating: Page contains some content when its scripts are not available +16ms
  status Evaluating: First meaningful paint +0ms
  status Evaluating: Perceptual Speed Index +15ms
  status Evaluating: Estimated Input Latency +954ms
  status Evaluating: Time To Interactive (alpha) +528ms
  status Evaluating: User Timing marks and measures +372ms
  status Evaluating: Screenshots of all captured frames +0ms
  status Evaluating: Critical Request Chains +156ms
  status Evaluating: Manifest exists +0ms
  status Evaluating: Manifest contains `background_color` +0ms
  status Evaluating: Manifest contains `theme_color` +0ms
  status Evaluating: Manifest contains icons at least 192px +16ms
  status Evaluating: Manifest contains icons at least 144px +0ms
  status Evaluating: Manifest contains `name` +0ms
  status Evaluating: Manifest contains `short_name` +0ms
  status Evaluating: Manifest's `short_name` won't be truncated when displayed on homescreen +0ms
  status Evaluating: Manifest contains `start_url` +0ms
  status Evaluating: HTML has a `<meta name="theme-color">` tag +0ms
  status Evaluating: Site does not have more than 10% unused CSS +0ms
  status Evaluating: Content is sized correctly for the viewport +0ms
  status Evaluating: Site does not use deprecated APIs +0ms
  status Evaluating: Element aria-* attributes are allowed for this role +15ms
  status Evaluating: Elements with ARIA roles have the required aria-* attributes +0ms
  status Evaluating: Element aria-* attributes have valid values +0ms
  status Evaluating: Element aria-* attributes are valid and not misspelled or non-existent. +0ms
  status Evaluating: Background and foreground colors have a sufficient contrast ratio +0ms
  status Evaluating: Every image element has an alt attribute +0ms
  status Evaluating: Every form element has a label +0ms
  status Evaluating: No element has a `tabindex` attribute greater than 0 +0ms
  status Evaluating: Site opens external anchors using rel="noopener" +0ms
  status Evaluating: Site does not use Application Cache +0ms
  status Evaluating: Page does not automatically request geolocation on page load +0ms
  status Evaluating: Site does not use <link> that delay first paint +16ms
  status Evaluating: Site does not use `console.time()` in its own scripts +0ms
  status Evaluating: Site does not use `Date.now()` in its own scripts +0ms
  status Evaluating: Site does not use document.write() +0ms
  status Evaluating: Site does not use Mutation Events in its own scripts +0ms
  status Evaluating: Site does not use the old CSS flexbox +0ms
  status Evaluating: Site does not use WebSQL DB. +15ms
  status Evaluating: Page does not automatically request notification permissions on page load +0ms
  status Evaluating: Site does not use <script> in head that delays first paint +0ms
  status Evaluating: Site uses HTTP/2 for its own resources +0ms
  status Evaluating: Site uses optimized images +0ms
  status Evaluating: Site uses appropriate image sizes +0ms
  status Evaluating: Site uses passive listeners to improve scrolling performance +16ms
  ChromeLauncher Killing all Chrome Instances +0ms
Runtime error encountered: Error: Expected expectedValue of type boolean, got number: Error in determining viewport
    at Function._convertToWeight (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\aggregator\aggregate.js:97:13)
    at expectedNames.forEach.e (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\aggregator\aggregate.js:191:35)
    at Array.forEach (native)
    at items.map.item (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\aggregator\aggregate.js:164:21)
    at Array.map (native)
    at Function.compare (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\aggregator\aggregate.js:148:18)
    at Function.aggregate (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\aggregator\aggregate.js:226:29)
    at config.aggregations.map.a (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\runner.js:133:28)
    at Array.map (native)
    at run.then.runResults (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\runner.js:132:46)
Error: Expected expectedValue of type boolean, got number: Error in determining viewport
    at Function._convertToWeight (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\aggregator\aggregate.js:97:13)
    at expectedNames.forEach.e (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\aggregator\aggregate.js:191:35)
    at Array.forEach (native)
    at items.map.item (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\aggregator\aggregate.js:164:21)
    at Array.map (native)
    at Function.compare (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\aggregator\aggregate.js:148:18)
    at Function.aggregate (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\aggregator\aggregate.js:226:29)
    at config.aggregations.map.a (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\runner.js:133:28)
    at Array.map (native)
    at run.then.runResults (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\runner.js:132:46)
```

**Comment by brendankenny** [comment]
de-duping into #1148
