### ISSUE TITLE
Protocol error (Storage.getUsageAndQuota): Quota information is not available

### ISSUE THREAD

**Issue by Uday-1011** [GoogleChrome/lighthouse#15848]
Protocol error (Storage.getUsageAndQuota): Quota information is not available
```
Channel: DevTools
Initial URL: https://www.amazon.in/?&tag=googhydrabk1-21&ref=pd_sl_7hz2t19t5c_e&adgrpid=155259815513&hvpone=&hvptwo=&hvadid=678802104188&hvpos=&hvnetw=g&hvrand=2252870100712201940&hvqmt=e&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9302350&hvtargid=kwd-10573980&hydadcr=14453_2371562&gad_source=1
Chrome Version: 122.0.0.0
Stack Trace: dt: Protocol error (Storage.getUsageAndQuota): Quota information is not available
    at <instance_members_initializer> (devtools://devtools/bundled/devtools-frontend/front_end/third_party/puppeteer/puppeteer.js:74:622)
    at new Kt (devtools://devtools/bundled/devtools-frontend/front_end/third_party/puppeteer/puppeteer.js:74:661)
    at $t.create (devtools://devtools/bundled/devtools-frontend/front_end/third_party/puppeteer/puppeteer.js:74:29)
    at s._rawSend (devtools://devtools/bundled/devtools-frontend/front_end/third_party/puppeteer/puppeteer.js:125:602)
    at Vt.send (devtools://devtools/bundled/devtools-frontend/front_end/third_party/puppeteer/puppeteer.js:74:1424)
    at Bh.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:454:8392)
    at getImportantStorageWarning (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:454:20930)
    at resetStorageForUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:457:1512)
    at async prepareTargetForNavigationMode (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:457:2585)
    at async _setup (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:457:9267)
```

**Comment by adamraine** [comment]
I can't reproduce this, does restarting Chrome help?
