### ISSUE TITLE
Invalid_url when trying to run in Incognito

### ISSUE THREAD

**Issue by tsgoldladder** [GoogleChrome/lighthouse#15855]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).

### URL

https://measurable.energy

### What happened?

INVALID_URL
```
Channel: DevTools
Initial URL: 
Chrome Version: 122.0.0.0
Stack Trace: LighthouseError: INVALID_URL
    at UrlUtils.normalizeUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:253:109917)
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:457:12406
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:450:3581)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:457:12377)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:457:13727)
    at async a (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%409d4c1072da62b411b351a38b9ed6214ab236aa7b%2F:1:2166)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%409d4c1072da62b411b351a38b9ed6214ab236aa7b%2F:1:2527)
```

### What did you expect?

Normal lighthouse report function. Wouldn't begin.

### What have you tried?

Mobile and Desktop scans.
Mode: Nav
Categories: Performance, Accessibility

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

not sure

### Chrome Version

122.0.6261.111

### OS

Windows 10

### Relevant log output

```shell
Channel: DevTools
Initial URL: 
Chrome Version: 122.0.0.0
Stack Trace: LighthouseError: INVALID_URL
    at UrlUtils.normalizeUrl (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:253:109917)
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:457:12406
    at Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:450:3581)
    at navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:457:12377)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:457:13727)
    at async a (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%409d4c1072da62b411b351a38b9ed6214ab236aa7b%2F:1:2166)
    at async self.onmessage (devtools://devtools/bundled/devtools-frontend/front_end/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%409d4c1072da62b411b351a38b9ed6214ab236aa7b%2F:1:2527)
```

**Comment by adamraine** [comment]
I can't reproduce this, but we did [fix a cause](https://issues.chromium.org/issues/41490473) of the `INVALID_URL` error in M123 and looks like you are on M122.

Does this work using a newer version of Chrome (e.g. Chrome beta)?
