### ISSUE TITLE
I don't know, it told me to report to the github repository

### ISSUE THREAD

**Issue by OinkiePie** [GoogleChrome/lighthouse#15996]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

http://127.0.0.1:5500/commands

### What happened?

error
![изображение_2024-05-13_233134717](https://github.com/GoogleChrome/lighthouse/assets/150623384/e4e4fef3-6bcc-41a3-8b63-f12144c58b39)

### What did you expect?

I expected this to check my site

### What have you tried?

check my site

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

11.3.0

### Chrome Version

121.0.0.0

### Node Version

20.10.0

### OS

windows 10

### Relevant log output

```sh
INVALID_URL

Channel: DevTools
Initial URL: 
Chrome Version: 121.0.0.0
Stack Trace: LighthouseError: INVALID_URL
    at UrlUtils.normalizeUrl (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:252:39542)
    at devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:449:12402
    at Runner.gather (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:446:3581)
    at navigationGather (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:449:12373)
    at async navigation (devtools://devtools/bundled/third_party/lighthouse/lighthouse-dt-bundle.js:449:13723)
    at async a (devtools://devtools/bundled/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%406f54147f20896c29d462c15c7b62fd0d8510cd41%2F:1:2166)
    at async self.onmessage (devtools://devtools/bundled/entrypoints/lighthouse_worker/lighthouse_worker.js?remoteBase=https%3A%2F%2Fchrome-devtools-frontend.appspot.com%2Fserve_file%2F%406f54147f20896c29d462c15c7b62fd0d8510cd41%2F:1:2520)
```
```

**Comment by adamraine** [comment]
The report is using M121 but we fixed a major cause of `INVALID_URL` errors in M123: https://chromiumdash.appspot.com/commit/f1d39232489aa8260d9cd4ca63d6f305838ff55a

It's possible this isn't happening on the latest version of Chrome.
