### ISSUE TITLE
PROTOCOL_TIMEOUT

### ISSUE THREAD

**Issue by Gennaro91** [GoogleChrome/lighthouse#16052]
### FAQ

- [X] Yes, my issue is not about [variability](https://github.com/GoogleChrome/lighthouse/blob/main/docs/variability.md) or [throttling](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md).
- [X] Yes, my issue is not about a specific accessibility audit (file with [axe-core](https://github.com/dequelabs/axe-core) instead).
- [X] Yes, my issue is not answered by [other FAQs](https://github.com/GoogleChrome/lighthouse#faq).

### URL

https://cercalatuascuola.istruzione.it/cercalatuascuola/istituti/LUTD00701D/abenedetti/informazioni/COMPETENZA/31

### What happened?

I got this error:

PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://cercalatuascuola.istruzione.it/cercalatuascuola/istituti/LUTD00701D/abenedetti/informazioni/COMPETENZA/31
Chrome Version: 118.0.0.0
Stack Trace: LighthouseError: PROTOCOL_TIMEOUT
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:300:781
    at new Promise (<anonymous>)
    at yp.sendCommand (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:300:734)
    at devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:446:863
    at _navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:446:11522)
    at async _navigations (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:446:11896)
    at async devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:446:12853
    at async Runner.gather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:259:196013)
    at async navigationGather (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:446:12537)
    at async navigation (devtools://devtools/bundled/devtools-frontend/front_end/third_party/lighthouse/lighthouse-dt-bundle.js:446:13956)
```

### What did you expect?

I expect that lighthouse analyse the webpage to tell me why it's slow in loading.

### What have you tried?

vv

### How were you running Lighthouse?

Chrome DevTools

### Lighthouse Version

boh

**Comment by adamraine** [comment]
https://github.com/GoogleChrome/lighthouse/issues/6512
