### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by tit** [GoogleChrome/lighthouse#1767]
I have:
- OSX, Darwin Kernel Version 16.5.0
- npm, 2.4.1
- node, v0.10.36
- lighthouse, 1.5.1

I installed lighthouse `# npm install -g lighthouse`.
When I call `lighthouse` in CLI, I have error:
```
$ lighthouse
/opt/local/lib/node_modules/lighthouse/lighthouse-cli/compiled-check.js:3
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/local/lib/node_modules/lighthouse/lighthouse-cli/index.js:5:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

What did I do wrong?
_Sorry for my bad English_

**Comment by patrickhulce** [comment]
Your version of node is quite old, Lighthouse only officially supports version 6+ (which has support for `const`/`let`/a host of other JS goodies. I suggest grabbing [nvm](https://github.com/creationix/nvm) to manage multiple node versions if you still need v0.10 for other packages.

**Comment by tit** [comment]
@patrickhulce, thanx!
It working for me.
I installed nvm and installed last node version (7.6.0).
After this I correctly run lighthouse.
