### ISSUE TITLE
perf config fails: Error: aggregations: unused-css-rules audit does not contain expectedValue or weight properties

### ISSUE THREAD

**Issue by tommycli** [GoogleChrome/lighthouse#1775]
Running:
lighthouse --perf http://google.com yields the below error.

Running just:
lighthouse http://google.com without the perf config works fine.

Runtime error encountered: Error: aggregations: unused-css-rules audit does not contain expectedValue or weight properties
    at Function._convertToWeight (/usr/local/google/home/tommycli/local/lib/node_modules/lighthouse/lighthouse-core/aggregator/aggregate.js:77:13)
    at expectedNames.forEach.e (/usr/local/google/home/tommycli/local/lib/node_modules/lighthouse/lighthouse-core/aggregator/aggregate.js:176:35)
    at Array.forEach (native)
    at items.map.item (/usr/local/google/home/tommycli/local/lib/node_modules/lighthouse/lighthouse-core/aggregator/aggregate.js:169:21)
    at Array.map (native)
    at Function.compare (/usr/local/google/home/tommycli/local/lib/node_modules/lighthouse/lighthouse-core/aggregator/aggregate.js:153:18)
    at Function.aggregate (/usr/local/google/home/tommycli/local/lib/node_modules/lighthouse/lighthouse-core/aggregator/aggregate.js:209:29)
    at config.aggregations.map.a (/usr/local/google/home/tommycli/local/lib/node_modules/lighthouse/lighthouse-core/runner.js:134:28)
    at Array.map (native)
    at run.then.runResults (/usr/local/google/home/tommycli/local/lib/node_modules/lighthouse/lighthouse-core/runner.js:133:46)
Error: aggregations: unused-css-rules audit does not contain expectedValue or weight properties
    at Function._convertToWeight (/usr/local/google/home/tommycli/local/lib/node_modules/lighthouse/lighthouse-core/aggregator/aggregate.js:77:13)
    at expectedNames.forEach.e (/usr/local/google/home/tommycli/local/lib/node_modules/lighthouse/lighthouse-core/aggregator/aggregate.js:176:35)
    at Array.forEach (native)
    at items.map.item (/usr/local/google/home/tommycli/local/lib/node_modules/lighthouse/lighthouse-core/aggregator/aggregate.js:169:21)
    at Array.map (native)
    at Function.compare (/usr/local/google/home/tommycli/local/lib/node_modules/lighthouse/lighthouse-core/aggregator/aggregate.js:153:18)
    at Function.aggregate (/usr/local/google/home/tommycli/local/lib/node_modules/lighthouse/lighthouse-core/aggregator/aggregate.js:209:29)
    at config.aggregations.map.a (/usr/local/google/home/tommycli/local/lib/node_modules/lighthouse/lighthouse-core/runner.js:134:28)
    at Array.map (native)
    at run.then.runResults (/usr/local/google/home/tommycli/local/lib/node_modules/lighthouse/lighthouse-core/runner.js:133:46)

**Comment by paulirish** [comment]
Thanks. This will be fixed when #1724 lands.

Which will be any second now...

**Comment by paulirish** [comment]
fixed by #1724
