### ISSUE TITLE
Latest master: Cannot find module './templates/report-templates'

### ISSUE THREAD

**Issue by XhmikosR** [GoogleChrome/lighthouse#1898]
```
C:\Users\xmr\Desktop\lighthouse>node -v && npm -v
v6.10.1
3.10.10

C:\Users\xmr\Desktop\lighthouse>git describe --tags
1.6.0-45-gca2600ac

C:\Users\xmr\Desktop\lighthouse>node lighthouse-cli\index.js --version
module.js:471
    throw err;
    ^

Error: Cannot find module './templates/report-templates'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\xmr\Desktop\lighthouse\lighthouse-core\report\report-generator.js:23:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by XhmikosR** [comment]
Duh, forgot to run `gulp`. I wish this was more automated someway...
