### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by Lidofernandez** [GoogleChrome/lighthouse#1900]
**Lighthouse Version**: 1.6.0
**Chrome Version**: 59.0.3046.0
**URL**: https://fashionunited.com/
**Error Message**: You must provide a url to the runner
**Stack Trace**:
 ```Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13600:23)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14685:15)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14711:18)
    at <anonymous>```

**Comment by XhmikosR** [comment]
Duplicate of #1899...
