### ISSUE TITLE
Unknown formatter: user-timings in exported lighthouse report in viewer

### ISSUE THREAD

**Issue by pedro93** [GoogleChrome/lighthouse#1985]
__Lighthouse version__: Pulled from master at 10/04/2017 10:37 GMT
__Google Chrome version__: 56.0.2924.87 64bit

__Stack trace__: 
```js
 Error: Unknown formatter: user-timings
    at Function.e.getByName (https://googlechrome.github.io/lighthouse/viewer/src/main.js:2:10262)
    at https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:12286
    at Array.forEach (native)
    at t._registerFormatters (https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:12206)
    at t.generateHTML (https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:12489)
    at e.replaceReportHTML (https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:25182)
    at https://googlechrome.github.io/lighthouse/viewer/src/main.js:4:27019
```

__Generated report__:
Its a zipped lighthouse-generated html file, github doesn't let me upload an html file. 
[github.com_2017-04-10_10-29-56.report.html.zip](https://github.com/GoogleChrome/lighthouse/files/909613/github.com_2017-04-10_10-29-56.report.html.zip)

**Comment by ebidel** [comment]
Yea sorry. Master and viewer speak different languages right now  :( 

Backstory is that we're refactoring things and have removed a bunch of code in master that Viewer expects. Everything should still work if you create the json report using the latest release of LH.

**Comment by gkalpak** [comment]
I am using lighthouse@2.1.0 and get an `Unknown formatter: url-list` error. My report looks like this:
```
{
  "userAgent": "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36(KHTML, like Gecko) Chrome/61.0.3116.0 Mobile Safari/537.36",
  "lighthouseVersion": "2.1.0",
  ...
  "audits": {
    "is-on-https": {
      "score": true,
      "displayValue": "",
      "rawValue": true,
      "extendedInfo": {
        "formatter": "url-list",
        "value": []
      },
      ...
```

I am using `require('lighthouse/lighthouse-cli/printer').write(results, 'json' outputFile)` to create the report.

##
Does this fall under the same category (lighthouse and viewer speaking different languages)?
