### ISSUE TITLE
Stuck on Retrieving: AnchorsWithNoRelNoopener

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#2086]
I can repro on v1.6.5 in both extension and CLI

```sh
node --trace-warnings lighthouse-cli https://www.webjet.com.au/
```
looks like a problem in `driver.getObjectProperty`:

output:
```sh
  status Retrieving: CSSUsage +1ms
  status Retrieving: EventListeners +60ms
  status Retrieving: AnchorsWithNoRelNoopener +857ms
(node:28599) TypeError: Cannot read property 'value' of undefined
    at sendCommand.then.properties (/Users/paulirish/code/lighthouse/lighthouse-core/gather/driver.js:509:40)
    at process._tickCallback (internal/process/next_tick.js:109:7)
(node:28599) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:69:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:86:11)
    at process._tickCallback (internal/process/next_tick.js:110:7)
(node:28599) TypeError: Cannot read property 'value' of undefined
    at sendCommand.then.properties (/Users/paulirish/code/lighthouse/lighthouse-core/gather/driver.js:509:40)
    at process._tickCallback (internal/process/next_tick.js:109:7)
(node:28599) TypeError: Cannot read property 'value' of undefined
    at sendCommand.then.properties (/Users/paulirish/code/lighthouse/lighthouse-core/gather/driver.js:509:40)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

source: 
![image](https://cloud.githubusercontent.com/assets/39191/25501576/183a2202-2b48-11e7-9108-df16b2145b67.png)

**Comment by patrickhulce** [comment]
fixed by #1892
