### ISSUE TITLE
Can't run cli on linux: Error: Cannot find module 'speedline'

### ISSUE THREAD

**Issue by m-renaud** [GoogleChrome/lighthouse#2188]
```
$ npm install -g lighthouse

/usr/local/bin/lighthouse -> /usr/local/lib/node_modules/lighthouse/lighthouse-cli/index.js
/usr/local/bin/chrome-debug -> /usr/local/lib/node_modules/lighthouse/lighthouse-cli/manual-chrome-launcher.js
lighthouse@1.6.5 /usr/local/lib/node_modules/lighthouse
├── json-stringify-safe@5.0.1
├── rimraf@2.2.8
├── metaviewport-parser@0.0.1
├── semver@5.3.0
├── marked@0.3.6
├── debug@2.2.0 (ms@0.7.1)
├── opn@4.0.2 (object-assign@4.1.1, pinkie-promise@2.0.1)
├── ws@1.1.1 (options@0.0.6, ultron@1.0.2)
├── whatwg-url@4.0.0 (webidl-conversions@3.0.1, tr46@0.0.3)
├── yargs@3.32.0 (decamelize@1.2.0, camelcase@2.1.1, y18n@3.2.1, window-size@0.1.4, os-locale@1.4.0, cliui@3.2.0, string-width@1.0.2)
├── axe-core@2.1.7
├── mkdirp@0.5.1 (minimist@0.0.8)
├── gl-matrix@2.3.2
├── update-notifier@2.1.0 (is-npm@1.0.0, semver-diff@2.1.0, xdg-basedir@3.0.0, lazy-req@2.0.0, chalk@1.1.3, configstore@3.0.0, latest-version@3.1.0, boxen@1.1.0)
├── handlebars@4.0.5 (async@1.5.2, source-map@0.4.4, optimist@0.6.1, uglify-js@2.8.23)
├── devtools-timeline-model@1.1.6 (resolve@1.1.7, chrome-devtools-frontend@1.0.401423)
├── chrome-devtools-frontend@1.0.422034
└── speedline@1.0.3 (image-ssim@0.2.0, babar@0.0.3, loud-rejection@1.6.0, jpeg-js@0.1.2, meow@3.7.0)
```

```
$ node --version
v7.10.0

$ npm --version
4.2.0
```

When running:

```
$ lighthouse https://www.chromium.org

Runtime error encountered: { Error: Cannot find module 'speedline'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/computed/speedline.js:20:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
Error: Cannot find module 'speedline'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/lighthouse/lighthouse-core/gather/computed/speedline.js:20:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by patrickhulce** [comment]
hm, very strange since even in the log it calls out the speedline version it installed 😆  does uninstalling and reinstalling help at all?

**Comment by m-renaud** [comment]
Uninstalling did not fix it.
Downgrading to node v6.10.3 did... *sigh*.

**Comment by lesteenman** [comment]
I have this issue on both node version 8.2.1, and node version 6.10.3. After either installing Lighthouse with `npm install lighthouse` or `npm install -g lighthouse`, running the created binary gives the same error:

```
Runtime error encountered: { Error: Cannot find module 'speedline'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/erik/pdp/node_modules/lighthouse/lighthouse-core/gather/computed/speedline.js:9:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
Error: Cannot find module 'speedline'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/erik/pdp/node_modules/lighthouse/lighthouse-core/gather/computed/speedline.js:9:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Re-installing does nothing.

**Comment by patrickhulce** [comment]
@lesteenman can you also confirm that the speedline directory was installed by `npm install`? For current Lighthouse, version 1.2 should be present in `node_modules`

**Comment by lesteenman** [comment]
It was not. Manually installing speedline (`npm install speedline`) still does not work, however, while it is in the correct place (I think):

```
erik@snatch /home/.../lib/node_modules echo $PWD
/home/erik/usr/local/lib/node_modules
erik@snatch /home/.../lib/node_modules which lighthouse
/home/erik/usr/local/bin/lighthouse
erik@snatch /home/.../lib/node_modules ls
lighthouse  npm   speedline

erik@snatch /home/.../lib/node_modules lighthouse --chrome-flags="--headless" https://google.nl
....
  ChromeLauncher Killing all Chrome Instances +12ms
Runtime error encountered: { Error: Cannot find module 'speedline'
    at Function.Module._resolveFilename (module.js:469:15)
```

**Comment by lesteenman** [comment]
Ok, it seems this is a local configuration issue, as we're running 2 versions of node side-by-side (one global, one for just the one user). This seems to be causing the issue, and it can probably be re-closed.

**Comment by patrickhulce** [comment]
thanks @lesteenman for the followup and sharing the issue for future puzzled installers :) glad it's sorted out!
