### ISSUE TITLE
DevTools Error: Unable to load the page: timeout reached (about:blank)

### ISSUE THREAD

**Issue by nimisis** [GoogleChrome/lighthouse#2362]
**Initial URL**: about:blank
**Chrome Version**: 60.0.3110.0
**Error Message**: Unable to load the page: timeout reached
**Stack Trace**:
```
Error: Unable to load the page: timeout reached
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@0d764046b1e7ea6eb145e2aa39a88a6d0ac3e714/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@0d764046b1e7ea6eb145e2aa39a88a6d0ac3e714/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by brendankenny** [comment]
We should probably just disable testing `about:blank`

**Comment by ev1stensberg** [comment]
I can work on this if you want to

**Comment by RockoDev** [comment]
I got the same error, but another URL and Chrome version. Just after trying to audit a site.

**Initial URL**: about:srcdoc
**Chrome Version**: 61.0.3119.0
**Error Message**: Unable to load the page: timeout reached
**Stack Trace**:
```
Error: Unable to load the page: timeout reached
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@177b9b934d8398dfb0d17b88fd9ff00f3291cca5/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@177b9b934d8398dfb0d17b88fd9ff00f3291cca5/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by patrickhulce** [comment]
Fix in progress https://chromium-review.googlesource.com/c/527430/

**Comment by patrickhulce** [comment]
fixed in https://chromium.googlesource.com/chromium/src/+/897b0f0e6b6054f5cf2419bf8891477a8eac1b20

**Comment by brendankenny** [comment]
do we want to block `about:blank` outside of devtools as well? The run ends with a timeout and the same error message in the CLI and extension.
