### ISSUE TITLE
npm package chrome-launcher miss dependencies rimraf

### ISSUE THREAD

**Issue by gwuhaolin** [GoogleChrome/lighthouse#2469]
only install package [chrome-launcher](https://www.npmjs.com/package/chrome-launcher) form npm without lighthouse, then use it will cause error:
```
Error: Cannot find module 'rimraf'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/halwu/WebstormProjects/chrome-render/node_modules/chrome-launcher/chrome-launcher.js:33:16)
```
and
```
module.js:472
    throw err;
    ^

Error: Cannot find module '../lighthouse-core/lib/log'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/halwu/WebstormProjects/chrome-render/node_modules/chrome-launcher/chrome-launcher.js:34:13)
```
it's cause by  miss dependencies `rimraf` in `chrome-launcher`'s package.json

**Comment by gwuhaolin** [comment]
why extra `chrome-launcher` from lighthouse to a standalone npm package? many scene need to launch chrome only instead of install lighthouse.

**Comment by ebidel** [comment]
It's also missing `log`:

```
module.js:487
    throw err;
    ^

Error: Cannot find module '../lighthouse-core/lib/log'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ericbidelman/projects/chrome/headless/node_modules/chrome-launcher/chrome-launcher.js:34:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by paulirish** [comment]
it's now published on npm as `chrome-launcher`.

docs: https://github.com/GoogleChrome/lighthouse/tree/master/chrome-launcher
