### ISSUE TITLE
DevTools Error: Unable to load the page: net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by ahmad1234567890zxvz** [GoogleChrome/lighthouse#2476]
**Initial URL**: https://www1.elm.com.sa/Portal/Ar/Topics/Services/Muqeem/
**Chrome Version**: 61.0.3124.0
**Error Message**: Unable to load the page: net::ERR_CONNECTION_TIMED_OUT
**Stack Trace**:
```
Error: Unable to load the page: net::ERR_CONNECTION_TIMED_OUT
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@e88b4570354eca47bc65a98bbba6013f73c6c816/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@e88b4570354eca47bc65a98bbba6013f73c6c816/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by patrickhulce** [comment]
@ahmad1234567890zxvz it looks like there are certificate issues on that site that prevent Chrome from visiting it without user intervention. If you're the owner of the site, you should try resolving those before running lighthouse.
