### ISSUE TITLE
 (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14050:23)

### ISSUE THREAD

**Issue by marktam** [GoogleChrome/lighthouse#2479]
**Lighthouse Version**: 2.1.0
**Chrome Version**: 59.0.3071.86
**Initial URL**: https://www.google.com/_/chrome/newtab-serviceworker.js
**Error Message**: You must provide a url to the runner
**Stack Trace**:
```
Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14050:23)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14505:15)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14530:18)
    at <anonymous>
```

**Comment by marktam** [comment]
https://www.google.com/_/chrome/newtab-serviceworker.js

**Comment by ebidel** [comment]
Lighthouse won't be able to test a .js file. You'll need to run it on a site.

Curious though, were you trying to test Chrome's new tab page? How did you get to this sw file?

**Comment by wardpeet** [comment]
@marktam can you tell us how you got to the newtab-serviceworker.js

**Comment by brendankenny** [comment]
As noted, testing a .js file won't work. Please comment and we can reopen if this URL was incorrectly reported
