### ISSUE TITLE
DevTools Error: Unable to load the page: net::ERR_FAILED

### ISSUE THREAD

**Issue by ispysoftware** [GoogleChrome/lighthouse#2559]
**Initial URL**: https://www.ispyconnect.com/monitor/app/summary
**Chrome Version**: 60.0.3112.32
**Error Message**: Unable to load the page: net::ERR_FAILED
**Stack Trace**:
```
Error: Unable to load the page: net::ERR_FAILED
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@17d6d37b6632cc655909327c7c0559c28bdbf388/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@17d6d37b6632cc655909327c7c0559c28bdbf388/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by ispysoftware** [comment]
my fault, missing file in manifest
