### ISSUE TITLE
DevTools Error: Unable to load the page: timeout reached

### ISSUE THREAD

**Issue by hugues-koolsol** [GoogleChrome/lighthouse#2590]
The bug happens in the test where the page is loaded with javascript disabled.

**Initial URL**: https://www.koolsol.com/?lang=fr
**Chrome Version**: 61.0.3139.0
**Error Message**: Unable to load the page: timeout reached
**Stack Trace**:
```
Error: Unable to load the page: timeout reached
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@2dd0ea84298d45e0962c595c591529bc84dd0ebd/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@2dd0ea84298d45e0962c595c591529bc84dd0ebd/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by hugues-koolsol** [comment]
Cannot reproduce today!
