### ISSUE TITLE
Extension Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by yaykyle** [GoogleChrome/lighthouse#2684]
Always gets stuck on the HTTP Redirect test (it somehow changes the page to about:blank).

**Lighthouse Version**: 2.2.1
**Chrome Version**: 59.0.3071.115
**Initial URL**: https://www.gifthero.com/lists
**Error Message**: You must provide a url to the runner
**Stack Trace**:
```
Error: You must provide a url to the runner
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13890:23)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14315:15)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14340:18)
    at <anonymous>
```

**Comment by patrickhulce** [comment]
Thanks for the report @yaykyle! Let's add this info over to #1834 

We visit 'about:blank' right before we try to visit the page, so that's probably what you're seeing if it doesn't move on to your page. Super useful info actually this helps!
