### ISSUE TITLE
DevTools Error: Unable to load the page: timeout reached

### ISSUE THREAD

**Issue by QuietWind** [GoogleChrome/lighthouse#2692]
**Initial URL**: about:blank
**Chrome Version**: 61.0.3157.3
**Error Message**: Unable to load the page: timeout reached
**Stack Trace**:
```
Error: Unable to load the page: timeout reached
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@e9ee32ca5aa5e126152abafb3e7b1c862c278435/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@e9ee32ca5aa5e126152abafb3e7b1c862c278435/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by patrickhulce** [comment]
@QuietWind what steps did you take to start the audit? Did you not see a message like below?

![image](https://user-images.githubusercontent.com/2301202/28235297-e01f11e2-68bf-11e7-8b94-560ead012f9a.png)

**Comment by wardpeet** [comment]
@QuietWind do you mind sharing a url?

**Comment by QuietWind** [comment]
sorry! I do not remember web Url,  Because this bug is the auto post!
