### ISSUE TITLE
DevTools Error: Unable to load the page: net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by dewaynesmith3711** [GoogleChrome/lighthouse#2707]
**Initial URL**: https://sharewareonsale.com/s/free-black-bird-image-optimizer-pro-100-discount
**Chrome Version**: 61.0.3160.0
**Error Message**: Unable to load the page: net::ERR_EMPTY_RESPONSE
**Stack Trace**:
```
Error: Unable to load the page: net::ERR_EMPTY_RESPONSE
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@226c080a029bd3ff8a6a577503cefe316c84325b/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@226c080a029bd3ff8a6a577503cefe316c84325b/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by wardpeet** [comment]
can you reproduce this in chrome stable or chrome canary?
