### ISSUE TITLE
DevTools Error: The url provided should have a proper protocol and hostname.

### ISSUE THREAD

**Issue by double1960** [GoogleChrome/lighthouse#2747]
**Initial URL**: :
**Chrome Version**: 60.0.3112.78
**Error Message**: The url provided should have a proper protocol and hostname.
**Stack Trace**:
```
Error: The url provided should have a proper protocol and hostname.
    at Function.run (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:849:67)
    at window.runLighthouseForConnection (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:873:288)
    at window.runLighthouseInWorker (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:873:1013)
    at Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:4735:117)
    at <anonymous>
```

**Comment by patrickhulce** [comment]
@double1960 Could you provide steps on how you reached this state?

**Comment by double1960** [comment]
I will have to think about that I havent done any thing intentionaly to mess it up My intention was to search tool not sure if that was your subject matter

**Comment by double1960** [comment]
I think I may need a ride on the short buss to school I havent done much of this but I am willing to learn

**Comment by double1960** [comment]
I need Better Understanding I will go thru the learnning this week.
