### ISSUE TITLE
DevTools Error: Unable to load the page: net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by softsaravanacse** [GoogleChrome/lighthouse#2756]
**Initial URL**: https://localhost:8081/admin/menu
**Chrome Version**: 60.0.3112.78
**Error Message**: Unable to load the page: net::ERR_EMPTY_RESPONSE
**Stack Trace**:
```
Error: Unable to load the page: net::ERR_EMPTY_RESPONSE
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by wardpeet** [comment]
Are you willing to provide the live URL you were testing on?

**Comment by patrickhulce** [comment]
dupe, see #2784
