### ISSUE TITLE
DevTools Error: Unable to load the page: net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by cksachdev** [GoogleChrome/lighthouse#2766]
**Initial URL**: https://localhost:3000/
**Chrome Version**: 62.0.3168.0
**Error Message**: Unable to load the page: net::ERR_EMPTY_RESPONSE
**Stack Trace**:
```
Error: Unable to load the page: net::ERR_EMPTY_RESPONSE
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@da2455bea333a5a4bfe61ba1fcfe9e325dc368e1/audits2_worker/audits2_worker_module.js:666:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@da2455bea333a5a4bfe61ba1fcfe9e325dc368e1/audits2_worker/audits2_worker_module.js:670:224)
    at <anonymous>
```

**Comment by wardpeet** [comment]
Could you share a live url?

Do you have the same issue when running the CLI or the extension?

**Comment by TheAmigo** [comment]
I get the same error "net::ERR_EMPTY_RESPONSE".  Unfortunately, the page on which I see this requires a login (Salesforce's Identity Connect).

**Comment by patrickhulce** [comment]
Thanks for the additional info @TheAmigo. This is another instance of what's best explained in #2784, so we'll close this as a duplicate.
