### ISSUE TITLE
DevTools Error: Unable to load the page: net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by gbracey** [GoogleChrome/lighthouse#2771]
**Initial URL**: https://localhost:44376/
**Chrome Version**: 60.0.3112.78
**Error Message**: Unable to load the page: net::ERR_CONNECTION_RESET
**Stack Trace**:
```
Error: Unable to load the page: net::ERR_CONNECTION_RESET
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:640:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:644:224)
    at <anonymous>
```

**Comment by wardpeet** [comment]
@gbracey do you have a live site we can test on?

Did you try running the extension or the cli on your site? If yes, did it work?

**Comment by patrickhulce** [comment]
Thanks for filing @gbracey! This is a known issue best captured by #2784, so we'll go ahead and close as a duplicate.
