### ISSUE TITLE
DevTools Error: Invalid string length

### ISSUE THREAD

**Issue by ahcarpenter** [GoogleChrome/lighthouse#2799]
**Initial URL**: https://www.hefleycarpenter.com/
**Chrome Version**: 60.0.3112.78
**Error Message**: Invalid string length
**Stack Trace**:
```
RangeError: Invalid string length
    at onChunkRead (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:612:17)
    at <anonymous>
```

**Comment by joegasper** [comment]
Sames:

**Initial URL**: https://agronomy.ifas.ufl.edu/
**Chrome Version**: 60.0.3112.78
**Error Message**: Invalid string length
**Stack Trace**:
```
RangeError: Invalid string length
    at onChunkRead (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:612:17)
    at <anonymous>

**Comment by paulirish** [comment]
Thanks for reporting guys. 

This happens when the trace file exceeds 256MB. This is fixed in the latest lighthouse and Chrome Canary.
