### ISSUE TITLE
DevTools Error: You probably have multiple tabs open to the same origin.

### ISSUE THREAD

**Issue by Phantom-Cluster** [GoogleChrome/lighthouse#2803]
**Initial URL**: https://www.google.co.in/
**Chrome Version**: 60.0.3112.78
**Error Message**: You probably have multiple tabs open to the same origin.
**Stack Trace**:
```
Error: You probably have multiple tabs open to the same origin.
    at versions.forEach.ver (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:588:65)
    at Array.forEach (<anonymous>)
    at registrations.filter.forEach.reg (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:587:419)
    at Array.forEach (<anonymous>)
    at getServiceWorkerRegistrations.then.then.then.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@f901216ec1e383df23283fec9bc8f4e8b67aa0fb/audits2_worker/audits2_worker_module.js:587:396)
    at <anonymous>
```

**Comment by wardpeet** [comment]
Issues says it all so closing.

Please reopen if this is something else.
