### ISSUE TITLE
DevTools Error: The url provided should have a proper protocol and hostname.

### ISSUE THREAD

**Issue by gimntut** [GoogleChrome/lighthouse#2877]
**Initial URL**: :
**Chrome Version**: 60.0.3112.90
**Error Message**: The url provided should have a proper protocol and hostname.
**Stack Trace**:
```
Error: The url provided should have a proper protocol and hostname.
    at Function.run (https://chrome-devtools-frontend.appspot.com/serve_file/@6ee4392c6cef820c64ff50b5fd5eeb8596cd0394/audits2_worker/audits2_worker_module.js:849:67)
    at window.runLighthouseForConnection (https://chrome-devtools-frontend.appspot.com/serve_file/@6ee4392c6cef820c64ff50b5fd5eeb8596cd0394/audits2_worker/audits2_worker_module.js:873:288)
    at window.runLighthouseInWorker (https://chrome-devtools-frontend.appspot.com/serve_file/@6ee4392c6cef820c64ff50b5fd5eeb8596cd0394/audits2_worker/audits2_worker_module.js:873:1013)
    at Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@6ee4392c6cef820c64ff50b5fd5eeb8596cd0394/audits2_worker/audits2_worker_module.js:4735:117)
    at <anonymous>
```

**Comment by ebidel** [comment]
Looks like the URL you tried to test was invalid.
