### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by burmik3333** [GoogleChrome/lighthouse#2968]
**Initial URL**: https://chrome.google.com/webstore/unsupported
**Chrome Version**: 60.0.3112.90
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@6ee4392c6cef820c64ff50b5fd5eeb8596cd0394/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by themorgantown** [comment]
Also hitting this. Occurs after I've started an audit. Exited that tab. Restarted an audit. Some process never closes after starting the initial audit.

**Comment by bryantee** [comment]
**Initial URL**: http://bryanswagerty.com/film-hopper/
**Chrome Version**: 60.0.3112.90
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@6ee4392c6cef820c64ff50b5fd5eeb8596cd0394/audits2_worker/audits2_worker_module.js:515:305)
    at <anonymous>
```

**Comment by patrickhulce** [comment]
dupe of #1091
