### ISSUE TITLE
DevTools Error: You must provide a url to the runner

### ISSUE THREAD

**Issue by SenseiRebeccah368333** [GoogleChrome/lighthouse#3049]
**Initial URL**: 
**Chrome Version**: 60.0.3112.101
**Error Message**: You must provide a url to the runner
**Stack Trace**:
```
Error: You must provide a url to the runner
    at Function.run (https://chrome-devtools-frontend.appspot.com/serve_file/@1f3c0cf4b3083dfbe4da434af1726820cf384ce3/audits2_worker/audits2_worker_module.js:848:659)
    at window.runLighthouseForConnection (https://chrome-devtools-frontend.appspot.com/serve_file/@1f3c0cf4b3083dfbe4da434af1726820cf384ce3/audits2_worker/audits2_worker_module.js:873:288)
    at window.runLighthouseInWorker (https://chrome-devtools-frontend.appspot.com/serve_file/@1f3c0cf4b3083dfbe4da434af1726820cf384ce3/audits2_worker/audits2_worker_module.js:873:1013)
    at Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@1f3c0cf4b3083dfbe4da434af1726820cf384ce3/audits2_worker/audits2_worker_module.js:4735:117)
    at <anonymous>
```

**Comment by SenseiRebeccah368333** [comment]
Merci / Cockneemoon.ca
