### ISSUE TITLE
Extension Error: Cannot read property 'setTitle' of undefined

### ISSUE THREAD

**Issue by nattji** [GoogleChrome/lighthouse#3160]
**Lighthouse Version**: 2.3.0
**Chrome Version**: 60.0.3112.113
**Initial URL**: chrome://extensions/?id=mlkejhoeobiibeeeahncjhhonbholbje
**Error Message**: Cannot read property 'setTitle' of undefined
**Stack Trace**:
```
TypeError: Cannot read property 'setTitle' of undefined
    at updateBadgeUI (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14501:25)
    at window.runLighthouseForConnection (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14532:3)
    at connection.getCurrentTabURL.then.url (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:14559:25)
    at <anonymous>
```

**Comment by patrickhulce** [comment]
Thanks for the report! I'm unable to reproduce with the latest version which should be shipping soon 👍
