### ISSUE TITLE
Error: Emulation.setVisibleSize wasn't found 

### ISSUE THREAD

**Issue by LeMoussel** [GoogleChrome/lighthouse#3345]
Windows 10
Node v8.3.0
Lighthouse Version 2.4.0
Chrome Version: 61.0.3163.91 (Build officiel) (64 bits)

**Error Message:** 'Emulation.setVisibleSize' wasn't found
**Stack Trace:**
```
Fri, 15 Sep 2017 05:16:42 GMT ChromeLauncher Waiting for browser.
Fri, 15 Sep 2017 05:16:42 GMT ChromeLauncher Waiting for browser...
Fri, 15 Sep 2017 05:16:43 GMT ChromeLauncher Waiting for browser...√
Fri, 15 Sep 2017 05:16:45 GMT Lighthouse:warn The URL provided should be on HTTPS
Fri, 15 Sep 2017 05:16:45 GMT Lighthouse:warn Performance stats will be skewed redirecting from HTTP to HTTPS.
Fri, 15 Sep 2017 05:16:53 GMT status Initializing…
Fri, 15 Sep 2017 05:16:53 GMT method <= browser ERR:error Emulation.setVisibleSize
Fri, 15 Sep 2017 05:16:53 GMT status Disconnecting from browser...
Fri, 15 Sep 2017 05:16:53 GMT ChromeLauncher Killing all Chrome Instances
Runtime error encountered: Error: Protocol error (Emulation.setVisibleSize): 'Emulation.setVisibleSize' wasn't found
    at callback.resolve.Promise.resolve.then._ (C:\Users\lemoussel\OneDrive\nodejs\headlessChromeConcurrently\node_modules\lighthouse\lighthouse-core\gather\connections\connection.js:95:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Protocol error (Emulation.setVisibleSize): 'Emulation.setVisibleSize' wasn't found
    at callback.resolve.Promise.resolve.then._ (C:\Users\lemoussel\OneDrive\nodejs\headlessChromeConcurrently\node_modules\lighthouse\lighthouse-core\gather\connections\connection.js:95:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Rem:** When I run [Lighthouse programmatically](https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#using-programmatically), I haven't error.

**Comment by LeMoussel** [comment]
I found out why this mistake was made.
I had 2 versions of Chrome on my PC.  One of the older versions (V48 in `C:\Users\lemoussel\AppData\Local\Google\Chrome SxS`) is launched by default by Lighthouse.  By deleting this old version, everything is OK.
