### ISSUE TITLE
DevTools Error: Unable to load the page: 

### ISSUE THREAD

**Issue by alph4delta** [GoogleChrome/lighthouse#3376]
**Initial URL**: http://www.purestorage.com/content/dam/purestorage/homepage/MQ%20Graphic%207%2017%2017.jpg.imgo.jpg
**Chrome Version**: 61.0.3163.91
**Error Message**: Unable to load the page: 
**Stack Trace**:
```
Error: Unable to load the page: 
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@2f544949507dc5330b714cb017e3f584e791a1bf/audits2_worker/audits2_worker_module.js:666:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@2f544949507dc5330b714cb017e3f584e791a1bf/audits2_worker/audits2_worker_module.js:670:224)
    at <anonymous>
```

**Comment by alph4delta** [comment]
The Image is not run via DevTools in web browser Chrome, but another images
is run.
