### ISSUE TITLE
DevTools Error: Unable to load the page: net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by mdmcginn** [GoogleChrome/lighthouse#3453]
**Initial URL**: https://localhost:3000/textwork.html
**Chrome Version**: 61.0.3163.100
**Error Message**: Unable to load the page: net::ERR_EMPTY_RESPONSE
**Stack Trace**:
```
Error: Unable to load the page: net::ERR_EMPTY_RESPONSE
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@57c9d07b416b5a2ea23d28247300e4af36329bdc/audits2_worker/audits2_worker_module.js:666:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@57c9d07b416b5a2ea23d28247300e4af36329bdc/audits2_worker/audits2_worker_module.js:670:224)
    at <anonymous>
```
The final URL before the error message was http://localhost:3000/textwork.html
This test app doesn't force redirect to https - is that the problem?

**Comment by mdmcginn** [comment]
I'm running Chrome as "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --allow-insecure-localhost

Lighthouse works when I uncheck the 'Progressive Web App" box.
