### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): Tracing is already started

### ISSUE THREAD

**Issue by adeyahya** [GoogleChrome/lighthouse#3465]
**Initial URL**: http://localhost:3000/
**Chrome Version**: 62.0.3198.0
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@3ea904e3488e7af8b03e29fc71d9b9998ffc325b/audits2_worker/audits2_worker_module.js:534:516)
    at <anonymous>
```

**Comment by spark008** [comment]
I just got the same message:

**Initial URL**: https://www.indiegogo.com/home
**Chrome Version**: 63.0.3222.0
**Error Message**: Protocol error (Tracing.start): Tracing is already started
**Stack Trace**:
```
Error: Protocol error (Tracing.start): Tracing is already started
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@7754c77f5af465147885e57c6ba7fc4e9095d842/audits2_worker/audits2_worker_module.js:534:516)
    at <anonymous>
```
