### ISSUE TITLE
Extension Error: Unable to load page: no document request found

### ISSUE THREAD

**Issue by StormCrusader** [GoogleChrome/lighthouse#3496]
**Lighthouse Version**: 2.5.0
**Lighthouse Commit**: 55137f8e387ef281ce79f232e78218a0a1393354
**Chrome Version**: 61.0.3163.100
**Initial URL**: https://simm.co.za/
**Error Message**: Unable to load page: no document request found
**Stack Trace**:
```
Error: Unable to load page: no document request found
    at Function.assertPageLoaded (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13597:21)
    at pass.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13704:20)
    at <anonymous>
```

**Comment by vinamratasingal** [comment]
- Hi StormCrusader- can you give us some more context as to how you ran this report? What other extensions do you have installed? What section of the report failed?
