### ISSUE TITLE
DevTools Error: You probably have multiple tabs open to the same origin.

### ISSUE THREAD

**Issue by nicholas-george** [GoogleChrome/lighthouse#3503]
**Initial URL**: https://nicholas.formistry.com/your-first-pwapp-master/final/
**Chrome Version**: 61.0.3163.100
**Error Message**: You probably have multiple tabs open to the same origin.
**Stack Trace**:
```
Error: You probably have multiple tabs open to the same origin.
    at versions.forEach.ver (https://chrome-devtools-frontend.appspot.com/serve_file/@57c9d07b416b5a2ea23d28247300e4af36329bdc/audits2_worker/audits2_worker_module.js:605:65)
    at Array.forEach (<anonymous>)
    at registrations.filter.forEach.reg (https://chrome-devtools-frontend.appspot.com/serve_file/@57c9d07b416b5a2ea23d28247300e4af36329bdc/audits2_worker/audits2_worker_module.js:604:419)
    at Array.forEach (<anonymous>)
    at getServiceWorkerRegistrations.then.then.then.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@57c9d07b416b5a2ea23d28247300e4af36329bdc/audits2_worker/audits2_worker_module.js:604:396)
    at <anonymous>
```

**Comment by vinamratasingal** [comment]
Hi Nicholas- can you try closing out some tabs out and try running the report again? If that fixes things then you should be good to go! :)

**Comment by nicholas-george** [comment]
Thnx. I read the error message. 

The issue I was trying to point out was about the need for same origin  pages not being there.

Can that itself be fixed?

**Comment by patrickhulce** [comment]
We're not going to be able to support that.
