### ISSUE TITLE
DevTools Error: Parsing problem

### ISSUE THREAD

**Issue by MeltedLux** [GoogleChrome/lighthouse#3511]
**Initial URL**: https://melted.me/
**Chrome Version**: 63.0.3230.0
**Error Message**: Parsing problem
**Stack Trace**:
```
Error: Parsing problem
    at Object.loadingComplete (chrome-devtools://devtools/remote/serve_file/@da95e4026511e4539097b7dc8e09c21cb92a0aee/audits2_worker/audits2_worker_module.js:797:479)
    at WebInspector.TimelineLoader.cancel (chrome-devtools://devtools/remote/serve_file/@da95e4026511e4539097b7dc8e09c21cb92a0aee/audits2_worker/audits2_worker_module.js:3335:37)
    at WebInspector.TimelineLoader._reportErrorAndCancelLoading (chrome-devtools://devtools/remote/serve_file/@da95e4026511e4539097b7dc8e09c21cb92a0aee/audits2_worker/audits2_worker_module.js:3355:42)
    at WebInspector.TimelineLoader._writeBalancedJSON (chrome-devtools://devtools/remote/serve_file/@da95e4026511e4539097b7dc8e09c21cb92a0aee/audits2_worker/audits2_worker_module.js:3353:49)
    at WebInspector.TextUtils.BalancedJSONTokenizer._reportBalanced (chrome-devtools://devtools/remote/serve_file/@da95e4026511e4539097b7dc8e09c21cb92a0aee/audits2_worker/audits2_worker_module.js:2201:13)
    at WebInspector.TextUtils.BalancedJSONTokenizer.write (chrome-devtools://devtools/remote/serve_file/@da95e4026511e4539097b7dc8e09c21cb92a0aee/audits2_worker/audits2_worker_module.js:2199:24)
    at WebInspector.TimelineLoader.write (chrome-devtools://devtools/remote/serve_file/@da95e4026511e4539097b7dc8e09c21cb92a0aee/audits2_worker/audits2_worker_module.js:3347:31)
    at TraceParser.parseChunk (chrome-devtools://devtools/remote/serve_file/@da95e4026511e4539097b7dc8e09c21cb92a0aee/audits2_worker/audits2_worker_module.js:800:30)
    at onChunkRead (chrome-devtools://devtools/remote/serve_file/@da95e4026511e4539097b7dc8e09c21cb92a0aee/audits2_worker/audits2_worker_module.js:635:8)
    at <anonymous>
```

**Comment by vinamratasingal** [comment]
Hi MeltedLux- I am running the report using Lighthouse audit in DevTools and not seeing an issue- can you please comment with more specifics? Otherwise we will close this bug out. 

![screen shot 2017-10-09 at 3 18 08 pm](https://user-images.githubusercontent.com/1828723/31360838-1bcceef6-ad05-11e7-9a03-e0e10144ff6a.png)

**Comment by patrickhulce** [comment]
let's merge this into #3306, if you're able to reproduce with a trace please comment over there! 👏 thanks!
