### ISSUE TITLE
Extension Error: Unable to load page: failed document request (net::ERR_EMPTY

### ISSUE THREAD

**Issue by SergerGood** [GoogleChrome/lighthouse#3527]
**Lighthouse Version**: 2.5.0
**Lighthouse Commit**: 55137f8e387ef281ce79f232e78218a0a1393354
**Chrome Version**: 61.0.3163.100
**Initial URL**: https://localhost:3687/network-structure
**Error Message**: Unable to load page: failed document request (net::ERR_EMPTY_RESPONSE)
**Stack Trace**:
```
Error: Unable to load page: failed document request (net::ERR_EMPTY_RESPONSE)
    at Function.assertPageLoaded (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13597:21)
    at pass.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13704:20)
    at <anonymous>
```

**Comment by paulirish** [comment]
@SergerGood can you reproduce this? I don't think we know enough about why the page was empty.. This page loads for you?
