### ISSUE TITLE
DevTools Error: Unable to load the page: timeout reached

### ISSUE THREAD

**Issue by ezwebcraft** [GoogleChrome/lighthouse#3637]
**Initial URL**: https://10.202.4.251/
**Chrome Version**: 61.0.3163.100
**Error Message**: Unable to load the page: timeout reached
**Stack Trace**:
```
Error: Unable to load the page: timeout reached
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@57c9d07b416b5a2ea23d28247300e4af36329bdc/audits2_worker/audits2_worker_module.js:666:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@57c9d07b416b5a2ea23d28247300e4af36329bdc/audits2_worker/audits2_worker_module.js:670:224)
    at <anonymous>
```

**Comment by ezwebcraft** [comment]
thanks bot
