### ISSUE TITLE
DevTools Error: You probably have multiple tabs open to the same origin.

### ISSUE THREAD

**Issue by select** [GoogleChrome/lighthouse#3646]
**Initial URL**: https://audius.rockdapus.org/
**Chrome Version**: 62.0.3202.62
**Error Message**: You probably have multiple tabs open to the same origin.
**Stack Trace**:
```
Error: You probably have multiple tabs open to the same origin.
    at versions.forEach.ver (chrome-devtools://devtools/remote/serve_file/@9da914b118cb0d10d715ccc4ad20575a0305a304/audits2_worker/audits2_worker_module.js:605:65)
    at Array.forEach (<anonymous>)
    at registrations.filter.forEach.reg (chrome-devtools://devtools/remote/serve_file/@9da914b118cb0d10d715ccc4ad20575a0305a304/audits2_worker/audits2_worker_module.js:604:419)
    at Array.forEach (<anonymous>)
    at getServiceWorkerRegistrations.then.then.then.then._ (chrome-devtools://devtools/remote/serve_file/@9da914b118cb0d10d715ccc4ad20575a0305a304/audits2_worker/audits2_worker_module.js:604:396)
    at <anonymous>
```

**Comment by select** [comment]
Why on earth would I submit this bug if I had multiple tabs open, it already said this in the error message so I made sure this was not the case. 

The option to file a bug report was super useless.

**Comment by brendankenny** [comment]
Hi @select. Will you take a look at the list of reasons in #3024 and see if they apply? Even if you don't have any other tabs open at all in that browser, reason (4) may still be applicable. I'm not able to reproduce any error with that URL, however, so that is evidence against it.

You could also try running the audits in a fresh download of Chrome or in Chrome Canary, which will have a separate profile from your main Chrome, to really make sure something else isn't interfering with the run.

**Comment by select** [comment]
Hey thanks, I was kinda ranting because I felt that I was lead here by the error message telling me to report the issue and then a bot just closed my issue. 

Thanks very much for verifying that the issue must have to do with my setup. I will look into your advice and hopfully overcome the problem. 💖
