### ISSUE TITLE
DevTools Error: Unable to load the page: 

### ISSUE THREAD

**Issue by LParkki** [GoogleChrome/lighthouse#3663]
[AirPortBRCM4360.docx](https://github.com/GoogleChrome/lighthouse/files/1419652/AirPortBRCM4360.docx)
**Initial URL**: https://yt3.ggpht.com/-ImIbMPZQILI/AAAAAAAAAAI/AAAAAAAAAAA/vltTTjH9Eco/s88-c-k-no-mo-rj-c0xffffff/photo.jpg
**Chrome Version**: 61.0.3163.100
**Error Message**: Unable to load the page: 
**Stack Trace**:
```
Error: Unable to load the page: 
    at Function.assertPageLoaded (https://chrome-devtools-frontend.appspot.com/serve_file/@57c9d07b416b5a2ea23d28247300e4af36329bdc/audits2_worker/audits2_worker_module.js:666:332)
    at pass.then._ (https://chrome-devtools-frontend.appspot.com/serve_file/@57c9d07b416b5a2ea23d28247300e4af36329bdc/audits2_worker/audits2_worker_module.js:670:224)
    at <anonymous>
```

**Comment by LParkki** [comment]
"necessarily-wide-alpaca"

**Comment by patrickhulce** [comment]
@LParkki It looks like you were trying to audit a jpeg file, not a real webpage. Could you explain the steps you took to reach this and how we can reproduce?
