### ISSUE TITLE
DevTools Error: Parsing problem

### ISSUE THREAD

**Issue by shrinathnayak07** [GoogleChrome/lighthouse#3767]
**Initial URL**: https://shrinath-nayak.firebaseapp.com/
**Chrome Version**: 62.0.3202.89
**Error Message**: Parsing problem
**Stack Trace**:
```
Error: Parsing problem
    at Object.loadingComplete (chrome-devtools://devtools/remote/serve_file/@4bc124ea2934343d106df5b937e78ce311311658/audits2_worker/audits2_worker_module.js:797:479)
    at WebInspector.TimelineLoader.cancel (chrome-devtools://devtools/remote/serve_file/@4bc124ea2934343d106df5b937e78ce311311658/audits2_worker/audits2_worker_module.js:3335:37)
    at WebInspector.TimelineLoader._reportErrorAndCancelLoading (chrome-devtools://devtools/remote/serve_file/@4bc124ea2934343d106df5b937e78ce311311658/audits2_worker/audits2_worker_module.js:3355:42)
    at WebInspector.TimelineLoader._writeBalancedJSON (chrome-devtools://devtools/remote/serve_file/@4bc124ea2934343d106df5b937e78ce311311658/audits2_worker/audits2_worker_module.js:3351:53)
    at WebInspector.TextUtils.BalancedJSONTokenizer._reportBalanced (chrome-devtools://devtools/remote/serve_file/@4bc124ea2934343d106df5b937e78ce311311658/audits2_worker/audits2_worker_module.js:2201:13)
    at WebInspector.TextUtils.BalancedJSONTokenizer.write (chrome-devtools://devtools/remote/serve_file/@4bc124ea2934343d106df5b937e78ce311311658/audits2_worker/audits2_worker_module.js:2199:24)
    at WebInspector.TimelineLoader.write (chrome-devtools://devtools/remote/serve_file/@4bc124ea2934343d106df5b937e78ce311311658/audits2_worker/audits2_worker_module.js:3347:31)
    at TraceParser.parseChunk (chrome-devtools://devtools/remote/serve_file/@4bc124ea2934343d106df5b937e78ce311311658/audits2_worker/audits2_worker_module.js:800:30)
    at onChunkRead (chrome-devtools://devtools/remote/serve_file/@4bc124ea2934343d106df5b937e78ce311311658/audits2_worker/audits2_worker_module.js:635:8)
    at <anonymous>
```

**Comment by vinamratasingal** [comment]
Thanks so much for submitting this. Looks similar to #3306 so we'll close out this bug in favor of the umbrella bug. 

If you think there's something else going on, feel free to reopen the issue. Thanks for using Lighthouse :)
