### ISSUE TITLE
DevTools Error: Unable to load page: no document request found

### ISSUE THREAD

**Issue by Mazen-Aljaradi** [GoogleChrome/lighthouse#3813]
**Initial URL**: https://wwwshaba-yemenye.000webhostapp.com/
**Chrome Version**: 64.0.3266.0
**Error Message**: Unable to load page: no document request found
**Stack Trace**:
```
Error: Unable to load page: no document request found
    at Function.assertPageLoaded (chrome-devtools://devtools/remote/serve_file/@9f1225c70924c5b3312d0571017f855ddaa60a78/audits2_worker/audits2_worker_module.js:826:73)
    at pass.then._ (chrome-devtools://devtools/remote/serve_file/@9f1225c70924c5b3312d0571017f855ddaa60a78/audits2_worker/audits2_worker_module.js:830:224)
    at <anonymous>
```

**Comment by Mazen-Aljaradi** [comment]
ok thx 👍
