### ISSUE TITLE
DevTools Error: Unable to load the page: timeout reached

### ISSUE THREAD

**Issue by labradorconnect** [GoogleChrome/lighthouse#3859]
**Initial URL**: http://www.eargroupie.com/
**Chrome Version**: 62.0.3202.94
**Error Message**: Unable to load the page: timeout reached
**Stack Trace**:
```
Error: Unable to load the page: timeout reached
    at Function.assertPageLoaded (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:666:332)
    at pass.then._ (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:670:224)
    at <anonymous>
```

**Comment by labradorconnect** [comment]
Thanks. I wasn't given the option to append to the existing ticket in Chrome...sorry for the duplicate. Thanks though!
