### ISSUE TITLE
DevTools Error: Unable to load page: no document request found

### ISSUE THREAD

**Issue by Taha-Di-Nero** [GoogleChrome/lighthouse#3960]
**Initial URL**: https://localhost:44355/
**Chrome Version**: 64.0.3281.0
**Error Message**: Unable to load page: no document request found
**Stack Trace**:
```
Error: Unable to load page: no document request found
    at Function.assertPageLoaded (chrome-devtools://devtools/remote/serve_file/@a9249a3ab02174ce71383e54fedb216ed578ba51/audits2_worker/audits2_worker_module.js:826:73)
    at pass.then._ (chrome-devtools://devtools/remote/serve_file/@a9249a3ab02174ce71383e54fedb216ed578ba51/audits2_worker/audits2_worker_module.js:830:224)
    at <anonymous>
```

**Comment by Taha-Di-Nero** [comment]
It was Chrome DevTools who suggested to open an issue................
