### ISSUE TITLE
Extension Error: Unable to load page: failed document request (net::ERR_PROXY

### ISSUE THREAD

**Issue by tryweird** [GoogleChrome/lighthouse#3971]
**Lighthouse Version**: 2.6.0
**Lighthouse Commit**: 32ed80c048552d4e9203a125174f16300458460a
**Chrome Version**: 62.0.3202.97
**Initial URL**: https://www.ask.com/
![royalarch](https://user-images.githubusercontent.com/34081425/33512502-d3516768-d6ff-11e7-9489-5d2cf1a923db.gif)

**Error Message**: Unable to load page: failed document request (net::ERR_PROXY_CONNECTION_FAILED)
**Stack Trace**:
```
Error: Unable to load page: failed document request (net::ERR_PROXY_CONNECTION_FAILED)
    at Function.assertPageLoaded (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13753:13)
    at pass.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:13873:14)
    at <anonymous>
```

**Comment by tryweird** [comment]
URL=https://www.ask.com

-Tim
