### ISSUE TITLE
DevTools Error: Unable to load the page: timeout reached

### ISSUE THREAD

**Issue by gaganChaudhary** [GoogleChrome/lighthouse#3972]
**Initial URL**: https://www.visitin.in/ooty
**Chrome Version**: 62.0.3202.94
**Error Message**: Unable to load the page: timeout reached
**Stack Trace**:
```
Error: Unable to load the page: timeout reached
    at Function.assertPageLoaded (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:666:332)
    at pass.then._ (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:670:224)
    at <anonymous>
```

**Comment by gaganChaudhary** [comment]
Gettig this error even if my page gets loaded

**Comment by vinamratasingal** [comment]
Hey Gagan- I'm not having this issue after testing your site on DevTools on my machine. Can you describe the setup you're using to see if we can reproduce this?

**Comment by patrickhulce** [comment]
dupe of #2784
