### ISSUE TITLE
DevTools Error: Parsing problem

### ISSUE THREAD

**Issue by deinok** [GoogleChrome/lighthouse#4001]
**Initial URL**: https://mypadel.herokuapp.com/about
**Chrome Version**: 62.0.3202.94
**Error Message**: Parsing problem
**Stack Trace**:
```
Error: Parsing problem
    at Object.loadingComplete (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:797:479)
    at WebInspector.TimelineLoader.cancel (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:3335:37)
    at WebInspector.TimelineLoader._reportErrorAndCancelLoading (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:3355:42)
    at WebInspector.TimelineLoader._writeBalancedJSON (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:3351:53)
    at WebInspector.TextUtils.BalancedJSONTokenizer._reportBalanced (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:2201:13)
    at WebInspector.TextUtils.BalancedJSONTokenizer.write (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:2199:24)
    at WebInspector.TimelineLoader.write (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:3347:31)
    at TraceParser.parseChunk (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:800:30)
    at onChunkRead (chrome-devtools://devtools/remote/serve_file/@4fd852a98d66564c88736c017b0a0b0478e885ad/audits2_worker/audits2_worker_module.js:635:8)
    at <anonymous>
```

**Comment by vinamratasingal** [comment]
Hi! I went ahead and re-ran your website and LH seems to be working fine so perhaps try rerunning your site? :) 

We've also seen this error before and we have an umbrella bug to track this (#3306). In favor of tracking progress there, I will close out your bug :)

**Comment by deinok** [comment]
NP ;)
