### ISSUE TITLE
Circular JSON returned by lighthouse() API

### ISSUE THREAD

**Issue by kodeninja** [GoogleChrome/lighthouse#4063]
Trying a simple `node 8` program to use Lighthouse to generate an HTML report.

**index.js**

```javascript
"use strict"

const lighthouse = require("lighthouse");
const Reporter = require("lighthouse/lighthouse-core/report/v2/report-generator");
const chromeLauncher = require("chrome-launcher");

const fs = require("fs-extra");
// const cj = require("circular-json-es6");

async function write(report) {
    let file = `/tmp/${Date.now()}/lighthouse-report.json`;
    console.log("Writing report to: %s", file);
    // let json = cj.stringify(report);
    // await fs.outputFile(file, json);
    await console.log(report);
}

function launchChrome(headless=true) {
    return chromeLauncher.launch({
      chromeFlags: [
        "--disable-gpu",
        "--no-sandbox",
        headless ? "--headless" : ''
      ],
      userDataDir: "/tmp",
      enableExtensions: true,
      logLevel: "verbose"
    });
}

async function start(url="https://www.google.com") {
    let chrome;

    try {
        chrome = await launchChrome();
        let options = {
            port: chrome.port,
            chromeFlags:[
                "--headless"
            ],
            logLevel: "debug"
        };

        console.log("Starting Lighthouse tests...");
        let result = await lighthouse(url, options);
        await write(result);

        // This blows up!
        let htmlReport = new Reporter().generateReportHtml(result);
        console.log(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        console.log(htmlReport);
        console.log("<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<");
        return htmlReport;
    } catch(e) {
        console.log(e);
    } finally {
        if(chrome) {
            await chrome.kill();
        }
    }
}

let url = process.argv[2];
if(url) { start(url); }
else { start(); }
```

**Exception**

```javascript
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at ReportGeneratorV2.generateReportHtml (~/Development/lighthouse-demo/node_modules/lighthouse/lighthouse-core/report/v2/report-generator.js:120:32)
    at start (~/Development/lighthouse-demo/index.js:49:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Execution Log**:

```bash
$ node index.js

  ChromeLauncher:verbose created /tmp +0ms
  ChromeLauncher:verbose Launching with command:
  ChromeLauncher:verbose "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --disable-translate --disable-background-networking --safebrowsing-disable-auto-update --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --remote-debugging-port=60600 --user-data-dir=/tmp --disable-gpu --no-sandbox --headless about:blank +5ms

  ChromeLauncher:verbose Chrome running with pid 23589 on port 60600. +6ms
  ChromeLauncher Waiting for browser. +1ms
  ChromeLauncher Waiting for browser... +0ms
  ChromeLauncher Waiting for browser..... +513ms
  ChromeLauncher Waiting for browser.....✓ +3ms
Starting Lighthouse tests...
  status Initializing… +658ms
  status Loading page & waiting for onload URL, Viewport, ViewportDimensions, ThemeColor, Manifest, RuntimeExceptions, ChromeConsoleMessages, ImageUsage, Accessibility, EventListeners, AnchorsWithNoRelNoopener, AppCacheManifest, DOMStats, JSLibraries, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, WebSQL, MetaDescription, FontSize, CrawlableLinks, MetaRobots, Hreflang +554ms
  statusEnd Loading page & waiting for onload +11s
  status Retrieving trace +1ms
  status Retrieving devtoolsLog and network records +240ms
  status Retrieving: URL +8ms
  status Retrieving: Viewport +0ms
  status Retrieving: ViewportDimensions +5ms
  status Retrieving: ThemeColor +4ms
  status Retrieving: Manifest +2ms
  status Retrieving: RuntimeExceptions +1ms
  status Retrieving: ChromeConsoleMessages +0ms
  status Retrieving: ImageUsage +2ms
  status Retrieving: Accessibility +16ms
  status Retrieving: EventListeners +241ms
  status Retrieving: AnchorsWithNoRelNoopener +254ms
  status Retrieving: AppCacheManifest +4ms
  status Retrieving: DOMStats +3ms
  status Retrieving: JSLibraries +18ms
  status Retrieving: OptimizedImages +14ms
  status Retrieving: PasswordInputsWithPreventedPaste +74ms
  status Retrieving: ResponseCompression +3ms
  status Retrieving: TagsBlockingFirstPaint +2ms
  status Retrieving: WebSQL +8ms
  status Retrieving: MetaDescription +507ms
  status Retrieving: FontSize +3ms
  status Retrieving: CrawlableLinks +308ms
  status Retrieving: MetaRobots +4ms
  status Retrieving: Hreflang +2ms
  status Loading page & waiting for onload ServiceWorker, Offline, StartUrl +314ms
  statusEnd Loading page & waiting for onload +13ms
  status Retrieving devtoolsLog and network records +2ms
  status Retrieving: ServiceWorker +1ms
  status Retrieving: Offline +0ms
  status Retrieving: StartUrl +2ms
  status Loading page & waiting for onload HTTPRedirect, HTMLWithoutJavaScript +308ms
  statusEnd Loading page & waiting for onload +181ms
  status Retrieving devtoolsLog and network records +0ms
  status Retrieving: HTTPRedirect +3ms
  status Retrieving: HTMLWithoutJavaScript +4ms
  status Disconnecting from browser... +5ms
  status Analyzing and running audits... +40ms
  status Evaluating: Uses HTTPS +0ms
  status Evaluating: Redirects HTTP traffic to HTTPS +4ms
  status Evaluating: Registers a service worker +1ms
  status Evaluating: Responds with a 200 when offline +0ms
  status Evaluating: Has a `<meta name="viewport">` tag with `width` or `initial-scale` +3ms
  status Evaluating: Contains some content when JavaScript is not available +1ms
  status Evaluating: First meaningful paint +0ms
  status Evaluating: Page load is fast enough on 3G +29ms
  status Evaluating: Perceptual Speed Index +18ms
  status Evaluating: Screenshot Thumbnails +1s
  status Evaluating: Estimated Input Latency +201ms
  status Evaluating: No browser errors logged to the console +29ms
  status Evaluating: Keep server response times low (TTFB) +1ms
  status Evaluating: First Interactive (beta) +1ms
  status Evaluating: Consistently Interactive (beta) +0ms
  status Evaluating: User Timing marks and measures +2ms
  status Evaluating: Critical Request Chains +2ms
  status Evaluating: Avoids page redirects +3ms
  status Evaluating: User can be prompted to Install the Web App +1ms
  status Evaluating: Configured for a custom splash screen +2ms
  status Evaluating: Address bar matches brand colors +0ms
  status Evaluating: Manifest's `short_name` won't be truncated when displayed on homescreen +1ms
  status Evaluating: Content is sized correctly for the viewport +0ms
  status Evaluating: Displays images with correct aspect ratio +1ms
  status Evaluating: Avoids deprecated APIs +1ms
  status Evaluating: Main thread work breakdown +1ms
  status Evaluating: JavaScript boot-up time +234ms
  status Evaluating: Site works cross-browser +15ms
  status Evaluating: Page transitions don't feel like they block on the network +1ms
  status Evaluating: Each page has a URL +0ms
  status Evaluating: `[accesskey]` values are unique. +0ms
  status Evaluating: `[aria-*]` attributes match their roles. +0ms
  status Evaluating: `[role]`s have all required `[aria-*]` attributes. +0ms
  status Evaluating: Elements with `[role]` that require specific children `[role]`s, are present. +1ms
  status Evaluating: `[role]`s are contained by their required parent element. +0ms
  status Evaluating: `[role]` values are valid. +0ms
  status Evaluating: `[aria-*]` attributes have valid values. +0ms
  status Evaluating: `[aria-*]` attributes are valid and not misspelled. +0ms
  status Evaluating: `<audio>` elements contain a `<track>` element with `[kind="captions"]`. +0ms
  status Evaluating: Buttons have an accessible name. +1ms
  status Evaluating: The page contains a heading, skip link, or landmark region. +0ms
  status Evaluating: Background and foreground colors have a sufficient contrast ratio. +0ms
  status Evaluating: `<dl>`'s contain only properly-ordered `<dt>` and `<dd>` groups, `<script>` or `<template>` elements. +0ms
  status Evaluating: Definition list items are wrapped in `<dl>` elements. +0ms
  status Evaluating: Document has a `<title>` element. +0ms
  status Evaluating: `[id]` attributes on the page are unique. +1ms
  status Evaluating: `<frame>` or `<iframe>` elements have a title. +0ms
  status Evaluating: `<html>` element has a `[lang]` attribute. +0ms
  status Evaluating: `<html>` element has a valid value for its `[lang]` attribute. +0ms
  status Evaluating: Image elements have `[alt]` attributes. +0ms
  status Evaluating: `<input type="image">` elements have `[alt]` text. +1ms
  status Evaluating: Form elements have associated labels. +0ms
  status Evaluating: Presentational `<table>` elements avoid using `<th>`, `<caption>` or the `[summary]` attribute. +0ms
  status Evaluating: Links have a discernible name. +0ms
  status Evaluating: Lists contain only `<li>` elements and script supporting elements (`<script>` and `<template>`). +0ms
  status Evaluating: List items (`<li>`) are contained within `<ul>` or `<ol>` parent elements. +0ms
  status Evaluating: The document does not use `<meta http-equiv="refresh">`. +0ms
  status Evaluating: `[user-scalable="no"]` is not used in the `<meta name="viewport">` element and the `[maximum-scale]` attribute is not less than 5. +0ms
  status Evaluating: `<object>` elements have `[alt]` text. +0ms
  status Evaluating: No element has a `[tabindex]` value greater than 0. +0ms
  status Evaluating: Cells in a `<table>` element that use the `[headers]` attribute only refer to other cells of that same table. +1ms
  status Evaluating: `<th>` elements and elements with `[role="columnheader"/"rowheader"]` have data cells they describe. +0ms
  status Evaluating: `[lang]` attributes have a valid value. +0ms
  status Evaluating: `<video>` elements contain a `<track>` element with `[kind="captions"]`. +0ms
  status Evaluating: `<video>` elements contain a `<track>` element with `[kind="description"]`. +0ms
  status Evaluating: Custom controls have associated labels +1ms
  status Evaluating: Custom controls have ARIA roles +0ms
  status Evaluating: User focus is not accidentally trapped in a region +0ms
  status Evaluating: Interactive controls are keyboard focusable +0ms
  status Evaluating: Headings don't skip levels +0ms
  status Evaluating: The page has a logical tab order +0ms
  status Evaluating: The user's focus is directed to new content added to the page +0ms
  status Evaluating: Offscreen content is hidden from assistive technology +0ms
  status Evaluating: HTML5 landmark elements are used to improve navigation +0ms
  status Evaluating: Visual order on the page follows DOM order +1ms
  status Evaluating: Uses efficient cache policy on static assets +0ms
  status Evaluating: Avoids enormous network payloads +2ms
  status Evaluating: Offscreen images +2ms
  status Evaluating: Serve images in next-gen formats +3ms
  status Evaluating: Optimize images +1ms
  status Evaluating: Enable text compression +0ms
  status Evaluating: Properly size images +0ms
  status Evaluating: Avoids Application Cache +1ms
  status Evaluating: Avoids an excessive DOM size +1ms
  status Evaluating: Opens external anchors using `rel="noopener"` +2ms
  status Evaluating: Avoids requesting the geolocation permission on page load +3ms
  status Evaluating: Reduce render-blocking stylesheets +1ms
  status Evaluating: Avoids `document.write()` +1ms
  status Evaluating: Avoids Mutation Events in its own scripts +0ms
  status Evaluating: Avoids front-end JavaScript libraries with known security vulnerabilities +136ms
  status Evaluating: Avoids WebSQL DB +0ms
  status Evaluating: Avoids requesting the notification permission on page load +1ms
  status Evaluating: Allows users to paste into password fields +0ms
  status Evaluating: Reduce render-blocking scripts +0ms
  status Evaluating: Uses HTTP/2 for its own resources +0ms
  status Evaluating: Uses passive listeners to improve scrolling performance +1ms
  status Evaluating: Document has a meta description +1ms
  status Evaluating: Page has successful HTTP status code. +0ms
  status Evaluating: Document uses legible font sizes. +0ms
  status Evaluating: Links have descriptive text. +3ms
  status Evaluating: Page isn’t blocked from indexing +18ms
  status Evaluating: Document has a valid `hreflang` +1ms
  status Generating results... +1ms
Writing report to: /tmp/1513321717012/lighthouse-report.json
{ userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/63.0.3239.84 Safari/537.36',
  lighthouseVersion: '2.7.0',
  generatedTime: '2017-12-15T07:08:37.011Z',
  initialUrl: 'https://www.google.com',
  url: 'https://www.google.com/',
  runWarnings: [],
  audits: 
 
...
```

**Comment by paulirish** [comment]
Delete result.artifacts

**Comment by kodeninja** [comment]
Thanks, @paulirish.

Sorry, I accidentally submitted the issue before I could put the whole context.

Let me try that.

**Comment by kodeninja** [comment]
@paulirish,  that worked! Thanks again!

Should this be treated as a bug?

**Comment by kodeninja** [comment]
Working snippet:

```javascript
...
        console.log("Starting Lighthouse tests...");
        let result = await lighthouse(url, options);

        // Remove artifacts (circular)!
        delete result.artifacts;

        let htmlReport = new Reporter().generateReportHtml(result);
...
```

**Comment by patrickhulce** [comment]
This is WAI @kodeninja artifacts can be enormous and should be pruned before sticking into the report HTML. This actually serves as a helpful enforcement of this best practice :)

If you have a need to serialize the artifacts result, you can take a look at our [asset saver class](https://github.com/GoogleChrome/lighthouse/blob/5e23dbba1a7129c17d71927b9b039dbbaeedaba4/lighthouse-core/lib/asset-saver.js) to see how it's done.
