### ISSUE TITLE
DevTools Error: Parsing problem

### ISSUE THREAD

**Issue by mirukutako** [GoogleChrome/lighthouse#4193]
**Initial URL**: https://mirukutako.github.io/bobr/index.html
**Chrome Version**: 63.0.3239.132
**Error Message**: Parsing problem
**Stack Trace**:
```
Error: Parsing problem
    at Object.loadingComplete (chrome-devtools://devtools/remote/serve_file/@2e6edcfee630baa3775f37cb11796b1603a64360/audits2_worker/audits2_worker_module.js:957:479)
    at WebInspector.TimelineLoader.cancel (chrome-devtools://devtools/remote/serve_file/@2e6edcfee630baa3775f37cb11796b1603a64360/audits2_worker/audits2_worker_module.js:3497:37)
    at WebInspector.TimelineLoader._reportErrorAndCancelLoading (chrome-devtools://devtools/remote/serve_file/@2e6edcfee630baa3775f37cb11796b1603a64360/audits2_worker/audits2_worker_module.js:3517:42)
    at WebInspector.TimelineLoader._writeBalancedJSON (chrome-devtools://devtools/remote/serve_file/@2e6edcfee630baa3775f37cb11796b1603a64360/audits2_worker/audits2_worker_module.js:3515:49)
    at WebInspector.TextUtils.BalancedJSONTokenizer._reportBalanced (chrome-devtools://devtools/remote/serve_file/@2e6edcfee630baa3775f37cb11796b1603a64360/audits2_worker/audits2_worker_module.js:2363:13)
    at WebInspector.TextUtils.BalancedJSONTokenizer.write (chrome-devtools://devtools/remote/serve_file/@2e6edcfee630baa3775f37cb11796b1603a64360/audits2_worker/audits2_worker_module.js:2361:24)
    at WebInspector.TimelineLoader.write (chrome-devtools://devtools/remote/serve_file/@2e6edcfee630baa3775f37cb11796b1603a64360/audits2_worker/audits2_worker_module.js:3509:31)
    at TraceParser.parseChunk (chrome-devtools://devtools/remote/serve_file/@2e6edcfee630baa3775f37cb11796b1603a64360/audits2_worker/audits2_worker_module.js:960:30)
    at onChunkRead (chrome-devtools://devtools/remote/serve_file/@2e6edcfee630baa3775f37cb11796b1603a64360/audits2_worker/audits2_worker_module.js:794:8)
    at <anonymous>
```

**Comment by vinamratasingal** [comment]
Hi! We've seen this issue before, so folding this into #3306, which is the umbrella bug. Feel free to comment directly on that issue!
