### ISSUE TITLE
DevTools Error: Parsing problem

### ISSUE THREAD

**Issue by jigs1996** [GoogleChrome/lighthouse#4274]
**Initial URL**: https://aksharjewelers.herokuapp.com/
**Chrome Version**: 65.0.3323.0
**Error Message**: Parsing problem
**Stack Trace**:
```
Error: Parsing problem
    at Object.loadingComplete (chrome-devtools://devtools/remote/serve_file/@470d3a6be2f380affa8de3dc0dd1508f3eeba9f7/audits2_worker/audits2_worker_module.js:1153:389)
    at WebInspector.TimelineLoader.cancel (chrome-devtools://devtools/remote/serve_file/@470d3a6be2f380affa8de3dc0dd1508f3eeba9f7/audits2_worker/audits2_worker_module.js:3767:37)
    at WebInspector.TimelineLoader._reportErrorAndCancelLoading (chrome-devtools://devtools/remote/serve_file/@470d3a6be2f380affa8de3dc0dd1508f3eeba9f7/audits2_worker/audits2_worker_module.js:3787:42)
    at WebInspector.TimelineLoader._writeBalancedJSON (chrome-devtools://devtools/remote/serve_file/@470d3a6be2f380affa8de3dc0dd1508f3eeba9f7/audits2_worker/audits2_worker_module.js:3785:49)
    at WebInspector.TextUtils.BalancedJSONTokenizer._reportBalanced (chrome-devtools://devtools/remote/serve_file/@470d3a6be2f380affa8de3dc0dd1508f3eeba9f7/audits2_worker/audits2_worker_module.js:2644:13)
    at WebInspector.TextUtils.BalancedJSONTokenizer.write (chrome-devtools://devtools/remote/serve_file/@470d3a6be2f380affa8de3dc0dd1508f3eeba9f7/audits2_worker/audits2_worker_module.js:2642:24)
    at WebInspector.TimelineLoader.write (chrome-devtools://devtools/remote/serve_file/@470d3a6be2f380affa8de3dc0dd1508f3eeba9f7/audits2_worker/audits2_worker_module.js:3779:31)
    at TraceParser.parseChunk (chrome-devtools://devtools/remote/serve_file/@470d3a6be2f380affa8de3dc0dd1508f3eeba9f7/audits2_worker/audits2_worker_module.js:1156:30)
    at onChunkRead (chrome-devtools://devtools/remote/serve_file/@470d3a6be2f380affa8de3dc0dd1508f3eeba9f7/audits2_worker/audits2_worker_module.js:851:8)
```

**Comment by vinamratasingal** [comment]
Hi! We've seen this issue before and are using #3306 to track issues similar to this. We're going to close out this issue, but feel free to voice your concerns on the other issue :)
