### ISSUE TITLE
DevTools Error: Cannot read property 'innerWidth' of null

### ISSUE THREAD

**Issue by noriega21** [GoogleChrome/lighthouse#4330]
**Initial URL**: http://www.t-online.de/nachrichten/ausland/krisen/id_83097508/bundesregierung-wegen-tuerkischer-offensive-gegen-kurden-in-der-kritik.html
**Chrome Version**: 62.0.3202.94
**Error Message**: Cannot read property 'innerWidth' of null
**Stack Trace**:
```
TypeError: Cannot read property 'innerWidth' of null
    at Emulation.AdvancedApp._onSetInspectedPageBounds (chrome-devtools://devtools/bundled/inspector.js:7758:78)
    at Emulation.InspectedPagePlaceholder.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:477:23)
    at Emulation.InspectedPagePlaceholder.update (chrome-devtools://devtools/bundled/inspector.js:7855:237)
    at Audits2.Audits2Panel._stopAndReattach (chrome-devtools://devtools/bundled/audits2/audits2_module.js:167:372)
    at <anonymous>
```

**Comment by brendankenny** [comment]
from #4939 by @FlippingKnight

**Initial URL**: https://tobiasdokken.com/
**Chrome Version**: 65.0.3325.181
**Error Message**: Cannot read property 'innerWidth' of null
**Stack Trace**:
```
TypeError: Cannot read property 'innerWidth' of null
    at Emulation.AdvancedApp._onSetInspectedPageBounds (chrome-devtools://devtools/bundled/inspector.js:8057:78)
    at Emulation.InspectedPagePlaceholder.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:482:23)
    at Emulation.InspectedPagePlaceholder.update (chrome-devtools://devtools/bundled/inspector.js:8154:237)
    at Audits2.Audits2Panel._stopAndReattach (chrome-devtools://devtools/bundled/audits2/audits2_module.js:177:372)
```

**Comment by paulirish** [comment]
FWIW, here's the source:

![image](https://user-images.githubusercontent.com/39191/40504436-23cf4506-5f46-11e8-9ffd-b0d636fab2b9.png)

**Comment by wardpeet** [comment]
I've tested these urls on chrome 69.0.3497.100 and did not get any error.
http://www.t-online.de/nachrichten/ausland/krisen/id_83097508/bundesregierung-wegen-tuerkischer-offensive-gegen-kurden-in-der-kritik.html
https://tobiasdokken.com/

@paulirish perhaps did got fixed in chromium source?

**Comment by wardpeet** [comment]
I'm marking this as pending-closed. Looks like it's not happening anymore

**Comment by connorjclark** [comment]
last saw this may / chrome 73 so probably still an issue.

**Comment by paulirish** [comment]
in #8122 this was repro'd in m73 which is pretty recent.. so likely still open.

**Comment by craftdelivery** [comment]
I'm getting this error

**Comment by connorjclark** [comment]
Doesn't happen for Canary w/ any of the reported urls. And we haven't seen this error in awhile. So let's close.
