### ISSUE TITLE
DevTools Error: Unable to load page: failed document request ()

### ISSUE THREAD

**Issue by Haris21071982** [GoogleChrome/lighthouse#4506]
**Initial URL**: http://www.swing-zone.com/m/photos/get_image/file/%D0%B4%D0%BE%D0%BC%D0%B0-2014-02-03.jpg
**Chrome Version**: 64.0.3282.119
**Error Message**: Unable to load page: failed document request ()
**Stack Trace**:
```
Error: Unable to load page: failed document request ()
    at Function.assertPageLoaded (chrome-devtools://devtools/remote/serve_file/@5e944b2d79bce5f96dc35a05a76b03d65a6e9a0a/audits2_worker/audits2_worker_module.js:826:73)
    at pass.then._ (chrome-devtools://devtools/remote/serve_file/@5e944b2d79bce5f96dc35a05a76b03d65a6e9a0a/audits2_worker/audits2_worker_module.js:830:224)
    at <anonymous>
```

**Comment by Haris21071982** [comment]
хотелось бы открыть

**Comment by patrickhulce** [comment]
дублировать #2784
