### ISSUE TITLE
DevTools Error: Unable to load page: failed document request ()

### ISSUE THREAD

**Issue by Rlynch621** [GoogleChrome/lighthouse#4672]
**Initial URL**: https://game.joincyberdiscovery.com/challenges-hq/0411/cat-gif-06.gif
**Chrome Version**: 64.0.3282.186
**Error Message**: Unable to load page: failed document request ()
**Stack Trace**:
```
Error: Unable to load page: failed document request ()
    at Function.assertPageLoaded (chrome-devtools://devtools/remote/serve_file/@9611116ee79c63602f452e4fae2242a61cf0672d/audits2_worker/audits2_worker_module.js:826:73)
    at pass.then._ (chrome-devtools://devtools/remote/serve_file/@9611116ee79c63602f452e4fae2242a61cf0672d/audits2_worker/audits2_worker_module.js:830:224)
    at <anonymous>
```

**Comment by Rlynch621** [comment]
Hi, Google-bot
Look if this is a known issue then why haven’t you solved it, I need to open this webpage so could you please solve the issue as soon as possible.
Thanks, Caz.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
