### ISSUE TITLE
DevTools Error: Unable to load page: no document request found

### ISSUE THREAD

**Issue by Empower1HMS** [GoogleChrome/lighthouse#4688]
**Initial URL**: https://business.google.com/site/l/09730982895470584567?hl=en
**Chrome Version**: 64.0.3282.186
**Error Message**: Unable to load page: no document request found
**Stack Trace**:
```
Error: Unable to load page: no document request found
    at Function.assertPageLoaded (chrome-devtools://devtools/remote/serve_file/@9611116ee79c63602f452e4fae2242a61cf0672d/audits2_worker/audits2_worker_module.js:826:73)
    at pass.then._ (chrome-devtools://devtools/remote/serve_file/@9611116ee79c63602f452e4fae2242a61cf0672d/audits2_worker/audits2_worker_module.js:830:224)
    at <anonymous>
```

**Comment by Empower1HMS** [comment]
I'm So New To Coding I'm Like A Baby. I Need Help...? A Contributer? someone That Is Really Bored....?lol J/K I Learn Really Fast
