### ISSUE TITLE
PFAFF Embroidery Machine PDF Manual DevTools Error: Unable to load page: failed document request (net::ERR_ABORT

### ISSUE THREAD

**Issue by tornadoturano2018** [GoogleChrome/lighthouse#4824]
**Initial URL**: http://www.pfaff.com/SiteMedia/PFAFF/Products/Machines/creative-line/Comparison-charts/comparison_chart_creative_line-2015-EN.pdf
**Chrome Version**: 64.0.3282.186
**Error Message**: Unable to load page: failed document request (net::ERR_ABORTED)
**Stack Trace**:
```
Error: Unable to load page: failed document request (net::ERR_ABORTED)
    at Function.assertPageLoaded (chrome-devtools://devtools/remote/serve_file/@9611116ee79c63602f452e4fae2242a61cf0672d/audits2_worker/audits2_worker_module.js:826:73)
    at pass.then._ (chrome-devtools://devtools/remote/serve_file/@9611116ee79c63602f452e4fae2242a61cf0672d/audits2_worker/audits2_worker_module.js:830:224)
    at <anonymous>
```

**Comment by tornadoturano2018** [comment]
Hola - It's Me Again, #HurricaneAri  #ayudandomimadre #LaChingonaAriana #GuamBiotchAqui
