### ISSUE TITLE
DevTools Error: Cannot read property 'innerWidth' of null

### ISSUE THREAD

**Issue by FlippingKnight** [GoogleChrome/lighthouse#4939]
**Initial URL**: https://tobiasdokken.com/
**Chrome Version**: 65.0.3325.181
**Error Message**: Cannot read property 'innerWidth' of null
**Stack Trace**:
```
TypeError: Cannot read property 'innerWidth' of null
    at Emulation.AdvancedApp._onSetInspectedPageBounds (chrome-devtools://devtools/bundled/inspector.js:8057:78)
    at Emulation.InspectedPagePlaceholder.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:482:23)
    at Emulation.InspectedPagePlaceholder.update (chrome-devtools://devtools/bundled/inspector.js:8154:237)
    at Audits2.Audits2Panel._stopAndReattach (chrome-devtools://devtools/bundled/audits2/audits2_module.js:177:372)
```

**Comment by brendankenny** [comment]
merging with #4330
