### ISSUE TITLE
Unhandled 'error' event (in Docker container)

### ISSUE THREAD

**Issue by marians** [GoogleChrome/lighthouse#5001]
I'm running lighthouse headless within a Docker container. I can create reports for some URLs, but lighthouse reproducibly crashes with some URLs with the error

```nohighlight
...
  Driver:warn Timed out waiting for page load. Moving on... +39s
  statusEnd Loading page & waiting for onload +1ms
  status Retrieving trace +3ms
  listen once for event =>:verbose Tracing.tracingComplete  +1ms
  method => browser:verbose Tracing.end {} +0ms
  status Disconnecting from browser... +1ms
  ChromeLauncher Killing Chrome instance 20 +2ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:46379
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1105:14)
```

Any idea whether I can do something on my end to fix this?

This is my Dockerfile:

```dockerfile
FROM debian:stretch
RUN apt-get update && apt-get install -y wget curl gnupg fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcairo2 libcups2 libdbus-1-3 libexpat1 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release xdg-utils
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g lighthouse
ENTRYPOINT ["lighthouse"]
```

Build: `docker build -t lighthouse .`

I run the container like this:

```nohighlight
docker run --rm -ti -v $PWD:/out lighthouse:latest \
  "https://gruene-roesrath.de/startseite/" \
  --no-enable-error-reporting \
  --output=json --output-path=/out/lighthouse.json \
  --chrome-flags="--headless --no-sandbox" \
  --verbose
```

**Comment by patrickhulce** [comment]
Thanks for filing @marians! To clarify, are you seeing this particular error *regularly on particular URLs only* or *frequently regardless of URL*?

The error just looks like Chrome crashed when it tried to stop tracing. If you have very limited resources available then it's likely that Chrome is unable to handle tracing for so long (the site also looked like it timed out from your output). You can reduce the `--max-wait-for-load` parameter to see if this helps
