### ISSUE TITLE
DevTools Error: Cannot read property 'objectId' of undefined

### ISSUE THREAD

**Issue by cmonzonc** [GoogleChrome/lighthouse#5198]
**Initial URL**: https://dev.stadio.io/dashboard/practice/
**Chrome Version**: 68.0.3428.0
**Error Message**: Cannot read property 'objectId' of undefined
**Stack Trace**:
```
TypeError: Cannot read property 'objectId' of undefined
    at SDK.RuntimeModel.createRemoteObject (chrome-devtools://devtools/bundled/shell.js:4987:165)
    at SDK.ExecutionContext._evaluateGlobal (chrome-devtools://devtools/bundled/shell.js:5057:33)
```

**Comment by paulirish** [comment]
thanks for reporting.
