### ISSUE TITLE
DevTools Error: Unable to load page: no document request found

### ISSUE THREAD

**Issue by kirikintha** [GoogleChrome/lighthouse#5247]
**Initial URL**: https://sandbox-esign-petitions.org/home
**Chrome Version**: 63.0.3239.132
**Error Message**: Unable to load page: no document request found
**Stack Trace**:
```
Error: Unable to load page: no document request found
    at Function.assertPageLoaded (chrome-devtools://devtools/remote/serve_file/@2e6edcfee630baa3775f37cb11796b1603a64360/audits2_worker/audits2_worker_module.js:826:73)
    at pass.then._ (chrome-devtools://devtools/remote/serve_file/@2e6edcfee630baa3775f37cb11796b1603a64360/audits2_worker/audits2_worker_module.js:830:224)
    at <anonymous>
```

Hello, I was running tests on my qa server and noticed this. I was running the performance audit. Thank you!

**Comment by kirikintha** [comment]
Hey there - I did figure out that this was the gateway in front of the application that was triggering this error. We have some threat detection settings that are stopping lighthouse profiling so, not necessarily necessarily-wide-alpaca, but perhaps mildly-robust-panda?

So, my issue is more of a - hey in case you are using an app gateway... be aware things may go wonk-a-doodle. Thanks!
