### ISSUE TITLE
DevTools Error: Cannot read property 'innerWidth' of null

### ISSUE THREAD

**Issue by mehrnaznazari** [GoogleChrome/lighthouse#5313]
**Initial URL**: http://localhost/medrick-kids-website/src/
**Chrome Version**: 66.0.3359.181
**Error Message**: Cannot read property 'innerWidth' of null
**Stack Trace**:
```
TypeError: Cannot read property 'innerWidth' of null
    at Emulation.AdvancedApp._onSetInspectedPageBounds (chrome-devtools://devtools/bundled/devtools_app.js:90:80)
    at Emulation.InspectedPagePlaceholder.dispatchEventToListeners (chrome-devtools://devtools/bundled/shell.js:486:23)
    at Emulation.InspectedPagePlaceholder.update (chrome-devtools://devtools/bundled/devtools_app.js:187:241)
    at Audits2.Audits2Dialog._stopAndReattach (chrome-devtools://devtools/bundled/audits2/audits2_module.js:219:374)
```

**Comment by patrickhulce** [comment]
duplicate #4330
