### ISSUE TITLE
Document dependency on node 8 LTS

### ISSUE THREAD

**Issue by machal** [GoogleChrome/lighthouse#5355]
#### Provide the steps to reproduce
```
$ npm i lighthouse@3.0.0-beta.0 -g
$ lighthouse --version
```

#### What is the current behavior?

```
/Users/machal/.nvm/versions/node/v8.1.2/lib/node_modules/lighthouse/lighthouse-core/scoring.js:58
        const member = {...configMember};
                        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/machal/.nvm/versions/node/v8.1.2/lib/node_modules/lighthouse/lighthouse-core/runner.js:11:23)
```

#### What is the expected behavior?

Show version.

#### Environment Information
* Affected Channels:  CLI
* Lighthouse version: 3.0.0-beta.0
* Node.js version: v8.1.2
* Operating System: MacOS High Sierra 10.13.4

**Comment by patrickhulce** [comment]
Thanks for reporting @machal! The minimum node version for v3 is now Node 8 LTS (8.9+, though you should be OK with 8.3+ it [seems](https://node.green/#ES2018-features-object-rest-spread-properties-object-rest-properties))
