### ISSUE TITLE
Node version error message not being printed when running with Node 4 without --harmony

### ISSUE THREAD

**Issue by andreban** [GoogleChrome/lighthouse#540]
When running with node 4.2.6

`node lighthouse-cli/index.js https://airhorner.com `

prints

```
/Users/andreban/IdeaProjects/lighthouse/lighthouse-core/lib/log.js:34
  const args = [...logargs].slice(1);
                ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/andreban/IdeaProjects/lighthouse/lighthouse-cli/printer.js:23:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

It seems the log library is using the spread operator, therefore displaying an error instead of the desired warning message. Should a simple console.log be used to display this error?

Also, running with --harmony still displays the message:
`node --harmony lighthouse-cli/index.js https://airhorner.com` works, but still prints: 
`Compatibility error Lighthouse requires node 5+ or 4 with --harmony`

Could `process.execArgv` be used to detect the usage of `--harmony`?

**Comment by paulirish** [comment]
Probably makes most sense to do a feature detect for the spread operator
and issue the warning based off that.

**Comment by wardpeet** [comment]
you can assign me if you want

**Comment by paulirish** [comment]
@andreban is gonna take this, actually. :)

**Comment by wardpeet** [comment]
perfect 👍
