### ISSUE TITLE
Extension Error: No tabId set for sendCommand

### ISSUE THREAD

**Issue by Sbosh11** [GoogleChrome/lighthouse#5595]
**Lighthouse Version**: 3.0.0
**Lighthouse Commit**: d6aa4416d7b60beb47207c476a674b0149e58675
**Chrome Version**: 69.0.3477.1
**Initial URL**: http://localhost:8000/
**Error Message**: No tabId set for sendCommand
**Stack Trace**:
```
Error: No tabId set for sendCommand
    at Promise (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17254:15)
    at new Promise (<anonymous>)
    at ExtensionConnection._sendCommand [as sendCommand] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17250:8)
    at Driver._sendCommand [as sendCommand] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:18585:25)
    at Object.clearAllNetworkEmulation (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:21414:15)
    at Driver.setThrottling (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:18384:18)
    at Function.afterPass (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:18888:14)
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:19014:35)
```

**Comment by patrickhulce** [comment]
Super strange that this error would appear so late in the process here 🤔 

@Sbosh11 do you have any reproduction steps, or was anything unique about your run?

**Comment by wardpeet** [comment]
this is the same as #5798 so closing, feel free to join the discussion in that thread
