### ISSUE TITLE
DevTools Error: Cannot read property 'innerWidth' of null

### ISSUE THREAD

**Issue by AlexanderMykulych** [GoogleChrome/lighthouse#5631]
**Initial URL**: http://localhost:50622/#
**Chrome Version**: 69.0.3484.0
**Error Message**: Cannot read property 'innerWidth' of null
**Stack Trace**:
```
TypeError: Cannot read property 'innerWidth' of null
    at Emulation.AdvancedApp._onSetInspectedPageBounds (chrome-devtools://devtools/bundled/devtools_app.js:92:80)
    at Emulation.InspectedPagePlaceholder.dispatchEventToListeners (chrome-devtools://devtools/bundled/shell.js:490:23)
    at Emulation.InspectedPagePlaceholder.update (chrome-devtools://devtools/bundled/devtools_app.js:189:241)
    at Audits2.Audits2Panel._resetEmulationAndProtocolConnection (chrome-devtools://devtools/bundled/audits2/audits2_module.js:188:381)
```

**Comment by patrickhulce** [comment]
duplicate #4330
