### ISSUE TITLE
error with `npm explore -g lighthouse -- npm run chrome`

### ISSUE THREAD

**Issue by paulirish** [GoogleChrome/lighthouse#565]
Reported by john pearson over email.

> npm explore -g lighthouse -- npm run chrome

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/sfjpp/.nvm/versions/node/v5.7.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'chrome' ]
2 info using npm@2.11.3
3 info using node@v5.7.1
4 verbose run-script [ 'prechrome', 'chrome', 'postchrome' ]
5 info prechrome lighthouse@1.1.1
6 info chrome lighthouse@1.1.1
7 verbose unsafe-perm in lifecycle true
8 info lighthouse@1.1.1 Failed to exec chrome script
9 verbose stack Error: lighthouse@1.1.1 chrome: `lighthouse-core/scripts/launch-chrome.sh`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at emitTwo (events.js:100:13)
9 verbose stack     at EventEmitter.emit (events.js:185:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:100:13)
9 verbose stack     at ChildProcess.emit (events.js:185:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid lighthouse@1.1.1
11 verbose cwd /Users/sfjpp/.nvm/versions/node/v5.7.1/lib/node_modules/lighthouse
12 error Darwin 15.5.0
13 error argv "/Users/sfjpp/.nvm/versions/node/v5.7.1/bin/node" "/usr/local/bin/npm" "run" "chrome"
```

**Comment by wardpeet** [comment]
Can not reproduce on El Capitan. Perhaps it's a specific issue on Yosemite? It looks like he can't find Chrome Canary but he doesn't output the string that should come with it.

**Comment by paulirish** [comment]
Closing. will reopen if we can find a way to reproduce this.
