### ISSUE TITLE
Extension Error: No tabId set for sendCommand

### ISSUE THREAD

**Issue by B3lf4g0r** [GoogleChrome/lighthouse#5680]
**Lighthouse Version**: 3.0.3
**Lighthouse Commit**: d1cae24fda4182406e02d3f4df6309d48878fc50
**Chrome Version**: 69.0.3494.0
**Initial URL**: https://www.stiricurate.ro/
**Error Message**: No tabId set for sendCommand
**Stack Trace**:
```
Error: No tabId set for sendCommand
    at Promise (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17427:15)
    at new Promise (<anonymous>)
    at ExtensionConnection._sendCommand [as sendCommand] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17423:8)
    at Driver._sendCommand [as sendCommand] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:18758:25)
    at Object.disableCPUThrottling (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:21716:15)
    at Driver.setThrottling (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:18562:11)
    at Function.afterPass (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:19061:14)
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:19187:35)
```

**Comment by B3lf4g0r** [comment]
duplicate of #5595
