### ISSUE TITLE
Extension Error: No tabId set for sendCommand

### ISSUE THREAD

**Issue by victorhugooo98** [GoogleChrome/lighthouse#5682]
**Lighthouse Version**: 3.0.3
**Lighthouse Commit**: d1cae24fda4182406e02d3f4df6309d48878fc50
**Chrome Version**: 69.0.3494.0
**Initial URL**: https://www.clubedebordar.com.br/
**Error Message**: No tabId set for sendCommand
**Stack Trace**:
```
Error: No tabId set for sendCommand
    at Promise (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17427:15)
    at new Promise (<anonymous>)
    at ExtensionConnection._sendCommand [as sendCommand] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:17423:8)
    at Driver._sendCommand [as sendCommand] (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:18758:25)
    at Object.clearAllNetworkEmulation (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:21687:15)
    at Driver.setThrottling (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:18557:18)
    at Function.afterPass (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:19061:14)
    at Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:19187:35)
```

**Comment by patrickhulce** [comment]
duplicate #5595
