### ISSUE TITLE
Extension Error: FAILED_DOCUMENT_REQUEST

### ISSUE THREAD

**Issue by rodrigo1987macedo** [GoogleChrome/lighthouse#5824]
**Lighthouse Version**: 3.0.3
**Lighthouse Commit**: d1cae24fda4182406e02d3f4df6309d48878fc50
**Chrome Version**: 68.0.3440.106
**Initial URL**: https://www.quieroescort.com/uruguay/
**Error Message**: FAILED_DOCUMENT_REQUEST
**Stack Trace**:
```
LHError: FAILED_DOCUMENT_REQUEST
    at Function.getPageLoadError (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:18937:13)
    at Function.afterPass (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:19042:32)
```

**Comment by rodrigo1987macedo** [comment]
not finishing the report due to this
