### ISSUE TITLE
DevTools Error: Protocol error (IO.read): Read failed

### ISSUE THREAD

**Issue by moimassmason** [GoogleChrome/lighthouse#5860]
**Initial URL**: https://pay.ebay.ca/xo?action=view&sessionid=929025612011
**Chrome Version**: 63.0.3239.108
**Error Message**: Protocol error (IO.read): Read failed
**Stack Trace**:
```
Error: Protocol error (IO.read): Read failed
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@d2626860fae283daee484943e6820af18fc73fd9/audits2_worker/audits2_worker_module.js:694:516)
    at <anonymous>
```xo?action=view&sessionid=929025612011:1 The SSL certificate used to load resources from https://pay.ebay.ca will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
xo?action=view&sessionid=929025612011:1 The SSL certificate used to load resources from https://c.paypal.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
xo?action=view&sessionid=929025612011:1 The SSL certificate used to load resources from https://www.paypalobjects.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
checkout-3.9.7.mpp.js:344 Paypal[post-robot] fullpage pay.ebay.ca #send postrobot_message_request identify {hash: "identify_816c03a5d4", type: "postrobot_message_request", name: "identify", data: {…}, id: "83fdfb0ac6", …}
checkout-3.9.7.mpp.js:344 Paypal[post-robot] fullpage pay.ebay.ca #send postrobot_message_request identify {hash: "identify_1b7575a2aa", type: "postrobot_message_request", name: "identify", data: {…}, id: "6f00d45e0c", …}
xo?action=view&sessionid=929025612011:1 The SSL certificate used to load resources from https://www.paypal.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
checkout-3.9.7.mpp.js:1137 PaypalError: You are calling paypal.checkout.setup() more than once. This function can only be called once per page load. Any further calls will be ignored.
247pxs.html:12 InitError:Init Call Failed. errorCode - 1002: Invalid value for request parameter: clientKey
N @ 247pxs.html:12
(anonymous) @ 247pxs.html:11
n @ 247pxs.html:10
XMLHttpRequest.send (async)
(anonymous) @ 247pxs.html:10
setTimeout (async)
g @ 247pxs.html:10
t @ 247pxs.html:10
n @ 247pxs.html:11
e @ 247pxs.html:13
setTimeout (async)
n @ 247pxs.html:13
(anonymous) @ 247pxs.html:13
(anonymous) @ 247pxs.html:13
setupFramework @ 247pxs.html:13
exports.initialize.exports.initialize @ 247pxs.html:13
(anonymous) @ 247pxs.html:14

**Comment by moimassmason** [comment]
Skip to content=Fixed!
 
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 @moimassmason
Sign out
 Watch 444
 Star 14,844  Fork 4,767 GoogleChrome/lighthouse
 Code  Issues 326  Pull requests 42  Projects 3  Insights
Edit New issue
DevTools Error: Protocol error (IO.read): Read failed #5860
 Closed	moimassmason opened this issue on Aug 17 · 1 comment Comments
Assignees
No one assigned
Labels
duplicate
Projects
None yet
Milestone
No milestone
Notifications
 Unsubscribe
You’re receiving notifications because you authored the thread.
2 participants
@moimassmason
@devtools-bot
@moimassmason
  
moimassmason commented on Aug 17
Initial URL: https://pay.ebay.ca/xo?action=view&sessionid=929025612011
Chrome Version: 63.0.3239.108
Error Message: Protocol error (IO.read): Read failed
Stack Trace:

Error: Protocol error (IO.read): Read failed
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@d2626860fae283daee484943e6820af18fc73fd9/audits2_worker/audits2_worker_module.js:694:516)
    at <anonymous>
```xo?action=view&sessionid=929025612011:1 The SSL certificate used to load resources from https://pay.ebay.ca will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
xo?action=view&sessionid=929025612011:1 The SSL certificate used to load resources from https://c.paypal.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
xo?action=view&sessionid=929025612011:1 The SSL certificate used to load resources from https://www.paypalobjects.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
checkout-3.9.7.mpp.js:344 Paypal[post-robot] fullpage pay.ebay.ca #send postrobot_message_request identify {hash: "identify_816c03a5d4", type: "postrobot_message_request", name: "identify", data: {…}, id: "83fdfb0ac6", …}
checkout-3.9.7.mpp.js:344 Paypal[post-robot] fullpage pay.ebay.ca #send postrobot_message_request identify {hash: "identify_1b7575a2aa", type: "postrobot_message_request", name: "identify", data: {…}, id: "6f00d45e0c", …}
xo?action=view&sessionid=929025612011:1 The SSL certificate used to load resources from https://www.paypal.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
checkout-3.9.7.mpp.js:1137 PaypalError: You are calling paypal.checkout.setup() more than once. This function can only be called once per page load. Any further calls will be ignored.
247pxs.html:12 InitError:Init Call Failed. errorCode - 1002: Invalid value for request parameter: clientKey
N @ 247pxs.html:12
(anonymous) @ 247pxs.html:11
n @ 247pxs.html:10
XMLHttpRequest.send (async)
(anonymous) @ 247pxs.html:10
setTimeout (async)
g @ 247pxs.html:10
t @ 247pxs.html:10
n @ 247pxs.html:11
e @ 247pxs.html:13
setTimeout (async)
n @ 247pxs.html:13
(anonymous) @ 247pxs.html:13
(anonymous) @ 247pxs.html:13
setupFramework @ 247pxs.html:13
exports.initialize.exports.initialize @ 247pxs.html:13
(anonymous) @ 247pxs.html:14
 @devtools-bot
  
devtools-bot commented on Aug 17
Howdy chief! Appreciate you filing this bug. clap

We think this is mighty similar to #2174. So, we'll automatically close this as a duplicate.

However, if you believe this is a mistake, please comment here with "necessarily-wide-alpaca" and I'll reopen this bug. robot Beep beep boop.
 @devtools-bot devtools-bot added the duplicate  label on Aug 17
 @devtools-bot devtools-bot closed this on Aug 17
 @karlcow karlcow referenced this issue on Sep 2
 Closed
ebay.co.uk - see bug description #18496
@moimassmason
   
 
 Write  Preview
 
Leave a comment
Choose Files Attach files by dragging & dropping, selecting them, or pasting from the clipboard.
 Styling with Markdown is supported
Comment
© 2018 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
Press h to open a hovercard with more details.
