### ISSUE TITLE
DevTools Error: Cannot read property 'requestAnimationFrame' of null

### ISSUE THREAD

**Issue by denzilm** [GoogleChrome/lighthouse#5979]
**Initial URL**: https://www.webafrica.co.za/
**Chrome Version**: 68.0.3440.106
**Error Message**: Cannot read property 'requestAnimationFrame' of null
**Stack Trace**:
```
TypeError: Cannot read property 'requestAnimationFrame' of null
    at Emulation.InspectedPagePlaceholder.onResize (chrome-devtools://devtools/bundled/devtools_app.js:183:96)
    at Emulation.InspectedPagePlaceholder._notify (chrome-devtools://devtools/bundled/shell.js:1036:66)
    at Emulation.InspectedPagePlaceholder._processOnResize (chrome-devtools://devtools/bundled/shell.js:1035:13)
    at Emulation.DeviceModeWrapper._callOnVisibleChildren (chrome-devtools://devtools/bundled/shell.js:1026:8)
    at Emulation.DeviceModeWrapper._processOnResize (chrome-devtools://devtools/bundled/shell.js:1035:41)
    at UI.RootView._callOnVisibleChildren (chrome-devtools://devtools/bundled/shell.js:1026:8)
    at UI.RootView.doResize (chrome-devtools://devtools/bundled/shell.js:1081:6)
    at UI.RootView.doResize (chrome-devtools://devtools/bundled/shell.js:2166:7)
    at UI.RootView.doLayout (chrome-devtools://devtools/bundled/shell.js:1083:41)
    at UI.RootView.invalidateConstraints (chrome-devtools://devtools/bundled/shell.js:1111:6)
```

**Comment by brendankenny** [comment]
This should be fine in latest Chrome (m69)

**Comment by paulirish** [comment]
Just repro'd this randomly.


```
lighthouse.js:formatted:3556 TypeError: Cannot read property 'requestAnimationFrame' of null
    at InspectedPagePlaceholder.onResize (emulation.js:formatted:2248)
    at InspectedPagePlaceholder._notify (ui.js:1)
    at InspectedPagePlaceholder._processOnResize (ui.js:1)
    at DeviceModeWrapper._callOnVisibleChildren (ui.js:1)
    at DeviceModeWrapper.doResize (ui.js:1)
    at DeviceModeWrapper.doLayout (ui.js:1)
    at DeviceModeWrapper.invalidateConstraints (ui.js:1)
    at InspectedPagePlaceholder.invalidateConstraints (ui.js:1)
    at InspectedPagePlaceholder.setMinimumSize (ui.js:1)
    at InspectedPagePlaceholder.restoreMinimumSize (emulation.js:formatted:2251)
```


it's throwing from the 2nd line of `onResize` because `this.element` is detached from the DOM:

```js
    onResize() {
        this._updateId && this.element.window().cancelAnimationFrame(this._updateId),
        this._updateId = this.element.window().requestAnimationFrame(this.update.bind(this, !1))
    }
```

The callstack walks back to `_setupEmulationAndProtocolConnection`:

![image](https://user-images.githubusercontent.com/39191/102828825-7f9dba80-439a-11eb-945f-0807ac7f4129.png)

So I'm guessing we fall into a weird state where our emulation setup/teardown state is corrupted. Like `_resetEmulationAndProtocolConnection` isn't called.

**Comment by paulirish** [comment]
Optimistically hoping that this got resolved in this devtools adjustment: https://github.com/GoogleChrome/lighthouse/issues/7911#issuecomment-759127156
