### ISSUE TITLE
Extension Error: INVALID_URL

### ISSUE THREAD

**Issue by sjf1256754123** [GoogleChrome/lighthouse#6144]
**Lighthouse Version**: 3.2.0
**Lighthouse Commit**: 081864eb30869df28f5ec05e28ca046b79b630cb
**Chrome Version**: 68.0.3440.106
**Initial URL**: file:///F:/test/h5/index.html
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:20063:7)
    at runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:44088:20)
```

**Comment by patrickhulce** [comment]
@sjf1256754123 can't run Lighthouse on `file://` URLs amigo, sorry! Thanks for filing anyway :)
