### ISSUE TITLE
Extension Error: INVALID_URL

### ISSUE THREAD

**Issue by double1960** [GoogleChrome/lighthouse#6155]
**Lighthouse Version**: 3.2.1
**Lighthouse Commit**: 3c03e2c4472ebf7d484623366ac89174cc7da253
**Chrome Version**: 69.0.3497.100
**Initial URL**: view-source:https://www.google.com/_/chrome/newtab?ie=UTF-8
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:20063:7)
    at runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:44088:20)
```

**Comment by patrickhulce** [comment]
Thanks for filing @double1960! You can't run LH on the view-source page though, you'll have to do it on the regular URL :)
