### ISSUE TITLE
Extension Error: INVALID_URL

### ISSUE THREAD

**Issue by Douglaslt17** [GoogleChrome/lighthouse#6168]
**Lighthouse Version**: 3.2.1
**Lighthouse Commit**: 3c03e2c4472ebf7d484623366ac89174cc7da253
**Chrome Version**: 69.0.3497.100
**Initial URL**: file:///D:/Projetos/_ToDo/index.html
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:20063:7)
    at runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:44088:20)
```

**Comment by exterkamp** [comment]
Lighthouse can't run over `file://` URLs.  Has to be running somehow i.e. localhost, for local dev!
