### ISSUE TITLE
Extension Error: INVALID_URLfile:///C:/Users/NNENNA%20PC/Desktop/ud891-gh-pages/lesson6-styling/03-contrast-audit/index.html

### ISSUE THREAD

**Issue by Nne85** [GoogleChrome/lighthouse#6193]
**Lighthouse Version**: 3.2.1
**Lighthouse Commit**: 3c03e2c4472ebf7d484623366ac89174cc7da253
**Chrome Version**: 69.0.3497.81
**Initial URL**: file:///C:/Users/NNENNA%20PC/Desktop/ud891-gh-pages/lesson6-styling/03-contrast-audit/index.html
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:20063:7)
    at runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:44088:20)
```

**Comment by patrickhulce** [comment]
Thanks @Nne85! You can't run Lighthouse on `file://` URLs you'll have to host it over http with a local server instead.
