### ISSUE TITLE
resourceChangedPriority and request.priorty errors

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/lighthouse#621]
Using Chrome Canary Version 55.0.2844.0 canary (64-bit) on OS X, launched via

```sh
$ npm explore -g lighthouse -- npm run chrome
```

I consistently get this error when running a full audit suite:

```sh
$ node lighthouse-cli/index.js https://ifixit-pwa.appspot.com

... logged output ...

/Users/jeffy/git/lighthouse/lighthouse-core/lib/network-recorder.js:90
    this.networkManager._dispatcher.resourceChangedPriority(data.requestId,
                                    ^
TypeError: this.networkManager._dispatcher.resourceChangedPriority is not a function
    at NetworkRecorder.onResourceChangedPriority (/Users/jeffy/git/lighthouse/lighthouse-core/lib/network-recorder.js:90:37)
    at emitOne (events.js:90:13)
    at Chrome.emit (events.js:182:7)
    at WebSocket.<anonymous> (/Users/jeffy/git/lighthouse/lighthouse-core/node_modules/chrome-remote-interface/lib/chrome.js:360:18)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.ontext (/Users/jeffy/git/lighthouse/lighthouse-core/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/jeffy/git/lighthouse/lighthouse-core/node_modules/ws/lib/Receiver.js:536:18
    at /Users/jeffy/git/lighthouse/lighthouse-core/node_modules/ws/lib/Receiver.js:368:7
    at /Users/jeffy/git/lighthouse/lighthouse-core/node_modules/ws/lib/PerMessageDeflate.js:249:5
```

When testing against a different site, I can reliably get a different error:

```sh
$ node lighthouse-cli/index.js https://airhorner.com

... logged output ...

Runtime error encountered: [TypeError: request.priority is not a function]
TypeError: request.priority is not a function
    at CriticalRequestChains.isCritical (/Users/jeffy/git/lighthouse/lighthouse-core/gather/computed/critical-request-chains.js:50:61)
    at /Users/jeffy/git/lighthouse/lighthouse-core/gather/computed/critical-request-chains.js:62:64
    at Array.filter (native)
    at CriticalRequestChains.getChains (/Users/jeffy/git/lighthouse/lighthouse-core/gather/computed/critical-request-chains.js:62:45)
    at CriticalRequestChains.request (/Users/jeffy/git/lighthouse/lighthouse-core/gather/computed/critical-request-chains.js:143:17)
    at Object.computedArtifacts.(anonymous function) [as requestCriticalRequestChains] (/Users/jeffy/git/lighthouse/lighthouse-core/gather/gather-runner.js:352:41)
    at Function.audit (/Users/jeffy/git/lighthouse/lighthouse-core/audits/critical-request-chains.js:44:22)
    at /Users/jeffy/git/lighthouse/lighthouse-core/runner.js:97:24
```

**Comment by deepanjanroy** [comment]
I cannot reproduce this error. I'm using  55.0.2844.0 canary (64-bit) on OS X with the exact commands you ran. 

From the output you shared, there's a chance the devtools-frontend module is out of date. Can you share the output of `npm list chrome-devtools-frontend`? You may have to do an `npm update`.

**Comment by jeffposnick** [comment]
Running `npm update` didn't change the version of `chrome-devtools-frontend`. Here's what I have:

```sh
$ npm list chrome-devtools-frontend

lighthouse@1.1.2 /Users/jeffy/git/lighthouse
└── chrome-devtools-frontend@1.0.401423
```

**Comment by deepanjanroy** [comment]
Very interesing - you do have the right version. Could you do `find . -type d -name chrome-devtools-frontend` in your toplevel lighthouse directory? I just want to eliminate the possibility of multiple installations of the package since IIRC we did move around the package.json file at some point.

**Comment by jeffposnick** [comment]
Sorry, I missed this while out of the office.

```sh
$ find . -type d -name chrome-devtools-frontend

./lighthouse-core/node_modules/chrome-devtools-frontend
./lighthouse-core/node_modules/devtools-timeline-model/node_modules/chrome-devtools-frontend
./node_modules/chrome-devtools-frontend
```

**Comment by deepanjanroy** [comment]
Ah as I expected, there's an old node_modules directory inside lighthouse-core. `rm -rf` that `lighthouse-core/node_modules`. We don't need it anymore.

**Comment by deepanjanroy** [comment]
Let me know if the problem is still there after you do that.

**Comment by jeffposnick** [comment]
Thanks! Mystery solved, and it works as expected now. 👍
