### ISSUE TITLE
Extension Error: INVALID_URL

### ISSUE THREAD

**Issue by Sybrandbos** [GoogleChrome/lighthouse#6232]
**Lighthouse Version**: 3.2.1
**Lighthouse Commit**: 3c03e2c4472ebf7d484623366ac89174cc7da253
**Chrome Version**: 69.0.3497.100
**Initial URL**: file:///C:/Users/sybra/Desktop/Radiuscollege/Periode_1/PR/PC4U/Website/home.html
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:20063:7)
    at runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:44088:20)
```

**Comment by exterkamp** [comment]
Unfortunately we can't analyze `file://` pages.
