### ISSUE TITLE
Running lighthouse from git repo?

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/lighthouse#624]
Say I clone the repo and then start hacking on the source. How do I run Lighthouse reports (both CLI and browser extension) using my hacked source?

**Comment by paulirish** [comment]
that work for you?

**Comment by kaycebasques** [comment]
# CLI

First try running the CLI I got a nice, straightforward error about needing to run with Node 5+. So I upgraded then tried again and got:

```
node lighthouse-cli https://google.com
  config:warn HTML is included, however no audit requires it. +0ms
  CRI driver:warn cannot create new tab, will reuse tab. +20ms { Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
Unable to connect to Chrome. Please run Chrome w/ debugging port 9222 open:
    npm explore -g lighthouse -- npm run chrome
```

Opening up Canary from the command line...

    /Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --remote-debugging-port=9222

...and then running again fixed it.

Wüd b nice to have a way around this, very least I'll mention it in the README

# Extension

First try yielded:

```
gulp watch
[19:10:48] Using gulpfile ~/Repositories/kaycebasques/lighthouse/lighthouse-extension/gulpfile.js
[19:10:48] Starting 'lint'...
[19:10:48] Starting 'browserify'...
[19:10:48] Starting 'html'...
[19:10:48] Starting 'copyReportScripts'...
/Users/kayce/Repositories/kaycebasques/lighthouse/lighthouse-extension/node_modules/eslint/lib/config/config-file.js:402
            throw e;
            ^

Error: Cannot find module 'eslint-config-xo'
Referenced from: google
Referenced from: /Users/kayce/Repositories/kaycebasques/lighthouse/.eslintrc
Referenced from: /Users/kayce/Repositories/kaycebasques/lighthouse/lighthouse-extension/.eslintrc
    at Object.resolve (/Users/kayce/Repositories/kaycebasques/lighthouse/lighthouse-extension/node_modules/eslint/lib/util/module-resolver.js:75:19)
    at resolve (/Users/kayce/Repositories/kaycebasques/lighthouse/lighthouse-extension/node_modules/eslint/lib/config/config-file.js:479:33)
    at load (/Users/kayce/Repositories/kaycebasques/lighthouse/lighthouse-extension/node_modules/eslint/lib/config/config-file.js:496:24)
    at /Users/kayce/Repositories/kaycebasques/lighthouse/lighthouse-extension/node_modules/eslint/lib/config/config-file.js:392:36
    at Array.reduceRight (native)
    at applyExtends (/Users/kayce/Repositories/kaycebasques/lighthouse/lighthouse-extension/node_modules/eslint/lib/config/config-file.js:363:28)
    at load (/Users/kayce/Repositories/kaycebasques/lighthouse/lighthouse-extension/node_modules/eslint/lib/config/config-file.js:530:22)
    at /Users/kayce/Repositories/kaycebasques/lighthouse/lighthouse-extension/node_modules/eslint/lib/config/config-file.js:392:36
    at Array.reduceRight (native)
    at applyExtends (/Users/kayce/Repositories/kaycebasques/lighthouse/lighthouse-extension/node_modules/eslint/lib/config/config-file.js:363:28)
```

I ran `npm install` from the extension directory... am I missing a global?

**Comment by wardpeet** [comment]
weird can you tell me your node version and npm? What Operating system? So I can try to reproduce

**Comment by kaycebasques** [comment]
It's working now so ¯\_(ツ)_/¯
