### ISSUE TITLE
Extension Error: INVALID_URL

### ISSUE THREAD

**Issue by tony710521** [GoogleChrome/lighthouse#6276]
**Lighthouse Version**: 3.2.1
**Lighthouse Commit**: 3c03e2c4472ebf7d484623366ac89174cc7da253
**Chrome Version**: 69.0.3497.100
**Initial URL**: view-source:http://114.32.4.30/
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:20063:7)
    at runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:44088:20)
```

**Comment by patrickhulce** [comment]
You can't run Lighthouse on the view-source page, you'll have to open the regular URL up!
