### ISSUE TITLE
Extension Error: INVALID_URL

### ISSUE THREAD

**Issue by rizubaba009** [GoogleChrome/lighthouse#6280]
**Lighthouse Version**: 3.2.1
**Lighthouse Commit**: 3c03e2c4472ebf7d484623366ac89174cc7da253
**Chrome Version**: 69.0.3497.100
**Initial URL**: blob:chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/34c938a4-15bd-493c-b94e-8293e3a710c4#runtime-settings
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:20063:7)
    at runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:44088:20)
```

**Comment by patrickhulce** [comment]
Can't run LH on `blob:` URLs/the report itself @rizubaba009  ;)

Navigate to a page served over HTTP(S) instead!
