### ISSUE TITLE
Extension Error: INVALID_URL

### ISSUE THREAD

**Issue by SandyFragrance** [GoogleChrome/lighthouse#6289]
**Lighthouse Version**: 3.2.1
**Lighthouse Commit**: 3c03e2c4472ebf7d484623366ac89174cc7da253
**Chrome Version**: 69.0.3497.100
**Initial URL**: blob:chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/b8c0c0df-085d-42c3-88c5-d86386c00f70
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:20063:7)
    at runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:44088:20)
```

**Comment by patrickhulce** [comment]
Can't run lighthouse on blob URLs, sorry! Navigate to a http/https page to start an audit.
