### ISSUE TITLE
Extension Error: INVALID_URL

### ISSUE THREAD

**Issue by btr1968** [GoogleChrome/lighthouse#6350]
**Lighthouse Version**: 3.2.1
**Lighthouse Commit**: 3c03e2c4472ebf7d484623366ac89174cc7da253
**Chrome Version**: 69.0.3497.100
**Initial URL**: file:///C:/Users/vasia/Desktop/%D0%9D%D0%BE%D0%B2%D0%B0%D1%8F%20%D0%BF%D0%B0%D0%BF%D0%BA%D0%B0/index.html#list
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:20063:7)
    at runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:44088:20)
```

**Comment by patrickhulce** [comment]
Can't run Lighthouse on `file:` URLs sorry! Host the content with a local server instead.
