### ISSUE TITLE
core: Increase timeout for Page.navigate

### ISSUE THREAD

**Issue by Hoten** [GoogleChrome/lighthouse#6407]
```
cjamcl@cjamcl-macbookpro  ~/src/lighthouse   issue-6386-speed-up-font-size-gatherer ? ⍟1  node lighthouse-cli https://www.flynashville.com/Pages/default.aspx --view                  ✔  1637  11:59:01
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +1ms
  ChromeLauncher Waiting for browser..... +518ms
  ChromeLauncher Waiting for browser.....✓ +1ms
  status Connecting to browser +138ms
  status Resetting state with about:blank +165ms
  status Benchmarking machine +327ms
  status Initializing… +511ms
  status Loading page & waiting for onload Scripts, CSSUsage, Viewport, ViewportDimensions, ThemeColor, Manifest, RuntimeExceptions, ChromeConsoleMessages, ImageUsage, Accessibility, AnchorsWithNoRelNoopener, AppCacheManifest, Doctype, DOMStats, JSLibraries, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, MetaDescription, FontSize, CrawlableLinks, MetaRobots, Hreflang, EmbeddedContent, Canonical, RobotsTxt +15ms
(node:33528) UnhandledPromiseRejectionWarning: LHError: PROTOCOL_TIMEOUT Method: Page.navigate
    at Timeout._ [as _onTimeout] (/Users/cjamcl/src/lighthouse/lighthouse-core/gather/driver.js:290:21)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

`Page.navigate` times out occasionally for `https://www.flynashville.com/Pages/default.aspx`.

**Comment by paulirish** [comment]
And what should we do with these rejections?

**Comment by Hoten** [comment]
ok, this is how long a bunch of `Page.navigate`s took.

```
Run 1
Connor custom page nav 0: 5.238ms
Connor custom page nav 1: 2755.836ms
Connor custom page nav 2: 1.133ms
Connor custom page nav 3: 7.180ms
Connor custom page nav 4: 4.838ms
Connor custom page nav 5: 820.551ms
Run 2
Connor custom page nav 0: 182.084ms
Connor custom page nav 1: 1970.088ms
Connor custom page nav 2: 3.705ms
Connor custom page nav 3: 9.040ms
Connor custom page nav 4: 4.335ms
Connor custom page nav 5: 988.872ms
Run 3
Connor custom page nav 0: 25.944ms
Connor custom page nav 1: 1189.222ms
Connor custom page nav 2: 3.843ms
Connor custom page nav 3: 8.833ms
Connor custom page nav 4: 4.405ms
Connor custom page nav 5: 791.345ms
Run 4
Connor custom page nav 0: 31.390ms
Connor custom page nav 1: 1408.069ms
Connor custom page nav 2: 3.397ms
Connor custom page nav 3: 8.486ms
Connor custom page nav 4: 6.635ms
Connor custom page nav 5: 671.888ms
Run 5
Connor custom page nav 0: 97.291ms
Connor custom page nav 1: 1242.109ms
Connor custom page nav 2: 3.329ms
Connor custom page nav 3: 9.176ms
Connor custom page nav 4: 6.447ms
Connor custom page nav 5: 1161.194ms
Run 6
Connor custom page nav 0: 80.388ms
Connor custom page nav 1: 1652.267ms
Connor custom page nav 2: 3.224ms
Connor custom page nav 3: 8.675ms
Connor custom page nav 4: 6.532ms
Connor custom page nav 5: 4269.703ms
Run 7
Connor custom page nav 0: 115.204ms
Connor custom page nav 1: 1942.420ms
Connor custom page nav 2: 3.103ms
Connor custom page nav 3: 7.839ms
Connor custom page nav 4: 5.487ms
Connor custom page nav 5: 2019.109ms
Run 8
Connor custom page nav 0: 23.291ms
Connor custom page nav 1: 1366.181ms
Connor custom page nav 2: 4.397ms
Connor custom page nav 3: 9.470ms
Connor custom page nav 4: 4.527ms
Connor custom page nav 5: 11632.777ms
Run 9
Connor custom page nav 0: 114.350ms
Connor custom page nav 1: 11629.240ms
Connor custom page nav 2: 1.506ms
Connor custom page nav 3: 7.925ms
Connor custom page nav 4: 6.022ms
Connor custom page nav 5: 4062.632ms
Run 10
Connor custom page nav 0: 12.812ms
Connor custom page nav 1: 1922.328ms
Connor custom page nav 2: 3.256ms
Connor custom page nav 3: 9.513ms
Connor custom page nav 4: 5.596ms
Connor custom page nav 5: 9470.082ms
```

I think setting the timeout to like, a minute will be good for now. If we see LR fail on many URLs still we can readdress.
