### ISSUE TITLE
Extension Error: INVALID_URL

### ISSUE THREAD

**Issue by BhavyaSingh2611** [GoogleChrome/lighthouse#6415]
**Lighthouse Version**: 3.2.1
**Lighthouse Commit**: 3c03e2c4472ebf7d484623366ac89174cc7da253
**Chrome Version**: 72.0.3590.0
**Initial URL**: file:///C:/Users/bhavy/.atom/projects/Classroom/template.html
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:20063:7)
    at runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:44088:20)
```

**Comment by exterkamp** [comment]
Sorry we can't analyze `file://` urls, host the file locally to analyze it.
