### ISSUE TITLE
Extension Error: INVALID_URL

### ISSUE THREAD

**Issue by smarescotti** [GoogleChrome/lighthouse#6419]
**Lighthouse Version**: 3.2.1
**Lighthouse Commit**: 3c03e2c4472ebf7d484623366ac89174cc7da253
**Chrome Version**: 70.0.3538.77
**Initial URL**: file:///Users/stefanomarescotti/Desktop/Re%CC%81servez%20de%CC%80s%20maintenant%20votre%20se%CC%81jour%20sur%20adagio-city.com.html
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:20063:7)
    at runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:44088:20)
```

**Comment by patrickhulce** [comment]
Can't run LH on `file:` URLs friend sorry!
