### ISSUE TITLE
DevTools Error: INVALID_URL when trying to audit extension

### ISSUE THREAD

**Issue by eridiniara** [GoogleChrome/lighthouse#6421]
**Initial URL**: chrome-extension://laookkfknpbbblfpciffpaejjkokdgca/dashboard.html
**Chrome Version**: 72.0.3590.0
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-devtools://devtools/remote/serve_file/@ec242826af28a2b3c3b47390ab6141cfe26fe9e7/audits2_worker/audits2_worker_module.js:1130:461)
    at runLighthouseInWorker (chrome-devtools://devtools/remote/serve_file/@ec242826af28a2b3c3b47390ab6141cfe26fe9e7/audits2_worker/audits2_worker_module.js:1570:200)
    at Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@ec242826af28a2b3c3b47390ab6141cfe26fe9e7/audits2_worker/audits2_worker_module.js:4593:133)
```

**Comment by brendankenny** [comment]
This is an interesting case for the [url check](https://github.com/GoogleChrome/lighthouse/blob/5a113dc567633fac3e5843b82c875d21a4b23564/lighthouse-core/index.js#L43) (in contrast to e.g. #6423). There's no reason that DevTools shouldn't be able to audit an extension's page.

**Comment by patrickhulce** [comment]
Oh yeah that check regressed `chrome-extension` support for DevTools then :/

**Comment by justinribeiro** [comment]
That's my bad. I can add `chrome-extension:` to `allowedProtocols` and that should resolve it:
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/url-shim.js#L27

**Comment by patrickhulce** [comment]
Yep that should do the trick sounds great! No worries at all @justinribeiro, tbh I completely forgot that DevTools could still audit chrome extensions until the new errors started popping up 😆
