### ISSUE TITLE
Extension Error: INVALID_URL

### ISSUE THREAD

**Issue by Jameson89** [GoogleChrome/lighthouse#6423]
**Lighthouse Version**: 3.2.1
**Lighthouse Commit**: 3c03e2c4472ebf7d484623366ac89174cc7da253
**Chrome Version**: 71.0.3578.21
**Initial URL**: chrome-extension://ckfjonhenjggkobbdmdgdhjmadanpenn/select.js
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:20063:7)
    at runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-background.js:44088:20)
```

**Comment by patrickhulce** [comment]
Can't audit other extensions with the extension, sorry!
