### ISSUE TITLE
killing Lighthouse early causes errors with ChromeLauncher

### ISSUE THREAD

**Issue by brendankenny** [GoogleChrome/lighthouse#664]
@boopathi 

Stack trace after crtl-c/SIGINT during run:
```
^CKilling all Chrome Instances
Removing /var/folders/vp/m2264gkn78z2t86hspz2d1j4003pf1/T/lighthouse.XXXXXXX.6DmHHTWS
~/lighthouse/node_modules/rimraf/rimraf.js:312
        throw er
        ^

Error: ENOTEMPTY: directory not empty, rmdir '/var/folders/vp/m2264gkn78z2t86hspz2d1j4003pf1/T/lighthouse.XXXXXXX.6DmHHTWS/Default'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:880:18)
    at rmkidsSync (~/lighthouse/node_modules/rimraf/rimraf.js:342:11)
    at rmdirSync (~/lighthouse/node_modules/rimraf/rimraf.js:332:7)
    at rimrafSync (~/lighthouse/node_modules/rimraf/rimraf.js:303:9)
    at ~/lighthouse/node_modules/rimraf/rimraf.js:340:5
    at Array.forEach (native)
    at rmkidsSync (~/lighthouse/node_modules/rimraf/rimraf.js:339:26)
    at rmdirSync (~/lighthouse/node_modules/rimraf/rimraf.js:332:7)
    at Function.rimrafSync [as sync] (~/lighthouse/node_modules/rimraf/rimraf.js:303:9)
```

Perhaps Chrome isn't closed when we try to delete the directory?

**Comment by boopathi** [comment]
Yeah. Chrome is still writing to that dir. 

What Node version are you using ?
