### ISSUE TITLE
Extension Error: INSECURE_DOCUMENT_REQUEST

### ISSUE THREAD

**Issue by gizzm0** [GoogleChrome/lighthouse#6652]
**Lighthouse Version**: 3.3.0.4001
**Lighthouse Commit**: 66100367e39d970f8208bd30c10bd97cc7240784
**Chrome Version**: 70.0.3538.110
**Initial URL**: https://localhost:4200/ch-aussendienst/dashboard?init=1
**Error Message**: INSECURE_DOCUMENT_REQUEST
**Stack Trace**:
```
LHError: INSECURE_DOCUMENT_REQUEST
    at Function.assertNoSecurityIssues (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:20163:7)
    at Function.afterPass (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:20298:6)
```

I am using invalid certificates for local development and enabled "Insecure origins treated as secure" and added "https://localhost" in chrome. Is there a way to do the same in lighthouse?

**Comment by patrickhulce** [comment]
duplicate #6455
