### ISSUE TITLE
DevTools Error: Invalid time zone specified: undefined

### ISSUE THREAD

**Issue by peaBerberian** [GoogleChrome/lighthouse#6691]
**Initial URL**: https://localhost:8443/
**Chrome Version**: 70.0.3538.110
**Error Message**: Invalid time zone specified: undefined
**Stack Trace**:
```
RangeError: Invalid time zone specified: undefined
    at new DateTimeFormat (native)
    at Date.toLocaleTimeString (native)
    at new Audits2.ReportSelector.Item (chrome-devtools://devtools/bundled/audits2/audits2_module.js:242:460)
    at Audits2.Audits2Panel._buildReportUI (chrome-devtools://devtools/bundled/audits2/audits2_module.js:184:28)
    at Audits2.Audits2Panel._startAudit (chrome-devtools://devtools/bundled/audits2/audits2_module.js:192:181)
```
Hi,

I have the issue above happening at the end of the diagnostics when running lighthouse on any given page.
To note that:
```js
new Date().toLocaleDateString()
```
Already throw on my system, so there's definitely something of with my timezone configuration on Chrome, whatever that means.

I looked a little at the ECMA262 standard ant it does not say anything about ``toLocaleDateString`` throwing. So this might be more of an issue with Chrome.

Still it depends on your point-of-view if you want to support edge-cases like mine, so I prefer to open an issue (others might have the same problem).

Feel free to close it if you think the problem is entirely on the "me-and-Chrome" side.

**Comment by patrickhulce** [comment]
Thanks for filing @peaBerberian! We certainly don't expect `toLocaleTimeString` to throw, and it does indeed look like there's something fishy going on with the locales on your machine :) 

Good to know the edge cases though, so thank you!

**Comment by peaBerberian** [comment]
I'm on Arch linux (Linux 4.19.4).
My timezone is ``Europe/Paris``.
``timedatectl status`` seems to return the right informations. I have also have ntp enabled.
``locale`` seems to indicate that ``LC_TIME`` is equal to ``"en_US.UTF-8"``.

Firefox (63) doesn't have any issue with the same JS API (it displays the date the american way).
To be honest, I already had seen that this API threw when called but it was never really problematic (the website didn't loose its functionalities) until now.

**Comment by wardpeet** [comment]
thanks, i'll spin up an arch linux.

could you give me the result of `window.navigator.languages`?

**Comment by peaBerberian** [comment]
Awesome, thanks!

``window.navigator.languages`` returns ``["fr-FR", "fr", "en-US", "en"]``.

**Comment by paulirish** [comment]
probably a dupe of #6046
 https://bugs.chromium.org/p/chromium/issues/detail?id=364374#c28 apparently landed in 70 which the user has.

real fix is the undefined timezone fallback in Audits2 devtools source (that we wrote for reportrenderer)
