### ISSUE TITLE
DevTools Error: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by vUdav** [GoogleChrome/lighthouse#6716]
**Initial URL**: https://timberland.ru/
**Chrome Version**: 70.0.3538.110
**Error Message**: Failed to construct 'URL': Invalid URL
**Stack Trace**:
```
TypeError: Failed to construct 'URL': Invalid URL
    at new URLShim (chrome-devtools://devtools/remote/serve_file/@ca97ba107095b2a88cf04f9135463301e685cbb0/audits2_worker/audits2_worker_module.js:4878:1)
    at NetworkRequest.onRequestWillBeSent (chrome-devtools://devtools/remote/serve_file/@ca97ba107095b2a88cf04f9135463301e685cbb0/audits2_worker/audits2_worker_module.js:1405:67)
    at NetworkRecorder.onRequestWillBeSent (chrome-devtools://devtools/remote/serve_file/@ca97ba107095b2a88cf04f9135463301e685cbb0/audits2_worker/audits2_worker_module.js:1384:151)
    at NetworkRecorder.dispatch (chrome-devtools://devtools/remote/serve_file/@ca97ba107095b2a88cf04f9135463301e685cbb0/audits2_worker/audits2_worker_module.js:1394:66)
    at devtoolsLog.forEach.message (chrome-devtools://devtools/remote/serve_file/@ca97ba107095b2a88cf04f9135463301e685cbb0/audits2_worker/audits2_worker_module.js:1397:126)
    at Array.forEach (<anonymous>)
    at Function.recordsFromLogs (chrome-devtools://devtools/remote/serve_file/@ca97ba107095b2a88cf04f9135463301e685cbb0/audits2_worker/audits2_worker_module.js:1397:93)
    at Function.afterPass (chrome-devtools://devtools/remote/serve_file/@ca97ba107095b2a88cf04f9135463301e685cbb0/audits2_worker/audits2_worker_module.js:1087:163)
```

**Comment by patrickhulce** [comment]
duplicate https://github.com/GoogleChrome/lighthouse/issues/6145, fixed by #6157
