### ISSUE TITLE
DevTools Error: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by Double5peed** [GoogleChrome/lighthouse#6771]
**Initial URL**: https://www.english-heritageshop.org.uk/
**Chrome Version**: 71.0.3578.80
**Error Message**: Failed to construct 'URL': Invalid URL
**Stack Trace**:
```
TypeError: Failed to construct 'URL': Invalid URL
    at new URLShim (chrome-devtools://devtools/remote/serve_file/@2ac50e7249fbd55e6f517a28131605c9fb9fe897/audits2_worker/audits2_worker_module.js:4575:1)
    at NetworkRequest.onRequestWillBeSent (chrome-devtools://devtools/remote/serve_file/@2ac50e7249fbd55e6f517a28131605c9fb9fe897/audits2_worker/audits2_worker_module.js:1421:67)
    at NetworkRecorder.onRequestWillBeSent (chrome-devtools://devtools/remote/serve_file/@2ac50e7249fbd55e6f517a28131605c9fb9fe897/audits2_worker/audits2_worker_module.js:1399:151)
    at NetworkRecorder.dispatch (chrome-devtools://devtools/remote/serve_file/@2ac50e7249fbd55e6f517a28131605c9fb9fe897/audits2_worker/audits2_worker_module.js:1409:66)
    at devtoolsLog.forEach.message (chrome-devtools://devtools/remote/serve_file/@2ac50e7249fbd55e6f517a28131605c9fb9fe897/audits2_worker/audits2_worker_module.js:1412:126)
    at Array.forEach (<anonymous>)
    at Function.recordsFromLogs (chrome-devtools://devtools/remote/serve_file/@2ac50e7249fbd55e6f517a28131605c9fb9fe897/audits2_worker/audits2_worker_module.js:1412:93)
    at Function.afterPass (chrome-devtools://devtools/remote/serve_file/@2ac50e7249fbd55e6f517a28131605c9fb9fe897/audits2_worker/audits2_worker_module.js:1115:163)
```

**Comment by patrickhulce** [comment]
duplicate, fixed by #6447
