### ISSUE TITLE
Extension Error: INSECURE_DOCUMENT_REQUEST

### ISSUE THREAD

**Issue by sandromacedo** [GoogleChrome/lighthouse#6829]
**Lighthouse Version**: 3.3.0.4001
**Lighthouse Commit**: 66100367e39d970f8208bd30c10bd97cc7240784
**Chrome Version**: 70.0.3538.110
**Initial URL**: https://behappywith.me/
**Error Message**: INSECURE_DOCUMENT_REQUEST
**Stack Trace**:
```
LHError: INSECURE_DOCUMENT_REQUEST
    at Function.assertNoSecurityIssues (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:20163:7)
    at Function.afterPass (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:20298:6)
```

**Comment by exterkamp** [comment]
The site seems to have an expried cert, so from a Lighthouse perspective this is WAI
![image](https://user-images.githubusercontent.com/6392995/50193371-243c1c00-02eb-11e9-988a-bfda21f3ed81.png)
