### ISSUE TITLE
DevTools Error: Protocol error (Runtime.evaluate): Promise was collected

### ISSUE THREAD

**Issue by khaled-ghareeb** [GoogleChrome/lighthouse#6847]
**Initial URL**: https://www.maspero.eg/wps/portal
**Chrome Version**: 71.0.3578.98
**Error Message**: Protocol error (Runtime.evaluate): Promise was collected
**Stack Trace**:
```
Error: Protocol error (Runtime.evaluate): Promise was collected
    at Function.fromProtocolMessage (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1341:121)
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:998:253)
```

**Comment by patrickhulce** [comment]
Fascinating I don't think I've ever seen this one before! Seems like a few others have run into this with axe before (https://github.com/cyrus-and/chrome-remote-interface/issues/89#issuecomment-292492617).

Locally, the page seems to hang on `ImageUsage`. It's very busy at rest but not 100% busy with tasks, so seems like we can do better on our end.

**Comment by paulirish** [comment]
duping into #5973
