### ISSUE TITLE
DevTools Error: INVALID_URL

### ISSUE THREAD

**Issue by B4BIPIN** [GoogleChrome/lighthouse#6853]
**Initial URL**: chrome-extension://laookkfknpbbblfpciffpaejjkokdgca/dashboard.html
**Chrome Version**: 71.0.3578.98
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1130:461)
    at runLighthouseInWorker (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1570:200)
    at Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:4593:133)
```

**Comment by B4BIPIN** [comment]
I was just searching google chrome Dev tools, and as I clicked over Audits button it shows me this kind of error.
![screenshot from 2018-12-20 17-23-42](https://user-images.githubusercontent.com/31282304/50283499-0f42c280-047c-11e9-93b7-689f1443321f.png)
