### ISSUE TITLE
DevTools Error: Runtime.evaluate response did not contain a "result" object

### ISSUE THREAD

**Issue by viclec** [GoogleChrome/lighthouse#6869]
**Initial URL**: http://localhost:3000/excursion/199/SSRBT.R/2013-06-01
**Chrome Version**: 71.0.3578.98
**Error Message**: Runtime.evaluate response did not contain a "result" object
**Stack Trace**:
```
Error: Runtime.evaluate response did not contain a "result" object
    at sendCommand.then.response (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1044:47)
```

**Comment by Hoten** [comment]
#6026 is the first mention of this issue. Seems the site listed there no longer presents the issue - probably just it has changed since the issue was created. @viclec are you able to share your site publicly?

@exterkamp to be clear, the fix was providing a more specific error message? Any theories for why `Runtime.evaluate` would return an empty response?

[haystack](https://bugs.chromium.org/p/chromium/issues/list?can=1&q=runtime.evaluate+component%3APlatform%3EDevTools&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids).

**Comment by viclec** [comment]
Unfortunatelly I cannot share the application publicly. If I can help in another way please let me know.

**Comment by exterkamp** [comment]
iirc we don't know why it would send nothing.  @viclec if this is happening consistently I'd love to know what `evaluationParams` are being sent, or what the logs look like.  Can you give us any background on the nature of these runs?

@brendankenny  @paulirish any ideas why `Runtime.evaluate` wouldn't send a result?  Our thoughts last time afaik was that the protocol was dead and that this issue would be transient, just bad luck.

**Comment by connorjclark** [comment]
Fixed in https://github.com/GoogleChrome/lighthouse/pull/6089. This issue will remain open b/c investigation is still needed.

**Comment by michalpokojski** [comment]
Runtime.evaluate response did not contain a "result" object
```
Channel: DevTools
Initial URL: https://justjoin.it/sniadanie-z-programowaniem
Chrome Version: 84.0.4147.105
Stack Trace: Error: Runtime.evaluate response did not contain a "result" object
    at Driver._evaluateInContext (devtools://devtools/remote/serve_file/@a6b12dfad6663f13a7e16e9a42a6a4975374096b/lighthouse_worker/lighthouse_worker_module.js:1471:55)
    at async Driver.evaluateAsync (devtools://devtools/remote/serve_file/@a6b12dfad6663f13a7e16e9a42a6a4975374096b/lighthouse_worker/lighthouse_worker_module.js:1459:145)
    at async Function.afterPass (devtools://devtools/remote/serve_file/@a6b12dfad6663f13a7e16e9a42a6a4975374096b/lighthouse_worker/lighthouse_worker_module.js:1571:812)
    at async Function.runPass (devtools://devtools/remote/serve_file/@a6b12dfad6663f13a7e16e9a42a6a4975374096b/lighthouse_worker/lighthouse_worker_module.js:1593:84)
    at async Function.run (devtools://devtools/remote/serve_file/@a6b12dfad6663f13a7e16e9a42a6a4975374096b/lighthouse_worker/lighthouse_worker_module.js:1585:576)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/remote/serve_file/@a6b12dfad6663f13a7e16e9a42a6a4975374096b/lighthouse_worker/lighthouse_worker_module.js:2257:151)
    at async Function.run (devtools://devtools/remote/serve_file/@a6b12dfad6663f13a7e16e9a42a6a4975374096b/lighthouse_worker/lighthouse_worker_module.js:2249:11)
```

**Comment by black-snow** [comment]
```
Runtime.evaluate response did not contain a "result" object

Channel: DevTools
Initial URL: https://xxxxxx
Chrome Version: 85.0.4183.102
Stack Trace: Error: Runtime.evaluate response did not contain a "result" object
    at Driver._evaluateInContext (devtools://devtools/remote/serve_file/@ffe848af6a5df4fa127e2929331116b7f9f1cb30/lighthouse_worker/lighthouse_worker_module.js:1471:55)
    at async Driver.evaluateAsync (devtools://devtools/remote/serve_file/@ffe848af6a5df4fa127e2929331116b7f9f1cb30/lighthouse_worker/lighthouse_worker_module.js:1459:145)
    at async Function.afterPass (devtools://devtools/remote/serve_file/@ffe848af6a5df4fa127e2929331116b7f9f1cb30/lighthouse_worker/lighthouse_worker_module.js:1571:812)
    at async Function.runPass (devtools://devtools/remote/serve_file/@ffe848af6a5df4fa127e2929331116b7f9f1cb30/lighthouse_worker/lighthouse_worker_module.js:1593:84)
    at async Function.run (devtools://devtools/remote/serve_file/@ffe848af6a5df4fa127e2929331116b7f9f1cb30/lighthouse_worker/lighthouse_worker_module.js:1585:576)
    at async Function._gatherArtifactsFromBrowser (devtools://devtools/remote/serve_file/@ffe848af6a5df4fa127e2929331116b7f9f1cb30/lighthouse_worker/lighthouse_worker_module.js:2257:151)
    at async Function.run (devtools://devtools/remote/serve_file/@ffe848af6a5df4fa127e2929331116b7f9f1cb30/lighthouse_worker/lighthouse_worker_module.js:2249:11)
```

**Comment by connorjclark** [comment]
Seems this does not occur anymore.
