### ISSUE TITLE
DevTools Error: INVALID_URL

### ISSUE THREAD

**Issue by melissakekko** [GoogleChrome/lighthouse#6913]
**Initial URL**: chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/data/js/options.html?anl=true
**Chrome Version**: 71.0.3578.98
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1130:461)
    at runLighthouseInWorker (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1570:200)
    at Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:4593:133)
```

**Comment by patrickhulce** [comment]
duplicate #6421
