### ISSUE TITLE
Extension Error: INSECURE_DOCUMENT_REQUEST

### ISSUE THREAD

**Issue by yogbharat1** [GoogleChrome/lighthouse#6921]
**Lighthouse Version**: 3.3.0.4001
**Lighthouse Commit**: 66100367e39d970f8208bd30c10bd97cc7240784
**Chrome Version**: 71.0.3578.98
**Initial URL**: https://elleviodev.azurewebsites.net/privat/
**Error Message**: INSECURE_DOCUMENT_REQUEST
**Stack Trace**:
```
LHError: INSECURE_DOCUMENT_REQUEST
    at Function.assertNoSecurityIssues (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:20163:7)
    at Function.afterPass (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:20298:6)
```

**Comment by exterkamp** [comment]
I can run this site fine from extension:
![image](https://user-images.githubusercontent.com/6392995/50653170-8036af80-0f3d-11e9-97d1-c8a0103a4e9b.png)

@Hoten wanna run your bot?
