### ISSUE TITLE
DevTools Error: INVALID_URL

### ISSUE THREAD

**Issue by ecoidealist** [GoogleChrome/lighthouse#6934]
**Initial URL**: chrome-extension://ckkdlimhmcjmikdlpkmbgfkaikojcbjk/content/options.html
**Chrome Version**: 71.0.3578.98
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1130:461)
    at runLighthouseInWorker (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1570:200)
    at Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:4593:133)
```

**Comment by patrickhulce** [comment]
Thanks for filing @ecoidealist! Can you reproduce this on Chrome Canary? We believe this issue was fixed in newer versions of Lighthouse.

**Comment by owenschoppe** [comment]
Ahh, I just filed a duplicate issue. It is indeed fixed in Canary! At least for me.
