### ISSUE TITLE
DevTools Error: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by Fgruntjes** [GoogleChrome/lighthouse#6979]
**Initial URL**: https://www.zitmaxx.nl/
**Chrome Version**: 71.0.3578.98
**Error Message**: Failed to construct 'URL': Invalid URL
**Stack Trace**:
```
TypeError: Failed to construct 'URL': Invalid URL
    at new URLShim (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:4575:1)
    at NetworkRequest.onRequestWillBeSent (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1421:67)
    at NetworkRecorder.onRequestWillBeSent (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1399:151)
    at NetworkRecorder.dispatch (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1409:66)
    at devtoolsLog.forEach.message (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1412:126)
    at Array.forEach (<anonymous>)
    at Function.recordsFromLogs (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1412:93)
    at Function.afterPass (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1115:163)
```

**Comment by exterkamp** [comment]
I can repro this.  Some wires are getting crossed somewhere.
![image](https://user-images.githubusercontent.com/6392995/50991510-ac1bdd00-14c9-11e9-9bc1-757015fa43f8.png)

**Comment by brendankenny** [comment]
@exterkamp that looks like that's in the report code (`util.js`)? But the call stack shows the throw in `network-request.js`

**Comment by exterkamp** [comment]
Yup, I'm still looking.  I was thinking  of the wrong part of `font-size` since SEO i18n is still on my mind :laughing: 

Current thought is that a network request has gone bad yea.

**Comment by Fgruntjes** [comment]
Guys thnx allot!
