### ISSUE TITLE
DevTools Error: INVALID_URL

### ISSUE THREAD

**Issue by jpeg99** [GoogleChrome/lighthouse#7033]
**Stack Trace**:
```Lighthouse audits

LHError: INVALID_URL
    at lighthouse (chrome-devtools://devtools/bundled/audits2_worker/audits2_worker_module.js:1130:461)
    at runLighthouseInWorker (chrome-devtools://devtools/bundled/audits2_worker/audits2_worker_module.js:1570:200)
    at Promise.resolve.then._ (chrome-devtools://devtools/bundled/audits2_worker/audits2_worker_module.js:4593:1

**Comment by jpeg99** [comment]
> if love is not love there is no love
