### ISSUE TITLE
DevTools Error: INVALID_URL

### ISSUE THREAD

**Issue by Lamar2019** [GoogleChrome/lighthouse#7183]
**Initial URL**: chrome-error://chromewebdata/
**Chrome Version**: 73.0.3683.20
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-devtools://devtools/bundled/audits2_worker/audits2_worker_module.js:1143:461)
    at runLighthouseInWorker (chrome-devtools://devtools/bundled/audits2_worker/audits2_worker_module.js:690:200)
    at eval (chrome-devtools://devtools/bundled/audits2_worker/audits2_worker_module.js:3611:103)
```

**Comment by patrickhulce** [comment]
Thanks @Lamar2019! Can't audit Chrome error pages though :)
