### ISSUE TITLE
DevTools Error: INVALID_URL

### ISSUE THREAD

**Issue by SkyFuInMC** [GoogleChrome/lighthouse#7188]
Cannot launch Lighthouse within my own developing extension.
**Initial URL**: chrome-extension://kpfmndiipibhlbnldfglkccojgphniih/index.htm
**Chrome Version**: 71.0.3578.98
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1130:461)
    at runLighthouseInWorker (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:1570:200)
    at Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@15234034d19b85dcd9a03b164ae89d04145d8368/audits2_worker/audits2_worker_module.js:4593:133)
```

**Comment by k-ivan** [comment]
I also get this error when checking my chrome extension.

**Comment by patrickhulce** [comment]
Thanks folks! This was fixed in https://github.com/GoogleChrome/lighthouse/commit/5b0105f3db57080667bc37e461c4d6d020b4fee4 and should be out in latest Chrome Canary.
