### ISSUE TITLE
DevTools Error: INVALID_URL

### ISSUE THREAD

**Issue by osmalia** [GoogleChrome/lighthouse#7226]
**Initial URL**: chrome-error://chromewebdata/
**Chrome Version**: 72.0.3626.96
**Error Message**: INVALID_URL
**Stack Trace**:
```
LHError: INVALID_URL
    at lighthouse (chrome-devtools://devtools/remote/serve_file/@84098ee7ef8622a9defc2ef043cd8930b617b10e/audits2_worker/audits2_worker_module.js:1130:461)
    at runLighthouseInWorker (chrome-devtools://devtools/remote/serve_file/@84098ee7ef8622a9defc2ef043cd8930b617b10e/audits2_worker/audits2_worker_module.js:1570:200)
    at Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@84098ee7ef8622a9defc2ef043cd8930b617b10e/audits2_worker/audits2_worker_module.js:4593:133)
```

**Comment by patrickhulce** [comment]
Can't audit the Chrome error pages, sorry!
