### ISSUE TITLE
DevTools Error: Protocol error (Runtime.evaluate): Promise was collected

### ISSUE THREAD

**Issue by Valuvan** [GoogleChrome/lighthouse#7244]
**Chrome Version**: 72.0.3626.109
**Error Message**: Protocol error (Runtime.evaluate): Promise was collected
**Stack Trace**:
```
Error: Protocol error (Runtime.evaluate): Promise was collected
    at Function.fromProtocolMessage (chrome-devtools://devtools/remote/serve_file/@fae8db7ab9280fa6704a59980263c804f809ebd5/audits2_worker/audits2_worker_module.js:1341:121)
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@fae8db7ab9280fa6704a59980263c804f809ebd5/audits2_worker/audits2_worker_module.js:998:253)
```

**Comment by exterkamp** [comment]
Thanks for reporting! Duping into #5973
