### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found

### ISSUE THREAD

**Issue by chinabrother** [GoogleChrome/lighthouse#7331]
**Initial URL**: http://localhost:8078/
**Chrome Version**: 72.0.3626.96
**Error Message**: Protocol error (Tracing.start): 'Tracing.start' wasn't found
**Stack Trace**:
```
Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found
    at Function.fromProtocolMessage (chrome-devtools://devtools/remote/serve_file/@84098ee7ef8622a9defc2ef043cd8930b617b10e/audits2_worker/audits2_worker_module.js:1341:121)
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@84098ee7ef8622a9defc2ef043cd8930b617b10e/audits2_worker/audits2_worker_module.js:998:253)
```

**Comment by patrickhulce** [comment]
duplicate #7246
