### ISSUE TITLE
LHError: INVALID_URL - Runtime error encountered: lighthouse-core/lib/lh-error.js | urlInvalid # 0

### ISSUE THREAD

**Issue by moosahassan** [GoogleChrome/lighthouse#7341]
Following the [instructions](https://developers.google.com/web/tools/lighthouse/#devtools
) for launching lighthouse for `www.google.com` causes the following runtime error
```
m @ app $ lighthouse www.google.com --view
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +1ms
  ChromeLauncher Waiting for browser..... +519ms
  ChromeLauncher Waiting for browser.....✓ +1ms
  ChromeLauncher Killing Chrome instance 45170 +1ms
Runtime error encountered: lighthouse-core/lib/lh-error.js | urlInvalid # 0
LHError: INVALID_URL
    at lighthouse (/Users/m/.nvm/versions/node/v8.11.3/lib/node_modules/lighthouse/lighthouse-core/index.js:44:11)
    at chromeP.then._ (/Users/m/.nvm/versions/node/v8.11.3/lib/node_modules/lighthouse/lighthouse-cli/run.js:191:12)
    at <anonymous>
m @ app $ 
```

**Comment by patrickhulce** [comment]
@moosahassan that's because it's an invalid URL. Try with the `https://`

```bash
lighthouse https://www.google.com --view

**Comment by moosahassan** [comment]
thank you @patrickhulce
