### ISSUE TITLE
DevTools Error: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by Daemeron** [GoogleChrome/lighthouse#7347]
**Initial URL**: https://www.tado.com/de/
**Chrome Version**: 72.0.3626.119
**Error Message**: Failed to construct 'URL': Invalid URL
**Stack Trace**:
```
TypeError: Failed to construct 'URL': Invalid URL
    at new URLShim (chrome-devtools://devtools/remote/serve_file/@9a65993e2cde1b5797ec98da4cd9abcea464cd7b/audits2_worker/audits2_worker_module.js:4575:1)
    at NetworkRequest.onRequestWillBeSent (chrome-devtools://devtools/remote/serve_file/@9a65993e2cde1b5797ec98da4cd9abcea464cd7b/audits2_worker/audits2_worker_module.js:1421:67)
    at NetworkRecorder.onRequestWillBeSent (chrome-devtools://devtools/remote/serve_file/@9a65993e2cde1b5797ec98da4cd9abcea464cd7b/audits2_worker/audits2_worker_module.js:1399:151)
    at NetworkRecorder.dispatch (chrome-devtools://devtools/remote/serve_file/@9a65993e2cde1b5797ec98da4cd9abcea464cd7b/audits2_worker/audits2_worker_module.js:1409:66)
    at devtoolsLog.forEach.message (chrome-devtools://devtools/remote/serve_file/@9a65993e2cde1b5797ec98da4cd9abcea464cd7b/audits2_worker/audits2_worker_module.js:1412:126)
    at Array.forEach (<anonymous>)
    at Function.recordsFromLogs (chrome-devtools://devtools/remote/serve_file/@9a65993e2cde1b5797ec98da4cd9abcea464cd7b/audits2_worker/audits2_worker_module.js:1412:93)
    at Function.afterPass (chrome-devtools://devtools/remote/serve_file/@9a65993e2cde1b5797ec98da4cd9abcea464cd7b/audits2_worker/audits2_worker_module.js:1115:163)
```

**Comment by Hoten** [comment]
Errors in 3.2, but has been fixed. 

```
npx -p lighthouse@3.2.0 lighthouse https://www.tado.com/de/ --view # fails
npx -p lighthouse@4.0 lighthouse https://www.tado.com/de/ --view # does not fail
```

4.0 comes out in Chrome 73 on March 12th. In the meantime, you can use Chrome canary or page speed insights.

**Comment by Daemeron** [comment]
👍
