### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found

### ISSUE THREAD

**Issue by lordcharlx** [GoogleChrome/lighthouse#7360]
**Initial URL**: https://cinchpos.com/
**Chrome Version**: 72.0.3626.109
**Error Message**: Protocol error (Tracing.start): 'Tracing.start' wasn't found
**Stack Trace**:
```
Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found
    at Function.fromProtocolMessage (chrome-devtools://devtools/remote/serve_file/@fae8db7ab9280fa6704a59980263c804f809ebd5/audits2_worker/audits2_worker_module.js:1341:121)
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@fae8db7ab9280fa6704a59980263c804f809ebd5/audits2_worker/audits2_worker_module.js:998:253)
```

**Comment by patrickhulce** [comment]
duplicate #7246
