### ISSUE TITLE
DevTools Error: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by Glisho** [GoogleChrome/lighthouse#7364]
**Initial URL**: https://flip.co.uk/
**Chrome Version**: 72.0.3626.119
**Error Message**: Failed to construct 'URL': Invalid URL
**Stack Trace**:
```
TypeError: Failed to construct 'URL': Invalid URL
    at new URLShim (chrome-devtools://devtools/remote/serve_file/@9a65993e2cde1b5797ec98da4cd9abcea464cd7b/audits2_worker/audits2_worker_module.js:4575:1)
    at NetworkRequest.onRequestWillBeSent (chrome-devtools://devtools/remote/serve_file/@9a65993e2cde1b5797ec98da4cd9abcea464cd7b/audits2_worker/audits2_worker_module.js:1421:67)
    at NetworkRecorder.onRequestWillBeSent (chrome-devtools://devtools/remote/serve_file/@9a65993e2cde1b5797ec98da4cd9abcea464cd7b/audits2_worker/audits2_worker_module.js:1399:151)
    at NetworkRecorder.dispatch (chrome-devtools://devtools/remote/serve_file/@9a65993e2cde1b5797ec98da4cd9abcea464cd7b/audits2_worker/audits2_worker_module.js:1409:66)
    at devtoolsLog.forEach.message (chrome-devtools://devtools/remote/serve_file/@9a65993e2cde1b5797ec98da4cd9abcea464cd7b/audits2_worker/audits2_worker_module.js:1412:126)
    at Array.forEach (<anonymous>)
    at Function.recordsFromLogs (chrome-devtools://devtools/remote/serve_file/@9a65993e2cde1b5797ec98da4cd9abcea464cd7b/audits2_worker/audits2_worker_module.js:1412:93)
    at Function.afterPass (chrome-devtools://devtools/remote/serve_file/@9a65993e2cde1b5797ec98da4cd9abcea464cd7b/audits2_worker/audits2_worker_module.js:1115:163)
```

**Comment by patrickhulce** [comment]
Thanks @Glisho! This has been fixed in Chrome Canary by #6157
