### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found

### ISSUE THREAD

**Issue by RamziHannachi** [GoogleChrome/lighthouse#7535]
**Initial URL**: http://localhost:4200/home
**Chrome Version**: 72.0.3626.122
**Error Message**: Protocol error (Tracing.start): 'Tracing.start' wasn't found
**Stack Trace**:
```
Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found
    at Function.fromProtocolMessage (chrome-devtools://devtools/remote/serve_file/@e78ac5b2c005af6b8bdcced26e44036559f636b0/audits2_worker/audits2_worker_module.js:1341:121)
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/remote/serve_file/@e78ac5b2c005af6b8bdcced26e44036559f636b0/audits2_worker/audits2_worker_module.js:998:253)
```

**Comment by patrickhulce** [comment]
Duplicate #7246.

If you are on Debian, this is an issue with Debian's distribution of Chromium. Use Google Chrome if you want to use Lighthouse.
