### ISSUE TITLE
DevTools Error: Cannot read property 'navigate' of null

### ISSUE THREAD

**Issue by tomdw** [GoogleChrome/lighthouse#7544]
**Initial URL**: http://localhost:4201/
**Chrome Version**: 73.0.3683.75
**Error Message**: Cannot read property 'navigate' of null
**Stack Trace**:
```
TypeError: Cannot read property 'navigate' of null
    at Audits2.Audits2Panel._resetEmulationAndProtocolConnection (chrome-devtools://devtools/bundled/audits2/audits2_module.js:221:562)
    at async Audits2.Audits2Panel._startAudit (chrome-devtools://devtools/bundled/audits2/audits2_module.js:214:126)
```

**Comment by patrickhulce** [comment]
Interesting this is a new one. @tomdw any steps you took that might help us reproduce?

**Comment by tomdw** [comment]
@patrickhulce I dont have specific steps. It happened suddenly.

**Comment by brendankenny** [comment]
Closing since it's been a while without an update. If you run into this again, please comment and we can reopen.
