### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found

### ISSUE THREAD

**Issue by Flo2ent** [GoogleChrome/lighthouse#7601]
**Initial URL**: http://127.0.0.1:5500/index.html
**Chrome Version**: 72.0.3626.121
**Error Message**: Protocol error (Tracing.start): 'Tracing.start' wasn't found
**Stack Trace**:
```
Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found
    at Function.fromProtocolMessage (chrome-devtools://devtools/bundled/audits2_worker/audits2_worker_module.js:1341:121)
    at callback.resolve.Promise.resolve.then._ (chrome-devtools://devtools/bundled/audits2_worker/audits2_worker_module.js:998:253)
```

**Comment by patrickhulce** [comment]
Duplicate #7246
