### ISSUE TITLE
DevTools Error: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by stevenruidigao** [GoogleChrome/lighthouse#7610]
**Initial URL**: http://localhost:3000/
**Chrome Version**: 73.0.3683.75
**Error Message**: Cannot read property 'match' of undefined
**Stack Trace**:
```
TypeError: Cannot read property 'match' of undefined
    at Driver.getBrowserVersion (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1013:212)
    at async Function.getBaseArtifacts (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1133:117)
    at async Function.run (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1134:134)
    at async Function._gatherArtifactsFromBrowser (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1591:151)
    at async Function.run (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1583:11)
```

**Comment by patrickhulce** [comment]
Man, how'd this one happen...

@stevenruidigao anything important about your environment and repro steps you can share?

**Comment by stevenruidigao** [comment]
I have gotten this error twice. I am trying to analyze a localhost webpage using chrome in incognito mode, and after this (like 10 seconds later) it says "DevTools Error: PROTOCOL_TIMEOUT". It seems to randomly happen, because I am not currently able to reproduce this error.

**Comment by patrickhulce** [comment]
Yeah it sounds like something really strange is going on with Chrome responding to Lighthouse messages. By chance do you have any anti-virus software/weird plugins/enterprise management policies that might interfere with Chrome traffic?

**Comment by stevenruidigao** [comment]
I don’t think that there are any weird plugins, because I am using incognito mode, and the only antivirus software I have apart from Windows Defender is Malwarebytes free. There are no enterprise management policies that can interfere with Chrome traffic because this is a personal computer that is running Windows 10 Home (doesn’t have enterprise management capabilities).

**Comment by stevenruidigao** [comment]
It just happened again... I turned off the network connection in Application and it happened. However, when I did it again, it didn't.

**Comment by patrickhulce** [comment]
If anyone else runs in this issue, any additional info you can provide would be excellent :)

Particularly, if you're using a different version of Chromium (Brave/Opera/Edge/etc), or running anything strange on your machine.
