### ISSUE TITLE
DevTools Error: Protocol error (Runtime.evaluate): Promise was collected

### ISSUE THREAD

**Issue by bshack** [GoogleChrome/lighthouse#7625]
I had Javascript disabled trying to test the performance of the page without JS.

**Initial URL**: https://www.baggallini.com/womens-handbags-all/
**Chrome Version**: 73.0.3683.75
**Error Message**: Protocol error (Runtime.evaluate): Promise was collected
**Stack Trace**:
```
Error: Protocol error (Runtime.evaluate): Promise was collected
    at Function.fromProtocolMessage (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1364:121)
    at eval (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:995:253)
```

**Comment by patrickhulce** [comment]
Thanks for filing! Duplicate #5973, we'll discuss over on that issue.
