### ISSUE TITLE
DevTools Error: PAGE_HUNG

### ISSUE THREAD

**Issue by Antonpc** [GoogleChrome/lighthouse#7663]
**Initial URL**: https://m.vk.com/mail
**Chrome Version**: 73.0.3683.75
**Error Message**: PAGE_HUNG
**Stack Trace**:
```
LHError: PAGE_HUNG
    at eval (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1063:1407)
    at async Driver._waitForFullyLoaded (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1063:1720)
    at async Driver.gotoURL (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1072:974)
    at async Function.loadPage (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1116:58)
    at async Function.pass (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1124:614)
    at async Function.run (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1135:60)
    at async Function._gatherArtifactsFromBrowser (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1591:151)
    at async Function.run (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1583:11)
```

**Comment by patrickhulce** [comment]
This error means that the page stopped responding. The solution here is to re-run. If the error repeats, the page has an infinite loop and needs to be fixed.
