### ISSUE TITLE
Release 1.1.5 seems to be broken (missing lighthouse-core/config/perf.json)

### ISSUE THREAD

**Issue by matz3** [GoogleChrome/lighthouse#769]
```shell
node --version
v6.5.0
```

```shell
npm --version
3.10.3
```

```shell
npm install --global lighthouse@1.1.5
```

```shell
> lighthouse https://airhorner.com/
module.js:457
    throw err;
    ^

Error: Cannot find module '../lighthouse-core/config/perf.json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/matz3/.nvm/versions/node/v6.5.0/lib/node_modules/lighthouse/lighthouse-cli/index.js:34:24)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

When downloading the npm module package I can also not find the file:
http://registry.npmjs.org/lighthouse/-/lighthouse-1.1.5.tgz

I hope I didn't miss anything. `1.1.4` works fine.

**Comment by amedina** [comment]
I am observing the same problem. I created an empty perf.json file in lighthouse-core/config and that enabled it to work.

**Comment by ithinkihaveacat** [comment]
The missing file is possibly <https://raw.githubusercontent.com/GoogleChrome/lighthouse/master/lighthouse-core/config/perf.json>. (I'm using this and it also seems to work.)

**Comment by samccone** [comment]
Thanks for the reports. We will get this fixed!

**Comment by paulirish** [comment]
1.1.6 is published and fixes this.

The problem was perf.json was included in an `.npmignore` from before it was checked into git. 

Thanks very much for reporting! And please comment again if you have any issues.
