### ISSUE TITLE
DevTools Error: Protocol error (Runtime.evaluate): Promise was collected

### ISSUE THREAD

**Issue by erleRocket** [GoogleChrome/lighthouse#7718]
**Initial URL**: https://www.reezocar.com/search.html
**Chrome Version**: 73.0.3683.86
**Error Message**: Protocol error (Runtime.evaluate): Promise was collected
**Stack Trace**:
```
Error: Protocol error (Runtime.evaluate): Promise was collected
    at Function.fromProtocolMessage (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:1364:121)
    at eval (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:995:253)
```

**Comment by patrickhulce** [comment]
Thanks for filing! Duplicate #5973, we'll discuss over on that issue.
