### ISSUE TITLE
Extension Error: PAGE_HUNG

### ISSUE THREAD

**Issue by carlHandy** [GoogleChrome/lighthouse#7761]
**Lighthouse Version**: 4.2.0
**Lighthouse Commit**: 35b285b87d681905777ed2545e48292312910485
**Chrome Version**: 73.0.3683.86
**Initial URL**: https://carlhandy.co/
**Error Message**: PAGE_HUNG
**Stack Trace**:
```
LHError: PAGE_HUNG
    at chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:21872:7
    at async Driver._waitForFullyLoaded (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:21891:1)
    at async Driver.gotoURL (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:22022:1)
    at async Function.loadPage (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:22502:16)
    at async Function.pass (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:22654:1)
    at async Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:22891:1)
    at async Function._gatherArtifactsFromBrowser (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:31641:17)
    at async Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:31520:11)
    at async runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:14563:14)
```

**Comment by patrickhulce** [comment]
This error means that the page stopped responding. The solution here is to re-run. If the error repeats, the page has an infinite loop and needs to be fixed.
