### ISSUE TITLE
DevTools Error: PAGE_HUNG

### ISSUE THREAD

**Issue by Yodapp** [GoogleChrome/lighthouse#7818]
I'm working on static web pages that's hosted on Netlify. Every time I try to run a site audit using Lighthouse and dev tools, the audit crashes after a while with similar stacktrace as the one bellow.

The website is extremly simple and basic, so I don't think Lighthouse should have any problem auditing it. Details bellow:

**Initial URL**: https://n33d-4-sp33d.netlify.com/
**Chrome Version**: 73.0.3683.86
**Error Message**: PAGE_HUNG
**Stack Trace**:
```
LHError: PAGE_HUNG
    at eval (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:1063:1407)
    at async Driver._waitForFullyLoaded (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:1063:1720)
    at async Driver.gotoURL (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:1072:974)
    at async Function.loadPage (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:1116:58)
    at async Function.pass (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:1124:614)
    at async Function.run (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:1135:60)
    at async Function._gatherArtifactsFromBrowser (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:1591:151)
    at async Function.run (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:1583:11)
```

**Comment by patrickhulce** [comment]
Can you share any specifics about your machine/setup? 

Lighthouse completes in ~6 seconds on this page with no issue on my machine. I suspect some sort of extension/Chrome plugin/anti-virus interference is locking up the page, but anything you can share would help.

**Comment by patrickhulce** [comment]
This error means that the page stopped responding. The solution here is to re-run. If the error repeats, the page or your machine creates infinite loops and needs to be fixed.
