### ISSUE TITLE
DevTools Error: Cannot read property 'navigate' of null

### ISSUE THREAD

**Issue by haraldnorden** [GoogleChrome/lighthouse#7911]
**Initial URL**: https://str-worktime.firebaseapp.com/
**Chrome Version**: 73.0.3683.86
**Error Message**: Cannot read property 'navigate' of null
**Stack Trace**:
```
TypeError: Cannot read property 'navigate' of null
    at Audits2.Audits2Panel._resetEmulationAndProtocolConnection (chrome-devtools://devtools/bundled/audits2/audits2_module.js:221:562)
    at async Audits2.Audits2Panel._startAudit (chrome-devtools://devtools/bundled/audits2/audits2_module.js:214:126)
```

**Comment by dnlmzw** [comment]
+1

Cannot read property 'navigate' of null
```
Channel: DevTools
Initial URL: http://localhost:3000/da-dk//
Chrome Version: 74.0.3729.131
Stack Trace: TypeError: Cannot read property 'navigate' of null
    at Audits2.Audits2Panel._resetEmulationAndProtocolConnection (chrome-devtools://devtools/bundled/audits2/audits2_module.js:231:562)
    at async Audits2.Audits2Panel._startAudit (chrome-devtools://devtools/bundled/audits2/audits2_module.js:224:126)
```

**Comment by paulirish** [comment]
@TimvdLippe fixed this for us in https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/2521136 :) 

also, might be related to #5979 (but perhaps not).
