### ISSUE TITLE
DevTools Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found

### ISSUE THREAD

**Issue by tzimos** [GoogleChrome/lighthouse#7998]
**Initial URL**: http://185.205.210.23:8000/#
**Chrome Version**: 73.0.3683.75
**Error Message**: Protocol error (Tracing.start): 'Tracing.start' wasn't found
**Stack Trace**:
```
Error: Protocol error (Tracing.start): 'Tracing.start' wasn't found
    at Function.fromProtocolMessage (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:1364:121)
    at eval (chrome-devtools://devtools/remote/serve_file/@909ee014fcea6828f9a610e6716145bc0b3ebf4a/audits2_worker/audits2_worker_module.js:995:253)
```

**Comment by patrickhulce** [comment]
duplicate #7246 , Debian doesn't ship a version of Chromium that supports Lighthouse. Use Chrome instead.
