### ISSUE TITLE
DevTools Error: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by TonicWorldWide** [GoogleChrome/lighthouse#8006]
**Initial URL**: https://mobiistar.in/
**Chrome Version**: 73.0.3683.86
**Error Message**: Cannot read property 'match' of undefined
**Stack Trace**:
```
TypeError: Cannot read property 'match' of undefined
    at Driver.getBrowserVersion (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:1013:212)
    at async Function.getBaseArtifacts (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:1133:117)
    at async Function.run (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:1134:134)
    at async Function._gatherArtifactsFromBrowser (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:1591:151)
    at async Function.run (chrome-devtools://devtools/remote/serve_file/@f9b0bec6063ea50ce2b71f5b9abbae7beee319a6/audits2_worker/audits2_worker_module.js:1583:11)
```

**Comment by patrickhulce** [comment]
Thanks for filing! Duplicate #7610, we'll discuss over there.
