### ISSUE TITLE
DevTools Error: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by atorau** [GoogleChrome/lighthouse#8143]
**Initial URL**: http://localhost:3000/
**Chrome Version**: 73.0.3683.103
**Error Message**: Cannot read property 'match' of undefined
**Stack Trace**:
```
TypeError: Cannot read property 'match' of undefined
    at Driver.getBrowserVersion (chrome-devtools://devtools/remote/serve_file/@e82a658d8159cabbd4938c1660f9bb00b4a82a23/audits2_worker/audits2_worker_module.js:1013:212)
    at async Function.getBaseArtifacts (chrome-devtools://devtools/remote/serve_file/@e82a658d8159cabbd4938c1660f9bb00b4a82a23/audits2_worker/audits2_worker_module.js:1133:117)
    at async Function.run (chrome-devtools://devtools/remote/serve_file/@e82a658d8159cabbd4938c1660f9bb00b4a82a23/audits2_worker/audits2_worker_module.js:1134:134)
    at async Function._gatherArtifactsFromBrowser (chrome-devtools://devtools/remote/serve_file/@e82a658d8159cabbd4938c1660f9bb00b4a82a23/audits2_worker/audits2_worker_module.js:1591:151)
    at async Function.run (chrome-devtools://devtools/remote/serve_file/@e82a658d8159cabbd4938c1660f9bb00b4a82a23/audits2_worker/audits2_worker_module.js:1583:11)
```

**Comment by patrickhulce** [comment]
Thanks for filing! Duplicate #7610, we'll discuss over there.
