### ISSUE TITLE
Deployment to GAE flex at Error: connect ECONNREFUSED 127.0.0.1:xxxx

### ISSUE THREAD

**Issue by michyliao** [GoogleChrome/lighthouse#8150]
Hi all,

I am able to deploy the same code to a GKE environment and GCE instance running it as a docker container. When I try to deploy onto GAE (App Engine) flex, I get the following errors to it not being able to connect. I had saw the previous error when I tried to deploy it on a GCE instance as a docker container, but was able to fix the issue by adding the flag --no-sandbox. I applied the same config to GAE, but still getting the error. Any help would be very appreciated!

Thanks.

#### Provide the steps to reproduce
1. Run LH on any URL to generate report. 

#### What is the current behavior?
The folder is created, but it gets stuck on this step and returns the following error:

`2019-04-10 17:23:57 default[20190410t131221]  2019-04-10T17|23|57.110Z

2019-04-10 17:24:06 default[20190410t131221]  Wed, 10 Apr 2019 17:24:06 GMT status Connecting to browser
2019-04-10 17:24:06 default[20190410t131221]  Wed, 10 Apr 2019 17:24:06 GMT status Resetting state with about:blank
2019-04-10 17:24:07 default[20190410t131221]  Wed, 10 Apr 2019 17:24:07 GMT status Benchmarking machine
2019-04-10 17:24:07 default[20190410t131221]  Wed, 10 Apr 2019 17:24:07 GMT status Initializing…
2019-04-10 17:24:07 default[20190410t131221]  Wed, 10 Apr 2019 17:24:07 GMT status Loading page & waiting for onload Scripts, CSSUsage, ViewportDimensions, RuntimeExceptions, ChromeConsoleMessages, Accessibility, AnchorElements, ImageElements, LinkElements, MetaElements, AppCacheManifest, Doctype, DOMStats, JSLibraries, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, FontSize, Hreflang, EmbeddedContent, Canonical, RobotsTxt, TapTargets
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: Scripts
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: CSSUsage
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: ViewportDimensions
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: RuntimeExceptions
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: ChromeConsoleMessages
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: Accessibility
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: AnchorElements
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: ImageElements
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: LinkElements
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: MetaElements
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: AppCacheManifest
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: Doctype
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: DOMStats
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: JSLibraries
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: OptimizedImages
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: PasswordInputsWithPreventedPaste
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: ResponseCompression
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: TagsBlockingFirstPaint
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: FontSize
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: Hreflang
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: EmbeddedContent
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: Canonical
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: RobotsTxt
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving in-page: TapTargets
2019-04-10 17:24:21 default[20190410t131221]  Wed, 10 Apr 2019 17:24:21 GMT status Retrieving trace
2019-04-10 17:24:23 default[20190410t131221]  Wed, 10 Apr 2019 17:24:23 GMT status Retrieving devtoolsLog & network records
2019-04-10 17:24:23 default[20190410t131221]  Wed, 10 Apr 2019 17:24:23 GMT status Retrieving: Scripts
2019-04-10 17:24:24 default[20190410t131221]  Wed, 10 Apr 2019 17:24:24 GMT status Retrieving: CSSUsage
2019-04-10 17:24:54 default[20190410t131221]  Wed, 10 Apr 2019 17:24:54 GMT status Retrieving: ViewportDimensions
2019-04-10 17:24:54 default[20190410t131221]  Wed, 10 Apr 2019 17:24:54 GMT status Retrieving: RuntimeExceptions
2019-04-10 17:24:54 default[20190410t131221]  Wed, 10 Apr 2019 17:24:54 GMT status Retrieving: ChromeConsoleMessages
2019-04-10 17:24:54 default[20190410t131221]  Wed, 10 Apr 2019 17:24:54 GMT status Retrieving: Accessibility
2019-04-10 17:24:54 default[20190410t131221]  Wed, 10 Apr 2019 17:24:54 GMT status Retrieving: AnchorElements
2019-04-10 17:24:54 default[20190410t131221]  Wed, 10 Apr 2019 17:24:54 GMT status Retrieving: ImageElements
2019-04-10 17:24:54 default[20190410t131221]  Wed, 10 Apr 2019 17:24:54 GMT status Retrieving: LinkElements
2019-04-10 17:24:54 default[20190410t131221]  Wed, 10 Apr 2019 17:24:54 GMT status Retrieving: MetaElements
2019-04-10 17:24:54 default[20190410t131221]  Wed, 10 Apr 2019 17:24:54 GMT status Retrieving: AppCacheManifest
2019-04-10 17:24:54 default[20190410t131221]  Wed, 10 Apr 2019 17:24:54 GMT status Retrieving: Doctype
2019-04-10 17:24:54 default[20190410t131221]  Wed, 10 Apr 2019 17:24:54 GMT status Retrieving: DOMStats
2019-04-10 17:24:54 default[20190410t131221]  Wed, 10 Apr 2019 17:24:54 GMT status Retrieving: JSLibraries
2019-04-10 17:24:54 default[20190410t131221]  Wed, 10 Apr 2019 17:24:54 GMT status Retrieving: OptimizedImages
2019-04-10 17:24:55 default[20190410t131221]  Wed, 10 Apr 2019 17:24:55 GMT status Retrieving: PasswordInputsWithPreventedPaste
2019-04-10 17:24:55 default[20190410t131221]  Wed, 10 Apr 2019 17:24:55 GMT status Retrieving: ResponseCompression
2019-04-10 17:24:55 default[20190410t131221]  Wed, 10 Apr 2019 17:24:55 GMT status Retrieving: TagsBlockingFirstPaint
2019-04-10 17:24:55 default[20190410t131221]  Wed, 10 Apr 2019 17:24:55 GMT status Retrieving: FontSize
2019-04-10 17:24:55 default[20190410t131221]  Wed, 10 Apr 2019 17:24:55 GMT status Retrieving: Hreflang
2019-04-10 17:24:55 default[20190410t131221]  Wed, 10 Apr 2019 17:24:55 GMT status Retrieving: EmbeddedContent
2019-04-10 17:24:55 default[20190410t131221]  Wed, 10 Apr 2019 17:24:55 GMT status Retrieving: Canonical
2019-04-10 17:24:55 default[20190410t131221]  Wed, 10 Apr 2019 17:24:55 GMT status Retrieving: RobotsTxt
2019-04-10 17:24:55 default[20190410t131221]  Wed, 10 Apr 2019 17:24:55 GMT status Retrieving: TapTargets
2019-04-10 17:24:55 default[20190410t131221]  Wed, 10 Apr 2019 17:24:55 GMT status Disconnecting from browser...
2019-04-10 17:24:55 default[20190410t131221]  (node:17) UnhandledPromiseRejectionWarning: Error: not opened      at WebSocket.send (/lighthouse/node_modules/ws/lib/WebSocket.js:344:18)      at CriConnection.sendRawMessage (/lighthouse/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:172:14)      at CriConnection.sendCommand (/lighthouse/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:65:10)      at Driver._innerSendCommand (/lighthouse/node_modules/lighthouse/lighthouse-core/gather/driver.js:324:29)      at Promise (/lighthouse/node_modules/lighthouse/lighthouse-core/gather/driver.js:298:35)      at new Promise (<anonymous>)      at Driver.sendCommand (/lighthouse/node_modules/lighthouse/lighthouse-core/gather/driver.js:289:12)      at Object.clearAllNetworkEmulation (/lighthouse/node_modules/lighthouse/lighthouse-core/lib/emulation.js:118:17)      at Driver.setThrottling (/lighthouse/node_modules/lighthouse/lighthouse-core/gather/driver.js:1318:24)      at Function.run (/lighthouse/node_modules/lighthouse/lighthouse-core/gather/gather-runner.js:474:22)
2019-04-10 17:24:55 default[20190410t131221]  (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 89)
2019-04-10 17:24:55 default[20190410t131221]  (node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-04-10 17:24:55 default[20190410t131221]  events.js:174
2019-04-10 17:24:55 default[20190410t131221]        throw er; // Unhandled 'error' event
2019-04-10 17:24:55 default[20190410t131221]        ^
2019-04-10 17:24:55 default[20190410t131221]
2019-04-10 17:24:55 default[20190410t131221]  Error: connect ECONNREFUSED 127.0.0.1:46465      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
2019-04-10 17:24:55 default[20190410t131221]  Emitted 'error' event at:
2019-04-10 17:24:55 default[20190410t131221]      at Socket.socketErrorListener (_http_client.js:392:9)
2019-04-10 17:24:55 default[20190410t131221]      at Socket.emit (events.js:189:13)
2019-04-10 17:24:55 default[20190410t131221]      at emitErrorNT (internal/streams/destroy.js:82:8)
2019-04-10 17:24:55 default[20190410t131221]      at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
2019-04-10 17:24:55 default[20190410t131221]      at process._tickCallback (internal/process/next_tick.js:63:19)
2019-04-10 17:24:55 default[20190410t131221]  npm ERR! code ELIFECYCLE
2019-04-10 17:24:55 default[20190410t131221]  npm ERR! errno 1
2019-04-10 17:24:55 default[20190410t131221]  npm ERR! 86164@0.0.0 start: `PORT=8080 node ./server/server.js`
2019-04-10 17:24:55 default[20190410t131221]  npm ERR! Exit status 1
2019-04-10 17:24:55 default[20190410t131221]  npm ERR!
2019-04-10 17:24:55 default[20190410t131221]  npm ERR! Failed at the 86164@0.0.0 start script.
2019-04-10 17:24:55 default[20190410t131221]  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-04-10 17:24:55 default[20190410t131221]
2019-04-10 17:24:55 default[20190410t131221]  npm ERR! A complete log of this run can be found in:
2019-04-10 17:24:55 default[20190410t131221]  npm ERR!     /home/chrome/.npm/_logs/2019-04-10T17_24_55_672Z-debug.log
2019-04-10 17:24:56 default[20190410t131221]  "GET /favicon.ico" 502
2019-04-10 17:25:03 default[20190410t131221]
2019-04-10 17:25:03 default[20190410t131221]  > 86164@0.0.0 start /lighthouse
2019-04-10 17:25:03 default[20190410t131221]  > PORT=8080 node ./server/server.js
2019-04-10 17:25:03 default[20190410t131221]
2019-04-10 17:25:08 default[20190410t131221]  Running on http://localhost:8080`

#### What is the expected behavior?
Reports to get generated

#### Environment Information
* Affected Channels: 
* Lighthouse version: latest
* Node.js version: 10
* Operating System: GAE flex on GCP

**Related issues**

**Comment by patrickhulce** [comment]
Does it always die in the same spot in the logs? Could you try running just the performance category and see if it survives?

**Comment by michyliao** [comment]
Hi @patrickhulce ,
Yes it dies on the spot. How would I run the performance category? I am trying to help someone deploy onto GCP, so im not sure how to run it properly.

**Comment by patrickhulce** [comment]
If you're running Lighthouse from the command-line, you can add the `--only-categories=performance` flag. See our README for more info and links on other environments.

**Comment by brendankenny** [comment]
Hopefully this was resolved. If not, please comment and we can reopen.
