### ISSUE TITLE
DevTools Error: Protocol error (Runtime.evaluate): Promise was collected

### ISSUE THREAD

**Issue by PrinsFrank** [GoogleChrome/lighthouse#8177]
Running an audit when visiting a page that has javascript disabled results in the following error:

**Initial URL**: http://www.google.com/
**Chrome Version**: 73.0.3683.103
**Error Message**: Protocol error (Runtime.evaluate): Promise was collected
**Stack Trace**:
```
Error: Protocol error (Runtime.evaluate): Promise was collected
    at Function.fromProtocolMessage (chrome-devtools://devtools/remote/serve_file/@e82a658d8159cabbd4938c1660f9bb00b4a82a23/audits2_worker/audits2_worker_module.js:1364:121)
    at eval (chrome-devtools://devtools/remote/serve_file/@e82a658d8159cabbd4938c1660f9bb00b4a82a23/audits2_worker/audits2_worker_module.js:995:253)
```

When the audit is run again on the same url with javascript enabled the error is not present.

**Comment by patrickhulce** [comment]
Thanks for filing! Duplicate #5973, we'll discuss over on that issue.
