### ISSUE TITLE
Extension Error: PAGE_HUNG

### ISSUE THREAD

**Issue by newtonsheesha** [GoogleChrome/lighthouse#8571]
**Lighthouse Version**: 4.3.0
**Lighthouse Commit**: 01b217be64ddff7ca500ad0f787f914fa9900b73
**Chrome Version**: 73.0.3683.103
**Initial URL**: https://www.spirit.com/en/flights-from-denver
**Error Message**: PAGE_HUNG
**Stack Trace**:
```
LHError: PAGE_HUNG
    at chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:22076:7
    at async Driver._waitForFullyLoaded (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:22095:1)
    at async Driver.gotoURL (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:22227:1)
    at async Function.loadPage (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:22707:16)
    at async Function.pass (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:22859:1)
    at async Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:23096:1)
    at async Function._gatherArtifactsFromBrowser (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:31921:17)
    at async Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:31791:11)
    at async runLighthouseInExtension (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:14647:14)
```

**Comment by patrickhulce** [comment]
This error means that the page stopped responding. The solution here is to re-run. If the error repeats, the page or your machine creates infinite loops and needs to be fixed.
