### ISSUE TITLE
Audit error in localhost React app

### ISSUE THREAD

**Issue by sendilkumarj** [GoogleChrome/lighthouse#8833]
This issue is reproducible and not able to audit a few of my web app pages only for mobile mode

NO_FCP
```
Channel: DevTools
Initial URL: http://localhost:3000/sub-page/
Chrome Version: 74.0.3729.131
Stack Trace: LHError: NO_FCP
    at eval (chrome-devtools://devtools/remote/serve_file/@518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f/audits2_worker/audits2_worker_module.js:1199:206)

**Comment by TheKaddarikRepository** [comment]
Hello,
I was just trying the tutorial for PWA from codelabs.
When launching the audit as prescribed in : 
https://codelabs.developers.google.com/codelabs/your-first-pwapp/#2

I get this Error for  Mobile :
`PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: http://localhost:8000/
Chrome Version: 75.0.3770.100
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (chrome-devtools://devtools/remote/serve_file/@cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0/audits2_worker/audits2_worker_module.js:1190:210)
````

I get this Error for Desktop : 
`NO_FCP
```
Channel: DevTools
Initial URL: http://localhost:8000/
Chrome Version: 75.0.3770.100
Stack Trace: LHError: NO_FCP
    at eval (chrome-devtools://devtools/remote/serve_file/@cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0/audits2_worker/audits2_worker_module.js:1219:206)
````
