### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: GathererClass is not a constructor

### ISSUE THREAD

**Issue by nazimdevs** [GoogleChrome/lighthouse#8950]
Light house version :4.3.1
puppeteer version:1.16.0

Getting below error:
C:\NewLearning\BrowserSidePerformance>node puppeteer-lighthouse
(node:11160) UnhandledPromiseRejectionWarning: TypeError: GathererClass is not a constructor
    at Function.requireGathererFromPath (C:\NewLearning\BrowserSidePerformance\node_modules\lighthouse\lighthouse-core\config\config.js:858:17)
    at Config.expandGathererShorthand.map.gathererDefn (C:\NewLearning\BrowserSidePerformance\node_modules\lighthouse\lighthouse-core\config\config.js:901:25)
    at Array.map (<anonymous>)
    at passes.map.pass (C:\NewLearning\BrowserSidePerformance\node_modules\lighthouse\lighthouse-core\config\config.js:882:76)
    at Array.map (<anonymous>)
    at Function.requireGatherers (C:\NewLearning\BrowserSidePerformance\node_modules\lighthouse\lighthouse-core\config\config.js:881:31)
    at new Config (C:\NewLearning\BrowserSidePerformance\node_modules\lighthouse\lighthouse-core\config\config.js:372:27)
    at generateConfig (C:\NewLearning\BrowserSidePerformance\node_modules\lighthouse\lighthouse-core\index.js:68:10)
    at lighthouse (C:\NewLearning\BrowserSidePerformance\node_modules\lighthouse\lighthouse-core\index.js:51:18)
    at gatherLighthouseMetrics (C:\NewLearning\BrowserSidePerformance\helpers.js:33:16)
(node:11160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:11160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by patrickhulce** [comment]
Are you using any custom config with your own gatherers?

**Comment by asaladino** [comment]
I had the same error and my custom config file was out of date. I'm using `"lighthouse": "^4.3.0"` with a custom config but no custom gathers. I copied the new default config (https://github.com/GoogleChrome/lighthouse/blob/v4.3.1/lighthouse-core/config/default-config.js) into my project src, changed the two require statements to:

```
const constants = require('lighthouse/lighthouse-core/config/constants');
const i18n = require('lighthouse/lighthouse-core/lib/i18n/i18n.js');
```
and commented out the screenshots (I didn't need them).

Then you just need to import and run:

```
import lighthouseDefaultConfig from "../Config/LighthouseDefault";
let results = await lighthouse(url.url, flags, lighthouseDefaultConfig);
```

Hope that helps.

**Comment by brendankenny** [comment]
thanks @asaladino!
