### ISSUE TITLE
Failed to Construct: Invalid URL

### ISSUE THREAD

**Issue by JonnytheMarketer** [GoogleChrome/lighthouse#9087]
#### Provide the steps to reproduce
1. Run LH on https://www.sce.com

#### What is the current behavior?
I instantly get an error message: 
**Lighthouse Version**: 5.0.0
**Lighthouse Commit**: 77e57c91b416913854f542abfcb1b8c24dc61f4c
**Chrome Version**: 74.0.3729.108
**Initial URL**: https://www.sce.com/
**Error Message**: Failed to construct 'URL': Invalid URL
**Stack Trace**:
```
TypeError: Failed to construct 'URL': Invalid URL
    at new URLShim (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:64148:1)
    at parseIcon (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:29281:11)
    at chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:29358:11
    at Array.map (<anonymous>)
    at parseIcons (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:29358:1)
    at parse (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:29503:7)
    at Function.getWebAppManifest (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:23781:8)
    at async Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:23828:30)
    at async Function._gatherArtifactsFromBrowser (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:33114:17)
    at async Function.run (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-ext-bundle.js:32983:11)
```
    
#### What is the expected behavior?
LH to run.

#### Environment Information
* Affected Channels: 
* Lighthouse version: 5.0.0
* Node.js version:
* Operating System: Chrome

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @JonnytheMarketer I can reproduce this!
