### ISSUE TITLE
Audit Crash

### ISSUE THREAD

**Issue by easystreet08** [GoogleChrome/lighthouse#9138]
DevTools Error: PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://zionmedicinals.com/
Chrome Version: 75.0.3770.80
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (chrome-devtools://devtools/remote/serve_file/@9a9aa15057b6b2cc0909bdcf638c0b65ecd516f2/audits2_worker/audits2_worker_module.js:1190:210)
```

**Comment by maltekosian** [comment]
PROTOCOL_TIMEOUT
```
Channel: DevTools
Initial URL: https://hogventure.com/
Chrome Version: 77.0.3816.0
Stack Trace: LHError: PROTOCOL_TIMEOUT
    at eval (devtools://devtools/remote/serve_file/@c7739c5560dc6259808f5dea14e249563b6d4105/audits_worker/audits_worker_module.js:1236:210)
```

**Comment by exterkamp** [comment]
This is a duplicate of #6512.  There is more context there on why this is happening and what you can do about it!
