### ISSUE TITLE
(Core)URLShim inheritance issue

### ISSUE THREAD

**Issue by hunterbreathat-wk** [GoogleChrome/lighthouse#9448]
#### Provide the steps to reproduce
1. launch lighthouse in js ex. 
browser is already launched
``` javascript
lighthouse('https://google.ca',{port:50855},null).then(report =>{
//do something
});
```

#### What is the current behavior?
Error stating 
```
class URLShim extends URL {
                      ^
ReferenceError: URL is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/lighthouse/lighthouse-core/lib/url-shim.js:35:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/lighthouse/lighthouse-core/lib/network-request.js:14:13)
    at Module._compile (module.js:652:30)
```
#### What is the expected behavior?
To launch lighthouse based on inputted site, in this case, google.ca as an example

#### Environment Information
* Affected Channels: Node
* Lighthouse version: 5.1.0
* Node.js version: 12.6.0, npm: 6.10.2
* Operating System: MacOsX Mojave

### Possible way to fix

`const URL = require('url');` appended to file

**Related issues**

**Comment by paulirish** [comment]
global.URL is a thing as of node 10. https://nodejs.org/api/globals.html#globals_url


> Node.js version: 12.6.0, 

are you sure you're using node >= 10?

**Comment by hunterbreathat-wk** [comment]
yes

**Comment by connorjclark** [comment]
could you upload a repo to github so we can investigate?

**Comment by hunterbreathat-wk** [comment]
its all good i got it figured out, it was the docker image not updating
fixed now thanks
