### ISSUE TITLE
Lighthouse Extension Error

### ISSUE THREAD

**Issue by cesarenaldi** [GoogleChrome/lighthouse#968]
**Lighthouse Version**: 1.2.0
**Chrome Version**: 54.0.2840.98
**Error Message**: aggregations: expected audit results not found under audit name service-worker
**Stack Trace**:
 ```Error: aggregations: expected audit results not found under audit name service-worker
    at expectedNames.forEach.e (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:5535:17)
    at Array.forEach (native)
    at items.map.item (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:5519:21)
    at Array.map (native)
    at Function.compare (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:5503:18)
    at Function.aggregate (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:5577:24)
    at config.aggregations.map.a (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10985:65)
    at Array.map (native)
    at run.then.auditResults (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10985:46)```

**Comment by wardpeet** [comment]
can we get a url as well to test on, can not reproduce it at the moment with perhaps some options

**Comment by brendankenny** [comment]
this is #921 and now fixed on master
