### ISSUE TITLE
Extension Error: `listeners.filter` is not a function

### ISSUE THREAD

**Issue by josemsantos** [GoogleChrome/lighthouse#975]
**Lighthouse Version**: 1.2.0
**Chrome Version**: 54.0.2840.71
**Error Message**: listeners.filter is not a function
**Stack Trace**:
 ```TypeError: listeners.filter is not a function
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:1044:31)
    at chain.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10959:24)```

**Comment by patrickhulce** [comment]
Another case of #941 biting us. The gatherer sets `usage: -1` instead of `rawValue: -1` (which is what the audit checks for)
