### ISSUE TITLE
Lighthouse Extension Error

### ISSUE THREAD

**Issue by lucasecdb** [GoogleChrome/lighthouse#980]
**Lighthouse Version**: 1.2.0
**Chrome Version**: 53.0.2785.92
**Error Message**: artifact.value.trim is not a function
**Stack Trace**:
 ```TypeError: artifact.value.trim is not a function
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:3452:24)
    at chain.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10959:24)```

**Comment by lucasecdb** [comment]
Ops, someone already issued this before (#979), sorry for the duplicate
