### ISSUE TITLE
net errors while loading manifest causes entire run to halt

### ISSUE THREAD

**Issue by kbardi** [GoogleChrome/lighthouse#9862]
Hey there, first I want to say thanks, because it's a great tool and absolutely useful. Usually it works great, but now I'm trying to test a website and it does not finish the report. It shows me a Driver:error when fetching the manifest (on Terminal) and it shows me a `Aw, snap!` error when using dev tool.

#### Provide the steps to reproduce
1. Run LH on https://aimementoring.com
  

#### What is the current behavior?
Error when using dev tool:
![image](https://user-images.githubusercontent.com/4523375/67117467-23993e00-f1b9-11e9-9506-dd6ce4550048.png)

Trace on terminal running command: `lighthouse https://aimementoring.com`

```shell
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +1ms
  ChromeLauncher Waiting for browser..... +510ms
  ChromeLauncher Waiting for browser.....✓ +2ms
  config:warn IFrameElements gatherer requested, however no audit requires it. +158ms
  config:warn MainDocumentContent gatherer requested, however no audit requires it. +0ms
  status Connecting to browser +10ms
  status Resetting state with about:blank +102ms
  status Benchmarking machine +601ms
  status Initializing… +507ms
  status Resetting state with about:blank +98ms
  status Setting up network for the pass trace +15ms
  status Cleaning browser cache +2ms
  status Beginning devtoolsLog and trace +2s
  status Loading page & waiting for onload CSSUsage, ViewportDimensions, RuntimeExceptions, ConsoleMessages, AnchorElements, ImageElements, LinkElements, MetaElements, ScriptElements, IFrameElements, MainDocumentContent, AppCacheManifest, Doctype, DOMStats, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, FontSize, EmbeddedContent, RobotsTxt, TapTargets, Accessibility +179ms
  status Gathering in-page: CSSUsage +12s
  status Gathering in-page: ViewportDimensions +0ms
  status Gathering in-page: RuntimeExceptions +0ms
  status Gathering in-page: ConsoleMessages +0ms
  status Gathering in-page: AnchorElements +0ms
  status Gathering in-page: ImageElements +0ms
  status Gathering in-page: LinkElements +0ms
  status Gathering in-page: MetaElements +0ms
  status Gathering in-page: ScriptElements +0ms
  status Gathering in-page: IFrameElements +0ms
  status Gathering in-page: MainDocumentContent +0ms
  status Gathering in-page: AppCacheManifest +0ms
  status Gathering in-page: Doctype +0ms
  status Gathering in-page: DOMStats +0ms
  status Gathering in-page: OptimizedImages +0ms
  status Gathering in-page: PasswordInputsWithPreventedPaste +1ms
  status Gathering in-page: ResponseCompression +0ms
  status Gathering in-page: TagsBlockingFirstPaint +0ms
  status Gathering in-page: FontSize +0ms
  status Gathering in-page: EmbeddedContent +0ms
  status Gathering in-page: RobotsTxt +0ms
  status Gathering in-page: TapTargets +0ms
  status Gathering in-page: Accessibility +0ms
  status Gathering trace +1ms
  status Gathering devtoolsLog & network records +462ms
  status Gathering: CSSUsage +8ms
  status Gathering: ViewportDimensions +76ms
  status Gathering: RuntimeExceptions +2ms
  status Gathering: ConsoleMessages +1ms
  status Gathering: AnchorElements +2ms
  status Gathering: ImageElements +7ms
  status Gathering: LinkElements +23ms
  status Gathering: MetaElements +5ms
  status Gathering: ScriptElements +4ms
  status Gathering: IFrameElements +70ms
  status Gathering: MainDocumentContent +7ms
  status Gathering: AppCacheManifest +5ms
  status Gathering: Doctype +5ms
  status Gathering: DOMStats +2ms
  status Gathering: OptimizedImages +5ms
  status Gathering: PasswordInputsWithPreventedPaste +2s
  status Gathering: ResponseCompression +2ms
  status Gathering: TagsBlockingFirstPaint +20ms
  status Gathering: FontSize +3ms
  status Gathering: EmbeddedContent +540ms
  status Gathering: RobotsTxt +2ms
  status Gathering: TapTargets +2s
  status Gathering: Accessibility +21ms
  Driver:error Failed fetching manifest { LHError: ~~~snip pro timeout~~~
    at Timeout.setTimeout [as _onTimeout] (/Users/kevinbardi/.nvm/versions/node/v10.15.3/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:409:21)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  name: 'LHError',
  code: 'PROTOCOL_TIMEOUT',
  friendlyMessage: 'lighthouse-core/lib/lh-error.js | protocolTimeout # 0',
  lhrRuntimeError: true,
  protocolMethod: 'Page.getAppManifest' } +10s
  status Disconnecting from browser... +1m
  ChromeLauncher Killing Chrome instance 90291 +9ms
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Runtime.evaluate)
LHError: ~~~snip pro timeout~~~
    at Timeout.setTimeout [as _onTimeout] (/Users/kevinbardi/.nvm/versions/node/v10.15.3/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:409:21)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

#### What is the expected behavior?
See the results about Performance, Accessibility, Best practices and SEO.

#### Environment Information
* Affected Channels: Node and DevTools 
* Lighthouse version: lighthouse --version -> 5.6.0
* Node.js version: v10.15.3
* Operating System: Mac OS Mojave 10.14.6
* Chrome Version: Version 77.0.3865.90 (Official Build) (64-bit)

**Related issues**
Suggestion from bot, but I think it is not the same: https://github.com/GoogleChrome/lighthouse/issues/6512

**Comment by connorjclark** [comment]
Thanks for the report!

Devtools-on-devtools shows this error message:

```
Driver:error Failed fetching manifest +10s LHError: PROTOCOL_TIMEOUT
```

The manifest.json file for that site causes this error: net::ERR_CONTENT_DECODING_FAILED

We apparently don't handle that very well.

**Comment by adrianaixba** [comment]
As per [Chrome’s updated Installability Criteria](https://developer.chrome.com/blog/update-install-criteria), Lighthouse will be deprecating the PWA category in the next upcoming release. For future PWA testing, users will be directed to use the [updated PWA documentation](https://developer.chrome.com/docs/devtools/progressive-web-apps/). Marking this as closed!
