### ISSUE TITLE
Lighthouse Extension Error

### ISSUE THREAD

**Issue by purushottam22887** [GoogleChrome/lighthouse#987]
**Lighthouse Version**: 1.2.0
**Chrome Version**: 54.0.2840.99
**Error Message**: listeners.filter is not a function
**Stack Trace**:
 ```TypeError: listeners.filter is not a function
    at Function.audit (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:1044:31)
    at chain.then._ (chrome-extension://blipmdconlkpinefehnmjammfjpmpbjk/scripts/lighthouse-background.js:10959:24)```

**Comment by ebidel** [comment]
Dupe of https://github.com/GoogleChrome/lighthouse/issues/975
