### ISSUE TITLE
searchbaron (redirect malware issue)

### ISSUE THREAD

**Issue by GuangYang98** [GoogleChrome/lighthouse#9892]
Protocol error (Runtime.evaluate): Promise was collected
```
Channel: DevTools
Initial URL: https://www.bing.com/search?q=hkh&pc=cosp&ptag=G6C999N3AEAF735706C&form=CONBNT&conlogo=CT3210127
Chrome Version: 78.0.3904.70
Stack Trace: Error: Protocol error (Runtime.evaluate): Promise was collected
    at Function.fromProtocolMessage (devtools://devtools/remote/serve_file/@edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5/audits_worker/audits_worker_module.js:1603:121)
    at eval (devtools://devtools/remote/serve_file/@edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5/audits_worker/audits_worker_module.js:1209:253)
```

**Comment by connorjclark** [comment]
I don't see this. Still happens for you?
