### ISSUE TITLE
Timeout 100% of runs for particular URL

### ISSUE THREAD

**Issue by patrickhulce** [GoogleChrome/lighthouse#9912]
The lantern collect script got stuck in an infinite loop because of `repeatUntilPass` and a site that never completes. I'm avoiding saying the name of the timeout for bot reasons but we all know what it is ;)

example WPT runs

https://www.webpagetest.org//results.php?test=191102_WJ_6eb1d4826d72f71ad8148fe4bc2411ae
https://www.webpagetest.org//results.php?test=191102_N6_eed705551506349bd8674d5742195212

#### Provide the steps to reproduce
1. Run LH on https://m.douban.com/

#### What is the current behavior?

Times out on Network.emulateNetworkConditions

#### What is the expected behavior?

Runs OK

```
lighthouse "https://m.douban.com/" --channel wpt --disable-network-throttling --disable-cpu-throttling --throttling-method provided --enable-error-reporting --max-wait-for-load 80000 --port 9259 --output html --output json --output-path "/home/pmeenan/wptagent/work/MotoG4_07/191102_WJ_6eb1d4826d72f71ad8148fe4bc2411ae.1.0/lighthouse.json" --save-assets --skip-audits screenshot-thumbnails --emulated-form-factor none
Sat, 02 Nov 2019 05:11:43 GMT status Connecting to browser
Sat, 02 Nov 2019 05:11:43 GMT status Resetting state with about:blank
Sat, 02 Nov 2019 05:11:43 GMT status Benchmarking machine
Sat, 02 Nov 2019 05:11:44 GMT status Initializing…
Sat, 02 Nov 2019 05:11:44 GMT status Resetting state with about:blank
Sat, 02 Nov 2019 05:11:44 GMT status Setting up network for the pass trace
Sat, 02 Nov 2019 05:11:44 GMT status Cleaning browser cache
Sat, 02 Nov 2019 05:11:44 GMT status Beginning devtoolsLog and trace
Sat, 02 Nov 2019 05:11:44 GMT status Loading page & waiting for onload CSSUsage, ViewportDimensions, RuntimeExceptions, ConsoleMessages, AnchorElements, ImageElements, LinkElements, MetaElements, ScriptElements, AppCacheManifest, Doctype, DOMStats, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, FontSize, EmbeddedContent, RobotsTxt, TapTargets, Accessibility
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: CSSUsage
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: ViewportDimensions
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: RuntimeExceptions
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: ConsoleMessages
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: AnchorElements
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: ImageElements
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: LinkElements
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: MetaElements
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: ScriptElements
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: AppCacheManifest
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: Doctype
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: DOMStats
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: OptimizedImages
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: PasswordInputsWithPreventedPaste
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: ResponseCompression
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: TagsBlockingFirstPaint
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: FontSize
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: EmbeddedContent
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: RobotsTxt
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: TapTargets
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: Accessibility
Sat, 02 Nov 2019 05:12:14 GMT status Gathering trace
Sat, 02 Nov 2019 05:12:14 GMT status Gathering devtoolsLog & network records
Sat, 02 Nov 2019 05:12:44 GMT status Disconnecting from browser...
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Network.emulateNetworkConditions)
LHError: YOU_KNOW_WHAT_TIMEOUT
    at Timeout.setTimeout [as _onTimeout] (/usr/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:409:21)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

```
lighthouse "https://m.douban.com/" --channel wpt --disable-network-throttling --disable-cpu-throttling --throttling-method provided --enable-error-reporting --max-wait-for-load 80000 --port 9264 --output html --output json --output-path "/home/pmeenan/wptagent/work/MotoG4_19/191102_N6_eed705551506349bd8674d5742195212.1.0/lighthouse.json" --save-assets --skip-audits screenshot-thumbnails --emulated-form-factor none
Sat, 02 Nov 2019 05:11:42 GMT status Connecting to browser
Sat, 02 Nov 2019 05:11:42 GMT status Resetting state with about:blank
Sat, 02 Nov 2019 05:11:43 GMT status Benchmarking machine
Sat, 02 Nov 2019 05:11:43 GMT status Initializing…
Sat, 02 Nov 2019 05:11:43 GMT status Resetting state with about:blank
Sat, 02 Nov 2019 05:11:43 GMT status Setting up network for the pass trace
Sat, 02 Nov 2019 05:11:43 GMT status Cleaning browser cache
Sat, 02 Nov 2019 05:11:43 GMT status Beginning devtoolsLog and trace
Sat, 02 Nov 2019 05:11:43 GMT status Loading page & waiting for onload CSSUsage, ViewportDimensions, RuntimeExceptions, ConsoleMessages, AnchorElements, ImageElements, LinkElements, MetaElements, ScriptElements, AppCacheManifest, Doctype, DOMStats, OptimizedImages, PasswordInputsWithPreventedPaste, ResponseCompression, TagsBlockingFirstPaint, FontSize, EmbeddedContent, RobotsTxt, TapTargets, Accessibility
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: CSSUsage
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: ViewportDimensions
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: RuntimeExceptions
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: ConsoleMessages
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: AnchorElements
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: ImageElements
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: LinkElements
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: MetaElements
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: ScriptElements
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: AppCacheManifest
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: Doctype
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: DOMStats
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: OptimizedImages
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: PasswordInputsWithPreventedPaste
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: ResponseCompression
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: TagsBlockingFirstPaint
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: FontSize
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: EmbeddedContent
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: RobotsTxt
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: TapTargets
Sat, 02 Nov 2019 05:12:14 GMT status Gathering in-page: Accessibility
Sat, 02 Nov 2019 05:12:14 GMT status Gathering trace
Sat, 02 Nov 2019 05:12:14 GMT status Gathering devtoolsLog & network records
Sat, 02 Nov 2019 05:12:44 GMT status Disconnecting from browser...
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Network.emulateNetworkConditions)
LHError: YOU_KNOW_WHAT_TIMEOUT
    at Timeout.setTimeout [as _onTimeout] (/usr/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:409:21)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

#### Environment Information
* Affected Channels: WPT
* Lighthouse version: 5.6.0
* Chrome version: 78
* Node.js version: 10?
* Operating System: Linux

#6512

**Comment by connorjclark** [comment]
seems it's hanging on `clearAllNetworkEmulation`. why do we bother to clear emulation settings if we aren't using devtools throttling?

**Comment by patrickhulce** [comment]
@connorjclark we need to `Network.emulateNetworkConditions` when we switch from online to offline and clear it when we go back. There is certainly a way to restructure to end up calling it fewer times but we want be able to get away without calling it at all. We should be able to rely on clearing network emulation not hanging :)

**Comment by connorjclark** [comment]
can't repro with latest master / stable chrome. close?

**Comment by patrickhulce** [comment]
Yeah I can't repro anymore either.
