### ISSUE TITLE
Error reporting as URL is not defined.

### ISSUE THREAD

**Issue by lgummadi7** [GoogleChrome/lighthouse#9938]
I work for an e-commerce company, trying to run lighthouse locally and want to integrate into the micro-level for early validations. And I faced this below issue, No one here in this organization tried this before. 
Note: I tried this in my personal Mac machine which has the same configuration and it is working there. 
Steps to reproduce
1. Run LH on <any URL>

#### What is the current behavior?
Not working In any way tried to install new version of chrome. 
ReferenceError: URL is not defined
at Object.<anonymous> (code/lightwallet/lighthouse-master/lighthouse-core/lib/url-shim.js:36:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (code/lightwallet/lighthouse-master/lighthouse-core/lib/network-request.js:14:13)
    at Module._compile (module.js:652:30)

#### What is the expected behavior?
IT should provide the metric reports on the chrome browser.

#### Environment Information
* Affected Channels: 
* Lighthouse version: I cannot populate version number either it is throwing sam error
* Chrome version: 78
* Node.js version: 8.11.4
* Operating System: Mac os Mojave (client provided laptop)

**Related issues**

**Comment by patrickhulce** [comment]
Thanks for filing @lgummadi7! The minimum node version required for Lighthouse is the latest LTS (v10). Upgrade the node version to use the latest Lighthouse.


From https://github.com/GoogleChrome/lighthouse#using-the-node-cli

> Lighthouse requires Node 10 LTS (10.13) or later.
