### ISSUE TITLE
Provided value "protocolMethod" does not match any placeholder in ICU message "An internal Chrome error occurred. Please restart Chrome and try re-running Lighthouse."

### ISSUE THREAD

**Issue by luucamay** [GoogleChrome/lighthouse#9992]
#### Provide the steps to reproduce
1. Run LH on [faacebook.com](facebook.com)
 

#### What is the current behavior?

Provided value "protocolMethod" does not match any placeholder in ICU message "An internal Chrome error occurred. Please restart Chrome and try re-running Lighthouse."
```
Channel: DevTools
Initial URL: https://www.facebook.com/
Chrome Version: 79.0.3945.24
Stack Trace: Error: Provided value "protocolMethod" does not match any placeholder in ICU message "An internal Chrome error occurred. Please restart Chrome and try re-running Lighthouse."
    at _preformatValues (devtools://devtools/bundled/audits_worker/audits_worker_module.js:1595:7)
    at _formatIcuMessage (devtools://devtools/bundled/audits_worker/audits_worker_module.js:1599:189)
    at _resolveIcuMessageInstanceId (devtools://devtools/bundled/audits_worker/audits_worker_module.js:1610:452)
    at Object.getFormatted (devtools://devtools/bundled/audits_worker/audits_worker_module.js:1607:104)
    at Function.run (devtools://devtools/bundled/audits_worker/audits_worker_module.js:1979:917)
```
#### What is the expected behavior?
Run the Lighthouse Audit

#### Environment Information
* Affected Channels: 
* Lighthouse version:  6.0
* Chrome version: 79.0.3945.24 (Official Build) dev (64-bit)
* Node.js version: 10.17
* Operating System: Chrome OS

**Related issues**

**Comment by connorjclark** [comment]
fixed by #9935 which can be found in Chrome Canary atm
